### ISSUE TITLE
I'm not able to install the software

### ISSUE THREAD

**Issue by simonecogno** [polonel/trudesk#102]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ x] BUG 
- [ ] FEATURE

**What happened**:
I'm not able to install the software and no error message is shown. I'm able to connect to database because in MongoDB logs I see this log line:
`2018-11-01T13:26:33.828+0100 I NETWORK  [listener] connection accepted from 127.0.0.1:53269 #2 (1 connection now open)
2018-11-01T13:26:33.834+0100 I NETWORK  [conn2] received client metadata from 127.0.0.1:53269 conn2: { driver: { name: "nodejs", version: "3.1.1" }, os: { type: "Darwin", name: "darwin", architecture: "x64", version: "17.7.0" }, platform: "Node.js v8.10.0, LE, mongodb-core: 3.1.0" }`

![image](https://user-images.githubusercontent.com/21952142/47852441-0f0f3a80-dddc-11e8-84d9-11e01258ff77.png)

**What did you expect to happen**:
Any idea how to solve this?
**How to reproduce it (as minimally and precisely as possible)**:
I've followed the documentation. Clone, build, install script via browser.

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: master
- OS (e.g. from /etc/os-release): MAC OS X 10.13
- Node.JS Version: 8.10
- MongoDB Version: 3.2
- Is this hosted on cloud.trudesk.io: no

**Comment by polonel** [comment]
Interesting. Can you open the console on chrome and see if the error is shown?

**Comment by polonel** [comment]
Thanks for the update. I'll investigate more.

**Comment by thamizhchandrasekar** [comment]
Hi, 
I'm trying to install trudesk software in my local windows machine. Here are the configuration.
OS: Windows server 2012 R2. 64-Bit
RAM: 8 GB

I am using the following documentation **http://trudesk.io/v1/guide/installation.html**

I'm not able to install the software when i run the **yarn** command. Below are the errors.

F:\Trudesk\trudesk-master\node_modules\bcrypt\build\binding.sln : error MSB3411:
 Could not load the Visual C++ component "VCBuild.exe". If the component is not
installed, either 1) install the Microsoft Windows SDK for Windows Server 2008 a
nd .NET Framework 3.5, or 2) install Microsoft Visual Studio 2008.
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (F:\Trudesk\trudesk-master\node_module
s\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:248:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "F:\\Trudesk\\trudesk-mas
ter\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--
module=F:\\Trudesk\\trudesk-master\\node_modules\\bcrypt\\lib\\binding\\bcrypt_l
ib.node" "--module_name=bcrypt_lib" "--module_path=F:\\Trudesk\\trudesk-master\\
node_modules\\bcrypt\\lib\\binding" "--napi_version=3" "--node_abi_napi=napi" "-
-napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd F:\Trudesk\trudesk-master\node_modules\bcrypt
gyp ERR! node -v v10.15.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.e
xe F:\Trudesk\trudesk-master\node_modules\node-gyp\bin\node-gyp.js build --fallb
ack-to-build --module=F:\Trudesk\trudesk-master\node_modules\bcrypt\lib\binding\
bcrypt_lib.node --module_name=bcrypt_lib --module_path=F:\Trudesk\trudesk-master
\node_modules\bcrypt\lib\binding --napi_version=3 --node_abi_napi=napi --napi_bu
ild_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (F:\Trudesk\trudesk-mast
er\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/chi
ld_process.js:259:5)
node-pre-gyp ERR! System Windows_NT 6.3.9600
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "F:\\Trudesk\\tr
udesk-master\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallba
ck-to-build"
node-pre-gyp ERR! cwd F:\Trudesk\trudesk-master\node_modules\bcrypt
node-pre-gyp ERR! node -v v10.15.2
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe F:\Trudesk\trudesk-master\no
de_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=F:\Trudes
k\trudesk-master\node_modules\bcrypt\lib\binding\bcrypt_lib.node --module_name=b
crypt_lib --module_path=F:\Trudesk\trudesk-master\node_modules\bcrypt\lib\bindin

**Comment by polonel** [comment]
As the error states...

> Could not load the Visual C++ component "VCBuild.exe". If the component is not
installed, either 1) install the Microsoft Windows SDK for Windows Server 2008 a
nd .NET Framework 3.5, or 2) install Microsoft Visual Studio 2008.

You can install the build tools through `npm i -g windows-build-tools`

Also the `master` branch doesn't require building as of version `v1.0.6`

**Comment by thamizhchandrasekar** [comment]
Thanks for the reply @polonel.

Even after installing the build tools I'm getting the same error so I skipped the **yarn** command and moved on to the **npm run build** command, was build successfully. Then moved on to **node runner** command but the command keeps on running. 

Also I already have visual studio 2017 community version and Windows SDK.


Please see the below details.

2019-03-07T05:26:29: PM2 log: App [trudesk:0] starting in -fork mode-
2019-03-07T05:26:29: PM2 log: App [trudesk:0] online
2019-03-07T05:26:31: PM2 log: App [trudesk:0] exited with code [1] via signal [S
IGINT]
2019-03-07T05:26:31: PM2 log: App [trudesk:0] starting in -fork mode-
2019-03-07T05:26:31: PM2 log: App [trudesk:0] online
2019-03-07T05:26:33: PM2 log: App [trudesk:0] exited with code [1] via signal [S
IGINT]
2019-03-07T05:26:33: PM2 log: App [trudesk:0] starting in -fork mode-
2019-03-07T05:26:33: PM2 log: App [trudesk:0] online
2019-03-07T05:26:35: PM2 log: App [trudesk:0] exited with code [1] via signal [S
IGINT]
2019-03-07T05:26:35: PM2 log: App [trudesk:0] starting in -fork mode-
2019-03-07T05:26:35: PM2 log: App [trudesk:0] online
2019-03-07T05:26:37: PM2 log: App [trudesk:0] exited with code [1] via signal [S
IGINT]

**Comment by polonel** [comment]
Show me contents of `logs/output.log`

**Comment by thamizhchandrasekar** [comment]
[output.log](https://github.com/polonel/trudesk/files/2939757/output.log)

**Comment by thamizhchandrasekar** [comment]
Yes. Here the attached log file. @polonel 
[output.log](https://github.com/polonel/trudesk/files/2939759/output.log)

**Comment by polonel** [comment]
Yea, It can't find multiple packages because it failed to build them. That's the issue with NPM. It will make you think everything worked fined even if postinstall scripts failed. 

It can't find the bcrypt binary because it couldn't build it. You followed the instructions to successfully install https://www.npmjs.com/package/windows-build-tools?

Also if you're looking at testing out a small deployment. I offer a Virtual Appliance: http://trudesk.io/v1/guide/installation.html#Virtual-Appliance

**Comment by thamizhchandrasekar** [comment]
HI @polonel ,

I already tried this cmd **npm install --global windows-build-tools**  It's installed successfully.
Again I'm getting same error.

I don't want to go with Virtual Appliance.

**Comment by polonel** [comment]
@thamizhchandrasekar And you ran it under an Admin Powershell prompt?

**Comment by thamizhchandrasekar** [comment]
@polonel ,

Yes. I ran it as an Admin Powershell and command prompt.

**Comment by thamizhchandrasekar** [comment]
@polonel ,

I restarted my machine. Now **node runner** command is working Polonel, 

**pm2-service-install -n PM2** command being idle for more than 5 mins.

**Comment by polonel** [comment]
@thamizhchandrasekar Yes thats an issue with pm2-service-install that has been reported with the latest version of node. (https://github.com/jon-hall/pm2-windows-service/issues/55) 

I haven't found the best alternative and have already removed it from my docs in the next release.

**Comment by thamizhchandrasekar** [comment]
@polonel  So How do I run the trudesk?

I skipped that command and moved on to **F:\Trudesk\trudesk-master>pm2 start F:\\Trudesk\\trudesk-master\\app.js --name trudesk -l F:\\Trudesk\\trudesk-master\\logs\\output.log --merge-logs** command.

Below are the status:

![error](https://user-images.githubusercontent.com/17143256/53938129-23738480-40a7-11e9-91da-07a8ec6a71c0.png)

**Comment by polonel** [comment]
I will need to see what the error is. `logs/output.log`

It doesn't need `pm2-windows-service` to run. That package just allows it to run as a server to survive a server reboot.

**Comment by thamizhchandrasekar** [comment]
@polonel  Here are the log file.

[output.log](https://github.com/polonel/trudesk/files/2939921/output.log)

**Comment by polonel** [comment]
Its the same error
```
Error: Cannot find module 'F:\Trudesk\trudesk-master\node_modules\bcrypt\lib\binding\bcrypt_lib.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (F:\Trudesk\trudesk-master\node_modules\bcrypt\bcrypt.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (F:\Trudesk\trudesk-master\src\models\user.js:18:14)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (F:\Trudesk\trudesk-master\src\passport\index.js:19:12)
    at Module._compile (internal/modules/cjs/loader.js:689:30) code: 'MODULE_NOT_FOUND' }
```

It can't find bcrypt which is a native module that gets build during the postinstall of `yarn install` 
Try to delete `node_modules` and run yarn install again. It has to successfully build the module.

**Comment by thamizhchandrasekar** [comment]
@polonel I tried your comments but no luck.

How do i run the trudesk??

**Comment by polonel** [comment]
If node-gyp is failing to build the native modules then you're missing the build tools or the build tools did not install correctly in an administrative PowerShell prompt. 

And as I stated, if it cannot build the native modules it cannot run. The native modules are built against your server arch. 

Another option you have is to use docker for windows and run the trudesk docker container which has all the modules prebuilt in the container. 

The error shows exactly that bcrypt is not being built so it cannot find the native module. 
I have tested with a fresh deploy of windows server 2012 on Azure and everything worked fine, so the error is indeed on your end. You need to figure out why the build tools are not installing correctly or why the native modules are not being built. See below screenshot.

![image](https://user-images.githubusercontent.com/626303/53942398-a46f5380-4088-11e9-8e89-0918a66b7e87.png)

**Comment by thamizhchandrasekar** [comment]
@polonel  Do we need to have Visual studio 2008 to install trudesk?

I have started fresh installation. I'm still facing the same error.

![error1](https://user-images.githubusercontent.com/17143256/53946001-bec22500-40ba-11e9-96c3-eb38eb99312e.png)
![error2](https://user-images.githubusercontent.com/17143256/53946003-bec22500-40ba-11e9-9d7d-3fa6b6b26bb9.png)
![error3](https://user-images.githubusercontent.com/17143256/53946004-bec22500-40ba-11e9-8c6d-d2a2c9cc1968.png)

**Comment by polonel** [comment]
The difference is I did not have VS2017 installed on the server. So my best guess is that its failing to build because of a conflict in the MSVS versions. The bcrypt install script is using `msvs_version=2015`

see this statement from the npm page of windows build tools
> This module is capable of installing either the build tools from Visual Studio 2017 or Visual Studio 2015.
By default, this tool will install the 2017 build tools. To change that, run this script with the --vs2015 parameter.

You may require the `--vs2015` flag because of having 2017 already installed.
