### ISSUE TITLE
Reply to email is creating as new ticket

### ISSUE THREAD

**Issue by kcs9198** [polonel/trudesk#105]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
When a reply is sent to the notification mail, it is creating a new ticket

**What did you expect to happen**:
It appends to the old ticket as an update

**How to reproduce it (as minimally and precisely as possible)**:
Send a mail to mailbox to create ticket. after notification is received with ticket number, reply to that email. trudesk is converting it as new ticket

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: 1.0.2
- OS (e.g. from /etc/os-release): ubuntu 16.04.5
- Node.JS Version: 10.11.0
- MongoDB Version: 4.0.3
- Is this hosted on cloud.trudesk.io: no

![image](https://user-images.githubusercontent.com/25685230/48398527-00634480-e747-11e8-9519-771353193b66.png)

**Comment by polonel** [comment]
You’re using the same email address to send the email as you are to check
that mailbox for the mail check. Right now there is not a way to update a
ticket through email. It’s a feature that’s being worked on but not fully
implemented yet.

Until then I recommend using a different drone address to prevent new
ticket creations, such as a no-reply notification email address or a
different mail check mailbox from the one sending notifications.
