### ISSUE TITLE
Trudesk stopped working unexpectedly. 

### ISSUE THREAD

**Issue by rayediaz** [polonel/trudesk#108]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
Trudesk stopped working unexpectedly. 

**What did you expect to happen**:
I expect it to work properly.

**How to reproduce it (as minimally and precisely as possible)**:
When I open ip address:port the login screen is working, but when I try to go to dashboard or other route, it fails.

**Anything else we need to know?**:

**Environment**: 
- Trudesk Version: 1.0.2
- OS (e.g. from /etc/os-release): Ubuntu 18.04
- Node.JS Version: v9.11.1
- MongoDB Version: v3.6.3
- Is this hosted on cloud.trudesk.io: no

![dash](https://user-images.githubusercontent.com/15975670/48710496-ee6a2180-ebde-11e8-854e-04b9a0d74e0f.png)
![loginh](https://user-images.githubusercontent.com/15975670/48710497-ee6a2180-ebde-11e8-83dc-806e8c7d72ad.png)

**Comment by polonel** [comment]
Can you post server logs?

**Comment by rayediaz** [comment]
There yo have!
[output.log](https://github.com/polonel/trudesk/files/2596379/output.log)

**Comment by polonel** [comment]
you upgraded node.js after you built the modules. 

Whenever you upgrade node.js you must rebuild the native modules.

delete the `node_modules` folder and run `yarn install`.

**Comment by polonel** [comment]
@rayediaz Did this resolve the issue?

**Comment by rayediaz** [comment]
Sorry for my late reply @polonel. I did solve the problem. Thanks fo taking yout time to help me.
