### ISSUE TITLE
Admin delete user application crashes

### ISSUE THREAD

**Issue by francisedulab** [polonel/trudesk#109]
- [ x] BUG 

**What happened**:
When admin deletes user that has tickets or conversations the application crashes 

**What did you expect to happen**:
If user is deleted then their history also should be deleted 

**How to reproduce it (as minimally and precisely as possible)**:
Create a admin user create a normal user account raise tickets or chat (do both ideally) and delete the user from the accounts tab 

**Anything else we need to know?**:
This is the console log output

TypeError: Cannot read property '_id' of undefined
    at /trudesk/src/helpers/viewdata/index.js:254:42
    at /trudesk/node_modules/mongoose/lib/model.js:4451:16
    at (anonymous function).call (/trudesk/node_modules/mongoose/lib/query.js:3606:7)
   at process.nextTick (/trudesk/node_modules/mongoose/lib/helpers/query/completeMany.js:35:39)
    at args.(anonymous function)

**Comment by polonel** [comment]
The account should be marked as _disabled_ if the user has tickets. Which I confirmed that. 
However, if the user has active conversations this crash does occur. 

Thank you for the bug report, working on a fix.
