### ISSUE TITLE
Group list only updates after refreshing.

### ISSUE THREAD

**Issue by Play-Real** [polonel/trudesk#110]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [X] BUG 
- [ ] FEATURE

**What happened**:
When you edit or create a group. you have to refresh your window 
If you create a ticket without refreshing it shows the old group list.
Not beeing able to create the ticket or add it to the group.

may be confusing when using trudesk in larger environments. (not a huge deal for us)
because all agents have to reload
**What did you expect to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Edit or create a group 
create a new ticket.
Add newly created or edited group to ticket

**Anything else we need to know?**:
Chrome Versie 70.0.3538.102 (Officiële build) (64-bits)

**Environment**:
- Trudesk Version: docker image polonel/trudesk:next
- OS (e.g. from /etc/os-release): 
- Node.JS Version:
- MongoDB Version:
- Is this hosted on cloud.trudesk.io:

**Comment by polonel** [comment]
Included in `v1.0.12`
