### ISSUE TITLE
Not able to run trudesk

### ISSUE THREAD

**Issue by eliyasbaby** [polonel/trudesk#111]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ x] BUG 
- [ ] FEATURE

**What happened**:

**What did you expect to happen**:
`11/23 07:18:15 [3112] - [32minfo[39m:     .                              .o8                     oooo
11/23 07:18:15 [3112] - [32minfo[39m:   .o8                             "888                     `888
11/23 07:18:15 [3112] - [32minfo[39m: .o888oo oooo d8b oooo  oooo   .oooo888   .ooooo.   .oooo.o  888  oooo
11/23 07:18:15 [3112] - [32minfo[39m:   888   `888""8P `888  `888  d88' `888  d88' `88b d88(  "8  888 .8P'
11/23 07:18:15 [3112] - [32minfo[39m:   888    888      888   888  888   888  888ooo888 `"Y88b.   888888.
11/23 07:18:15 [3112] - [32minfo[39m:   888 .  888      888   888  888   888  888    .o o.  )88b  888 `88b.
11/23 07:18:15 [3112] - [32minfo[39m:   "888" d888b     `V88V"V8P' `Y8bod88P" `Y8bod8P' 8""888P' o888o o888o
11/23 07:18:15 [3112] - [32minfo[39m: ==========================================================================
11/23 07:18:15 [3112] - [32minfo[39m: trudesk v1.0.2 Copyright (C) 2014-2018 Chris Brame
11/23 07:18:15 [3112] - [32minfo[39m:  
11/23 07:18:15 [3112] - [32minfo[39m: Running in: development
11/23 07:18:15 [3112] - [32minfo[39m: Server Time: Fri Nov 23 2018 07:18:15 GMT+0000 (Coordinated Universal Time)
11/23 07:18:16 [3112] - [32minfo[39m: Connected to MongoDB
11/23 07:18:19 [3112] - [32minfo[39m: TruDesk is now listening on port: 8118
11/23 07:18:19 [3112] - [32minfo[39m: SocketServer Running
11/23 07:18:20 [3112] - [34mdebug[39m: Checking Default Settings...
11/23 07:18:20 [3112] - [34mdebug[39m: Timezone set to America/New_York
TypeError: Cannot read property '_id' of undefined
    at C:\Program Files\iCuboid\trudesk-master\src\settings\defaults.js:109:33
    at C:\Program Files\iCuboid\trudesk-master\node_modules\mongoose\lib\model.js:4451:16
    at model.Query.(anonymous function).call (C:\Program Files\iCuboid\trudesk-master\node_modules\mongoose\lib\query.js:3606:7)
    at C:\Program Files\iCuboid\trudesk-master\node_modules\kareem\index.js:315:21
    at C:\Program Files\iCuboid\trudesk-master\node_modules\kareem\index.js:135:16
    at args.(anonymous function) (C:\USERS\ICUBOID\APPDATA\ROAMING\NPM\node_modules\pm2\node_modules\event-loop-inspector\index.js:138:29)
    at process._tickCallback (internal/process/next_tick.js:112:11)`
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Trudesk Version:1.0.2
- OS (e.g. from /etc/os-release):windows
- Node.JS Version:9.10.0
- MongoDB Version:4.0.4
- Is this hosted on cloud.trudesk.io:no

**Comment by polonel** [comment]
Did you manually edit the database?

It can not find any ticket types in your database and thus preventing the server from starting.

**Comment by eliyasbaby** [comment]
@polonel  No. for fixing this error i added manually one ticket type in db with id and name.after that at least my application got up.now the problem is its showing no user found.Do i want to do the same thing again?
or any alternatives is there for restoring my account.i think my mongodb got screwed up

**Comment by polonel** [comment]
Was this an existing deployment or fresh install? 

It seems like your MongoDB data is lost.

**Comment by eliyasbaby** [comment]
@polonel existing deployment only ,but doesn't have much data.and also some time i am getting error on npm start as "Address in use, exiting...".is it due to pm2 process manager?.ifi kill the processes  i got rid of this error.

**Comment by polonel** [comment]
@eliyasbaby No you cannot run the trudesk server under PM2 and standalone at the same time. PM2 monitors the process automatically and restarts it if it fails. 

Seems like your data has been modified outside of trudesk and has been wiped or seriously damaged.
If you have a backup I would restore, or start fresh.

**Comment by eliyasbaby** [comment]
@polonel  yes that was the problem.Thanks for your help.one last thing ,can we configure mailer in local or any http instance,why because i am getting error as error:CONNECTION on clicking test settings button.

**Comment by polonel** [comment]
I'm not sure I understand your questions.
You can configure the mailer to use any SMTP server.
