### ISSUE TITLE
Priority of tickets in ticket overview.

### ISSUE THREAD

**Issue by Play-Real** [polonel/trudesk#112]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ ] BUG 
- [ X] FEATURE

**What happened**:
When you look at the ticket overview.
it would be nice to see to be able to see the priority of tickets. 
and beeing able to order them to their priority. :)

**Comment by polonel** [comment]
![capture](https://user-images.githubusercontent.com/626303/49038311-96a55a80-f18a-11e8-843b-fa9b838314c5.JPG)

This color code on the left of each ticket is the color code set for the priority.

The priority sort / filter is part of the Elasticsearch featureset. I'll see how easily I can implement a sort.

**Comment by Play-Real** [comment]
Oops i did not see that. because all my tickets had the same priority. but sorting would be nice feature.
