### ISSUE TITLE
Any plans for knowledge base?

### ISSUE THREAD

**Issue by XcrossD** [polonel/trudesk#114]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ ] BUG 
- [x] FEATURE

As the title suggests, are there any plans for knowledge base in the future? I believe having a knowledge base can more or less help alleviate the inflow of new support tickets.

**Comment by polonel** [comment]
Yes. Its already started its development. Some other systems needed to be in place first (elasticsearch) to make the rollout work smoothly. It's coming! 😄

**Comment by XcrossD** [comment]
Nice. Is there an ETA for this next release? If not that's okay too. Thank you for creating this slick application.

**Comment by polonel** [comment]
Around January 2019

**Comment by XcrossD** [comment]
Awesome! Closing this because that's all I want to ask.
