### ISSUE TITLE
Not able to generate reports

### ISSUE THREAD

**Issue by eliyasbaby** [polonel/trudesk#115]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x ] BUG 
- [ ] FEATURE

**What happened**:on generating reports application got crash
TypeError: $document.createElement is not a function
    at downloadReport (4.js:11)
    at 4.js:11
    at vendor.js:29
    at n.$eval (vendor.js:29)
    at n.$digest (vendor.js:29)
    at n.$apply (vendor.js:29)
    at h (vendor.js:29)
    at K (vendor.js:29)
    at XMLHttpRequest.z.onload (vendor.js:29)

**What did you expect to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Go to Reports->generates->click any one of the option->select date and option->click  generate

**Anything else we need to know?**:

**Environment**:
- Trudesk Version:1.0.2
- OS (e.g. from /etc/os-release):windows
- Node.JS Version:9.10.0
- MongoDB Version:4.0.4
- Is this hosted on cloud.trudesk.io:

**Comment by polonel** [comment]
This has been fixed on `develop` just hasn't made its release on master yet. Its included in upcoming `1.0.3`

Please see #106

**Comment by eliyasbaby** [comment]
when are you going for the release 1.0.3?

**Comment by polonel** [comment]
This weekend. Saturday Night - Sunday Morning
12-1-2018 - 12-2-2018

**Comment by eliyasbaby** [comment]
will it contain a feature for scheduling reports generation and send to a particular user or group
