### ISSUE TITLE
Change Password Rest API call is failling

### ISSUE THREAD

**Issue by gaurav0914** [polonel/trudesk#123]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [X ] BUG 
- [ ] FEATURE

**What happened**:
Unable to change password via rest API
**What did you expect to happen**:
Change password should work but its not working i am sending request data in following format 
{
   "aUsername":       "KKG30",
    "aFullname":      "Kumar KKG30",
    "aTitle":         "EndUser",
    "aPass":          "password3",
    "aPassconfirm":   "password3",
    "aEmail":         "kkg30@trudesk.in",
    "aRole":          "User",
    "aGrps":          ["5babcbd272393708892ef7b0"]
              
}

  Getting error in response {"error": "Invalid ObjectId - UserSchema.GetUser()"}

**How to reproduce it (as minimally and precisely as possible)**:
Send the request data in format described above and check the response

**Anything else we need to know?**:
problem with API documentation of trudesk application each request should be checked and corrected.
**Environment**:test and development
- Trudesk Version:1.10 Virtual Appliance
- OS (e.g. from /etc/os-release):Alpine linux3.7 kernel 4.9.73-0-virthardend
- Node.JS Version:4.2.0
- MongoDB Version:3.6.3
- Is this hosted on cloud.trudesk.io:No

**Comment by gaurav0914** [comment]
![image](https://user-images.githubusercontent.com/40995164/50816219-e65c7180-1345-11e9-95d3-81fd87d21ce2.png)

**Comment by polonel** [comment]
I've tested this with multiple users and not seeing this error. The error linked in the screenshot isn't even in the API call for update users. It's in the call for `GET` on `/api/v1/users/{username}`

To update the password you can call:

`PUT` `/api/v1/users/andrew.rogers`
```json
{
	"aPass": "newpass",
	"aPassConfirm": "newpass"
}
```

![capture](https://user-images.githubusercontent.com/626303/50864499-394b1e80-1370-11e9-9593-a1b8d188f61d.JPG)

**Comment by gaurav0914** [comment]
Hi ,

Please reopen this case as still i am facing this issue.
I have tried passing the value suggested in the above screenshot but i am getting error "{"error": "Invalid ObjectId - UserSchema.GetUser()"}"

**Comment by gaurav0914** [comment]
![image](https://user-images.githubusercontent.com/40995164/50897498-4fb9ae80-1432-11e9-83e9-64612cf4a802.png)

**Comment by gaurav0914** [comment]
Can you please let me know what is missing

**Comment by polonel** [comment]
I suggest upgrading to the latest version. In your original post, you show you're running v1.10 which I believe to be version 0.1.10. It's a pre-release version. The latest version is 1.0.4. I cannot revert back to test on 0.1.10 because of the databases changes since then. Once the latest version is downloaded and rebuild it will automatically upgrade the database.

FYI version 1.0.5 will release this week.

**Comment by polonel** [comment]
[Annoucement: Trudesk v1.0.4 Release](https://forum.trudesk.io/t/annoucement-trudesk-v1-0-4-release/68)
