### ISSUE TITLE
Can't connect to server ( web socket )

### ISSUE THREAD

**Issue by earteza** [polonel/trudesk#125]
![image](https://user-images.githubusercontent.com/45551566/50955948-a2ec3980-14e4-11e9-99fa-9e26e1809535.png)
 
After Running sometimes , Truedesk got disconnected . 

Active online user 8 
close ticket 800+ 
Active ticket 3 

another issue here user continuously disconnected and connected 

![image](https://user-images.githubusercontent.com/45551566/50956297-869ccc80-14e5-11e9-95e5-588efc321d9d.png)

**Comment by polonel** [comment]
Does this happen when using chrome?

**Comment by earteza** [comment]
@polonel all user use Chrome

**Comment by polonel** [comment]
Can you try with the latest version of 1.0.5. An event leak was fixed that was causing the cpu to increase after.

**Comment by earteza** [comment]
@polonel  oky we will test and update you here

**Comment by polonel** [comment]
@earteza Are you behind a reverse proxy, such as nginx? Do you access the trudesk server directly using port 8118?

**Comment by polonel** [comment]
@earteza Please see https://forum.trudesk.io/t/excess-cpu-node/63
I'm curious to know if this is the same for you as well as far as using the android app. 
Much like in that thread I cannot reproduce the high CPU. I see it exists and I'm just trying to find the cause. I don't know if its a data issue causing it.

**Comment by polonel** [comment]
@earteza Correct. I have spent most of tonight refactoring all of the socket.io code to handle that event loop. If you don't mind, comment out this code https://github.com/polonel/trudesk/blob/master/src/socketserver.js#L93-L97 and give it a test to see if it still spikes (I have not been able to reproduce but I see where this could be an issue so I have already refactored) This will disable some automatic background UI updates.

If that seems to correct the problem, I know the refactored code will increase the performance greatly.

**Comment by earteza** [comment]
we are no longer have spike
CPU at 2% alway
loading page still have spike tho

we already comment out of that

and check this log and let us know is it possible to happen like this. when 1 account / 1 tab but a lot of log when disconnect and reconnect, is that possible leaking somewhere or something is not fully release make it stuck in there . check the time
it happens at the same time so it must be something leak and not fully released

`1/11 12:29:05 [68] - debug: User successfully connected: earteza
1/11 12:31:35 [68] - debug: User successfully connected: earteza
1/11 12:35:59 [68] - debug: User disconnected: earteza - VvETA5uEJLqhvq1zAAAD
1/11 12:35:59 [68] - debug: User disconnected: earteza - TYdll50NhIQsyb-8AAAE
1/11 12:35:59 [68] - debug: User successfully connected: earteza
1/11 12:35:59 [68] - debug: User successfully connected: earteza
1/11 12:35:59 [68] - debug: User successfully connected: earteza
1/11 12:35:59 [68] - debug: User successfully connected: earteza
1/11 12:35:59 [68] - debug: User successfully connected: earteza
1/11 12:35:59 [68] - debug: User successfully connected: earteza
1/11 12:35:59 [68] - debug: User successfully connected: earteza
1/11 12:35:59 [68] - debug: User successfully connected: earteza
1/11 12:35:59 [68] - debug: User successfully connected: earteza
1/11 12:35:59 [68] - debug: User successfully connected: earteza
1/11 12:36:02 [68] - debug: User successfully connected: namkazt
1/11 12:36:29 [68] - debug: User disconnected: earteza - Fwh2_DwqszhtBdMjAAAF
1/11 12:36:29 [68] - debug: User disconnected: earteza - 8NVcONp4zHiTgAMRAAAG
1/11 12:36:29 [68] - debug: User disconnected: earteza - F6cCej1WU15BnkcPAAAH
1/11 12:36:29 [68] - debug: User disconnected: earteza - 2KuJaY01QtRq__vdAAAI
1/11 12:36:29 [68] - debug: User disconnected: earteza - lBYJMP3dZlpf0kgZAAAJ
1/11 12:36:29 [68] - debug: User disconnected: earteza - V_sNVyPSHBM9o3AYAAAK
1/11 12:36:29 [68] - debug: User disconnected: earteza - svMvM8YJI9Af8bHdAAAL
1/11 12:36:29 [68] - debug: User disconnected: earteza - A_SC_LitRlOULXFLAAAM
1/11 12:36:29 [68] - debug: User disconnected: earteza - naTjXbcxQcqkcTBaAAAN`



Now : user is 2 , i can test around 8-10 user on sunday, cause office is close now

**Comment by polonel** [comment]
I believe I have fixed this in the refactor. I will push out a hotfix branch tomorrow that we can test this on. 

Will ping you when it's available. I appreciate all the assistance in helping identify this issue.

**Comment by earteza** [comment]
Oky , we will wait for you . .

**Comment by earteza** [comment]
![image](https://user-images.githubusercontent.com/45551566/51081673-7d973f80-171f-11e9-87c2-4efd0e03f060.png)
when creating new ticket, CPU performance went high peak 
even load page it raise like 10% CPU with our current server gen

**Comment by polonel** [comment]
The Warn on TPS not being enabled is just a simple warning in case your users were using the mobile app they would not receive push notifications.

I think the issue is not so much when creating the ticket but the server has to send out notifications to multiple clients that aren't "really" connected. If a user is only using one device with one session, it should not connect them more than once. I haven't experienced that issue on any of my deployments. I wonder if you have a Load Balancer in front of your server that doesn't have `sticky sessions` enabled. 

I will have the WebSocket refactor pushed out for testing tomorrow.

**Comment by earteza** [comment]
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'archiver'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\Administrator\Documents\radidesk\src\backup\backup.js:19:16)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)

```
error on backup.js (edited) 
maybe missing dependency ?

**Comment by polonel** [comment]
The socketio refactor is on branch `refactor` for testing.

**Comment by earteza** [comment]
![image](https://user-images.githubusercontent.com/45551566/51098300-abe64f00-17f3-11e9-8545-0107795cf836.png)

issue not fixed after update.

**Comment by earteza** [comment]
is there any way we can use your BOT in our system ? We need to test 8-10 user outside of our network to make sure that our network system have issue or not .

**Comment by polonel** [comment]
Can you join me on Slack? https://trudesk.slack.com

**Comment by polonel** [comment]
Issue resolved over slack.

Increase socket.io pingTimeout.
