### ISSUE TITLE
connect to the mongo db database.

### ISSUE THREAD

**Issue by AnderLyws** [polonel/trudesk#127]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
I can not connect to mongodb
**What did you expect to happen**:
Install
**How to reproduce it (as minimally and precisely as possible)**:

When I try to connect with mongodb, an error occurs. I'm using MacOS. I checked on some issues, people with the same problem and until somebody made to set the mongodb to trudesk. Could someone explain me better because I could not find documentation or some tutorial for this problem.

**Anything else we need to know?**:
No
**Environment**:
- Trudesk Version:1.0.5
- OS (e.g. from /etc/os-release):MacOs Sierra
- Node.JS Version:10.14.2
- MongoDB Version:4.0.5
- Is this hosted on cloud.trudesk.io: No
<img width="643" alt="captura de tela 2019-01-16 as 12 20 17" src="https://user-images.githubusercontent.com/36680211/51255208-e8e44a00-1989-11e9-97ad-f15c1d184de7.png">

**Comment by polonel** [comment]
This is not a big. You haven’t enabled auth or MongoDB or setup the Trudesk user within MongoDB and given it dbOwner, readWrite permissions.

Please refer to the MongoDB documentation for enabling auth and creating a user for your platform and version.

If you have trouble with this I provide many options to get Trudesk up and running with zero configuration on your side. Including a one liner Ubuntu script and a fully deployed Virtual Appliance.

**Comment by AnderLyws** [comment]
Thank you, you became more objective. I was able to install.

**Comment by bert3ch** [comment]
facing the same problem. Server is on Virtualbox. someone can help please ?  can not connect via mangoshell too.
I m stuck.
