### ISSUE TITLE
[BUG] Use of RegEx is high performance hit and unnecessary.

### ISSUE THREAD

**Issue by apboon** [polonel/trudesk#129]
Use of RegEx circumvents MongoDB's ability to rely on indexes. Maybe its better to add `lowercase: true` to the schema of the email address field and simply check against the lower-case value?

https://github.com/polonel/trudesk/blob/520a62b6fb4b42733f46991f09aab7a4e4367eae/src/models/user.js#L330

---
Here the use of RegEx is a major performance hit, making the application feel sluggish. Besides this, it also limits usability; if a ticket contains `companyname  123caseid` (accidental double space when the ticket was created), a search for `companyname 123caseid` (single space) or `123caseid companyname` won't yield any results.

https://github.com/polonel/trudesk/blob/master/src/models/ticket.js#L916

I recommend using MongoDB's full text search. Here's an example for creating an index:

```
schema.index(
 {
  'name.personal': 'text',
  'name.family': 'text',
  'name.display': 'text',
 },
 {
  name: 'name',
  weights:
   {
    'name.personal': 10,
    'name.family': 5,
    'name.display': 15,
   }
 });
```

In the example above I have given more weight to the display name, so that anything that matches the display name is prioritized.

Full text search also yields results when mistyping "companie" instead of "company". Not sure on the latest of MongoDB, but also might yield results when dealing with diacritics.

**Comment by polonel** [comment]
Perfect timing. I'm in the process right now of refactoring a lot of old outdated code from years back. You've spotted two great examples of that old code. I will get these refactored.

**Comment by apboon** [comment]
@polonel Congrats! :)
