### ISSUE TITLE
[FEATURE] Unable to group issues based on client's project.

### ISSUE THREAD

**Issue by apboon** [polonel/trudesk#132]
- [ ] BUG 
- [x] FEATURE

Trudesk focuses on a scenario in which issues can only revolve around the globally services (tags) offered by the owner (of the Trudesk instance). Currently there seems to be no way to group, view, manage or report issues per client service/application.

If client A has custom applications A, B and C, and client B has custom applications D, E and F, there is currently no neat way to group these, or for these clients to specifically report issues for these specific client applications.

In the context of doing projects for a customer (which has a shorter life cycle compared to an application), it would be great if able to integrating with other services. It would be ideal if I could automate updating the list of applications/projects people can report issues on.

For the moment, the only solution I can think of now is to disable the issue creation window, and create a separate form outside of the application where I can require people to select from a list of projects relevant to them. But it would be grand if this is possible from within Trudesk.

**Comment by polonel** [comment]
I think this will get resolved when custom ticket fields get implemented. It will allow Admins to create additional fields on the ticket object/form. The issue I see assigning that custom form to the end user group. On the plan, I have the custom ticket fields being set via which ticket type was selected, but may need to look at custom ticket forms entirely. Allowing a drop down of applications to populate based on user groups. 

Or make tags assignable to user groups.

**Comment by apboon** [comment]
Nooooooohh stale-bot! Please don't close this issue! :S
I'll give you candy?
