### ISSUE TITLE
[FEATURE] Unable to edit the subject of an issue.

### ISSUE THREAD

**Issue by apboon** [polonel/trudesk#133]
- [ ] BUG 
- [x] FEATURE

Users don't think in technical terms. They just have a problem and just want you to fix it. Too often users only muster a "Doesn't work". After deciphering the content of the issue, a helpdesk technicians often changes the subject of an issue to contain something more descriptive, also to better identify issues in the overview.

Unfortunately this is not possible yet. One a ticket has a non-descriptive subject (looking very similar to other tickets), you're unable to change it :P

I suspect this can be fixed quite easily, and would make Trudesk more versatile.

**Comment by polonel** [comment]
Yes, this has been neglected and I'm aware. Its been a limitation of my daily use of trudesk as well. I'll get it done.

**Comment by apboon** [comment]
Your additute is admirable ^^
