### ISSUE TITLE
[QUESTION] File uploads in ticket creation

### ISSUE THREAD

**Issue by AnderLyws** [polonel/trudesk#135]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ ] BUG 
- [X] FEATURE

**What happened**: In order to improve the creation of the tickets it would be interesting to make uploads of files already in the creation without being necessary to enter after the ticket is created to attach the files. 

**What did you expect to happen**: I'm trying to implement upload files, but having difficulties in making it work. Has anyone tried this and how did it?

**How to reproduce it (as minimally and precisely as possible)**:

<img width="605" alt="captura de tela 2019-01-24 as 11 37 39" src="https://user-images.githubusercontent.com/36680211/51682733-44888600-1fcf-11e9-83c5-d7f08e14b56e.png">

**Comment by polonel** [comment]
Please see #122 

This was implemented in the ticket creation window latest night. It will support inline images. 
I plan to support uploading files, but for now, it will online support inline images until I refactor ticket creation.

**Comment by fabarr** [comment]
Hello, thanks for the informations. When do you have in plan to support uploading files? It will be very usefull for the project i work in. thanks a lot.

**Comment by polonel** [comment]
Uploading files are already implemented, just not during ticket creation. Inline image uploads are implemented in both ticket creation/updating. I don't want to confuse anyone into thinking that it is not possible to upload files, it just requires an extra step right now until the ticket creation process is refactored.

**Comment by fabarr** [comment]
@polonel
Thank you. I'm configuring system and i will test it. Thanks

**Comment by julienveliarun** [comment]
> @fabarr
> Uploading files are already implemented, just not during ticket creation. Inline image uploads are implemented in both ticket creation/updating. I don't want to confuse anyone into thinking that it is not possible to upload files, it just requires an extra step right now until the ticket creation process is refactored.

what is this extra step you are talking about, where is it in the actual code? pls

**Comment by polonel** [comment]
Ticket attachments are stored with the ticket object in the underlining database. The uploading of the file happens when the attachment is selected. As it stands right now this process doesn't work for ticket creation due to the fact that the ticket isn't created yet so it can't store the uploaded attachment within the uncreated ticket.

**Comment by julienveliarun** [comment]
So it should work on ticket updating ?

**Comment by polonel** [comment]
I'm not sure what you mean? Ticket attachments (including PDFs) are implemented on the single ticket page by clicking the paperclip icon on this issue.

![image](https://user-images.githubusercontent.com/626303/59738425-331a7180-922f-11e9-8c09-876a8af6510a.png)

**Comment by julienveliarun** [comment]
This doesn't seem to work for me

**Comment by polonel** [comment]
Create a new issue. I'll look into it. I'm not in a position to check right now.

**Comment by julienveliarun** [comment]
![report](https://user-images.githubusercontent.com/45491044/59739166-d17cf600-9274-11e9-9d90-29dee28e8a32.gif)

The file is not uploaded

**Comment by chandrashekhar-ar** [comment]
Is there an option to attach a file after ticket creation using API?
