### ISSUE TITLE
Title attribute on buttons

### ISSUE THREAD

**Issue by 0x3333** [polonel/trudesk#138]
- [X] BUG 
- [ ] FEATURE

**What happened**:
None of the buttons have the title attribute set. This is very annoying because a newbie will have problems identifying what a button does.

**What did you expect to happen**:
Hovering a button, a short description of what it does.

**How to reproduce it (as minimally and precisely as possible)**:
Just hover some button, none have the title attribute.

**Anything else we need to know?**:
I can work on a PR, but I need some directions, there are not contribution guidelines, I don't know if you guys accept PRs.

**Environment**:
- Trudesk Version: 1.0.5 
- OS (e.g. from /etc/os-release):  Alpine Linux v3.8
- Node.JS Version: v10.10.0
- MongoDB Version: v3.7.0-4757-gc31a4d0fd5
- Is this hosted on cloud.trudesk.io: No, Docker container

**Comment by polonel** [comment]
Thank you for reporting this issue. I have already started implementing this request.

The project does indeed accept pull requests and the contribution guidelines are still being written. A major code shift is already being worked on that will affect this. (I'm dropping Angular 1.7 and refactoring to React)

**Comment by 0x3333** [comment]
That's great! 
So, I'll wait, as you already implemented in the new version.

Thanks!

**Comment by 0x3333** [comment]
Is that possible to run the Development version in a container? Is there any workaround? 
I'll try in a couple of hours, but would like to get a heads-up.

**Comment by polonel** [comment]
Not easily. The Docker container is built off the `docker` branch, which gets merged with `develop` branch right before an update is released. You would have to merge develop into docker and then build the docker image once it's done.

I will be merging them this weekend with release `1.0.6`

**Comment by 0x3333** [comment]
I see! Ok, I'll wait then. Thanks!
