### ISSUE TITLE
[Feature] MailFetch Abilities, Users & Groups, File Upload Types

### ISSUE THREAD

**Issue by tmswr** [polonel/trudesk#140]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ ] BUG 
- [X] FEATURE

**What happened**:

1. User accounts are automatically registered and added to groups. There should have the option to utilize MailFetch, but not create a user account or automatically add them to a user group.
2. Allow more file types for upload. I see this is being implemented, but so far all I can get to upload is .jpg files (we can get excel sheets, for example).

**What did you expect to happen**:

1. The ability for users to submit tickets via email, not be added as a user or group. For example, Spiceworks allows tickets via email, not creating a user. Ticket updates get sent the user who submitted the tickets via email. This would allow a clean user group, which would be very nice.
2. Users to be able to upload files via email for MailFetch in various formats.

**Anything else we need to know?**:

Will you be offering beta testing for new versions? Looking to implement this and replace Spiceworks. The ability to customize wording of pages (i.e. "New Issue" on ticket submission via online url) would be very helpful.

**Environment**:
- Trudesk Version: 1.0.5
- OS (e.g. from /etc/os-release): Windows 10
- Node.JS Version: 10.15.0
- MongoDB Version: 4.0.5
- Is this hosted on cloud.trudesk.io: No

**Comment by tmswr** [comment]
Let me elaborate on what our current process is within Spiceworks:

1. We have a designated email where people can submit a ticket using the subject line, body, and attachments. This works much like the current Mail Fetch feature.

2. Spiceworks doesn't save users or user groups, which is a feature we are wanting (you've implimented). Because there is no information on the user, all updates are sent to the email address that created the ticket. From there, the end user gets updated via Email used to create the ticket and can reply through email so all updates are kept in one thread. This process can happen multiple times in our company, often with new attachments added throughout the process. 

Is there a way to change the interval at which Mail is fetched? 

<hr>

We are currently wanting to utilize User Groups for departments of the company who respond to tickets which would work great with the reporting you have. For example, two departments who primarly use our current ticketing solution are:

- IT Department
- Creative Services

I understand the need to assign new users to a group, so a suggestive solution would be to automatically assign all new users to a specific group? Maybe something like "Users", although this would effect the notification settings. It would be nice to have "Send notifications to creator of ticket" option. 

I'm not sure how you could impliment this if you want to, but it is a system a lot of Spiceworks people are currently use to.

<hr>

On attachments, I think Office file extentions would be a great addition as we see a lot of images, but also get a ton of Word documents, Excel sheets, etc. 

<hr>

When the option to submit tickets publically is switched on, you're brough to the pace host/newissue which has predefined text, like a header that says "New Issue". I think the wording/url should be customizable in case something like a new Graphic is being requested, which is not an issue but is a ticket.

**Comment by polonel** [comment]
Thank you for clarifying. I have a better understanding of what you're looking for. Right now this is a design flaw that has already begun its refactor. Basically, groups were implemented in a while to house which users had access to which tickets. As the project grew, this became a problem. Please see https://forum.trudesk.io/t/agent-system-redesign/34 for more information on this issue. With these changes it will allow for things as you request; Its just not there yet but its actively being worked on.

The interval for the mail fetch is configurable in the next release.

I'll get the office attachments added.

Thanks for clarifying which pages you were requesting be customizable. This can be done but will probably be tied to the knowledge base when it hits develop. 
In the meantime you can customize the template if you want, located here:
https://github.com/polonel/trudesk/blob/master/src/views/pub_createTicket.hbs

**Comment by tmswr** [comment]
The system redesign is exactly what we are looking for! I know it's very early in development, but there goal in mind for implementation for the first phase of changes? 

If you ever need some UI work, I'd be glad to help out whichever way I can.
