### ISSUE TITLE
[Docs] Update documentation for getting groups

### ISSUE THREAD

**Issue by basavarajvs** [polonel/trudesk#142]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [X] BUG 
- [ ] FEATURE

**What happened**:
The Group API mentioned in the documentation is wrong at http://trudesk.io/v1/api/#Get-1 
It is currently typed as

curl -H "accesstoken: {accesstoken}" -l http://{url}/api/v1/group/all

whereas the api is
/api/v1/groups/all

Please note that the curl request mentions "group" instead of "group**s**"

**What did you expect to happen**:
Please update the documentation to
curl -H "accesstoken: {accesstoken}" -l http://{url}/api/v1/groups/all

/api/v1/groups/all
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
URL to access site is 
http://trudesk.io/v1/api/#Get-1

**Environment**:
- Trudesk Version:
- OS (e.g. from /etc/os-release):
- Node.JS Version:
- MongoDB Version:
- Is this hosted on cloud.trudesk.io:

**Comment by polonel** [comment]
Thanks. I have fixed the typo.
