### ISSUE TITLE
[FEATURE] Mentioning file name in issue description to show attached image in place of image name.

### ISSUE THREAD

**Issue by apboon** [polonel/trudesk#143]
- [ ] BUG 
- [x] FEATURE

It would be wonderful if mentioning the image filename in the issue description would cause the image filename to be replaced with the image. It's a small little feature with loads of benefits :) a quick win.

**Comment by polonel** [comment]
How would this work exactly? Are you talking about files located on your local system? Trudesk would need to scan every _potentional_ filename in the body then search for that file locally before ever uploading it to the server.

I may be a little confused on what you're requesting. Correct me, but I believe you're requesting something like this:

Ex:
This is my issue text. Please see _**myissue.jpg**_ for more information.

**Comment by apboon** [comment]
Greatings polonel! :)

I meant something different. Namely, after you've created an issue, and attached an image to that issue, your issue would look like this:

![image](https://user-images.githubusercontent.com/5346609/53570584-25998880-3b67-11e9-9dd7-40d97909dbe3.png)

It would be nice of some JavaScript would simply add an `<img />` at the end of the message if the attachment is a JPEG or PNG.

Or when the filename of the attachment is detected within the body of the image, simply inject the `<img />` element there.

A little piece of (almost finished) JavaScript code what would run in the browser (not changing the issue's body in the database):

```javascript
let strIssue_Body = `Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                     webp_image.webp
                     Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`;

let arystrIssue_Attachment_Path =
 [
  'attachment/webp_image.webp',
  'attachment/png_image.png',
  'attachment/jpeg_image.jpeg',
  'attachment/msdos8.3.jpg',
 ];


// For each attachment.
arystrIssue_Attachment_Path.forEach(strIssue_Attachment_Path =>
 {
  if (!strIssue_Attachment_Path.match(/\.(webp|jpe?g|png)$/))
   {
    // Abort if not an image.
    return;
   }
  // Is an image.


  let strIssue_Attachment_Name = strIssue_Attachment_Path.replace(/^.*\//);
  let strIssue_Attachment_Image_Element = '<img src="' + html_entity_encode(strIssue_Attachment_Path) + '" alt="' + html_entity_encode(strIssue_Attachment_Name) + '" />';

  // First attempt: Try to insert `<img />` tag before image name. Placing the image name in plain text underneath the inserted image.
  let strIssue_Body_Modified = strIssue_Body.replace(strIssue_Attachment_Name, strIssue_Attachment_Image_Element + ' ' + strIssue_Attachment_Name);

  // If not modified..
  if (strIssue_Body.length === strIssue_Body_Modified.length)
   {
    // Fall back: Add `<img />` tag at the end of the issue body.
    strIssue_Body_Modified = strIssue_Body + ' ' + strIssue_Attachment_Image_Element;
   }

  // Make modified issue body final.
  strIssue_Body = strIssue_Body_Modified;
 });
```
