### ISSUE TITLE
[QUESTION] Does not connect mongodb Version 1.0.6

### ISSUE THREAD

**Issue by AnderLyws** [polonel/trudesk#145]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [X] BUG 
- [ ] FEATURE

I'm having a problem installing version 1.0.6. Trying to connect the mongodb takes in the connection part until it gives an error that could not connect.
As the image shows, when I do the yarn command this error appears in the "warning" message.
Version 1.0.6 
![captura de tela 2019-02-11 as 09 03 10](https://user-images.githubusercontent.com/36680211/52562221-fc49d000-2de4-11e9-82e1-694a1c45163b.png)

I also checked the mongo terminal for this information.
![captura de tela 2019-02-11 as 09 41 09](https://user-images.githubusercontent.com/36680211/52562272-27ccba80-2de5-11e9-95e0-39947bd11603.png)

I already tested with version 1.0.5 and the installation takes place perfectly and without the error in the yarn command.
Version 1.0.5
![captura de tela 2019-02-11 as 09 48 19](https://user-images.githubusercontent.com/36680211/52562314-46cb4c80-2de5-11e9-84b1-f65ed3e97548.png)

![captura de tela 2019-02-11 as 09 51 28](https://user-images.githubusercontent.com/36680211/52562325-5185e180-2de5-11e9-8757-e57245d0b542.png)

Can someone help me?

**Environment**:
- Trudesk Version:1.0.5 /1.0.6

**Comment by polonel** [comment]
More information is needed. What you see in the yarn console is not an error it's a `devdependency`  warning. I'm not sure where you say the install script is failing. Also if you already had 1.0.5 installed upgrading to 1.0.6 doesn't require the install script again and pulls the same configuration. I do not see an error in the information you provided.

**Comment by AnderLyws** [comment]
So I did not have a version 1.0.5, implemented at the moment, so I'm doing it initially at 1.0.6. Have you checked for first installation everything is going well?

Sorry for my ignorance, but I do not have much development experience.
I tried to do the installation on windows, with nodejs, mongodb and git installed and at the time of running the **yarn** command, the same error occurs **"> eslint-plugin-prettier@3.0.1" has unmet peer dependency "prettier @> = 1.13.0 "**. and many others that interrupted the installation because so much error that I was a little stunned.
The following image: 
![sem titulo](https://user-images.githubusercontent.com/36680211/52823895-c5eaaa00-309d-11e9-8b8a-81e7d6770240.png)


If you can see for me if everything is going well in the first installation, thank you. At work I tried in MacOs and at home Windows.

**Comment by polonel** [comment]
`eslint-plugin-prettier@3.0.1" has unmet peer dependency "prettier @> = 1.13.0`

This is not an error. It is a warning (as yarn states) that can be ignored. This plugin only gets installed on development as it is a `devdependency`.

The bcrypt error is occuring because you do not have windows build tools installed. So windows can not install/build native packages. https://www.npmjs.com/package/windows-build-tools

**Comment by polonel** [comment]
I would also like to recommened using the [Virtual Appliance](http://trudesk.io/v1/guide/installation.html#Virtual-Appliance), its already configured and ready to run in a virtualbox or vmware setup.
