### ISSUE TITLE
[Question] L2Auth

### ISSUE THREAD

**Issue by RickAag** [polonel/trudesk#146]
BUG REPORT 

As best as I am aware I did not select Level 2 Authentication.  However trying to login /l2auth is showing in url and it is asking for a code I have not setup. ... As only administrator I am locked out.

**Environment**:
- Trudesk Version: 1.06
- OS (e.g. from /etc/os-release): Ubuntu 18.04
- Node.JS Version:
- MongoDB Version:
- Is this hosted on cloud.trudesk.io: No

**Comment by polonel** [comment]
L2Auth is enabled in the profile page. Do you have the mailer enabled? If so you can click the “can’t login” link and it will reset your L2Auth setting. If the mailer is not enabled another admin can login and enabled the mailer, thus enabling the can’t login link.

**Comment by RickAag** [comment]
Mailed not enabled.  Did on purpose or to my knowledge click auth2 to be
on.  No link showing?

**Comment by polonel** [comment]
The can’t login link won’t show with the mailer disabled. It sends an email to your email address with reset link that’s generated at time of email.

**Comment by RickAag** [comment]
ah... yes... there is no other admin setup.  So is this a delete and
reinstall issue?

**Comment by polonel** [comment]
Is this issue resolved?

**Comment by RickAag** [comment]
it is on a hosted site i only have ssh access to.  i am now reading up on
mongodb to learn how to get in and fix it.

**Comment by polonel** [comment]
Was this issue ever resolved?

**Comment by RickAag** [comment]
Sadly family (3 young kids) came down with flu... just now better.  I
honestly had not had a chance to work on it.  My server is on Digital
Ocean.  Not sure how to remotely analyze mongodb to make changes you
mentioned.  As most of my experiance has been with mysql dbs in past.   I
do greatly appreciate you interest in helping and following up.

Rick
