### ISSUE TITLE
[Question] login to mongdb mLab

### ISSUE THREAD

**Issue by yadacompany** [polonel/trudesk#147]
Hello, 

Thank you guys for this tool that seem great! I am trying to install it on a heroku server with a free mongodb.com base. But despite all my trials I keep getting this "couldn't connect, make sure connection is correct" error (see full console error below)
i've tried both on a local version and on a heroku version. 
i've created my trudesk user with write rights on a trudesk database created in my cluster.

I looked into the src/ install.js code and understood it's building the URI with the mongodb:// protocol from the install input fields. 

But in the mongodb interface, they provide a different protocol, mongodb+srv://
 Otherwise, according to mongdb documentation, there are 3 different servers we need to input for the mongodb:// protocol

So sad there is not more documentation on install :-), it indicates weshould use mLab but impossible to make it work from that!

thanks if you have any idea where this come from, I've searched for hours

---- Console error
VM132:1 POST http://0.0.0.0:8118/install/mongotest net::ERR_CONNECTION_REFUSED
(anonymous) @ VM132:1
send @ vendor.js:39
ajax @ vendor.js:39
(anonymous) @ install:502
dispatch @ vendor.js:39
elemData.handle @ vendor.js:39
install:518 
====

im running on a mac with the latest mongodb from the mLab service

**Comment by polonel** [comment]
The problem you show in the console isn't with MongoDB. It is trying to make a POST request to 0.0.0.0 which is not a valid IP address. 

**How are you accessing the Install Wizard?**

I can not speak for heroku but I run my development Mongo from mlab so I'm sure it works with mlab directly.

**Comment by yadacompany** [comment]
Thank you polonel for your quick reply

I actually tested locally when I got this error,
According to the [Trudesk](https://trudesk.io/v1/guide/installation.html) installation guide 0.0.0.0:8118 is my local adress to access trudesk.
Though the error does not appear this morning (maybe the server went down last night), I just get an object back (screenshot https://ibb.co/G5x7xfx  ) and the connection error popup.

As I found no trace of "srv" in the code, I deduct we need to use the standard mongodb connection URI to connnect, which uses a replica set instead of DNS seedlist like accessed

So my Atlas connection URI ressembles:
mongodb://admin:<PASSWORD>@SERVER-shard-00-00-h9rbq.gcp.mongodb.net:27017,SERVER-shard-00-01-h9rbq.gcp.mongodb.net:27017,SERVER-shard-00-02-h9rbq.gcp.mongodb.net:27017/trudesk?ssl=true&replicaSet=grafox-shard-0&authSource=admin&retryWrites=true

What should I input in the Trudesk host field then? It might come there there ? :-)

Thanks

**Comment by polonel** [comment]
Short answer: Replica Sets are not supported yet during install. 

I've tested with a replica set after the install was complete. It requires advanced configuration with the `CONNECTION_URI` after the initial install is done. 

The install wizard builds the connection string which does not support multiple hosts.

You can set the connection string fully with the environment variable `MONGOHQ_URI` but you would need to do this after the initial install. 

I have not tested replica sets in a while but you can try:

Host: **SERVER-shard-00-00-h9rbq.gcp.mongodb.net**
Port: **27017**
Username: **admin**
Password: _You're Password_
Database: **trudesk**

If that allows you to complete the install you can set the env var `MONGOHQ_URI` to 
```
mongodb://admin:@SERVER-shard-00-00-h9rbq.gcp.mongodb.net:27017,SERVER-shard-00-01-h9rbq.gcp.mongodb.net:27017,SERVER-shard-00-02-h9rbq.gcp.mongodb.net:27017/trudesk?ssl=true&replicaSet=SERVER-shard-0&authSource=admin&retryWrites=true
```

Then restart trudesk.

_I'm not sure this will work, I'm not in a position to test it right now._

**Comment by yadacompany** [comment]
Actually that thought the right way to me and that's what I tried but it never worked

Host: **SERVER-shard-00-00-h9rbq.gcp.mongodb.net**
Port: **27017**
Username: **admin**
Password: _You're Password_
Database: **trudesk**

Weirdly, I just finally succeeded to logged in with this config:

**host:** <SERVER>-shard-00-00-h9rbq.gcp.mongodb.net,<SERVER>-shard-00-01-h9rbq.gcp.mongodb.net,<SERVER>-shard-00-02-h9rbq.gcp.mongodb.net
**Port:** 27017
**user:** your user with access to your DB
**password :** your user password
**Database:** <DB>?ssl=true&replicaSet=<SERVER>-shard-0&authSource=admin&retryWrites=true

Mistery remains! :-)
Thanks for your help
