### ISSUE TITLE
[Question] localization turkish language

### ISSUE THREAD

**Issue by meteyalciner** [polonel/trudesk#148]
i want to download turkish language files from crowdin and how i change language to turkish thankyou for your intrested .
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ ] BUG 
- [ ] FEATURE

**What happened**:

**What did you expect to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Trudesk Version:
- OS (e.g. from /etc/os-release):
- Node.JS Version:
- MongoDB Version:
- Is this hosted on cloud.trudesk.io:

**Comment by polonel** [comment]
The localization is not fully implemented yet. Its current on branch `feature/i18n` 

You would have to switch to that branch and load in the download locales from crowdin in the `locale` directory.

**Comment by meteyalciner** [comment]
ok thanks

**Comment by HoseinGhanbari** [comment]
> The localization is not fully implemented yet. Its current on branch `feature/i18n`
> 
> You would have to switch to that branch and load in the download locales from crowdin in the `locale` directory.

I think this should be noticed on README.md on project root.
