### ISSUE TITLE
[Question] Couldn't know how to get access token via API 

### ISSUE THREAD

**Issue by nithya-cc** [polonel/trudesk#149]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
    Am trying to create the account & ticket from API. But I didn't know where can I get the access token to create the ticket from API
**What did you expect to happen**:
   I wanna to get the access token from the API not login to website & copy paste from the website. 

**How to reproduce it (as minimally and precisely as possible)**:
   Created the account by using API.
   Trying to create the ticket by using API- But I didn't know how to get the access token from API instead 
   of copy-paste from the website.

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: v1.0.5 (your master branch code)
- OS (e.g. from /etc/os-release):
- Node.JS Version: v8.10.0
- MongoDB Version:
- Is this hosted on cloud.trudesk.io:

**Comment by polonel** [comment]
Login endpoint: 
`/api/v1/login
``` json
{
  "username": "yourusername",
  "password": "yourpassword"
}
```
Returns access token and your user object.

**Comment by nithya-cc** [comment]
Thank you @polonel. It's working
