### ISSUE TITLE
[BUG] Account Import, Ticket view is partially displayed

### ISSUE THREAD

**Issue by basavarajvs** [polonel/trudesk#151]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [X] BUG 
- [ ] FEATURE

**What happened**:
In the development branch version : 1.0.7-beta , the import screen is not completely shown.
![image](https://user-images.githubusercontent.com/7840518/53004693-af56a100-3457-11e9-8f95-01a1253c9355.png)
The accounts screen is also not completely shown if accounts screen is selected after import
![image](https://user-images.githubusercontent.com/7840518/53004900-1c6a3680-3458-11e9-93fc-c5cd75801e07.png)

Also in the ticket view
![image](https://user-images.githubusercontent.com/7840518/53006085-8edc1600-345a-11e9-9b5d-fe1ebc989705.png)

**What did you expect to happen**:
The screens should display the content completely.

**How to reproduce it (as minimally and precisely as possible)**:
Go to accounts, Select the Red Icon at the bottom for adding Users, select Import
Selecting refresh from the browser on any of these views restore the complete content.

**Anything else we need to know?**:
This is in the development version 1.0.7-beta
Seems like this issue is common across multiple screens.

**Environment**:
- Trudesk Version: 1.0.7-beta
- OS (e.g. from /etc/os-release): OS-X
- Node.JS Version:
- MongoDB Version:
- Is this hosted on cloud.trudesk.io:

**Comment by basavarajvs** [comment]
Has it something to do with collapsible side menu..?

**Comment by polonel** [comment]
Yes. The whole sidebar was rewritten to react. I'll have a fix out soon.

**Comment by basavarajvs** [comment]
Tested and is fixed.
