### ISSUE TITLE
Moderators Cannot assign tags to already created tickets

### ISSUE THREAD

**Issue by akhlaaqbadulla** [polonel/trudesk#154]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
   Moderators cannot assign tags after tickets has been issued.

**What did you expect to happen**:
   i created 3 moderator accounts to overview the tickets in case there missing tags and such others. but 
   moderator nor support can assign ticket after the ticket has been created. only administrator can.

**How to reproduce it (as minimally and precisely as possible)**:
  Create a moderator user and create a ticket. when trying to assign a tag to a already created ticket it   
   will say error.

**Anything else we need to know?**:
   
**Environment**: Linux
- Trudesk Version: v1.0.6
- OS (e.g. from /etc/os-release): Ubuntu 18.04
- Node.JS Version: v11.9.0
- MongoDB Version: v4.0.6
- Is this hosted on cloud.trudesk.io: Hosted locally

**Comment by polonel** [comment]
Thank you for the report. The entire permission/role system has been rewritten. I've tested with the new system to make sure tags could be added to already created tickets. The focus is on the new role system which is currently in testing on develop. Won't be long.

Please see https://forum.trudesk.io/t/wip-upcoming-permission-update/106
