### ISSUE TITLE
[BUG] User role name not reflected in UI immediately after update.

### ISSUE THREAD

**Issue by basavarajvs** [polonel/trudesk#155]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [X] BUG 
- [ ] FEATURE

**What happened**:
Update of user role not reflected until refresh.

**What did you expect to happen**:
User role should be immediately reflected after the role change is saved.

**How to reproduce it (as minimally and precisely as possible)**:
1. Go to **accounts**.
2. Select an existing user
3. Select edit and Change the role to a different role than the existing one.
4. Save the changes.
5. Verify that the role is not updated for the User whose role was changed.
6. Refresh the browser and verify that the changes are reflected.

**Anything else we need to know?**:

**Environment**:
- Trudesk Version:1.0.7-beta
- OS (e.g. from /etc/os-release): OS-X
- Node.JS Version:
- MongoDB Version:
- Is this hosted on cloud.trudesk.io:

**Comment by polonel** [comment]
Accounts have been moved to react which fixes this issue. At its current state on develop (a180497), account creation has not been converted yet. Just be aware if you update the beta. Should be converted in a day or two.

**Comment by polonel** [comment]
Fixed in v1.0.7-beta
