### ISSUE TITLE
[BUG] Groups are not displayed while creating or view of ticket.

### ISSUE THREAD

**Issue by basavarajvs** [polonel/trudesk#156]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [X] BUG 
- [ ] FEATURE

**What happened**:
Groups are not listed while creating a ticket.

**What did you expect to happen**:
All available groups should be displayed while creating a ticket.

**How to reproduce it (as minimally and precisely as possible)**:
0. Login as an administrator.
1. Create a group and add members to it.
2. Select the create ticket option
3. The dropdown does not list any group other than the Administrator.

![image](https://user-images.githubusercontent.com/7840518/53073961-87c30f80-350f-11e9-816a-4770970eccf7.png)

The problem is also seen in the view ticket option. Only the administrator group is displayed.
![image](https://user-images.githubusercontent.com/7840518/53074008-a3c6b100-350f-11e9-8081-a4d7f5541838.png)

**Anything else we need to know?**:
Since ticket cannot be assigned to any group, assigning ticket to a User does not display ticket in his list.

**Environment**:
- Trudesk Version: 1.0.7-beta
- OS (e.g. from /etc/os-release): OS-X
- Node.JS Version:
- MongoDB Version:
- Is this hosted on cloud.trudesk.io:

**Comment by polonel** [comment]
Did you add yourself as a member of that group?

**Comment by basavarajvs** [comment]
I created 2 different users and added them into the group.
I am the admin and did not add myself to any of these groups.

**Comment by polonel** [comment]
I want to point out the limitations in the design and why it is being rewritten (https://forum.trudesk.io/t/agent-system-redesign/34/4)

Any user (admin, mod, support, user) will only have access or views of the tickets in their group. If any user is not a member of that group they will not have access to anything related to that group. Including not showing in ticket creation or updates. 

This is being addressed with the link above. As explained in the forum post, groups originally act as a bucket to store the users into and the tickets link to those groups to allow what users can see what tickets. It was a very flat design.

**Comment by basavarajvs** [comment]
Agree.. Will close this
