### ISSUE TITLE
[BUG] Customer groups menu item displayed for Support role users even when group permissions disabled

### ISSUE THREAD

**Issue by basavarajvs** [polonel/trudesk#157]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [X] BUG 
- [ ] FEATURE

**What happened**:
"Customer groups" menu item is displayed for users with "Support" role when the support role has no permissions for the group.
On selecting the menu item the dashboard is displayed.

**What did you expect to happen**:
"Customer groups" menu item should not be displayed for users with "Support" role.

**How to reproduce it (as minimally and precisely as possible)**:
1. Verify that support role does not have all "Customer groups" options disabled.
![image](https://user-images.githubusercontent.com/7840518/53075367-fce41400-3512-11e9-8626-55b0d2ced2b6.png)

2. Create a user with Support role.
3. Login as a user with Support role.
4. Verify that the "Customer groups" icon is displayed.
5. Click on the "Customer groups" menu item and verify that the Dashboard is displayed.

![image](https://user-images.githubusercontent.com/7840518/53075420-20a75a00-3513-11e9-96f2-c2f692f4a439.png)

**Anything else we need to know?**:

**Environment**:
- Trudesk Version:
- OS (e.g. from /etc/os-release):
- Node.JS Version:
- MongoDB Version:
- Is this hosted on cloud.trudesk.io:

**Comment by polonel** [comment]
I pushed a fix to develop, forgot to link the issue.

**Comment by basavarajvs** [comment]
Tested and is fixed.
