### ISSUE TITLE
[FEATURE]Want to run trudesk on different url "/support" need to change universal url of trudesk.

### ISSUE THREAD

**Issue by francisedulab** [polonel/trudesk#158]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ ] BUG 
- [x] FEATURE

**What happened**:
There is no way that we can change the trudesk solution to specific url because there is no constant configuration file where we can edit the url

**What did you expect to happen**:
example : abc.com is a website and if abc.com needs to use the trudesk solution and want to host it 
on abc.com/support then the login will route to abc.com/login and not abc.com/support/login

**How to reproduce it (as minimally and precisely as possible)**:
just create a angular/node applciation or any static website and serve it on port 80 on nginx
add this configuration to nginx file 
upstream node-myapp {
        server 127.0.0.1:4001; //url of the solution
}
server {
    listen       80;
    location / {
		proxy_set_header          Host $host;
		proxy_set_header          X-Real-IP $remote_addr;
		proxy_set_header          X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header          X-Forwarded-Proto $scheme;

		proxy_read_timeout        90;
		proxy_pass                http://node-myapp;
	}
     location ~ ^/(uploads/) {
                root /path/to/trudesk/public;
                access_log off;
                expires modified +1h;
        }
        location /support/ {
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_http_version 1.1;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $host;
                proxy_cache one;
                proxy_cache_key trudesk$request_uri$scheme;
                proxy_pass http://127.0.0.1:8118/;
        } 
   
}

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: 1.0.3
- OS (e.g. from /etc/os-release): Ubuntu 17.10
- Node.JS Version:9.10
- MongoDB Version:  v3.6.10
- Is this hosted on cloud.trudesk.io: no

**Comment by polonel** [comment]
Just curious. What's wrong with running it as a subdomain and virtual hosts in nginx?

**Comment by francisedulab** [comment]
We are hosting it on port 443 so everything like my nodejs my socket server
is running on it can't run all on https it works on http correctly but when
I try to shift it to https then these problems occur

**Comment by polonel** [comment]
I must be confused. I have multiple clients that run multiple services over 443 https. Using a cert from Let's Encrypt for each subdomain. With an nginx proxy between acting as a load balancer and serving the https cert. Not sure what you mean by "can't run all on https".

**Comment by bhaveshrao96** [comment]
PS E:\BhaveshWork\New_Project_30-12-2019\trudesk> nodemon
[nodemon] 1.19.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] starting `node ./app`
1/2 20:58:46 [12204] - info:     .                              .o8                     oooo
1/2 20:58:46 [12204] - info:   .o8                             "888                     `888      
1/2 20:58:46 [12204] - info: .o888oo oooo d8b oooo  oooo   .oooo888   .ooooo.   .oooo.o  888  oooo
1/2 20:58:46 [12204] - info:   888   `888""8P `888  `888  d88' `888  d88' `88b d88(  "8  888 .8P'
1/2 20:58:46 [12204] - info:   888    888      888   888  888   888  888ooo888 `"Y88b.   888888.
1/2 20:58:46 [12204] - info:   888 .  888      888   888  888   888  888    .o o.  )88b  888 `88b.
1/2 20:58:46 [12204] - info:   "888" d888b     `V88V"V8P' `Y8bod88P" `Y8bod8P' 8""888P' o888o o888o
1/2 20:58:46 [12204] - info: ==========================================================================
1/2 20:58:46 [12204] - info: trudesk v1.1.1 Copyright (C) 2014-2019 Chris Brame
1/2 20:58:46 [12204] - info:  
1/2 20:58:46 [12204] - info: Running in: development
1/2 20:58:46 [12204] - info: Server Time: Thu Jan 02 2020 20:58:46 GMT+0530 (India Standard Time)
1/2 20:58:49 [12204] - info: Trudesk Install Server Running...


Nothing happing after this
