### ISSUE TITLE
[Question] Generate accessToken via API

### ISSUE THREAD

**Issue by nithya-cc** [polonel/trudesk#159]
I am getting this error when trying to get access token via API
`data: { success: false, error: 'No API Key assigned to this User.' }`
**How to assign the access token for the newly created user via API?**

**Comment by polonel** [comment]
It should be done with the WebUI for now. In v1.0.7 all new users will have an accessToken generated during account creation.

**Comment by nithya-cc** [comment]
@polonel When can we expect that v1.0.7 release?

**Comment by polonel** [comment]
@nithya-cc It's being worked on nightly. Its current state is on the develop branch. (which is beta code)
