### ISSUE TITLE
[Question] Get all tickets for  the particular user via API

### ISSUE THREAD

**Issue by nithya-cc** [polonel/trudesk#160]
Is there any way to Get all tickets detail for the particular user via API?

**Comment by polonel** [comment]
When you say **for** the particular you, are you referring to the owner of the ticket or the user assign?

**Comment by nithya-cc** [comment]
@polonel  Owner of the ticket

**Comment by polonel** [comment]
There is no endpoint in v1 for this query. v2 will have a better filter on the ticket endpoint to support querying the owner of the ticket.

**Comment by nithya-cc** [comment]
@polonel When can we expect that V2 API?

**Comment by polonel** [comment]
@nithya-cc It may be a while. Its planned after the agent system which will be partially built off of apiv2.

**Comment by nithya-cc** [comment]
Okay, @polonel. I will try to do that. But one more question any default admin account is there once we installed true desk? If it's not how can I create the default account?

**Comment by polonel** [comment]
Yes. The default admin is created during the install wizard. 

![image](https://user-images.githubusercontent.com/626303/53394127-3df18380-396c-11e9-96e9-bd512fa0d994.png)
