### ISSUE TITLE
[Question] How to change the branch of the source in docker file?

### ISSUE THREAD

**Issue by nithya-cc** [polonel/trudesk#162]
If I want to install Trudesk with a Develop branch instead of the master in Docker. How can I do that?

**Comment by polonel** [comment]
If you're using docker you will need to switch to the git branch and build a custom docker image on that branch. 

**NOTE: That once you move to the develop branch it will convert your user roles and the only way back is through a backup.** Please see: https://forum.trudesk.io/t/wip-upcoming-permission-update/106
