### ISSUE TITLE
[BUG] Unable to add users from Admin

### ISSUE THREAD

**Issue by basavarajvs** [polonel/trudesk#163]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [X ] BUG 
- [ ] FEATURE

**What happened**:
There is no "add user" option available under accounts.

**What did you expect to happen**:
"Add user" option should be present under Accounts .

**How to reproduce it (as minimally and precisely as possible)**:
Login as admin
From the side menu visit Accounts

**Anything else we need to know?**:
This is on the dev branch.

**Environment**:
- Trudesk Version: 1.0.7-beta
- OS (e.g. from /etc/os-release):OS-X
- Node.JS Version:
- MongoDB Version:
- Is this hosted on cloud.trudesk.io:

**Comment by polonel** [comment]
Please see my comment in #155
