### ISSUE TITLE
uid is not auto incrementing when saving a new ticket

### ISSUE THREAD

**Issue by LuigiElleBalotta** [polonel/trudesk#165]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x ] BUG 
- [ ] FEATURE

**What happened**:
uid is always null when creating a new ticket from web api

**What did you expect to happen**:
uid should auto increment

**How to reproduce it (as minimally and precisely as possible)**:
make a web api call to api/v1/tickets/create

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: 1.0.6
- OS (e.g. from /etc/os-release): Win Server 2008r2
- Node.JS Version: 10.15.1
- MongoDB Version: 4.0.6
- Is this hosted on cloud.trudesk.io: nope

**Comment by LuigiElleBalotta** [comment]
this is the error: 
{"success":false,"error":{"driver":true,"name":"MongoError","index":0,"code":11000,"errmsg":"E11000 duplicate key error collection: trudesk.tickets index: uid_1 dup key: { : null }"}}

Also i've made a library for using with ASP.NET CORE: https://github.com/LuigiElleBalotta/TrudeskNetCore

This is what i'm doing from asp:
`public async Task<ActionResult> Salva(TicketRequest ticket)
        {
            var trudesk = new TrudeskManager();
            TicketCreateResponse ret = null;
            if(!ticket.subject.Contains($"[{CurrentUser.LastName} {CurrentUser.FirstName} - {CurrentUser.Id}] - "))
                ticket.subject = $"[{CurrentUser.LastName} {CurrentUser.FirstName} - {CurrentUser.Id}] - {ticket.subject}";

            if (string.IsNullOrWhiteSpace(ticket.owner))
            {
                ticket.group = "5c80e6dfb7e1470fbc710a94";
                ticket.owner = "5c80e6ccb7e1470fbc710a92";
                ticket.type = "5c7ce6ffdafd070e282bb3eb";
                ret = await trudesk.CreateTicket(ticket);
            }
            else
            {
                ret = await trudesk.UpdateTicket(ticket.id, ticket);
            }

            if (ret.success)
                return RedirectToAction("Elenco", "Tickets");

            return Json(ret.error);
        }`

**Comment by LuigiElleBalotta** [comment]
this is the error:
{"success":false,"error":{"driver":true,"name":"MongoError","index":0,"code":11000,"errmsg":"E11000 duplicate key error collection: trudesk.tickets index: uid_1 dup key: { : null }"}}

Also i've made a library for using with ASP.NET CORE: https://github.com/LuigiElleBalotta/TrudeskNetCore

This is what i'm doing from asp:

``
public async Task<ActionResult> Salva(TicketRequest ticket)
        {
            var trudesk = new TrudeskManager();
            TicketCreateResponse ret = null;
            if(!ticket.subject.Contains($"[{CurrentUser.LastName} {CurrentUser.FirstName} - {CurrentUser.Id}] - "))
                ticket.subject = $"[{CurrentUser.LastName} {CurrentUser.FirstName} - {CurrentUser.Id}] - {ticket.subject}";

            if (string.IsNullOrWhiteSpace(ticket.owner))
            {
                ticket.group = "5c80e6dfb7e1470fbc710a94";
                ticket.owner = "5c80e6ccb7e1470fbc710a92";
                ticket.type = "5c7ce6ffdafd070e282bb3eb";
                ret = await trudesk.CreateTicket(ticket);
            }
            else
            {
                ret = await trudesk.UpdateTicket(ticket.id, ticket);
            }

            if (ret.success)
                return RedirectToAction("Elenco", "Tickets");

            return Json(ret.error);
        }
``

**Comment by LuigiElleBalotta** [comment]
This is CREATETICKET function:
`
public async Task<TicketCreateResponse> CreateTicket(TicketRequest ticket)
        {
            HttpResponseMessage response = await HttpClient.PostAsJsonAsync("api/v1/tickets/create", ticket);

            response.EnsureSuccessStatusCode();

            TicketCreateResponse ret = JsonConvert.DeserializeObject<TicketCreateResponse>(response.Content.ReadAsStringAsync().Result);

            return ret;
        }
`

**Comment by polonel** [comment]
I can promise it's incrementing the UID. Its checked before the ticket even saves.
https://github.com/polonel/trudesk/blob/master/src/models/ticket.js#L107

I also tested with the API using postman and it returned the newly created ticket with the UID set.

Give it a test using postman.

**Comment by LuigiElleBalotta** [comment]
You don't have any clue why on the app is correct and using web api not? Because o think they use the same function but.. It continue give me null..

**Comment by polonel** [comment]
When using the API the newly created ticket is returned. It has the generated UID included in that ticket response. This is the same for both the app and the web api. See ScreenShot below.

![image](https://user-images.githubusercontent.com/626303/53993876-90fecf80-40fe-11e9-84f3-cf0511e6b7e3.png)

![image](https://user-images.githubusercontent.com/626303/53993914-b4297f00-40fe-11e9-9401-1d8c069f19b7.png)

**Comment by polonel** [comment]
In your TicketCreateResponse. Your Deserializing the response Ticket back to a TicketRequest. Which doesn't have the UID property, Thus making it Null. So your next request using that same TicketRequest from the TicketCreateResponse has a null UID that you're sending back to the server.

Also the properties on your TicketRequest are incorrect. Every property in the object should be sent as a string. The MongoDB Object IDs are not `int`

I have a working copy of your code with the correct Object Models.

**Comment by LuigiElleBalotta** [comment]
Hey polonel, morning, today at work i will modfiy things and test.. By the way i didnt delete counters Collection and the uid null is not in c# but directly on the row (sorry for the maybe not correct words, i come from mysql) of Mongodb table

**Comment by polonel** [comment]
I understand that there is a null UID that was saved to the database. The C# code (or at least the latest on github) was sending the TicketRequest to the server as a TicketUpdate with a null UID proptery (its not part of the TicketRequest). Trudesk was then saving this Ticket as an update to an existing Ticket. 
https://github.com/LuigiElleBalotta/TrudeskNetCore/blob/master/ElleTrudeskUtils/TrudeskManager.cs#L49-L60
This code here is sending the ID with a TicketRequest Object. Trudesk is taking that object and using its values to save overtop of the existing ticket with id passed to that function. When I tested your code I was getting ticket creation with a valid UID but when I used your code to update the ticket, the uid became null. 

Another note: v1 of the api uses a custom header for the accesstoken field and not the Authorization Header. I had to comment out this line https://github.com/LuigiElleBalotta/TrudeskNetCore/blob/master/ElleTrudeskUtils/TrudeskManager.cs#L24 and add:

``` c#
HttpClient.DefaultRequestHeaders.Add("accesstoken", Configuration.TrudeskAccessToken);
```

**Comment by LuigiElleBalotta** [comment]
Sorry polonel, i updated the repo with the code changes, now you should have the version i am using.. Can you check it?

**Comment by LuigiElleBalotta** [comment]
![trudeskerror](https://user-images.githubusercontent.com/16773213/54015019-ba5f4000-417e-11e9-948b-e2c48fd0eaa5.PNG)

This is my test with postman

**Comment by polonel** [comment]
In postman don't send as query parms. Send the payload as JSON in the Body.

**Comment by LuigiElleBalotta** [comment]
![errore2](https://user-images.githubusercontent.com/16773213/54015552-55a4e500-4180-11e9-84b4-0a6bc71e2673.PNG)

sigh....

**Comment by LuigiElleBalotta** [comment]
I restarted trudesk and now it's working.. strange.. but with postman, now i try with asp.net core

**Comment by LuigiElleBalotta** [comment]
With asp.net core i get:
`response.Content.ReadAsStringAsync().Result => {"success":false,"error":{"driver":true,"name":"MongoError","index":0,"code":11000,"errmsg":"E11000 duplicate key error collection: trudesk.tickets index: uid_1 dup key: { : null }"}}`

UPDATE: solved.
For Create and Update request i was sending the same object: TicketCreateRequest
TicketCreateRequest.cs was defined as:

```
public string   subject { get; set; }

public string   issue { get; set; }

public string   owner { get; set; }

public string   group { get; set; }

public string   type { get; set; }

public string   priority { get; set; }

public string[] tags { get; set; }

public string id { get; set; }

public int?    uid { get; set; }
```

The last 2 properties aren't ok for a create request, in fact the Trudesk application seems use that uid in any case, not using the function to auto increment its value.

In fact, for an update request that object is perfect.

So i removed the field id and uid from that class and i made a TicketUpdateRequest object.

By the way, this is a workaround. Why i say this? Because in every application i made, i send an object and based on the method i am calling, i take only the fields i really need, so i think Trudesk should know that it has to take the uid from the request only if i am calling an update function.. I'm not saying my method is the best, but i think it has no sense to get an id field in a logic where i'm creating something, simply because i am going to create that id

**Comment by polonel** [comment]
I agree with you that ID and UID should not be on a TicketCreateRequest. I'm not sure why you even had them on the request to start with. The documentation of the API doesn't even have them on the request.
http://trudesk.io/v1/api/#Create-3

You should have a Request object and a Response object. The Response object is where you're doing it wrong. You are parsing the response Ticket object back into a TicketCreateRequest. You should parse the response into the Ticket object. 
https://github.com/LuigiElleBalotta/TrudeskNetCore/blob/master/ElleTrudeskUtils/Entities/TicketCreateResponse.cs

``` c#
using System;
using System.Collections.Generic;
using System.Text;

namespace ElleTrudeskUtils.Entities
{
    public class TicketCreateResponse
    {
        public bool success { get; set; }
        public string error { get; set; }
        public Ticket ticket { get; set; }
    }
}
```
That ticket object is what holds the UID and ID. Not the TicketCreateRequest. I return the newly created ticket in the response.
