### ISSUE TITLE
JS-Files/CSS-Files comes from the wrong Site-URL

### ISSUE THREAD

**Issue by Hardenberg** [polonel/trudesk#169]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
the website doesn'd load the css or js-files 

**What did you expect to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

1. Configuration: General -> Site_URL -> 'http://aaa.local/support/'
2. pm2 restart trudesk -> everything is okay.
3. http://aaa.local/support/ -> in chrome or firefox 
-> Side is coming (200) over http://aaa.local/support/
-> js-File are coming over http://aaa.local/ -> without support.

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: 1.0.8
- OS (e.g. from /etc/os-release): debian 9 
- Node.JS Version: n latest 
- MongoDB Version: current 
- Is this hosted on cloud.trudesk.io: no

**Comment by akhlaaqbadulla** [comment]
It might help but i did this through my nginx config file.
 **Instead of :** 
`location / {
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_http_version 1.1;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $host;
                proxy_cache_key trudesk$request_uri$scheme;
                proxy_pass http://192.168.0.12:8118;
        }`

**i did :** 
location /support {
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_http_version 1.1;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $host;
                proxy_cache_key trudesk$request_uri$scheme;
                proxy_pass http://Your_IP:8081;
        }

**Comment by polonel** [comment]
Thanks for the information. I'll see about getting it added to the docs.
