### ISSUE TITLE
[BUG] Backup error

### ISSUE THREAD

**Issue by Pummelchen** [polonel/trudesk#172]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ X] BUG 
- [ ] FEATURE

**What happened**:
Settings > Backup > Backup Now

The result is an error message: "Error: [object Object]"

**What did you expect to happen**:
Guess a backup package should be prepared for download.

**How to reproduce it (as minimally and precisely as possible)**:
Try Settings > Backup > Backup Now

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: 1.0.9
- OS (e.g. from /etc/os-release): Windows 2019
- Node.JS Version: 11.12.0
- MongoDB Version: 4.0.6
- Is this hosted on cloud.trudesk.io: Nope

**Comment by polonel** [comment]
Is there an error displayed in the web browser console?

On Windows, the backup tools should download automatically during trudesk startup.

**Comment by Pummelchen** [comment]
`POST http://10.0.0.21/api/v1/backup 400 (Bad Request)
(anonymous) @ 6.js:21
module.exports @ 6.js:21
module.exports @ 6.js:61
Promise.then (async)
Axios.request @ 6.js:61
Axios.(anonymous function) @ 6.js:61
(anonymous) @ 6.js:21
api.settings.backupNow @ 9.js:15
(anonymous) @ 6.js:74
runEffect @ 6.js:74
next @ 6.js:74
currCb @ 6.js:74
(anonymous) @ 6.js:74
exec @ 6.js:21
flush @ 6.js:21
asap @ 6.js:21
(anonymous) @ 6.js:16
emit @ 6.js:16
(anonymous) @ 6.js:74
(anonymous) @ 6.js:54
(anonymous) @ 6.js:16
value @ 9.js:15
onClick @ 9.js:15
(anonymous) @ 6.js:37
ka @ 6.js:37
(anonymous) @ 6.js:37
xa @ 6.js:37
Ba @ 6.js:37
za @ 6.js:37
Ea @ 6.js:37
Gd @ 6.js:37
Th @ 6.js:37
Ob @ 6.js:37
Jd @ 6.js:37
Wh @ 6.js:37
Id @ 6.js:37
Show 5 more frames`

**Comment by Pummelchen** [comment]
TruDesk console:

`3/26 17:35:49 [Child:Backup:3452] - debug: 2019-03-26T17:35:49.636+0000 Failed: error writing data for collection `trudesk.notifications` to disk: error reading collection: Failed to parse: { find: "notifications", skip: 0, snapshot: true, $readPreference: { mode: "secondaryPreferred" }, $db: "trudesk" }. Unrecognized field 'snapshot'.`

**Comment by Aroshana123456** [comment]
how can i fix this backup error          =       error[object.object]

**Comment by polonel** [comment]
I believe this is an issue with mongo 4. As I'm using the mongodb 3.6 binaries to perform the dump.

@Pummelchen This feature uses mongodump to backup the mongo database. It also copies all the assets you have to the single zip file.

@Aroshana123456 Are you also on MongoDB 4.0? I have 3.6 on my dev machine and works fine.

**Comment by polonel** [comment]
This has been fixed in an upcoming release.
