### ISSUE TITLE
Apple application Freezing

### ISSUE THREAD

**Issue by akhlaaqbadulla** [polonel/trudesk#173]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
The application would not respond and wont even pull the tickets from the server.
would work fine from iphone 6 to 8 but would not respond and hang in iphone x and so forth..

**What did you expect to happen**:
Being able to manage, comment chqnge status of tckets normally.

**How to reproduce it (as minimally and precisely as possible)**:
install the trudesk ios applicqtion on iphone X etc...

**Anything else we need to know?**:
not the issue with iphone 6 to 8.

**Environment**:
- Trudesk Version: 1.0.9
- OS (e.g. from /etc/os-release): ubuntu 18.04 lts
- Node.JS Version: 8.11.3
- MongoDB Version: v4.0.7
- Is this hosted on cloud.trudesk.io: no

**Comment by polonel** [comment]
I’m not seeing this, I use an iPhone XS daily with Trudesk at my day job. 

Have you tried deleting the app and reinstalling?

**Comment by akhlaaqbadulla** [comment]
I reinstalled the application so far its seems stable. 
I will revert back to you after further testing. 

> Are there any errors showing the Nginx logs?
No the nginx log i clear. the request are serve without error. yet the application does not receive the requests.

Thank you.

**Comment by akhlaaqbadulla** [comment]
No more hiccups. After reinstalling
