### ISSUE TITLE
[BUG] Incorrect email link in password-reset template. (HTTPS)

### ISSUE THREAD

**Issue by obutov** [polonel/trudesk#174]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**: The site is publicly accessible over https and a custom port  (ngnix reverse proxy). When requesting a password reset through "Forgot your password", the email arrives with an incorrect link to reset password - https is replaced by http, and port is missing in the URL. Effectively, the link is invalid and the users will not be able to access the site.

**What did you expect to happen**: The email link should have correct site URL (with https and port).

**How to reproduce it (as minimally and precisely as possible)**: Publish site behind ngnix reverse proxy and enable SSL access on a custom port. Trigger password reset email.

**Anything else we need to know?**: Email that uses new "Ticket Created" template has correct URL, while the new (template) "Password Reset" email still contains incorrect URL. 

**Environment**:
- Trudesk Version: 1.0.9
- OS (e.g. from /etc/os-release): Windows 2008 R2
- Node.JS Version: 10.15.3 (x64)
- MongoDB Version: 4.0.6
- Is this hosted on cloud.trudesk.io: No

**Comment by polonel** [comment]
Thanks. I'll get the default template fixed.
