### ISSUE TITLE
[Help Request] Updating ticket status

### ISSUE THREAD

**Issue by LuigiElleBalotta** [polonel/trudesk#175]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
I am trying to update ticket status,  but i get an unexpected validation error

**What did you expect to happen**:
TIcket update

**How to reproduce it (as minimally and precisely as possible)**:
Make a postman request as in the screenshot
![UpdateTicket](https://user-images.githubusercontent.com/16773213/55219865-40aef500-5206-11e9-8151-701377b76215.PNG)

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: latest
- OS (e.g. from /etc/os-release): windows server 2008r2
- Node.JS Version: latest
- MongoDB Version: latest
- Is this hosted on cloud.trudesk.io: no

**Comment by polonel** [comment]
Its a bug in the request object. I fixed it but you can work around it for now with sending the group object as:
```json
{
  "group": {
    "_id": "<GROUPID>"
  }
}
```

**Comment by LuigiElleBalotta** [comment]
Thanks :)
