### ISSUE TITLE
Unable to access Trudesk From Windows Virtual desktops

### ISSUE THREAD

**Issue by akhlaaqbadulla** [polonel/trudesk#177]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
After hosting the application and signing it using letsencrypt. I cannot access it on windows virtual desktop on my windows server. i can acess it on the local machine browser but not the virtual desktop. be it in http or https both is unacessible.

**What did you expect to happen**:
being able to acess the web app throught the given link.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
the browser gives a wait time error and the console is clean.
the network part shows GET failed.

**Environment**:
- Trudesk Version:1.0.9
- OS (e.g. from /etc/os-release): ubuntu 18.04LTS
- Node.JS Version: v11.13.0
- MongoDB Version: v4.0.8
- Is this hosted on cloud.trudesk.io: NO

**Comment by Pummelchen** [comment]
Thats not a Trudesk bug but a configuration issue of your VM networking.
