### ISSUE TITLE
[BUG] The mobile app wont connect

### ISSUE THREAD

**Issue by akhlaaqbadulla** [polonel/trudesk#178]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
when login in into the ios app it says 

> error Could not connect. Please check server and try again.

Everything is connected and working i can access trudesk trought pc but the app fail to connect.
yet i have the issue where i cannot access trudesk from windows server virtual desktop but locally i can access the website. 

**Do i need to enable the mongodb port on the router as well?**

**What did you expect to happen**:
being able to connect to my account

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
-Trudesk Version:1.0.9
-OS (e.g. from /etc/os-release): ubuntu 18.04LTS
-Node.JS Version: v11.13.0
-MongoDB Version: v4.0.8
-Is this hosted on cloud.trudesk.io: NO

**Comment by polonel** [comment]
The mobile app currently has an http:// hardcoded prefix to the server field. This is getting resolved but not there yet. In the meantime, the workaround is to redirect the request to https through nginx.

**Comment by MortadhaFadhlaoui** [comment]
Hello @polonel, same for me, is that fixed?

**Comment by ToeiRei** [comment]
any updates here?

**Comment by jessequinn** [comment]
so to better understand the situation. the mobile app does not work?

**Comment by leonjuan** [comment]
It does work, just point to the http (non-ssl) URL (you can have a cname for that) or point directly to the public IP address.

**Comment by spydmobile** [comment]
Might be better to rename this issue to say:
[BUG] The mobile app wont connect to secure (HTTPS) Instance of Trudesk.

**Comment by polonel** [comment]
Apple has removed the app from its app store. This is backlogged until a new mobile app is created from scratch.
