### ISSUE TITLE
[BUG] Multiple similar role names

### ISSUE THREAD

**Issue by basavarajvs** [polonel/trudesk#179]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [X ] BUG 
- [ ] FEATURE

**What happened**:
There are multiple similar role names installed
Users
User
Also the roles cannot be changed after creating the user.

**What did you expect to happen**:
In earlier versions there was only the User option.

**How to reproduce it (as minimally and precisely as possible)**:
In the create user modal the Role option is displayed.
![image](https://user-images.githubusercontent.com/7840518/55400908-c0bdbd80-556c-11e9-8804-a940407bf546.png)

**Anything else we need to know?**:
The problem is seen in the development branch.
The roles cannot be changed after creating the user.

**Environment**:
- Trudesk Version: 1.0.10-beta
- OS (e.g. from /etc/os-release):OS-X
- Node.JS Version:
- MongoDB Version:
- Is this hosted on cloud.trudesk.io: no

**Comment by polonel** [comment]
Was an upgraded instance or a fresh deployment?

**Comment by basavarajvs** [comment]
This is a fresh deployment.
This issue was seen in the earlier version too.

**Comment by basavarajvs** [comment]
Is it because
src/controllers/install.js uses the term 'Users'
and
src/settings/defaults.js uses the term 'User'

**Comment by polonel** [comment]
Thanks for this. I'll get this fixed.
