### ISSUE TITLE
[FEATURE] Mount as an app

### ISSUE THREAD

**Issue by turnerhayes** [polonel/trudesk#180]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ ] BUG 
- [x] FEATURE

It would be nice if Trudesk could be mounted as an Express app on an existing Express(/Connect) app. In my thinking, one could install trudesk as a dependency (e.g. `npm install --save trudesk`) and then, in their app code, could do something like `app.use("/trudesk", require("trudesk"))`, and all the routes and such could be accessed at `/trudesk/<Trudesk API endpoint>`.

I don't know how self-contained the app really is, so this might end up being prohibitively difficult.

**Comment by polonel** [comment]
The would require the endpoints to be rewritten.
Can you describe a use case for this? So I can better understand the need in bundling it inside an application.

It is possible to achieve this with NGINX and proxy the request through.

**Comment by turnerhayes** [comment]
My use case is the following: I'm developing a web app to help me manage my condo that I'm renting, and I'd like to include a ticketing system to track issues (e.g. broken plumbing) along with the other features. Of course, I could deploy a separate instance of Trudesk and integrate it (whether through an iframe, a separate link, etc.), but it would be easier to not have to manage two different backends.

**Comment by polonel** [comment]
This is something that could be possible but not on the roadmap. If trudesk's core every splits into multiple components it would make more sense. ex. serve the API on its own backend and you can integrate your own UI to fit your design.

I think its best (for now) to just serve both applications through NGINX and have NGINX route the request to the correct backend based on URL.

**Comment by turnerhayes** [comment]
That seems reasonable; I figured it would probably be a tall order, just wanted to put it on the radar.
