### ISSUE TITLE
[BUG] Error 400 while doing Backup

### ISSUE THREAD

**Issue by LuigiElleBalotta** [polonel/trudesk#183]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
Returned Status Code 400 while doing backup

![Error400](https://user-images.githubusercontent.com/16773213/55791805-9d8c9400-5abf-11e9-9c78-cdc7eaab44b4.PNG)

**What did you expect to happen**:
No error, StatusCode 200

**How to reproduce it (as minimally and precisely as possible)**:
Settings -> Backup/restore -> Backup Now

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: 1.0.10
- OS (e.g. from /etc/os-release): Windows Server 2008 r2
- Node.JS Version: latest
- MongoDB Version: latest
- Is this hosted on cloud.trudesk.io: no

**Comment by polonel** [comment]
This has been fixed in an upcoming release.
