### ISSUE TITLE
Assigned groups are cleared when updating password

### ISSUE THREAD

**Issue by obutov** [polonel/trudesk#188]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**: Admin users are removed from all assigned groups when they update their password through the User Profile section

**What did you expect to happen**: Group assignments should not be removed when updating the password

**How to reproduce it (as minimally and precisely as possible)**: Login as Admin user. Assign the user to a few available groups. Navigate to the Profile section by clicking on the User Icon > Profile. Update password and click Save. All group assignments are cleared. 

**Anything else we need to know?**:

**Environment**: 1.0.9
- Trudesk Version: Windows 2008 R2
- OS (e.g. from /etc/os-release):
- Node.JS Version: 10.15.3 (x64)
- MongoDB Version: 4.0.6
- Is this hosted on cloud.trudesk.io: No

**Comment by obutov** [comment]
Actually, group assignments are removed when any information on the profile is updated

**Comment by polonel** [comment]
This has already been fixed on `develop` and will make its way to `master` soon. Thanks for the report.

**Comment by polonel** [comment]
Fixed in `v1.0.11-beta`
