### ISSUE TITLE
Direct Message channel

### ISSUE THREAD

**Issue by LuigiElleBalotta** [polonel/trudesk#189]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ ] BUG 
- [x] FEATURE

**What happened**:
Nothing particular

**What did you expect to happen**:
An idea: why not implement a direct message chat channel in discord.com or gitter.im ?
Then put the badge in the README.MD

**How to reproduce it (as minimally and precisely as possible)**:
Sometimes can be useful using a chat

**Anything else we need to know?**:

**Environment**:
- Trudesk Version:
- OS (e.g. from /etc/os-release):
- Node.JS Version:
- MongoDB Version:
- Is this hosted on cloud.trudesk.io:

**Comment by polonel** [comment]
Are you referring to a support chat channel of such?

**Comment by LuigiElleBalotta** [comment]
kind of, where users can support each other, most project have this, on discord or gitter

**Comment by polonel** [comment]
We have the forums (https://forum.trudesk.io) which most users use and there is also [Slack](https://join.slack.com/t/trudesk/shared_invite/enQtNDY5NTIwNzg1NTY5LWFkMGRhNGEwNTc4ODA1Y2RkMDJmNTllMjk1ODc3MTJmOTBmNzM1YjU3YzBjMWM5MzAwOWFmYmEyZTY4YWRlZmI).

[Trudesk Community](https://forum.trudesk.io/t/trudesk-community-launch/26) - A post about the forums becoming the official outlet for support and insight into the project.

Here is the gitter.im link, but it's not much activity there. Activity is usually at the forums.
