### ISSUE TITLE
[QUESTION] Deploying online

### ISSUE THREAD

**Issue by LoicSellaye** [polonel/trudesk#190]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ x ] BUG 
- [] FEATURE

**What happened**:
I receive the following errors when deploying it on heroku : 
2019-04-21T18:23:28.057506+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2019-04-21T18:23:28.057627+00:00 heroku[web.1]: Stopping process with SIGKILL
2019-04-21T18:23:28.206619+00:00 heroku[web.1]: State changed from starting to crashed
2019-04-21T18:23:28.183096+00:00 heroku[web.1]: Process exited with status 137
2019-04-21T18:23:29.219165+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=app-name.herokuapp.com request_id=b4657c8c-8b67-4031-a21d-a499084a15b9 fwd="ip_address" dyno= connect= service= status=503 bytes= protocol=https
2019-04-21T18:23:30.566932+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=app-name.herokuapp.com request_id=f088c7c9-3499-42c9-a23f-dfe4c6504622 fwd="62.61.197.84" dyno= connect= service= status=503 bytes= protocol=https
**What did you expect to happen**:
Good deploying online and trudesk working
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**: Ubuntu 18.04
- Trudesk Version: 1.0.10
- OS (e.g. from /etc/os-release):
- Node.JS Version:
- MongoDB Version:
- Is this hosted on cloud.trudesk.io: no but heroku

**Comment by polonel** [comment]
I need more information. How did you deploy to heroku? What method did you use? Did you configure the env vars on Heroku? What mongodb service did you select?

**Comment by LoicSellaye** [comment]
Hello, 

First of all : 
-Thank you for your incredible with with Trudesk and for your quick answer!

Well I deploy my project on Heroku through my CLI on Ubuntu 18.04.
I followed your tuto for Linux Install in local : 
$ git clone https://www.github.com/polonel/trudesk
$ cd trudesk
$ npm install -g yarn
$ yarn
$ yarn run build
// This command yarn run build didn't work I received an error so I installed pm2 and started it and it worked well through http://localhost:8118/ 

In local, no problem (I created an admin user on mongodb and successfully pass the test connection) but when I deployed it on heroku for testing online rendering (I already created an account on heroku and successfully login on my CLI with heroku login) I received the error : Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch.

On Google I saw I had to add 'process.env.PORT' near listen() method in order to inform heroku to start a node.js app. 
So, in your code, I added 'process.env.PORT' in some files : 

-app.js l.233 : 
ws.listen(process.env.PORT || 5000, function () {...

-gruntfile.js l.16 : 
port: process.env.PORT || 8118

-test.js l.8 (even it's a test :)) : 
server.listen(process.env.PORT || 1337)

-node_modules/express-hbs/example/app.js l.105 
app.listen(process.env.PORT || 3000);

-node_modules/grunt-express-server/tasks/express.js l.32
port:             process.env.PORT || 3000,

- node_modules/grunt-express-server/tasks/lib/server.js l.56
process.env.PORT = options.port;

-src/webserver.js l.26
var port = process.env.PORT || nconf.get('port') || 8118

On my Heroku account in 'Config vars' I put env vars MONGODB_URI and its value : 'mongodb://<username>:<password>@ds137255.mlab.com:37255/db_name' (with username, password and db created above).


I also created an account on mongoDB ATLAS, created an admin user setting his password and put this code.
I installed 'mLab MongoDB' resource on heroku and as I can't create an account on mlab.com I created it on https://cloud.mongodb.com created a Cluster and added this code : process.env.MONGO_URI in some files : 

-node_modules/connect-mongo/node_modules/mongodb/insert_bench.js l.17
MongoClient.connect(process.env.MONGO_URI || 'mongodb://localhost:27017/bench', function(err, db) {...

-node_modules/mongoose/tools/auth.js l.20
const db = yield mongodb.MongoClient.connect(process.env.MONGO_URI || 'mongodb://localhost:27017/admin');

-test/0_database.js l.13
var CONNECTION_URI = process.env.MONGO_URI || 'mongodb://localhost:27017/polonel_trudesk31908899'

I also added a Procfile with (web: node runner.js) at the root of my project and made 'git add .' then 'git commit -am "my comment" and finally 'git push heroku master".

What was wrong to your mind?

Best and thank you in advance for your precious time!

**Comment by polonel** [comment]
Thank you for this information. This helps.

I will do additional testing on Heroku, as it's been a while since I deployed trudesk on the platform.

I do know that the current release has an issue connecting to MongoDB Atlas as it uses clusters. I will provide additional instructions for Heroku once I give it a test tomorrow.

Standby....

**Comment by LoicSellaye** [comment]
Really thanks again.

Before using this wonderful tool in production I wanted to test it online on heroku because it's free.

But if you can advise me a good hosting solution (even not free) and instructions to deploy trudesk on it I would be grateful.

I can wait, there is no problem. 

Best

**Comment by polonel** [comment]
Here is a referral link to DigitalOcean: https://m.do.co/c/1e53b4841d3f

Create a $10 Ubuntu 16.04 Droplet and once the droplet is deployed and you're able to connect to the shell, install using the Ubuntu 16.04 install script.

http://trudesk.io/v1/guide/installation.html#Ubuntu-Install-Script

This is the easiest and fastest way to get a trudesk deployment running. I have deployed quite a few clients using this method.

**Comment by LoicSellaye** [comment]
Hi,

Thank you for your helpful answer.

I will try DigitalOcean for production after testing on Heroku with your help.

**Comment by LoicSellaye** [comment]
I tried DigitalOcean droplet, I succeed to install trudesk on it (not with linux script install because I didn't receive the same results on CLI as yours in the video 'see picture below' but with manual Linux commands).
![CaptureAfterCurl](https://user-images.githubusercontent.com/6016018/56576760-4cf65a00-65da-11e9-8cff-2b7b41c03de9.JPG)

On digitalOcean droplet CLI, what must I do after 'node runner.js' to see online results, please?
I tried to go to the IP adress of my droplet like <droplet_ip_adress>:8118/ but I received the error message 'This site can't be reached.' on my browser.

I missed something according to you?

Best

**Comment by polonel** [comment]
That install script finished correctly. All you had to do after that was assign a floating IP to the droplet and mission complete....

**Comment by LoicSellaye** [comment]
Yes indeed I finally succeed to put it online by assigning a floating IP address.
Thank you very much for all!
I have other questions to ask you about other functionalities I needed to your amazing app.
How can we discuss if you have some time this week or when you will be available, please?

Mainly it's about adding a 'Handwritten signature' module and editing some fields and save a defined templated pdf file and send it by email to many addressees.

**Comment by polonel** [comment]
The best place to make feature requests and see if it aligns with the community would be the [forums](https://forum.trudesk.io). Feel free to ask any questions over there or send me an email (polonel@trudesk.io). I will respond when I can.

You're always welcome to fork the project and add any customization you see fit for your use case.

Please understand that this is a side project for me and I do have a full-time position away from this project. I personally do not implement any custom features unless it aligns with the goals of the project and community has a vote for the feature to make it to the mainstream.

**Comment by LoicSellaye** [comment]
Thanks a lot.
I have another question please in your script for Ubuntu 16.04 I saw a git checkout v1.0.10. Why is this so important to do, please? What changes was so important? Because without this I go back to the 'Let's start page' in an infinite loop which block me the access to the backend.

Best

**Comment by polonel** [comment]
The command `git checkout v1.0.10` checks out (clone) the repo at tag `v1.0.10`
Currently the `master` branch is on the same commit as the tag. Meaning cloning the repo and checkout v1.0.10 does the same thing.

You're getting the loop because either, the install wizard fails to save the config.json file or the server is not restarting when you click the "Restart Me" button. The server can only restart itself if you are using `PM2`. If you used the install script it handles installing PM2 for you.

**Comment by LoicSellaye** [comment]
Thanks for explanations it seems so logical, I will check further in this direction.

Best

**Comment by LoicSellaye** [comment]
Hi sorry again this what mongod logs in loop for my latest infinite loop problem : 
2019-04-29T15:46:06.025+0400 I NETWORK  [listener] connection accepted from 127.0.0.1:43760 #87 (2 connections now open)
2019-04-29T15:46:06.026+0400 I ACCESS   [conn87] Successfully authenticated as principal trudesk on trudesk
2019-04-29T15:46:06.028+0400 I NETWORK  [listener] connection accepted from 127.0.0.1:43764 #88 (3 connections now open)
2019-04-29T15:46:06.029+0400 I ACCESS   [conn88] Successfully authenticated as principal trudesk on trudesk
2019-04-29T15:46:06.031+0400 I NETWORK  [listener] connection accepted from 127.0.0.1:43768 #89 (4 connections now open)
2019-04-29T15:46:06.032+0400 I ACCESS   [conn89] Successfully authenticated as principal trudesk on trudesk
2019-04-29T15:46:06.061+0400 I NETWORK  [listener] connection accepted from 127.0.0.1:43772 #90 (5 connections now open)
2019-04-29T15:46:06.063+0400 I ACCESS   [conn90] Successfully authenticated as principal trudesk on trudesk
2019-04-29T15:46:06.170+0400 I NETWORK  [conn90] end connection 127.0.0.1:43772 (4 connections now open)
2019-04-29T15:46:06.170+0400 I NETWORK  [conn89] end connection 127.0.0.1:43768 (2 connections now open)
2019-04-29T15:46:06.170+0400 I NETWORK  [conn88] end connection 127.0.0.1:43764 (3 connections now open)
2019-04-29T15:46:06.170+0400 I NETWORK  [conn87] end connection 127.0.0.1:43760 (1 connection now open)
2019-04-29T15:46:06.170+0400 I NETWORK  [conn86] end connection 127.0.0.1:43756 (0 connections now open)
^C2019-04-29T15:46:06.733+0400 I CONTROL  [signalProcessingThread] got signal 2 (Interrupt), will terminate after current cmd ends
2019-04-29T15:46:06.733+0400 I NETWORK  [signalProcessingThread] shutdown: going to close listening sockets...
2019-04-29T15:46:06.733+0400 I NETWORK  [signalProcessingThread] removing socket file: /tmp/mongodb-27017.sock
2019-04-29T15:46:06.734+0400 I CONTROL  [signalProcessingThread] Shutting down free monitoring
2019-04-29T15:46:06.734+0400 I FTDC     [signalProcessingThread] Shutting down full-time diagnostic data capture
2019-04-29T15:46:06.737+0400 I STORAGE  [signalProcessingThread] WiredTigerKVEngine shutting down
2019-04-29T15:46:06.737+0400 I STORAGE  [signalProcessingThread] Shutting down session sweeper thread
2019-04-29T15:46:06.737+0400 I STORAGE  [signalProcessingThread] Finished shutting down session sweeper thread
2019-04-29T15:46:06.847+0400 I STORAGE  [signalProcessingThread] shutdown: removing fs lock...
2019-04-29T15:46:06.847+0400 I CONTROL  [signalProcessingThread] now exiting
2019-04-29T15:46:06.847+0400 I CONTROL  [signalProcessingThread] shutting down with code:0

**Comment by polonel** [comment]
This doesn't provide any real information. How far does the install script get before the mongo server crashes? Why is the mongo server crashing?

Was this a manual install of both MongoDB and trudesk or did you use the ubuntu install script?

**Comment by LoicSellaye** [comment]
It was installing with ubuntu 16.04 script.
It's really weird but to solve my problem (no loop in /install) I just manually restarted the pm2 server like this :
- pm2 stop 0 (id of pm2 process),
- pm2 start 0.

So I think it's about the "Restart Me" button like you said (I mean the function inside).

For the moment it's ok.

Best

**Comment by akhlaaqbadulla** [comment]
I ran in the same loop issue. When I ran a second instance of trudesk it wont restart thus staying in the installing loop. I restarted the app from the terminal pm2 restart 1. The id is not always 0.

**Comment by LoicSellaye** [comment]
After ding a pm2 logs that's the result that I received in loop : 
0|ManixDeskOk  | TypeError: Invalid Version: 1.0
0|ManixDeskOk  |     at new SemVer (/etc/ManixDeskOk/node_modules/semver/semver.js:312:11)
0|ManixDeskOk  |     at Range.test (/etc/ManixDeskOk/node_modules/semver/semver.js:1137:15)
0|ManixDeskOk  |     at Function.satisfies (/etc/ManixDeskOk/node_modules/semver/semver.js:1189:16)
0|ManixDeskOk  |     at /etc/ManixDeskOk/src/migration/index.js:146:22
0|ManixDeskOk  |     at /etc/ManixDeskOk/src/migration/index.js:67:12
0|ManixDeskOk  |     at /etc/ManixDeskOk/node_modules/mongoose/lib/model.js:4659:16
0|ManixDeskOk  |     at /etc/ManixDeskOk/node_modules/mongoose/lib/utils.js:255:16
0|ManixDeskOk  |     at _hooks.execPost (/etc/ManixDeskOk/node_modules/mongoose/lib/query.js:4065:11)
0|ManixDeskOk  |     at /etc/ManixDeskOk/node_modules/kareem/index.js:135:16
0|ManixDeskOk  |     at process._tickCallback (internal/process/next_tick.js:61:11)
PM2            | App [ManixDeskOk:0] exited with code [1] via signal [SIGINT]
PM2            | App [ManixDeskOk:0] starting in -fork mode-
PM2            | App [ManixDeskOk:0] online

**Comment by polonel** [comment]
Yup. That is your issue. `1.0` is not a valid semver version number, thus crashing the server. It pulls the version number from the package.json in order to provide in place updates and database migrations. Once you changed the number and started the server with an incorrect valid it saves the migrated version number to the database, so now after each boot it detects it has an invalid version number.
