### ISSUE TITLE
[INFO] Node 12 not working due to bcrypt failure

### ISSUE THREAD

**Issue by Pummelchen** [polonel/trudesk#191]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [X] BUG 
- [ ] FEATURE

**What happened**:
bcrypt doesnt build/install using Node 12

**What did you expect to happen**:
Well upon research Trudesk needs bcrypt it seems and it wont work with Node 12:
https://github.com/kelektiv/node.bcrypt.js/issues/684

Not sure if/how/when this will be fixed. So for now we should inform TruDesk users to not install Node 12 to avoid a broken installation.

**How to reproduce it (as minimally and precisely as possible)**:
Well, better dont try to reproduce lol

**Environment**:
- Trudesk Version: 1.0.10
- OS (e.g. from /etc/os-release): Debian 9 Stable
- Node.JS Version: 12.0.0
- MongoDB Version: forgot
- Is this hosted on cloud.trudesk.io: no

**Comment by polonel** [comment]
Can you test with bcrypt at version `3.0.6`

**Comment by Pummelchen** [comment]
Yes, it did not work at all as V8 APIs which bcrypt requires have been removed from Node 12.

**Comment by polonel** [comment]
I would report to bcrypt repo directly. I see where the repo hasn't released the prebuilt binaries yet but they claim its compatible with Node 12.

https://github.com/kelektiv/node.bcrypt.js#version-compatibility

**Comment by Pummelchen** [comment]
Got it working with Node 12.1.0 and source compilation.
