### ISSUE TITLE
[BUG] Error while installing trudesk

### ISSUE THREAD

**Issue by ElavanResu** [polonel/trudesk#192]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [X] BUG 
- [ ] FEATURE

**What happened**: Tried to git clone on mac. Gives me an error while configuring database.

**What did you expect to happen**: Should successfully create database with all the collections

**How to reproduce it (as minimally and precisely as possible)**: Just a fresh trudesk install. Note: I skipped the elasticsearch configuration

**Anything else we need to know?**:
This is the error json that I got: `{"success":false,"error":{"errors":{"value":{"message":"Path `value` is required.","name":"ValidatorError","properties":{"message":"Path `value` is required.","type":"required","path":"value"},"kind":"required","path":"value"}},"_message":"settings validation failed","message":"settings validation failed: value: Path `value` is required.","name":"ValidationError"}}
`

**Environment**:
- Trudesk Version: 1.0.11
- OS (e.g. from /etc/os-release): MacOs High Sierra 10.13.6
- Node.JS Version: 10.14.2
- MongoDB Version: 4.0.3
- Is this hosted on cloud.trudesk.io: Nope
![Screen Shot 2019-05-02 at 4 03 52 PM](https://user-images.githubusercontent.com/33317917/57070052-ea950c00-6cf3-11e9-861c-bf5d4ec4b94a.png)

**Comment by polonel** [comment]
Does the server print out a stacktrace?

**Comment by ElavanResu** [comment]
Just got these lines in output.log
5/3 13:39:50 [3410] - [32minfo[39m: Trudesk Install Server Running...
5/3 13:40:24 [3410] - [32minfo[39m: Connected to MongoDB

After that the error comes.
No stacktrace in console.log

**Comment by polonel** [comment]
I'm working on getting this resolved, but I'm current out of town.

A workaround would buy checkout `v1.0.10` and run the install. 

Once complete you can then 
```
git checkout v1.0.11
yarn install
pm2 restart trudesk
```

**Comment by shivajimagadum15** [comment]
Thanks, this is working with your given solution.

**Comment by bhaveshrao96** [comment]
PS E:\BhaveshWork\New_Project_30-12-2019\trudesk> nodemon
[nodemon] 1.19.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] starting `node ./app`
1/2 20:58:46 [12204] - info:     .                              .o8                     oooo
1/2 20:58:46 [12204] - info:   .o8                             "888                     `888      
1/2 20:58:46 [12204] - info: .o888oo oooo d8b oooo  oooo   .oooo888   .ooooo.   .oooo.o  888  oooo
1/2 20:58:46 [12204] - info:   888   `888""8P `888  `888  d88' `888  d88' `88b d88(  "8  888 .8P'
1/2 20:58:46 [12204] - info:   888    888      888   888  888   888  888ooo888 `"Y88b.   888888.
1/2 20:58:46 [12204] - info:   888 .  888      888   888  888   888  888    .o o.  )88b  888 `88b.
1/2 20:58:46 [12204] - info:   "888" d888b     `V88V"V8P' `Y8bod88P" `Y8bod8P' 8""888P' o888o o888o
1/2 20:58:46 [12204] - info: ==========================================================================
1/2 20:58:46 [12204] - info: trudesk v1.1.1 Copyright (C) 2014-2019 Chris Brame
1/2 20:58:46 [12204] - info:  
1/2 20:58:46 [12204] - info: Running in: development
1/2 20:58:46 [12204] - info: Server Time: Thu Jan 02 2020 20:58:46 GMT+0530 (India Standard Time)
1/2 20:58:49 [12204] - info: Trudesk Install Server Running...

nothing happens after this Plz help

**Comment by polonel** [comment]
That is correct. You need to navigate to `http://localhost:8118` to configure and install the database.
