### ISSUE TITLE
[Question] How to automaticaly reload .jsx files

### ISSUE THREAD

**Issue by LoicSellaye** [polonel/trudesk#194]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ ] BUG 
- [ x ] FEATURE

**What happened**:
In development, when I change code into jsx files, the result in browser doesn't render my changes.

**What did you expect to happen**:
Automatic page refreshing (with webpack plugin).

**How to reproduce it (as minimally and precisely as possible)**:
Just modifying one text in the code and manually refresh the webpage.

**Anything else we need to know?**:

**Environment**: Ubuntu 18.04
- Trudesk Version: 1.0.10
- OS (e.g. from /etc/os-release):
- Node.JS Version: 10.15.3
- MongoDB Version: 3.6
- Is this hosted on cloud.trudesk.io: no

**Comment by polonel** [comment]
Trudesk doesn't support hot reloading right now because its not 100% react. It still relies some on angular as I've not fully migrated. 

I will support hot reloading React Components once the angular is fully decommissioned.
