### ISSUE TITLE
issue after fresh install of version 1.0.11

### ISSUE THREAD

**Issue by akhlaaqbadulla** [polonel/trudesk#199]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [X] BUG 
- [ ] FEATURE

**What happened**:
i went through the installation wizard but after  completing the creation of admin account i get this error. everytime.

{"success":false,"error":{"errors":{"value":{"message":"Path `value` is required.","name":"ValidatorError","properties":{"message":"Path `value` is required.","type":"required","path":"value"},"kind":"required","path":"value"}},"_message":"settings validation failed","message":"settings validation failed: value: Path `value` is required.","name":"ValidationError"}}

i checked the database it isnt showing the account i just added.

**What did you expect to happen**:
create the admin account and get presented with the login screen. 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**: 
- Trudesk Version: 1.0.11
- OS (e.g. from /etc/os-release): ubuntu 18.0.4
- Node.JS Version: v11.13.0
- MongoDB Version: v4.0.9
- Is this hosted on cloud.trudesk.io: nop

**Comment by polonel** [comment]
Fix for this has been pushed. Included in v1.0.12
