### ISSUE TITLE
Please upgrade to v1.0.7+ Exiting

### ISSUE THREAD

**Issue by digvijayjaiswar21** [polonel/trudesk#201]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ ] BUG 
- [ ] FEATURE

**What happened**:

**What did you expect to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Trudesk Version:
- OS (e.g. from /etc/os-release):
- Node.JS Version:
- MongoDB Version:
- Is this hosted on cloud.trudesk.io:

![trudesk](https://user-images.githubusercontent.com/49781650/57848202-f99cb380-77f5-11e9-8bb1-2d4983c7c27d.png)

**Comment by shahyar** [comment]
The error is quite self-explanatory. And in the future, please fill out the issue form completely.

**Comment by MortadhaFadhlaoui** [comment]
Hello same for me, @digvijayjaiswar21 do you find solution for that ?

**Comment by fnaquira** [comment]
I just downloaded and got the same error.
