### ISSUE TITLE
[Bug] Build ERROR

### ISSUE THREAD

**Issue by bromoapp** [polonel/trudesk#203]
**What happened**:
And I got an error after trying to execute YARN before YARN run build 

Part of the error like below:

binding.target.mk:127: recipe for target 'Release/obj.target/binding/src/binding.o' failed
make: *** [Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory '/trudesk/node_modules/node-sass/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/trudesk/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:257:12)
gyp ERR! System Linux 4.4.0-135-generic
gyp ERR! command "/usr/bin/node" "/trudesk/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /trudesk/node_modules/node-sass
gyp ERR! node -v v12.2.0

**How to reproduce it (as minimally and precisely as possible)**:
1. Update ubuntu
2. Install Git
3. Install Nodejs
4. Install Mongodb
5. Executing your install steps.

**Environment**:
- Trudesk Version: v1.0.12
- OS Ubuntu 16.04 LTS
- Node.JS Version: 12.2.0
- MongoDB Version: 6.9.0
- Is this hosted on vmware workstation

**Comment by polonel** [comment]
version `1.0.12` is compatible with node 12 due to node-sass. You'll have to downgrade node to 10 or 11.

**Comment by bromoapp** [comment]
Ok I will try that.. thanks
