### ISSUE TITLE
App not working in development mode

### ISSUE THREAD

**Issue by harishankards** [polonel/trudesk#205]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ x ] BUG 

**What happened**:
I cloned the master branch and ran the following commands:
```
$ git clone https://www.github.com/polonel/trudesk
$ cd trudesk
$ npm install -g yarn
$ yarn
```
and then `node app.js` to run the application in development mode. I was able to see the server saying `Running in: development` and the app serving at `localhost:8118`, but when I click Let's start, nothing happened. But when I ran the following commands
```
$ yarn run build
$ node runner
```
it works fine saying `Launching in no daemon mode`.

Also in development mode, I was able to see the following error in browser console
```
Uncaught SyntaxError: Unexpected token < at install:1
install:420 Uncaught TypeError: window.truRequire is not a function
    at install:420
(anonymous) @ install:420
```
but not in daemon mode.

--

**What did you expect to happen**:
The development mode to work like how the daemon worked when `node runner` was commanded

**How to reproduce it (as minimally and precisely as possible)**:
```
$ git clone https://www.github.com/polonel/trudesk
$ cd trudesk
$ npm install -g yarn
$ yarn
$ node app.js
```

**Anything else we need to know?**:

**Environment**:
- Trudesk Version:  trudesk v1.0.13
- OS (e.g. from /etc/os-release): Ubuntu 18.04 
- Node.JS Version: v10.15.3
- MongoDB Version: v3.6.3
- Is this hosted on cloud.trudesk.io: No

Thanks in advance

**Comment by polonel** [comment]
`yarn run build` builds the files needed to run in dev mode.
After running `yarn build`, `node app.js` will run correctly. You will need to reload the browser to pull the new build files. 

If you're trying to run in dev mode, its best to run `grunt` to handle everything for you so any changes you made will take effect. If not you will need to run `yarn build` after every file change and restart the server.

**Comment by harishankards** [comment]
Hi @polonel ,

Thanks for the response. It works fine. However, when I run `grunt` I'm receiving this warning the in the console. 

```
WARNING in asset size limit: The following asset(s) exceed the recommended size limit (977 KiB).
This can impact web performance.
Assets: 
  1.js (1.64 MiB)
  3.js (4.07 MiB)
  4.js (1.35 MiB)
  5.js (3.19 MiB)
  6.js (1.81 MiB)
  truRequire.js (1.58 MiB)
  vendor.js (1.18 MiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (391 KiB). This can impact web performance.
Entrypoints:
  truRequire (2.76 MiB)
      vendor.js
      truRequire.js

```

How can I overcome this?

**Comment by polonel** [comment]
You don't. It's normal.
