### ISSUE TITLE
[BUG] Departements Unacessible after creating

### ISSUE THREAD

**Issue by akhlaaqbadulla** [polonel/trudesk#206]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [X] BUG 
- [ ] FEATURE

**What happened**:
i upraded from version 1.0.10 directly to version 1.0.13. after creating a department the department page went blank.

these are the errors that comes up in the console:

`api/v2/es/status:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
6.js:68 trudesk:error Error: Request failed with status code 500    at module.exports (http://ganord.ovh/js/6.js:28:17866)    at module.exports (http://ganord.ovh/js/6.js:68:2106)    at XMLHttpRequest.request.<computed> (http://ganord.ovh/js/6.js:28:16353) +0ms
6.js:44 TypeError: Cannot read property 'map' of null
    at 9.js:10
    at 6.js:16
    at List.withMutations (6.js:16)
    at List.map (6.js:16)
    at DepartmentsContainer.value (9.js:10)
    at xg (6.js:44)
    at wg (6.js:44)
    at Ag (6.js:44)
    at lh (6.js:44)
    at mh (6.js:44)
Kg @ 6.js:44
6.js:16 uncaught at fetchDepartments TypeError: Cannot read property 'map' of null
    at http://ganord.ovh/js/9.js:10:636333
    at http://ganord.ovh/js/6.js:16:171793
    at List.withMutations (http://ganord.ovh/js/6.js:16:154127)
    at List.map (http://ganord.ovh/js/6.js:16:171716)
    at DepartmentsContainer.value (http://ganord.ovh/js/9.js:10:635964)
    at xg (http://ganord.ovh/js/6.js:44:59863)
    at wg (http://ganord.ovh/js/6.js:44:59658)
    at Ag (http://ganord.ovh/js/6.js:44:63372)
    at lh (http://ganord.ovh/js/6.js:44:78924)
    at mh (http://ganord.ovh/js/6.js:44:79289)
log @ 6.js:16
6.js:28 GET http://ganord.ovh/api/v2/es/status 500 (Internal Server Error)
(anonymous) @ 6.js:28
module.exports @ 6.js:28
module.exports @ 6.js:68
Promise.then (async)
Axios.request @ 6.js:68
Axios.<computed> @ 6.js:68
(anonymous) @ 6.js:28
value @ 9.js:10
value @ 9.js:10
wrapper @ 6.js:16
(anonymous) @ 6.js:16
Sh @ 6.js:44
Ph @ 6.js:44
Qh @ 6.js:44
sh @ 6.js:44
Uf @ 6.js:44
enqueueSetState @ 6.js:44
G.setState @ 6.js:36
(anonymous) @ 6.js:1
dispatch @ 6.js:23
(anonymous) @ 6.js:81
(anonymous) @ 6.js:61
dispatch @ 6.js:23
(anonymous) @ 6.js:16
(anonymous) @ 6.js:81
exec @ 6.js:28
flush @ 6.js:28
asap @ 6.js:28
(anonymous) @ 6.js:81
runEffect @ 6.js:81
next @ 6.js:81
currCb @ 6.js:81
Promise.then (async)
resolvePromise @ 6.js:81
(anonymous) @ 6.js:81
runEffect @ 6.js:81
next @ 6.js:81
proc @ 6.js:81
runForkEffect @ 6.js:81
runEffect @ 6.js:81
next @ 6.js:81
currCb @ 6.js:81
(anonymous) @ 6.js:81
runEffect @ 6.js:81
next @ 6.js:81
currCb @ 6.js:81
takeCb @ 6.js:81
put @ 6.js:16
(anonymous) @ 6.js:16
(anonymous) @ 6.js:16
exec @ 6.js:28
flush @ 6.js:28
asap @ 6.js:28
(anonymous) @ 6.js:16
emit @ 6.js:16
(anonymous) @ 6.js:81
(anonymous) @ 6.js:61
(anonymous) @ 6.js:23
value @ 9.js:10
Sh @ 6.js:44
Ph @ 6.js:44
Qh @ 6.js:44
sh @ 6.js:44
Uf @ 6.js:44
Xh @ 6.js:44
Yh @ 6.js:44
ci.render @ 6.js:44
(anonymous) @ 6.js:44
Uh @ 6.js:44
fi @ 6.js:44
render @ 6.js:44
renderer @ 9.js:10
init @ 9.js:1
(anonymous) @ 9.js:1
dispatch @ 1.js:25
elemData.handle @ 1.js:25
trigger @ 1.js:25
(anonymous) @ 1.js:25
each @ 1.js:14
each @ 1.js:14
trigger @ 1.js:25
(anonymous) @ 9.js:1
opt.complete @ 1.js:25
fire @ 1.js:25
add @ 1.js:25
Animation @ 1.js:25
doAnimation @ 1.js:25
dequeue @ 1.js:25
(anonymous) @ 1.js:25
each @ 1.js:14
each @ 1.js:14
queue @ 1.js:25
animate @ 1.js:25
success @ 9.js:1
fire @ 1.js:25
fireWith @ 1.js:25
done @ 1.js:25
(anonymous) @ 1.js:25
load (async)
send @ 1.js:25
ajax @ 1.js:25
(anonymous) @ 9.js:1
dispatch @ 1.js:25
elemData.handle @ 1.js:25
trigger @ 1.js:25
(anonymous) @ 1.js:25
each @ 1.js:14
each @ 1.js:14
trigger @ 1.js:25
trigger @ 7.js:27
h.onPopState @ 7.js:27
dispatch @ 1.js:25
elemData.handle @ 1.js:25
Show 65 more frames
6.js:68 trudesk:error Error: Request failed with status code 500    at module.exports (http://ganord.ovh/js/6.js:28:17866)    at module.exports (http://ganord.ovh/js/6.js:68:2106)    at XMLHttpRequest.request.<computed> (http://ganord.ovh/js/6.js:28:16353) +0ms
6.js:44 TypeError: Cannot read property 'map' of null
    at 9.js:10
    at 6.js:16
    at List.withMutations (6.js:16)
    at List.map (6.js:16)
    at DepartmentsContainer.value (9.js:10)
    at xg (6.js:44)
    at wg (6.js:44)
    at Ag (6.js:44)
    at lh (6.js:44)
    at mh (6.js:44)
Kg @ 6.js:44
Vg.c.callback @ 6.js:44
vf @ 6.js:44
uf @ 6.js:44
Sh @ 6.js:44
Ph @ 6.js:44
Qh @ 6.js:44
sh @ 6.js:44
Uf @ 6.js:44
Xh @ 6.js:44
Yh @ 6.js:44
ci.render @ 6.js:44
(anonymous) @ 6.js:44
Uh @ 6.js:44
fi @ 6.js:44
render @ 6.js:44
renderer @ 9.js:10
init @ 9.js:1
(anonymous) @ 9.js:1
dispatch @ 1.js:25
elemData.handle @ 1.js:25
trigger @ 1.js:25
(anonymous) @ 1.js:25
each @ 1.js:14
each @ 1.js:14
trigger @ 1.js:25
(anonymous) @ 9.js:1
opt.complete @ 1.js:25
fire @ 1.js:25
add @ 1.js:25
Animation @ 1.js:25
doAnimation @ 1.js:25
dequeue @ 1.js:25
(anonymous) @ 1.js:25
each @ 1.js:14
each @ 1.js:14
queue @ 1.js:25
animate @ 1.js:25
success @ 9.js:1
fire @ 1.js:25
fireWith @ 1.js:25
done @ 1.js:25
(anonymous) @ 1.js:25
load (async)
send @ 1.js:25
ajax @ 1.js:25
(anonymous) @ 9.js:1
dispatch @ 1.js:25
elemData.handle @ 1.js:25
trigger @ 1.js:25
(anonymous) @ 1.js:25
each @ 1.js:14
each @ 1.js:14
trigger @ 1.js:25
trigger @ 7.js:27
h.onPopState @ 7.js:27
dispatch @ 1.js:25
elemData.handle @ 1.js:25
trigger @ 1.js:25
(anonymous) @ 1.js:25
each @ 1.js:14
each @ 1.js:14
trigger @ 1.js:25
trigger @ 7.js:27
h.pushState @ 7.js:27
(anonymous) @ 9.js:1
dispatch @ 1.js:25
elemData.handle @ 1.js:25
Show 13 more frames
6.js:44 Uncaught TypeError: Cannot read property 'map' of null
    at 9.js:10
    at 6.js:16
    at List.withMutations (6.js:16)
    at List.map (6.js:16)
    at DepartmentsContainer.value (9.js:10)
    at xg (6.js:44)
    at wg (6.js:44)
    at Ag (6.js:44)
    at lh (6.js:44)
    at mh (6.js:44)
(anonymous) @ 9.js:10
(anonymous) @ 6.js:16
withMutations @ 6.js:16
List.map @ 6.js:16
value @ 9.js:10
xg @ 6.js:44
wg @ 6.js:44
Ag @ 6.js:44
lh @ 6.js:44
mh @ 6.js:44
Ph @ 6.js:44
Qh @ 6.js:44
sh @ 6.js:44
Uf @ 6.js:44
Xh @ 6.js:44
Yh @ 6.js:44
ci.render @ 6.js:44
(anonymous) @ 6.js:44
Uh @ 6.js:44
fi @ 6.js:44
render @ 6.js:44
renderer @ 9.js:10
init @ 9.js:1
(anonymous) @ 9.js:1
dispatch @ 1.js:25
elemData.handle @ 1.js:25
trigger @ 1.js:25
(anonymous) @ 1.js:25
each @ 1.js:14
each @ 1.js:14
trigger @ 1.js:25
(anonymous) @ 9.js:1
opt.complete @ 1.js:25
fire @ 1.js:25
add @ 1.js:25
Animation @ 1.js:25
doAnimation @ 1.js:25
dequeue @ 1.js:25
(anonymous) @ 1.js:25
each @ 1.js:14
each @ 1.js:14
queue @ 1.js:25
animate @ 1.js:25
success @ 9.js:1
fire @ 1.js:25
fireWith @ 1.js:25
done @ 1.js:25
(anonymous) @ 1.js:25
load (async)
send @ 1.js:25
ajax @ 1.js:25
(anonymous) @ 9.js:1
dispatch @ 1.js:25
elemData.handle @ 1.js:25
trigger @ 1.js:25
(anonymous) @ 1.js:25
each @ 1.js:14
each @ 1.js:14
trigger @ 1.js:25
trigger @ 7.js:27
h.onPopState @ 7.js:27
dispatch @ 1.js:25
elemData.handle @ 1.js:25
trigger @ 1.js:25
(anonymous) @ 1.js:25
each @ 1.js:14
each @ 1.js:14
trigger @ 1.js:25
trigger @ 7.js:27
h.pushState @ 7.js:27
(anonymous) @ 9.js:1
dispatch @ 1.js:25
elemData.handle @ 1.js:25
Show 18 more frames`

**What did you expect to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: v1.0.13
- OS (e.g. from /etc/os-release): ubuntu
- Node.JS Version: 12
- MongoDB Version: 4
- Is this hosted on cloud.trudesk.io: no

**Comment by polonel** [comment]
Some build files were missing on the release. I updated the release. Please re-pull from git.

```
git pull
git checkout v1.0.13
```

**Comment by akhlaaqbadulla** [comment]
Tried it did not work.

**Comment by polonel** [comment]
Confirmed.
