### ISSUE TITLE
empty reply from server when pm2 shows status online

### ISSUE THREAD

**Issue by sushant0219** [polonel/trudesk#207]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x ] BUG 
- [ ] FEATURE

**What happened**:
when trudesk is running pm2 shows that the process is running but using curl -I 127.0.0.1 gives the error empty reply from server when we restart the process(**pm2 restart trudesk**) manually we get the reply even **pm2 logs trudesk** does not yield any errors  

**What did you expect to happen**:
Trudesk should run seamleasly

**How to reproduce it (as minimally and precisely as possible)**:
We are unsure of any events that we can reproduce it happens more than twice daily.

**Anything else we need to know?**:
how can we watch what are the last thing executed successfully in trudesk ?
is there any way to restart the process .
**Environment**:
- Trudesk Version: 1.0.3
- OS (e.g. from /etc/os-release): ubuntu 17.04 
- Node.JS Version: 9.10
- MongoDB Version:3.6.9
- Is this hosted on cloud.trudesk.io:no

**Comment by polonel** [comment]
Trudesk runs on port `8118`. Also, you should upgrade from version `1.0.3`

The upgrade path is: `1.0.3 -> 1.0.7 -> 1.0.10 -> 1.0.13`

**Comment by sushant0219** [comment]
After upgrading i am getting the following error : 
 message=Cast to ObjectId failed for value "admin" at path "_id" for model "roles", stack=CastError: Cast to ObjectId failed for value "admin" at path "_id" for model "roles"



full logs given below : 
PS D:\trudesk\td> node .\app.js
5/30 16:15:09 [924] - info:     .                              .o8                     oooo
5/30 16:15:09 [924] - info:   .o8                             "888                     `888
5/30 16:15:09 [924] - info: .o888oo oooo d8b oooo  oooo   .oooo888   .ooooo.   .oooo.o  888  oooo
5/30 16:15:09 [924] - info:   888   `888""8P `888  `888  d88' `888  d88' `88b d88(  "8  888 .8P'
5/30 16:15:09 [924] - info:   888    888      888   888  888   888  888ooo888 `"Y88b.   888888.
5/30 16:15:09 [924] - info:   888 .  888      888   888  888   888  888    .o o.  )88b  888 `88b.
5/30 16:15:09 [924] - info:   "888" d888b     `V88V"V8P' `Y8bod88P" `Y8bod8P' 8""888P' o888o o888o
5/30 16:15:09 [924] - info: ==========================================================================
5/30 16:15:09 [924] - info: trudesk v1.0.13 Copyright (C) 2014-2019 Chris Brame
5/30 16:15:09 [924] - info:
5/30 16:15:09 [924] - info: Running in: development
5/30 16:15:09 [924] - info: Server Time: Thu May 30 2019 16:15:09 GMT+0530 (India Standard Time)
5/30 16:15:10 [924] - info: Connected to MongoDB
5/30 16:15:12 [924] - debug: Checking Default Settings...
5/30 16:15:16 [924] - debug: Timezone set to America/New_York
5/30 16:15:16 [924] - warn: No Types Defined!
5/30 16:15:16 [924] - debug: Registering Permissions...
5/30 16:15:17 [924] - info: SocketServer Running
5/30 16:15:17 [924] - debug: Building dynamic sass...
5/30 16:15:17 [924] - info: TruDesk is now listening on port: 8118
5/30 16:15:17 [924] - info: trudesk Ready
5/30 16:15:22 [Child:Cache:11416] - debug: Pulled 0
5/30 16:15:22 [Child:Cache:11416] - debug: Cache Loaded
PS D:\trudesk\td> node .\app.js
5/30 16:16:22 [9636] - info:     .                              .o8                     oooo
5/30 16:16:22 [9636] - info:   .o8                             "888                     `888
5/30 16:16:22 [9636] - info: .o888oo oooo d8b oooo  oooo   .oooo888   .ooooo.   .oooo.o  888  oooo
5/30 16:16:22 [9636] - info:   888   `888""8P `888  `888  d88' `888  d88' `88b d88(  "8  888 .8P'
5/30 16:16:22 [9636] - info:   888    888      888   888  888   888  888ooo888 `"Y88b.   888888.
5/30 16:16:22 [9636] - info:   888 .  888      888   888  888   888  888    .o o.  )88b  888 `88b.
5/30 16:16:22 [9636] - info:   "888" d888b     `V88V"V8P' `Y8bod88P" `Y8bod8P' 8""888P' o888o o888o
5/30 16:16:22 [9636] - info: ==========================================================================
5/30 16:16:22 [9636] - info: trudesk v1.0.13 Copyright (C) 2014-2019 Chris Brame
5/30 16:16:22 [9636] - info:
5/30 16:16:22 [9636] - info: Running in: development
5/30 16:16:22 [9636] - info: Server Time: Thu May 30 2019 16:16:22 GMT+0530 (India Standard Time)
5/30 16:16:38 [9636] - info: Connected to MongoDB
5/30 16:16:40 [9636] - debug: Checking Default Settings...
5/30 16:16:54 [9636] - debug: Timezone set to Asia/Calcutta
5/30 16:16:56 [9636] - debug: Registering Permissions...
5/30 16:16:57 [9636] - info: SocketServer Running
5/30 16:16:57 [9636] - debug: Building dynamic sass...
5/30 16:16:58 [9636] - info: TruDesk is now listening on port: 8118
5/30 16:16:58 [9636] - info: trudesk Ready
5/30 16:17:06 [Child:Cache:10660] - debug: Pulled 280
5/30 16:17:06 [Child:Cache:10660] - warn:  message=Cast to ObjectId failed for value "admin" at path "_id" for model "roles", stack=CastError: Cast to ObjectId failed for value "admin" at path "_id" for model "roles"
    at new CastError (D:\trudesk\td\node_modules\mongoose\lib\error\cast.js:29:11)
    at ObjectId.cast (D:\trudesk\td\node_modules\mongoose\lib\schema\objectid.js:232:11)
    at ObjectId.SchemaType.applySetters (D:\trudesk\td\node_modules\mongoose\lib\schematype.js:845:12)
    at ObjectId.SchemaType._castForQuery (D:\trudesk\td\node_modules\mongoose\lib\schematype.js:1248:15)
    at ObjectId.SchemaType.castForQuery (D:\trudesk\td\node_modules\mongoose\lib\schematype.js:1238:15)
    at D:\trudesk\td\node_modules\mongoose\lib\schematype.js:1187:18
    at Array.map (<anonymous>)
    at ObjectId.handle$in (D:\trudesk\td\node_modules\mongoose\lib\schematype.js:1183:14)
    at ObjectId.SchemaType.castForQuery (D:\trudesk\td\node_modules\mongoose\lib\schematype.js:1235:20)
    at ObjectId.SchemaType.castForQueryWrapper (D:\trudesk\td\node_modules\mongoose\lib\schematype.js:1212:17)
    at cast (D:\trudesk\td\node_modules\mongoose\lib\cast.js:288:39)
    at model.Query.Query.cast (D:\trudesk\td\node_modules\mongoose\lib\query.js:4331:12)
    at model.Query.Query._castConditions (D:\trudesk\td\node_modules\mongoose\lib\query.js:1726:10)
    at model.Query.<anonymous> (D:\trudesk\td\node_modules\mongoose\lib\query.js:1753:8)
    at model.Query._wrappedThunk [as _find] (D:\trudesk\td\node_modules\mongoose\lib\helpers\query\wrapThunk.js:16:8)
    at D:\trudesk\td\node_modules\kareem\index.js:278:20, name=CastError, stringValue="admin", kind=ObjectId, value=admin, path=_id, reason=undefined, model=function model(doc, fields, skipId) {
      model.hooks.execPreSync('createModel', doc);
      if (!(this instanceof model)) {
        return new model(doc, fields, skipId);
      }
      Model.call(this, doc, fields, skipId);
    }
D:\trudesk\td\node_modules\mongoose\lib\utils.js:250
            throw error;
            ^

Error: Callback was already called.
    at D:\trudesk\td\node_modules\async\dist\async.js:966:32
    at D:\trudesk\td\node_modules\async\dist\async.js:3885:13
    at D:\trudesk\td\src\cache\quickStats.js:43:29
    at D:\trudesk\td\node_modules\mongoose\lib\model.js:4659:16
    at D:\trudesk\td\node_modules\mongoose\lib\utils.js:247:11
    at next (D:\trudesk\td\node_modules\mongoose\lib\model.js:3668:14)
    at next (D:\trudesk\td\node_modules\mongoose\lib\model.js:3828:21)
    at D:\trudesk\td\node_modules\mongoose\lib\model.js:4659:16
    at D:\trudesk\td\node_modules\mongoose\lib\utils.js:247:11
    at (anonymous function).call (D:\trudesk\td\node_modules\mongoose\lib\query.js:4057:18)
    at D:\trudesk\td\node_modules\kareem\index.js:246:48
    at D:\trudesk\td\node_modules\kareem\index.js:135:16
    at process._tickCallback (internal/process/next_tick.js:61:11)
Emitted 'error' event at:
    at D:\trudesk\td\node_modules\mongoose\lib\model.js:4661:13
    at D:\trudesk\td\node_modules\mongoose\lib\utils.js:247:11
    [... lines matching original stack trace ...]
    at process._tickCallback (internal/process/next_tick.js:61:11)
