### ISSUE TITLE
Fresh Install V1.0.14 stuck in load loop

### ISSUE THREAD

**Issue by akhlaaqbadulla** [polonel/trudesk#218]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [X] BUG 
- [ ] FEATURE

**What happened**:
**install v1.0.14 and aftr login Trudesk fails and it thows this in console:**
trudesk.min.js:1 TypeError: Cannot read property 'call' of undefined

>     at __webpack_require__ (trudesk.min.js:1)
>     at Object.8 (1.js:57)
>     at __webpack_require__ (trudesk.min.js:1)
>     at Object.9 (1.js:57)
>     at __webpack_require__ (trudesk.min.js:1)
>     at trudesk.min.js:1
> __webpack_require__.oe @ trudesk.min.js:1
> Promise.catch (async)
> (anonymous) @ trudesk.min.js:1
> 35 @ trudesk.min.js:1
> __webpack_require__ @ trudesk.min.js:1
> (anonymous) @ trudesk.min.js:1
> (anonymous) @ trudesk.min.js:1
> trudesk.min.js:1 Uncaught (in promise) TypeError: Cannot read property 'call' of undefined
>     at __webpack_require__ (trudesk.min.js:1)
>     at Object.8 (1.js:57)
>     at __webpack_require__ (trudesk.min.js:1)
>     at Object.9 (1.js:57)
>     at __webpack_require__ (trudesk.min.js:1)
>     at trudesk.min.js:1
> __webpack_require__ @ trudesk.min.js:1
> 8 @ 1.js:57
> __webpack_require__ @ trudesk.min.js:1
> 9 @ 1.js:57
> __webpack_require__ @ trudesk.min.js:1
> (anonymous) @ trudesk.min.js:1
> Promise.catch (async)
> (anonymous) @ trudesk.min.js:1
> 35 @ trudesk.min.js:1
> __webpack_require__ @ trudesk.min.js:1
> (anonymous) @ trudesk.min.js:1
> (anonymous) @ trudesk.min.js:1

**What did you expect to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
fresh install v1.0.14 after set up will stay stuck on loading screen.

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: 1.0.14
- OS (e.g. from /etc/os-release): ubuntu 18.04
- Node.JS Version: 11.15
- MongoDB Version: 4

**Comment by vorion** [comment]
@akhlaaqbadulla Have you tried re-cloning the master? My first clone was missing every single public/js file. Try to re-clone repo, ensure you have the files in public/js/ then rebuild.

**Comment by akhlaaqbadulla** [comment]
@vorion thank you. your were right.. though i had the file but still did not work so i cloned the master again.

**Comment by akhlaaqbadulla** [comment]
@polonel doing a git clone fixed the error temporarily then it broke again.
The same error appearing in console:
`trudesk.min.js:1 TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (trudesk.min.js:1)
    at Object.8 (1.js:57)
    at __webpack_require__ (trudesk.min.js:1)
    at Object.9 (1.js:57)
    at __webpack_require__ (trudesk.min.js:1)
    at trudesk.min.js:1
__webpack_require__.oe @ trudesk.min.js:1
trudesk.min.js:1 Uncaught (in promise) TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (trudesk.min.js:1)
    at Object.8 (1.js:57)
    at __webpack_require__ (trudesk.min.js:1)
    at Object.9 (1.js:57)
    at __webpack_require__ (trudesk.min.js:1)
    at trudesk.min.js:1`

**Comment by polonel** [comment]
That tells me its something with your custom code. If my bundled build files work, and when you run `yarn build` fails tells me you have custom code that's failing.

**Comment by akhlaaqbadulla** [comment]
@polonel  the only custom part is the port number. 
i tried a  yarn build and it build without any error.
but still it wont work.

**Comment by polonel** [comment]
Then your node deps are not up-to-date. 
`yarn install`

**Comment by akhlaaqbadulla** [comment]
@polonel the node deps are up to date
same error.

> trudesk.min.js:1 TypeError: Cannot read property 'call' of undefined
>     at __webpack_require__ (trudesk.min.js:1)
>     at Object.8 (1.js:57)
>     at __webpack_require__ (trudesk.min.js:1)
>     at Object.9 (1.js:57)
>     at __webpack_require__ (trudesk.min.js:1)
>     at trudesk.min.js:1
> __webpack_require__.oe @ trudesk.min.js:1
> trudesk.min.js:1 Uncaught (in promise) TypeError: Cannot read property 'call' of undefined
>     at __webpack_require__ (trudesk.min.js:1)
>     at Object.8 (1.js:57)
>     at __webpack_require__ (trudesk.min.js:1)
>     at Object.9 (1.js:57)
>     at __webpack_require__ (trudesk.min.js:1)
>     at trudesk.min.js:1

**Comment by polonel** [comment]
I don't understand why you need to build the bundled files? What's wrong with the ones that are bundled. The port number change doesn't require a new build.

**Comment by akhlaaqbadulla** [comment]
Actually as soon as i did a `git checkout v1.0.14` and `pm2 restarted`. 
when the page refreshed it stucks on the jumping ball. 
the this error appear in the console.

> trudesk.min.js:1 TypeError: Cannot read property 'call' of undefined
>     at __webpack_require__ (trudesk.min.js:1)
>     at Object.8 (1.js:57)
>     at __webpack_require__ (trudesk.min.js:1)
>     at Object.9 (1.js:57)
>     at __webpack_require__ (trudesk.min.js:1)
>     at trudesk.min.js:1
> __webpack_require__.oe @ trudesk.min.js:1
> trudesk.min.js:1 Uncaught (in promise) TypeError: Cannot read property 'call' of undefined
>     at __webpack_require__ (trudesk.min.js:1)
>     at Object.8 (1.js:57)
>     at __webpack_require__ (trudesk.min.js:1)
>     at Object.9 (1.js:57)
>     at __webpack_require__ (trudesk.min.js:1)
>     at trudesk.min.js:1

**Comment by polonel** [comment]
did you `git reset --hard` before `git checkout v1.0.14`?

**Comment by akhlaaqbadulla** [comment]
no i did not.

**Comment by akhlaaqbadulla** [comment]
first error point to this:
![image](https://user-images.githubusercontent.com/7328076/59407194-8b7de900-8dc1-11e9-9b48-f4503d3c0a19.png)

**Comment by polonel** [comment]
I just did the following...
```
git clone https://github.com/polonel/trudesk
git checkout v1.0.14
yarn install
node runner
```
Everything worked fine. Went through install wizard and then logged into the dashboard and created a ticket.

I then did the following.
```
CTRL+C
yarn build
node runner
```
Refreshed the page and created another ticket. I'm not seeing this at all.

_NOTE: `node runner` is same as running `pm2`._

**Comment by akhlaaqbadulla** [comment]
Followed the same step you mentioned about. i am still getting the error.
it fails to load the dashboard.

> TypeError: Cannot read property 'call' of undefined
>     at __webpack_require__ (trudesk.min.js:1)
>     at Object.8 (1.js:57)
>     at __webpack_require__ (trudesk.min.js:1)
>     at Object.9 (1.js:57)
>     at __webpack_require__ (trudesk.min.js:1)
>     at trudesk.min.js:1
> __webpack_require__.oe @ trudesk.min.js:1
> Promise.catch (async)
> (anonymous) @ trudesk.min.js:1
> 35 @ trudesk.min.js:1
> __webpack_require__ @ trudesk.min.js:1
> (anonymous) @ trudesk.min.js:1
> (anonymous) @ trudesk.min.js:1
> trudesk.min.js:1 Uncaught (in promise) TypeError: Cannot read property 'call' of undefined
>     at __webpack_require__ (trudesk.min.js:1)
>     at Object.8 (1.js:57)
>     at __webpack_require__ (trudesk.min.js:1)
>     at Object.9 (1.js:57)
>     at __webpack_require__ (trudesk.min.js:1)
>     at trudesk.min.js:1
> __webpack_require__ @ trudesk.min.js:1
> 8 @ 1.js:57
> __webpack_require__ @ trudesk.min.js:1
> 9 @ 1.js:57
> __webpack_require__ @ trudesk.min.js:1
> (anonymous) @ trudesk.min.js:1
> Promise.catch (async)
> (anonymous) @ trudesk.min.js:1
> 35 @ trudesk.min.js:1
> __webpack_require__ @ trudesk.min.js:1
> (anonymous) @ trudesk.min.js:1
> (anonymous) @ trudesk.min.js:1

**Comment by polonel** [comment]
Last thing I can suggest then is try we a different database. Create a new one to test.

**Comment by akhlaaqbadulla** [comment]
@polonel yes i did try a new database and still it will not work. i even did a reinstall a new vm and i get the same isssue.

**Comment by akhlaaqbadulla** [comment]
@polonel the issue is persistent. i cannot upgrade from v1.0.10 -> v1.0.14. as soon as i do the upgrade. i get the above error. 

> TypeError: Cannot read property 'call' of undefined
> at **webpack_require** (trudesk.min.js:1)
> at Object.8 (1.js:57)
> at **webpack_require** (trudesk.min.js:1)
> at Object.9 (1.js:57)
> at **webpack_require** (trudesk.min.js:1)
> at trudesk.min.js:1
> **webpack_require**.oe @ trudesk.min.js:1
> Promise.catch (async)
> (anonymous) @ trudesk.min.js:1
> 35 @ trudesk.min.js:1
> **webpack_require** @ trudesk.min.js:1
> (anonymous) @ trudesk.min.js:1
> (anonymous) @ trudesk.min.js:1
> trudesk.min.js:1 Uncaught (in promise) TypeError: Cannot read property 'call' of undefined
> at **webpack_require** (trudesk.min.js:1)
> at Object.8 (1.js:57)
> at **webpack_require** (trudesk.min.js:1)
> at Object.9 (1.js:57)
> at **webpack_require** (trudesk.min.js:1)
> at trudesk.min.js:1
> **webpack_require** @ trudesk.min.js:1
> 8 @ 1.js:57
> **webpack_require** @ trudesk.min.js:1
> 9 @ 1.js:57
> **webpack_require** @ trudesk.min.js:1
> (anonymous) @ trudesk.min.js:1
> Promise.catch (async)
> (anonymous) @ trudesk.min.js:1
> 35 @ trudesk.min.js:1
> **webpack_require** @ trudesk.min.js:1
> (anonymous) @ trudesk.min.js:1
> (anonymous) @ trudesk.min.js:1

**Comment by polonel** [comment]
I’m just not seeing this. You said when you do a fresh clone it doesn’t happen. My build files in the repo are good. I’ve also not had anyone else with this issue. This is an isolated case and is something on your end. I have tested the repo build files multiple times and cannot reproduce this error.

**Comment by akhlaaqbadulla** [comment]
@polonel is it possible that Running as root is the issue? 
what is the setup of your environnement?

**Comment by polonel** [comment]
I have a client that runs as root. You have to make sure you clone as root, run build as root, etc.

When I tested I used I deployed a new Ubuntu 16.04 on GCP and ran the ubuntu install script. 

When I upgrade all my clients:

1. SSH into box
2. `cd /etc/trudesk`
3. `sudo git pull && git checkout v1.0.14`
4. `sudo pm2 restart trudesk`
5. Upgrade complete.

**Comment by akhlaaqbadulla** [comment]
@polonel i have been trying to debug the issue am getting. and everything i try comes back to the call function of the webpack. when i run `yarn run build` or `yarn install` both executes without error and yet when i run the app. after the login screen right away it throws this webpack call error. is there a way to check if a module is failing or anything else.


![Screenshot from 2019-06-20 10-20-03](https://user-images.githubusercontent.com/7328076/59825506-3e5fc100-9345-11e9-9353-40fb71a40a00.png)

**Comment by akhlaaqbadulla** [comment]
@polonel i dont really understand but when i build with yarn version 1.15.2 it works but with the lastest version it throws the call error. is there a difference between the two versions of yarn?
and i guess this issue it has been resolved so far to running.

**Comment by polonel** [comment]
Yarn shouldn’t affect the build process because you can even run npm run build.

Only we pack has to do with build process. But why are you building anyway? The build files are included on tag releases.

**Comment by akhlaaqbadulla** [comment]
@polonel well that was a fail. i keep getting this webpack error.
i tried rebuilding still would not work. i checked if i have all the files and yes l the files are here. yet it keeps giving me this error.

```
trudesk.min.js:1 Uncaught (in promise) TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (trudesk.min.js:1)
    at Object.8 (1.js:57)
    at __webpack_require__ (trudesk.min.js:1)
    at Object.9 (1.js:57)
    at __webpack_require__ (trudesk.min.js:1)
    at trudesk.min.js:1
__webpack_require__ @ trudesk.min.js:1
8 @ 1.js:57
__webpack_require__ @ trudesk.min.js:1
9 @ 1.js:57
__webpack_require__ @ trudesk.min.js:1
(anonymous) @ trudesk.min.js:1
Promise.catch (async)
(anonymous) @ trudesk.min.js:1
35 @ trudesk.min.js:1
__webpack_require__ @ trudesk.min.js:1
(anonymous) @ trudesk.min.js:1
(anonymous) @ trudesk.min.js:1
```

**Comment by polonel** [comment]
Again.. why are you running yarn build anyway? Why aren’t you just using the build files included in the repo. They work.
