### ISSUE TITLE
Not able to run trudesk

### ISSUE THREAD

**Issue by priyanka-24** [polonel/trudesk#222]
- Trudesk Version:1.0.13
- OS (e.g. from /etc/os-release):Ubuntu
- Node.JS Version:10.15.3
- MongoDB Version:4.0.10
- Is this hosted on cloud.trudesk.io:

**Comment by priyanka-24** [comment]
This issue is not been resolved . Need help

**Comment by polonel** [comment]
It's impossible to know what your issue is when you provide zero information. Please fill out the issue for correctly.
