### ISSUE TITLE
Confusion UI button separator

### ISSUE THREAD

**Issue by 0x3333** [polonel/trudesk#223]
In the UI we have the 3 dots as a separator, but they are also used as a menu icon, the famous "`menu icon`", they denote an action, more actions, or something, they are even called "`more_vert`".

Would be better if we change these separators as a more subtle icon, like, a bar or something.

![Screen Shot 2019-06-12 at 15 01 18](https://user-images.githubusercontent.com/289289/59374934-68046100-8d23-11e9-8a67-ba76b078cc25.png)

Like this:
![Screen Shot 2019-06-12 at 15 14 12](https://user-images.githubusercontent.com/289289/59375554-c5e57880-8d24-11e9-99e6-e8a2c83992ed.png)
I'm using "`remove`" icon in a 90 deg rotation, as there is no other option like this in Material Icons. This is not ideal, as it should have be higher, but is a start, maybe be dimmer also would help.

**Comment by polonel** [comment]
Can you do a pull request? I'll merge it over.

**Comment by 0x3333** [comment]
Sure, give me a couple minutes.

**Comment by 0x3333** [comment]
I'll not be able to push today, tomorow morning I'll push, just need some test...

**Comment by 0x3333** [comment]
Here we go, I did the change. But I'd like your opinion on the color:

A: ![Screen Shot 2019-06-13 at 11 51 53](https://user-images.githubusercontent.com/289289/59443023-ac4e3a80-8dd1-11e9-8d97-516195b04954.png)

B: ![Screen Shot 2019-06-13 at 11 51 20](https://user-images.githubusercontent.com/289289/59443025-ac4e3a80-8dd1-11e9-9b8f-f84787b5fd79.png)

I prefer B, as it is clear that it is not a element of the toolbar, just a separator.

**Comment by polonel** [comment]
B is fine with me.

**Comment by akhlaaqbadulla** [comment]
@0x3333 B is nice
