### ISSUE TITLE
Files ( pdf ) are not uploaded on the single ticket page

### ISSUE THREAD

**Issue by julienveliarun** [polonel/trudesk#227]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [X] BUG 
- [ ] FEATURE

**What happened**: Files ( pdf ) are not uploaded on the single ticket page by clicking the paperclip icon on the issue. nothing happens even in the console ( no error ) 

**What did you expect to happen**: the (pdf) file should be uploaded

**How to reproduce it (as minimally and precisely as possible)**:

![report](https://user-images.githubusercontent.com/45491044/59739222-0e48ed00-9275-11e9-87ca-03d4af38cf0f.gif)

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: 1.0.10
- OS (e.g. from /etc/os-release): Ubuntu 18.04.2 LTS
- Node.JS Version: v10.16.0
- MongoDB Version: v3.6.13 
- Is this hosted on cloud.trudesk.io: no

**Comment by polonel** [comment]
Looking at your version number, and testing on latest. This was fixed back in `v1.0.12`. Which you should upgrade to latest `v1.0.14`.
Version 1.0.11+ is going to come with teams and departments.

If your not wanting to upgrade past version `1.0.10` you can look at the commit that fixed the bug and self implement it.

https://forum.trudesk.io/t/announcement-trudesk-v1-0-12-release

**Comment by julienveliarun** [comment]
I'll look into self implementing it thank you
