### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by dhelland** [polonel/trudesk#229]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**: Error: {"success":false,"error":"Invalid Origin!"}

**What did you expect to happen**: Continue installation

**How to reproduce it (as minimally and precisely as possible)**: Boot from Docker, click Lets Start, complete admin form and submit

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: latest
- OS (e.g. from /etc/os-release): Ubuntu 18.04.2 LTS
- Node.JS Version: 10.10
- MongoDB Version: 3.6
- Is this hosted on cloud.trudesk.io: No

**Comment by polonel** [comment]
Which browser are you using?

**Comment by dhelland** [comment]
Chrome

**Comment by dhelland** [comment]
Just tried it in Firefox and it worked. Any idea why Chrome didn't like it?

**Comment by akhlaaqbadulla** [comment]
@dhelland have you tried clearing your cache and cookies.

**Comment by jessequinn** [comment]
clearing cache in chrome does not fix this issue. I have this error when im using my nginx reverse proxy. To install i need to stick with the localhost:8118

**Comment by the-jojo-jj** [comment]
hi @jessequinn, did @polonel fix this issue?
or do you fix with nginx reverse proxy?

**Comment by jessequinn** [comment]
@the-jojo-jj no longer using. from what I remember i have to stick with port 8118 and was not fixed by nginx.
