### ISSUE TITLE
Not getting any response also system gets hang on Amazon ec2 64bit ARM

### ISSUE THREAD

**Issue by shivajimagadum15** [polonel/trudesk#230]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x ] BUG 
- [ ] FEATURE

**What happened**:
No response after 'yarn run build' command. I have to kill the process. If i forgot to kill the process then i have to reboot the ec2 instance manually.
**What did you expect to happen**:
Should get response
**How to reproduce it (as minimally and precisely as possible)**:
1) Git clone codebase from github
2) npm install -g yarn
3) yarn
4) yarn run build

**Anything else we need to know?**:
Cloning into 'trudesk'...
warning: redirecting to https://github.com/polonel/trudesk.git/
remote: Enumerating objects: 150, done.
remote: Counting objects: 100% (150/150), done.
remote: Compressing objects: 100% (91/91), done.
remote: Total 20276 (delta 97), reused 98 (delta 58), pack-reused 20126
Receiving objects: 100% (20276/20276), 40.97 MiB | 18.29 MiB/s, done.
Resolving deltas: 100% (13934/13934), done.
[root@ip codebase]# cd trudesk/
[root@ip trudesk]# npm install -g yarn
/usr/local/nvm/versions/node/v10.16.0/bin/yarn -> /usr/local/nvm/versions/node/v10.16.0/lib/node_modules/yarn/bin/yarn.js
/usr/local/nvm/versions/node/v10.16.0/bin/yarnpkg -> /usr/local/nvm/versions/node/v10.16.0/lib/node_modules/yarn/bin/yarn.js
+ yarn@1.16.0
updated 1 package in 0.369s
[root@ip trudesk]# yarn
yarn install v1.16.0
[1/6] Validating package.json...
[2/6] Resolving packages...
[3/6] Fetching packages...
info fsevents@1.2.7: The platform "linux" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/6] Linking dependencies...
warning " > eslint-plugin-prettier@3.0.1" has unmet peer dependency "prettier@>= 1.13.0".
[5/6] Building fresh packages...
[6/6] Cleaning modules...
Done in 34.50s.
[root@ip trudesk]# yarn run build
yarn run v1.16.0
$ grunt build
Running "uglify:uikit" (uglify) task
>> 1 file created 317.57 kB → 200.31 kB

Running "cssmin:target" (cssmin) task
>> 1 file created. 501.22 kB → 380.17 kB

Running "cssmin:minify" (cssmin) task
>> 3 files created. 388.37 kB → 382.4 kB

Running "shell:webpackDist" (shell) task

> trudesk@1.0.14 webpackdist /root/codebase/trudesk
> rimraf public/js/* && webpack --env.production -p --config webpack.config.js

Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade caniuse-lite browserslist`

**Environment**:  
- Trudesk Version: v1.0.14
- OS (e.g. from /etc/os-release): Amazon ec2 ARM Linux kernel
- Node.JS Version: v10.16.0
- MongoDB Version: MongoDB Atlas
- Is this hosted on cloud.trudesk.io: NA

**Comment by polonel** [comment]
Not enough RAM to do the build. But you don’t need to do the build. The build files are included on tagged releases. No reason to run yarn build after a fresh clone of master.
