### ISSUE TITLE
Unable to restart Trudesk after 1st install

### ISSUE THREAD

**Issue by kmyles82** [polonel/trudesk#231]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [X] BUG 
- [ ] FEATURE

**What happened**:
I the Trudesk installation and made it to the point where I was told to restart the Trudesk. I stopped the service and restarted it with the command "node runner", but the output just keep repeating:

    2019-06-21T13:21:21: PM2 log: App [trudesk:0] exited with code [1] via signal [SIGINT]
    2019-06-21T13:21:21: PM2 log: App [trudesk:0] starting in -fork mode-
    2019-06-21T13:21:21: PM2 log: App [trudesk:0] online

I looked in the log and get this output:
<img width="675" alt="Capture" src="https://user-images.githubusercontent.com/40246370/59944104-8eb04f00-9429-11e9-9f19-c9a7afd2326e.PNG">

     

**What did you expect to happen**:
To login Trudesk for the first time

**How to reproduce it (as minimally and precisely as possible)**:
Install MongoDB
Install ElasticSearch
Install Trudesk (go through the installation steps and click the Restart Me button

**Anything else we need to know?**:
I tried to open the login at localhost:8118 and get error page localhost refused connection.
I tried to open localhost:27017 and the error 'It looks like you are trying to access MongoSB over HTTP on the native driver port'

I'm totally lost and have no idea what to do to make this work. Yes, I am a noob. Is there a detail walk through of how to setup Trudesk and MongoDB (video tutorial for Windows 10)

**Environment**:
- Trudesk Version: 1.0.14
- OS (e.g. from /etc/os-release): Windows 10
- Node.JS Version: 10.16.0
- MongoDB Version: 1.18.0
- Is this hosted on cloud.trudesk.io: No

**Comment by polonel** [comment]
You were on a version prior to 1.0.7. Which the error states you need to upgrade to v1.0.7

So the upgrade path would be: `1.0.7 -> 1.0.10 -> 1.0.14`

**Comment by kmyles82** [comment]
thank you for your response. I will try your recommendations and keep you posted.

**Comment by kmyles82** [comment]
when running the command git checkout v.1.0.7, i get the error "fatal: not a git repository (or any of the parent directories): 

which is weird. So i create an entirely new directory and cloned https://github.com/polonel/trudesk.git and when run "git pull" or any git command, I still get that same fatal error. Is this a git issue?

**Comment by polonel** [comment]
@kmyles82 Status? Can this be closed?
