### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by TheDoctorMagic** [polonel/trudesk#233]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [X] BUG 
- [ ] FEATURE

**What happened**:
we updated our Truedesk version from 1.0.7 to 1.0.12 this week and it seemed that everything went as good as it could but today weird things happend ... at a certain point it stopped receiving mails.
**What did you expect to happen**:
displaying mails as normal
**How to reproduce it (as minimally and precisely as possible)**:
dunno happend out of nowhere

**Anything else we need to know?**:
Logs:
1|trudesk  | 6/25 10:51:20 [11612] - debug: Processed 1 Mail > Ticket
1|trudesk  | TypeError: Cannot read property '_id' of undefined
1|trudesk  |     at async.auto.handleCreateTicket (/services/trudesk/src/mailer/mailCheck.js:344:40)
1|trudesk  |     at runTask (/services/trudesk/node_modules/async/dist/async.js:1632:13)
1|trudesk  |     at /services/trudesk/node_modules/async/dist/async.js:1572:13
1|trudesk  |     at processQueue (/services/trudesk/node_modules/async/dist/async.js:1582:13)
1|trudesk  |     at taskComplete (/services/trudesk/node_modules/async/dist/async.js:1601:9)
1|trudesk  |     at /services/trudesk/node_modules/async/dist/async.js:1625:17
1|trudesk  |     at /services/trudesk/node_modules/async/dist/async.js:969:16
1|trudesk  |     at /services/trudesk/src/mailer/mailCheck.js:288:24
1|trudesk  |     at /services/trudesk/node_modules/mongoose/lib/model.js:4659:16
1|trudesk  |     at /services/trudesk/node_modules/mongoose/lib/utils.js:255:16
1|trudesk  |     at _hooks.execPost (/services/trudesk/node_modules/mongoose/lib/query.js:4065:11)
1|trudesk  |     at /services/trudesk/node_modules/kareem/index.js:135:16
1|trudesk  |     at args.(anonymous function) (/usr/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:138:29)
1|trudesk  |     at processTicksAndRejections (internal/process/next_tick.js:74:9)

**Environment**:
- Trudesk Version: 1.0.12
- OS (e.g. from /etc/os-release): Debian
- Node.JS Version: 11.12.0
- MongoDB Version: current version
- Is this hosted on cloud.trudesk.io: no

**Comment by polonel** [comment]
Why `v1.0.12` and not `v1.0.14`?

**Comment by TheDoctorMagic** [comment]
we'll do it today and give u feedback :)

**Comment by TheDoctorMagic** [comment]
so we successfully updated on v.1.0.14 but the issue is still there  --> not receiving mail updates --> getting a type error and then pm2 restarts the service  😐

**Comment by TheDoctorMagic** [comment]
now we're in a loop with the following error message..... side note (there is no duplicate): 

- info: Connected to MongoDB                                                                                                    |
|                                                                   || trudesk > 6/26 11:47:04 [29111] - debug: Checking Default Settings...                                                                                           |
|                                                                   || trudesk > 6/26 11:47:04 [29111] - debug: Timezone set to Europe                                                                                          |
|                                                                   || trudesk > 6/26 11:47:04 [29111] - debug: Registering Permissions...                                                                                             |
|                                                                   || trudesk > 6/26 11:47:04 [29111] - info: SocketServer Running                                                                                                    |
|                                                                   || trudesk > 6/26 11:47:05 [29111] - debug: Starting MailCheck...                                                                                                  |
|                                                                   || trudesk > Error: MongoError: E11000 duplicate key error collection: db.teams index: name_1 dup key: { : "Support (Default)" }                            |
|                                                                   || trudesk >     at /services/trudesk/app.js:222:24                                                                                                                |
|                                                                   || trudesk >     at /services/trudesk/node_modules/async/dist/async.js:3888:9                                                                                      |
|                                                                   || trudesk >     at /services/trudesk/node_modules/async/dist/async.js:473:16                                                                                      |
|                                                                   || trudesk >     at iterateeCallback (/services/trudesk/node_modules/async/dist/async.js:988:17)                                                                   |
|                                                                   || trudesk >     at /services/trudesk/node_modules/async/dist/async.js:969:16                                                                                      |
|                                                                   || trudesk >     at /services/trudesk/node_modules/async/dist/async.js:3885:13                                                                                     |
|                                                                   || trudesk >     at /services/trudesk/src/migration/index.js:234:23                                                                                                |
|                                                                   || trudesk >     at /services/trudesk/node_modules/async/dist/async.js:3888:9                                                                                      |
|                                                                   || trudesk >     at /services/trudesk/node_modules/async/dist/async.js:473:16                                                                                      |
|                                                                   || trudesk >     at iterateeCallback (/services/trudesk/node_modules/async/dist/async.js:988:17)                                                                   |
|                                                                   || trudesk >     at /services/trudesk/node_modules/async/dist/async.js:969:16                                                                                      |
|                                                                   || trudesk >     at /services/trudesk/node_modules/async/dist/async.js:3885:13                                                                                     |
|                                                                   || trudesk >     at /services/trudesk/node_modules/async/dist/async.js:3888:9                                                                                      |
|                                                                   || trudesk >     at /services/trudesk/node_modules/async/dist/async.js:473:16                                                                                      |
|                                                                   || trudesk >     at iteratorCallback (/services/trudesk/node_modules/async/dist/async.js:1062:13)                                                                  |
|                                                                   || trudesk >     at /services/trudesk/node_modules/async/dist/async.js:969:16                                                                                      |
|                                                                   || trudesk >     at /services/trudesk/node_modules/async/dist/async.js:3885:13                                                                                     |
|                                                                   || trudesk >     at /services/trudesk/node_modules/async/dist/async.js:473:16                                                                                      |
|                                                                   || trudesk >     at next (/services/trudesk/node_modules/async/dist/async.js:5329:29)                                                                              |
|                                                                   || trudesk >     at /services/trudesk/node_modules/async/dist/async.js:969:16                                                                                      |
|                                                                   || trudesk >     at /services/trudesk/node_modules/mongoose/lib/model.js:4659:16                                                                                   |
|                                                                   || trudesk >     at /services/trudesk/node_modules/mongoose/lib/utils.js:247:11                                                                                    |
|                                                                   || PM2 > App [trudesk:1] exited with code [1] via signal [SIGINT]                                                                                                  |
|                                                                   || PM2 > App [trudesk:1] starting in -fork mode-                                                                                                                   |
|                                                                   || PM2 > App [trudesk:1] online

**Comment by ninanoe** [comment]
I have the same issue.   

TypeError: Cannot read property '_id' of undefined
    at async.auto.handleCreateTicket (C:\trudesk\src\mailer\mailCheck.js:344:40)
    at runTask (C:\trudesk\node_modules\async\dist\async.js:1632:13)
    at C:\trudesk\node_modules\async\dist\async.js:1572:13
    at processQueue (C:\trudesk\node_modules\async\dist\async.js:1582:13)
    at taskComplete (C:\trudesk\node_modules\async\dist\async.js:1601:9)
    at C:\trudesk\node_modules\async\dist\async.js:1625:17
    at C:\trudesk\node_modules\async\dist\async.js:969:16
    at C:\trudesk\src\mailer\mailCheck.js:288:24
    at C:\trudesk\node_modules\mongoose\lib\model.js:4659:16
    at C:\trudesk\node_modules\mongoose\lib\utils.js:255:16
    at _hooks.execPost (C:\trudesk\node_modules\mongoose\lib\query.js:4065:11)
    at C:\trudesk\node_modules\kareem\index.js:135:16
    at args.(anonymous function) (C:\trudesk\node_modules\event-loop-inspector\index.js:138:29)
    at process._tickCallback (internal/process/next_tick.js:61:11)

Environment:

Trudesk Version: 1.0.14
OS (e.g. from /etc/os-release): Windows
Node.JS Version: 10.16.0

IMAP plain text 
New mails not processed ,   nor deleted , or accounts created

**Comment by polonel** [comment]
Again, what mail service is being used? Gmail? Exchange? Some custom IMAP server?

**Comment by ninanoe** [comment]
Plain IMAP (143)  on hMailserver without encryption.     

I did some more testing,    mail to ticket works with emails from customers. 

But it crashes when you recieve an email FROM the email address of the Admin account.

**Comment by TheDoctorMagic** [comment]
@polonel we're using MS Office 365

**Comment by TheDoctorMagic** [comment]
@polonel we've overridden the _id part ... because he can not identify _id ... we put every mail in an preset group id if undefined

**Comment by polonel** [comment]
@TheDoctorMagic Where did you override the _id part of mail check. So I can quickly resolve.

**Comment by Hardenberg** [comment]
hey, we've overridden: 
mailer/mailcheck -> 'handleCreateTicket'

**Comment by polonel** [comment]
Fix is included in `v1.0.16`

Currently on `develop`

**Comment by TheDoctorMagic** [comment]
nice I appreciate it :)
