### ISSUE TITLE
creating a new ticket 

### ISSUE THREAD

**Issue by TheDoctorMagic** [polonel/trudesk#234]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
we set up a fresh Trudesk
**What did you expect to happen**:
create a new ticket 
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Log: 
success=false, message=Cast to ObjectID failed for value "" at path "group", name=CastError, stringValue="",          |
|                                                                   || kind=ObjectID, value=, path=group, message=Cast to ObjectId failed for value "" at path "group", name=CastError, stringValue="", kind=ObjectId, value=,         |
|                                                                   || path=group, reason=undefined, _message=tickets validation failed, message=tickets validation failed: group: Cast to ObjectID failed for value "" at path        |
|                                                                   || "group", name=ValidationError  

Error: [object Object]

Environment:

Trudesk Version: 1.0.14
OS (e.g. from /etc/os-release): Debian
Node.JS Version: 11.12.0
MongoDB Version: current version
Is this hosted on cloud.trudesk.io: no

**Comment by polonel** [comment]
Do you have any groups created? None or created by default...

**Comment by TheDoctorMagic** [comment]
> Do you have any groups created? None or created by default...

just the default one ... but i did changed the name of the default.

**Comment by polonel** [comment]
Are their users in your groups? Does groups show up in the group drop down when creating the ticket? How is the ticket being created?

**Comment by TheDoctorMagic** [comment]
as far as i know there wasn't a group showing up at the ticket creation process, but i created a few user and added them into the default group

**Comment by TheDoctorMagic** [comment]
!closed ... it was just an occasionally DB Bug
