### ISSUE TITLE
Switch between languagues

### ISSUE THREAD

**Issue by suiteappdev** [polonel/trudesk#235]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ ] BUG 
- [x] FEATURE

**What happened**:

**What did you expect to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Trudesk Version:
- OS (e.g. from /etc/os-release):
- Node.JS Version:
- MongoDB Version:
- Is this hosted on cloud.trudesk.io:

Hello, I am testing on branch with  locales but cant switch between langs,  How can set my language?

**Comment by polonel** [comment]
The `i18n` branch is very old and out-dated. I do not recommend using it, it was never completed and the language switching is hard coded.
