### ISSUE TITLE
[FEATURE] Asset management/Inventory (like fusioninventory.org)

### ISSUE THREAD

**Issue by dlonghi** [polonel/trudesk#236]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ ] BUG 
- [x] FEATURE

Asset (computers, laptops, printers, VMs, etc) management/inventory like fusioninventory.org would be nice.

- Ability to specify a different db/host for the storing asset information;
- updates to the information via API;

**Comment by Wqrld** [comment]
Would be nice but it wouldn't really fit into this program

**Comment by polonel** [comment]
This will eventually be a plugin. I've already created something along these lines for IPAM (IP Address Management) as a plugin.
 
_The plugin system is currently disabled_
