### ISSUE TITLE
Cannot connect to MongoDB Atlas and finish Installation

### ISSUE THREAD

**Issue by javaknight** [polonel/trudesk#243]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x ] BUG 
- [ ] FEATURE

**What happened**:
Trudesk is unable to connect to our MongoDB Atlas cluster. As a result, we cannot finish the installation wizard and start Trudesk.

**What did you expect to happen**:
Successful connection to mongodb atlas cluster.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a cluster on mongodb atlas
2. Attempt to connect truedesk to it.

**Anything else we need to know?**:
I cannot perform any of the known workarounds, since I cannot complete the installation wizard, unless Truedesk is able to succesfully connect to Mongo

**Environment**:
- Trudesk Version:
1.0.14
- OS (e.g. from /etc/os-release):
ubuntu 18.04
- Node.JS Version:
10.16.0
- MongoDB Version:
atlas
- Is this hosted on cloud.trudesk.io:
no

**Comment by gavry** [comment]
Bump

**Comment by polonel** [comment]
Put your host from atlas in the Server / Host field and in the port field enter `---`.

This is will activate mongo+srv URI.

**Comment by javaknight** [comment]
![trudesk](https://user-images.githubusercontent.com/4492571/62145348-4b1af180-b2c1-11e9-9bd3-ff0f34a9023a.png)

It's not working. I put in the port as you describe, with spaces and without. No combination I input seems to allow me to connect to a Mongo Atlas URI.

**Comment by polonel** [comment]
Why did you leave all the other fields blank? No wonder it won't connect. It needs a username/password and database...

https://github.com/polonel/trudesk/blob/299edb4f66fc47e1e1c0ba8354778a2d1f1bdf2b/src/controllers/install.js#L61-L62
