### ISSUE TITLE
 Error: Cannot find module 'pm2'

### ISSUE THREAD

**Issue by ArashKeifi** [polonel/trudesk#246]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x ] BUG 
- [ ] FEATURE

hi
i got this error when i tried install Trudesk

Support         | internal/modules/cjs/loader.js:583
Support         |     throw err;
Support         |     ^
Support         |
Support         | Error: Cannot find module 'pm2'
Support         |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
Support         |     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
Support         |     at Module.require (internal/modules/cjs/loader.js:637:17)
Support         |     at require (internal/modules/cjs/helpers.js:20:18)
Support         |     at /usr/src/trudesk/runner.js:4:13
Support         |     at Object.<anonymous> (/usr/src/trudesk/runner.js:28:3)
Support         |     at Module._compile (internal/modules/cjs/loader.js:689:30)
Support         |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
Support         |     at Module.load (internal/modules/cjs/loader.js:599:32)
Support         |     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)

**Comment by polonel** [comment]
This is an NPM error. Its failing to download PM2 and unpackage it. I have this same issue on my build servers waiting for them to fix it.
