### ISSUE TITLE
Bug datepicker with format changed

### ISSUE THREAD

**Issue by IneoO** [polonel/trudesk#247]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
When changing date format, date picker bug

**What did you expect to happen**:
get the good date in date picker

**How to reproduce it (as minimally and precisely as possible)**:
in settings change date format
go to date picker in the edit ticket form

**Anything else we need to know?**:
_settings_
![captured](https://user-images.githubusercontent.com/8982189/61447424-35b4d780-a951-11e9-825d-ecff8aa6c723.png)
_Gif of the bug_
![captured](https://user-images.githubusercontent.com/8982189/61447434-39485e80-a951-11e9-88d1-539841e45814.gif)

**Environment**:
- Trudesk Version: 299edb4f : 1.0.15
- OS (e.g. from /etc/os-release): ubuntu 18.04.2 LTS (Bionic Beaver)
- Node.JS Version: 6.7.0
- MongoDB Version: v3.6.12
- Is this hosted on cloud.trudesk.io: no

**Comment by polonel** [comment]
Are you referring to the rendering issue where the date renders the default format and then quickly switches to the customized format?

**Comment by IneoO** [comment]
Nop, picking 4 January change the date to 1 may in the date picker

**Comment by IneoO** [comment]
Up

**Comment by jackd942** [comment]
I can confirm this on our end as well. Although in our case, the date that gets stored to mongo appears to be one day off...ie select 8/6/2019 saves 8/5/2019.

**Comment by polonel** [comment]
I store all dates in mongo as UTC so I can handle the time zone offset
depending on user settings. This might be why you’re seeing them one day
off. They get set back to +0

**Comment by jackd942** [comment]
Just double checked to make sure my Timezone was set correctly and it is. So I guess the logic in the component is not taking the timezone setting into account?

**Comment by polonel** [comment]
That may be the case. I’m going to dive deeper into it tonight

**Comment by jackd942** [comment]
Actually I'm not sure if that is the case. We are -5 and still seeing the behavior I described above. It is currently 11:45am 8/6 here and utc is 4:45 8/6. We still see that behavior, so I think that may rule that out.

**Comment by polonel** [comment]
@IneoO @jackd942 
I pushed a fix (hopefully) to develop. If you guys don't mind giving it a test on your environments.

**Comment by IneoO** [comment]
thx, that's fine for me ! (we can close)
