### ISSUE TITLE
ElasticSearch Connection Fails

### ISSUE THREAD

**Issue by DustyArmstrong** [polonel/trudesk#250]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
Fresh installation of Trudesk, unable to connect to ElasticSearch on Test Connection. Error states "couldn't connect; make sure connection is correct". 

**What did you expect to happen**:
The connection to ElasticSearch to be made. 

**How to reproduce it (as minimally and precisely as possible)**:
Run the Ubuntu installation script, allow it to install all prerequisite packages. Open a web browser and navigate to the Trudesk installation page. Provide the details as requested to connect to ElasticSearch. 

**Anything else we need to know?**:
I couldn't find any information around ElasticSearch in the documentation in regards to its configuration or integration. I have never used ElasticSearch so it is entirely possible I'm just not aware of how to set it up. 

**Environment**:
- Trudesk Version: 1.0.12
- OS (e.g. from /etc/os-release): Ubuntu 18.04.2
- Node.JS Version: v10.16.0
- MongoDB Version: v3.6.13
-ElasticSearch Version: 6.8.1
- Is this hosted on cloud.trudesk.io: No

**Comment by polonel** [comment]
If you used the ubuntu install script provided [here](http://trudesk.io/v1/guide/installation.html#Ubuntu-Install-Script), it should automatically setup the configuration and start ElasticSearch for you. Then during the install wizard, the default values should connect just fine. (localhost)

Check to make sure the ubuntu firewall is not running (`sudo ufw status`) and that ES is running. 
(`sudo systemctl status elasticsearch`)

**Comment by DustyArmstrong** [comment]
I found an old post (https://forum.trudesk.io/t/could-not-connect-to-elasticsearch-error/183) that had a post process, and that seemed to work, though I don't think it searches still. It did change the status to connected, at the least. 

I'll do what you suggest, thank you.

**Comment by DustyArmstrong** [comment]
That didn't seem to make any change, the output of `sudo ufw status` was inactive, and Elastic Search is running. I followed some suggestions people had with Elastic Search issues, and interestingly any change to the config resulted in `Connection refused`. 

Under `/etc/elasticsearch/elasticsearch.yml` there is an entry appended to the bottom `network.host: [_local_]`. Removing this and instead uncommenting the line `network.host: 0.0.0.0` allowed CURL to pull, as well as the browser. I'm assuming though that `network.host: [_local_]` being set was on purpose and for good reason. 

I suppose I can live without the search, just something to be aware that it may have some issues (unless I'm the only one, in which case oh well!).

**Comment by DustyArmstrong** [comment]
Can confirm does now work with the suggested fix at https://forum.trudesk.io/t/could-not-connect-to-elasticsearch-error/183.
