### ISSUE TITLE
[REQUEST] - Create and assignt ticket to an user

### ISSUE THREAD

**Issue by cotanmarius** [polonel/trudesk#252]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ ] BUG 
- [x] FEATURE

**What happened**:
I'm not sure if this feature already exists or not, but i have the following scenario:
A customer or a colleague calls the IT department and one of the IT guys will create a ticket for him. The customer already exist in the Trudesk DB and we want to create the ticket in the name of that customer, so to be able to select the customer at the creation time.

**What did you expect to happen**:
At the moment, o can't find an option to choose the customer at the creation time

**How to reproduce it (as minimally and precisely as possible)**:
Click on the "+" symbol and create a new ticket.

**Anything else we need to know?**:

Trudesk Version: 1.0.15
OS (e.g. from /etc/os-release): Ubuntu 18.04.2 LTS x64
Node.JS Version: v10.16.1
MongoDB Version: v3.6.13
Is this hosted on cloud.trudesk.io: No

**Comment by polonel** [comment]
Currently not possible through the web UI. It is something I will add for agents/admins.

Right now the owner can be set through the API during ticket creation only.

**Comment by cotanmarius** [comment]
@polonel 
Thank you, i appreciate!

**Comment by ramezrafla** [comment]
Indeed, this would be really cool. A major requirement for production ticketing system, being able to manually subscribe users to a ticket. Thanks!
