### ISSUE TITLE
Can i change tickets'subject to any other field. Or can i add another field in ticket section, like location or else.

### ISSUE THREAD

**Issue by wowhiren** [polonel/trudesk#253]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x ] BUG 
- [x] FEATURE

**What happened**:

**What did you expect to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Trudesk Version:
- OS (e.g. from /etc/os-release):
- Node.JS Version:
- MongoDB Version:
- Is this hosted on cloud.trudesk.io:

Can i change tickets'subject to any other field. Or can i add another field in ticket section, like location or else.

**Comment by wowhiren** [comment]
Basically I want to change the Subject label to something else. and i could not find it the source file... Thank for help

**Comment by polonel** [comment]
Not currently possible unless you change all references to the ticket subject in the codebase.
