### ISSUE TITLE
this site can't be reached

### ISSUE THREAD

**Issue by naufalscofield** [polonel/trudesk#256]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [] BUG 
- [X] FEATURE

i've already install trudesk, mongodb and node, i followed the instructions on trudesk web and i'm using windows.

i'm start mongod and mongo in cmd and then i start trudesk with command "node runner"
and i'm open browser to the url "localhost:8118"

but the login page doesn't appear, all i get is "This Site Can't Be Reached" i dunno where i was wrong.

however, yesterday i successfully install trudesk and it's like normal, i've created a ticket too. But today i start trudesk again with "node runner" but the login page doesn't appear

**Environment**:
- Trudesk Version:1.0.12
- OS (e.g. from /etc/os-release): windows 10
- Node.JS Version: 10.16.3
- MongoDB Version:4.2.0
- Is this hosted on cloud.trudesk.io: still on localhost

![trudesk](https://user-images.githubusercontent.com/38066867/64230301-a9696e80-cf16-11e9-980f-a124b3f3b2df.JPG)

**Comment by naufalscofield** [comment]
![trudesk1](https://user-images.githubusercontent.com/38066867/64230392-f2212780-cf16-11e9-9854-97b18f238d00.JPG)
![mongod](https://user-images.githubusercontent.com/38066867/64230391-f2212780-cf16-11e9-9d33-45eeb49d6a4c.JPG)
![mongo](https://user-images.githubusercontent.com/38066867/64230393-f2212780-cf16-11e9-82d6-28692f9dda9f.JPG)

**Comment by polonel** [comment]
Did you clone at a tagged version? If so what version?

Run `yarn start` instead of `node runner`

**Comment by naufalscofield** [comment]
thanks for your reply, it's my first time using trudesk,

here an error when i run yarn start

![yarn](https://user-images.githubusercontent.com/38066867/64230901-4c6eb800-cf18-11e9-9c22-88e24eda39c3.JPG)

**Comment by polonel** [comment]
Make sure all the deps are installed, `yarn install` and then run `yarn run build`

**Comment by naufalscofield** [comment]
ok i'll try thanks for your support

**Comment by naufalscofield** [comment]
so after i clone, i install yarn with yarn install and not npm install -g yarn ???

**Comment by naufalscofield** [comment]
ah so i have another problem, i've succesfully install trudesk , but now after i fill out the "setup account" and the trudesk ask me to restart, after i restart the page isn't redirect to login page, but return to welcome page

**Comment by naufalscofield** [comment]
i have succesfully run `yarn start` but the process is stacked here
![yarns](https://user-images.githubusercontent.com/38066867/64305617-20a40e80-cfba-11e9-94db-8a71e572b43a.jpg)

**Comment by polonel** [comment]
It's hung because I do not have binaries for MongoDB 4.2. Only 3.6.9 and 4.0.
Trudesk looks at your running mongodb server version and tries to download MongoDB tools from trudesk servers running in AWS. 

You can either downgrade to mongodb 4.0 or download the Mongo-Tools binaries from [Mongodb](https://www.mongodb.com/download-center/community) and put them in `trudesk/src/backup/bin/win32` folder

**Comment by naufalscofield** [comment]
so i've downgraded my mongodb to 4.0 and when i run `yarn start` i get this error
![yarn2](https://user-images.githubusercontent.com/38066867/64316714-d0d83e00-cfdf-11e9-9b8e-10840b610773.JPG)

**Comment by polonel** [comment]
That is a bug. I'm working on a fix now. In the meantime. To workaround...

you need to `git checkout v1.0.7` start the server then `git checkout v1.0.10` start the server. etc. all the way to v1.0.15. The following upgrade path.

`v1.0.7 -> v1.0.10 -> v1.0.13 -> v1.0.15`

**Comment by naufalscofield** [comment]
ok

**Comment by polonel** [comment]
I just noticed that its showing `No Types defined` I believe you wiped your mongodb when you did the downgrade. you will also need to delete `trudesk/config.json` and run the install wizard again by restarting the server after you delete that file.

**Comment by naufalscofield** [comment]
so i've reach login page, but i can't login. is there a way to see my admin account? i kinda not sure with my admin account

**Comment by naufalscofield** [comment]
![login](https://user-images.githubusercontent.com/38066867/64329877-27eb0c80-cffa-11e9-8a65-346d75217745.jpg)
 or can i add another admin account?

**Comment by vorion** [comment]
@naufalscofield If you've deleted the mongodb collections then your user account is gone and needs to be rebuilt. Like polonel says, you need to do the install again. At this point you may just want to do a fresh clone and follow his steps from the beginning again, since you haven't even logged in with an account.
