### ISSUE TITLE
Unable to setup trudesk on windows 10 x64 OS.

### ISSUE THREAD

**Issue by Mohamed-Abubucker** [polonel/trudesk#257]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x ] BUG 
- [ ] FEATURE

**What happened**:
I am using windows 10 OS and Nodejs v12+ with VSCode and powershell.

when i tried to install trudesk, i cloned the latest code and tried to do yarn. i am getting below errors.

(skipped error junk)

    33 Warning(s)
    48 Error(s)

Time Elapsed 00:01:35.27
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (E:\TMS\trudesk\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\TMS\\trudesk\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd E:\TMS\trudesk\node_modules\node-sass
gyp ERR! node -v v12.9.1

Kindly help me to resolve this and setup trudesk on windows.
**Environment**:
- Trudesk Version:
- OS Windows 10 x64:
- Node.JS v12+:
- MongoDB v4 from atlas:
- trying to setup selfhosted trudesk on windows server.

**Comment by polonel** [comment]
You didn't install the windows build tools needed to compile native packages. https://www.npmjs.com/package/windows-build-tools
