### ISSUE TITLE
Stuck on "Windows platform detected. Downloading MongoDB Tools"

### ISSUE THREAD

**Issue by tojimat** [polonel/trudesk#265]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ x] BUG 
- [ ] FEATURE

**What happened**:
TruDesk installed and user has been created and after restart login page not loaded. Log shows:

 [9560] - [34mdebug[39m: Windows platform detected. Downloading MongoDB Tools

And it is waiting indefinitely it seems and no download is happening
**What did you expect to happen**:
Login screen to display
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**: 
- Trudesk Version: 1.0.16
- OS (e.g. from /etc/os-release): Windows 8.1
- Node.JS Version: v10.16.3
- MongoDB Version: 4.2.0
- Is this hosted on cloud.trudesk.io: No, On local windows machine

**Comment by tobecwb** [comment]
same here!
perhaps the same problem of #139 ?

**Comment by ChpeX** [comment]
Hi, i had the same problem and i did this:
go to src/settings/defaults.js and in this line 
var dbVersion = require('../database').db.version || '3.6.9'
just rewrite with:
var dbVersion = '3.6.9'
and save it 
and retry.

Hope that it helps

**Comment by tobecwb** [comment]
tried the suggestion from @ChpeX and started successfully on Windows plataform.

**Comment by tojimat** [comment]
Thank you @ChpeX . You solved our problem!  It started working for me as well.

**Comment by HoseinGhanbari** [comment]
**same issue here...**
window 10
node 12.16.3
npm 6.14.5
mongodb 4.2.5
