### ISSUE TITLE
How can we Reset the password.., Is there any way that we can achieve?

### ISSUE THREAD

**Issue by urstrulymahesh24** [polonel/trudesk#271]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x ] BUG 
- [ ] FEATURE

**What happened**: Unable to Reset the Password, Mail configuration not working..

**What did you expect to happen**: Password reset & Mail configuration.

**Comment by polonel** [comment]
Without mailer setup. You will need another administrator to login and reset the password for the given user.
