### ISSUE TITLE
Node runner. Frozen on "Trudesk Install Server Running..."

### ISSUE THREAD

**Issue by NeroAlfonso** [polonel/trudesk#274]
Hi everyone. After "node runner"
![image](https://user-images.githubusercontent.com/30022632/68022350-79bab680-fc7a-11e9-8573-79473d098f34.png)
and PM2 log
![image](https://user-images.githubusercontent.com/30022632/68022376-8a6b2c80-fc7a-11e9-8ad2-7d6041710469.png)
the process is frozen and not showing errors
EDIT: the process is frozen here now
![image](https://user-images.githubusercontent.com/30022632/68053382-28361a00-fcc2-11e9-80ef-95ff59821451.png)

**Comment by polonel** [comment]
Please see #265 
Note that if you perform this workaround, backups will not work on Windows. I do not currently have the binaries hosted for the latest version of MongoDB, thus it is unable to download the backup tools.

**Comment by NeroAlfonso** [comment]
his method works for me. Thank you
