### ISSUE TITLE
Invalid graph data on entering the dashboard page

### ISSUE THREAD

**Issue by unexpectedShr3k** [polonel/trudesk#275]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
A notification with error on graph data being invalid.

**What did you expect to happen**:
the graph loads. I have two issues created in the last 10 minutes.

**How to reproduce it (as minimally and precisely as possible)**:
create tickets, go to the dashboard.

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: 1.0.0
- OS (e.g. from /etc/os-release): Ubuntu 18 LTS
- Node.JS Version: pulled from docker
- MongoDB Version: 3.6
- Is this hosted on cloud.trudesk.io: no

**Comment by polonel** [comment]
Can you confirm that this bug exists on the latest version of trudesk, which is `v1.0.17`?

**Comment by unexpectedShr3k** [comment]
I've updated and I confirm it happens in version 1.0.17 as well.
