### ISSUE TITLE
Ticket detail 'Back' button disappears in mobile view

### ISSUE THREAD

**Issue by unexpectedShr3k** [polonel/trudesk#276]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
The Back button in ticket detail view (/mobile/#/tab/tickets/XXXX) disappears if the browser tab is reloaded. It is impossible for the user to navigate back to ticket listing. The bottom navigation bar ticket button also doesn't work.

**What did you expect to happen**:
an option to go from ticket detail to ticket list after reloading the page, which can  happen if the agent has connectivity problems for a moment, it can disrupt support service.

**How to reproduce it (as minimally and precisely as possible)**:
In mobile view, go to ticket listing (second icon in the bottom navigation bar). Click on a ticket. Once it is opened, reload the tab.

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: 1.0.0
- OS (e.g. from /etc/os-release): Ubuntu 18 LTS
- Node.JS Version: pulled docker image
- MongoDB Version: 3.6
- Is this hosted on cloud.trudesk.io: no

**Comment by polonel** [comment]
Can you confirm that this bug exists on the latest version of trudesk which is `1.0.17`?

**Comment by unexpectedShr3k** [comment]
I've updated and I confirm it happens in version 1.0.17 as well.

**Comment by unexpectedShr3k** [comment]
And it also happens for the chat view in mobile version. you can't go back to the chat roster.
