### ISSUE TITLE
Error: Please upgrade to v1.0.7 Exiting...

### ISSUE THREAD

**Issue by marquetingca** [polonel/trudesk#278]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
when connecting Trudesk to the database and starting the installation it shows the following error
**What did you expect to happen**:
finish the installation successfully
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
logs: 
4|trudesk  | 11/14 10:41:30 [29355] - info:     .                              .o8                     oooo
4|trudesk  | 11/14 10:41:30 [29355] - info:   .o8                             "888                     `888
4|trudesk  | 11/14 10:41:30 [29355] - info: .o888oo oooo d8b oooo  oooo   .oooo888   .ooooo.   .oooo.o  888  oooo
4|trudesk  | 11/14 10:41:30 [29355] - info:   888   `888""8P `888  `888  d88' `888  d88' `88b d88(  "8  888 .8P'
4|trudesk  | 11/14 10:41:30 [29355] - info:   888    888      888   888  888   888  888ooo888 `"Y88b.   888888.
4|trudesk  | 11/14 10:41:30 [29355] - info:   888 .  888      888   888  888   888  888    .o o.  )88b  888 `88b.
4|trudesk  | 11/14 10:41:30 [29355] - info:   "888" d888b     `V88V"V8P' `Y8bod88P" `Y8bod8P' 8""888P' o888o o888o
4|trudesk  | 11/14 10:41:30 [29355] - info: ==========================================================================
4|trudesk  | 11/14 10:41:30 [29355] - info: trudesk v1.0.16 Copyright (C) 2014-2019 Chris Brame
4|trudesk  | 11/14 10:41:30 [29355] - info:  
4|trudesk  | 11/14 10:41:30 [29355] - info: Running in: development
4|trudesk  | 11/14 10:41:30 [29355] - info: Server Time: Thu Nov 14 2019 10:41:30 GMT-0400 (GMT-04:00)
4|trudesk  | 11/14 10:41:30 [29355] - info: Connected to MongoDB
4|trudesk  | 11/14 10:41:31 [29355] - debug: Checking Default Settings...
4|trudesk  | 11/14 10:41:32 [29355] - debug: Timezone set to America/New_York
4|trudesk  | 11/14 10:41:32 [29355] - warn: No Types Defined!
4|trudesk  | 11/14 10:41:32 [29355] - debug: Registering Permissions...
4|trudesk  | 11/14 10:41:32 [29355] - info: SocketServer Running
4|trudesk  | Error: Please upgrade to v1.0.7 Exiting...
4|trudesk  |     at /var/www/asoTrudesk/src/migration/index.js:66:25
4|trudesk  |     at /var/www/asoTrudesk/node_modules/mongoose/lib/model.js:4659:16
4|trudesk  |     at /var/www/asoTrudesk/node_modules/mongoose/lib/utils.js:255:16
4|trudesk  |     at _hooks.execPost (/var/www/asoTrudesk/node_modules/mongoose/lib/query.js:4065:11)
4|trudesk  |     at /var/www/asoTrudesk/node_modules/kareem/index.js:135:16
4|trudesk  |     at process._tickCallback (internal/process/next_tick.js:61:11)
**Environment**:
- Trudesk Version: v1.0.16
- OS (e.g. from /etc/os-release): Debian 9
- Node.JS Version: v10.16.0
- MongoDB Version: v4.2.1
- Is this hosted on cloud.trudesk.io:

**Comment by NeroAlfonso** [comment]
I have this problem too
