### ISSUE TITLE
[BUG] Losing Modal information

### ISSUE THREAD

**Issue by kingsCodeGriffin** [polonel/trudesk#284]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
When a user clicks out of the Create Ticket  form container all data entered is lost
**What did you expect to happen**:
A prompt to confirm exiting modal without saving ticket detail.
**How to reproduce it (as minimally and precisely as possible)**:
Start New Ticket > Click outside of the ticket form

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: 1.0.16
- OS (e.g. from /etc/os-release): docker image polonel/trudesk:1
- Node.JS Version: 6.14.3
- MongoDB Version: 3.6.15
- Is this hosted on cloud.trudesk.io:
No

**Comment by polonel** [comment]
I will get this implemented.

**Comment by polonel** [comment]
If they "click the background" or if they click cancel? If I click the background it doesn't close the create ticket window.
