### ISSUE TITLE
Getting error when using the Ubuntu script for installing Truedesk

### ISSUE THREAD

**Issue by Hemavasudevan05** [polonel/trudesk#286]
I am using the below Ubuntu version.
test@DESKTOP-8ET9IU0:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04

I am trying to install truedesk tool using the below commad
curl -L -s http://www.trudesk.io/install/install_ubuntu.sh | sudo bash

This is now working for me and I am getting the below error:
bash: line 1: syntax error near unexpected token `newline'
bash: line 1: `<!DOCTYPE html>'

Could you please help me to resolve this issue?

Best Regards
Hemalatha Vasudevan

**Comment by MarcHochleutner-Koellisch** [comment]
Remove the www., then it works.

**Comment by vpmuhsin** [comment]
in my case, internal connectivity issue ..  command curl -L -s http://www.trudesk.io/install/install_ubuntu.sh | sudo bash worked and finished everything.. i launch the installer on browser , but its raise error **Couldn't connect make sure connection is correct** on Elastic search configure steps ..same error on MongoDB connection configuration also ...
![Screenshot from 2020-07-05 14-37-33](https://user-images.githubusercontent.com/32394805/86529346-a5f39a80-becd-11ea-851d-d095cacdb199.png)
![Screenshot from 2020-07-05 14-42-31](https://user-images.githubusercontent.com/32394805/86529362-c6bbf000-becd-11ea-908d-a8a4a8034005.png)
