### ISSUE TITLE
No API Key assigned to this User

### ISSUE THREAD

**Issue by jjuanchini** [polonel/trudesk#287]
**Is this a BUG REPORT or FEATURE REQUEST?**:
- [x] BUG 
- [ ] FEATURE

**What happened**:
I'm trying to login with a user in the mobile version, and I'm getting "No API Key assigned to this User". If I use the user created while installation process, it works great.

**What did you expect to happen**:
Log any user in the mobile version

**How to reproduce it (as minimally and precisely as possible)**:
Create a user as an Admin, and try to login in the mobile version with the new user.

**Anything else we need to know?**:

I'm seeing the code, and the mobile version is using the API v1 for login, and **getUserByUsername** is not returning an accessToken when the user is not the original admin.

the desktop version is working well (I guess because it's using the API v2)

**Environment**:
- Trudesk Version: 1.0.17
- OS (e.g. from /etc/os-release): macOS 10.14.6
- Node.JS Version: v13.2.0
- MongoDB Version: mongod version: 3.6.12 (MMAPv1) (heroku plugin)
- Is this hosted on cloud.trudesk.io: No (heroku)

**Comment by polonel** [comment]
If the user logs into the web app one time and goes to the Profile section, from there they can generate an API key.
