### ISSUE TITLE
Tickets created using API not visible to ticket owner

### ISSUE THREAD

**Issue by ArpanKIIT2017** [polonel/trudesk#292]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
Created a ticket using v2 api, giving an owner id. The assigned user and admins can see the correct requester. But the owner can see his ticket from trudesk login

**What did you expect to happen**:
The owner user should see the tickets raised through API as well.

**How to reproduce it (as minimally and precisely as possible)**:
Create a ticket using the v2 API giving an owner field. The owner user will not see his ticket in the dashboard.

**Anything else we need to know?**:
**Environment**:
- Trudesk Version: IN TRUDESK CLOUD
- OS (e.g. from /etc/os-release): IN TRUDESK CLOUD
- Node.JS Version: IN TRUDESK CLOUD
- MongoDB Version: IN TRUDESK CLOUD
- Is this hosted on cloud.trudesk.io: YES

**Comment by trudesk** [comment]
Issue has been transferred to cloud repo.
