### ISSUE TITLE
Not able to Create Ticket

### ISSUE THREAD

**Issue by Hasbanos** [polonel/trudesk#294]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:

Unable to fetch mails.
12/31 15:36:44 [22637] - warn: [trudesk:events:sendSubscriberEmail] - Error: 139716338517888:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

12/31 15:36:47 [22637] - debug: MailCheck: Nothing to Fetch.
12/31 15:38:47 [22637] - debug: MailCheck: Nothing to Fetch.
12/31 15:40:47 [22637] - debug: Processed 1 Mail > Ticket
12/31 15:42:39 [22637] - debug: Authenticated socket s7oRY_2kUP7iNkRGAAAP -  ****@***.com
12/31 15:42:47 [22637] - debug: MailCheck: Nothing to Fetch.

**What did you expect to happen**:
Any idea how to solve this?

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Trudesk Version:
- OS (e.g. from /etc/os-release):
- Node.JS Version:
- MongoDB Version:
- Is this hosted on cloud.trudesk.io:

**Comment by polonel** [comment]
Can you provide more information? 
What version of Trudesk?
Who is the mail provider?

**Comment by Hasbanos** [comment]
Trudesk version 1.1.0 .
Mail Provider : Gmail.

And also Trudesk Restart automatically while creating Ticket.

Backend Error.
12/31 14:34:44 [22297] - ^[[34mdebug^[[39m: MailCheck: Nothing to Fetch.
12/31 14:36:44 [22297] - ^[[34mdebug^[[39m: MailCheck: Nothing to Fetch.
TypeError: email.render(...).then(...).catch(...).finally is not a function
    at /opt/trudesk/src/emitter/events.js:174:35
    at /opt/trudesk/node_modules/mongoose/lib/model.js:4659:16
    at /opt/trudesk/node_modules/mongoose/lib/query.js:4090:12
    at process.nextTick (/opt/trudesk/node_modules/mongoose/lib/query.js:2682:28)
    at process._tickCallback (internal/process/next_tick.js:176:11)
12/31 14:38:41 [22637] - ^[[32minfo^[[39m:

**Comment by Hasbanos** [comment]
OS : CentOS Linux 7
Node.JS Version: v9.11.2
MongoDB Version: v4.2.2
Is this hosted on cloud.trudesk.io: No (Hosted in over own server)

**Comment by polonel** [comment]
Can you try to disable the Mailer (`Settings > Mailer`), restart the server and try again? I believe it may be an issue with different versions of the `email-templates` module. My local dev machine has `4.0.3`. You can find the version of that module via opening `node_modules/email-templates/package.json` version property. This is just a hunch as I will dive deeper into the issue tomorrow.

![image](https://user-images.githubusercontent.com/626303/71639878-88f3bb80-2c4d-11ea-846b-768512738890.png)

**Comment by Hasbanos** [comment]
Still same .
Getting same issue while creating Ticket after disable the Mailer and Restarted.
TypeError: email.render(...).then(...).catch(...).finally is not a function
    at /opt/trudesk/src/emitter/events.js:174:35
    at /opt/trudesk/node_modules/mongoose/lib/model.js:4659:16
    at /opt/trudesk/node_modules/mongoose/lib/query.js:4090:12
    at process.nextTick (/opt/trudesk/node_modules/mongoose/lib/query.js:2682:28)
    at process._tickCallback (internal/process/next_tick.js:176:11)

Module Version.
"version": "4.0.3"

**Comment by polonel** [comment]
And this was installed using the ubuntu script?

**Comment by Hasbanos** [comment]
Thank You Chris Brame.
Now messages are Received successfully(from mail to ticket).
but have a warning ;
1/2 15:18:10 [21296] - warn: [trudesk:events:ticket:created] - Error: 140347564676992:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

And  not send mail notification while creating a ticket.
Error log;
1/2 16:52:10 [21296] - debug: No users to push too | UserSize: 0
1/2 16:52:10 [21296] - warn: [trudesk:events:ticket:created] - Error: 140347564676992:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

1/2 16:52:10 [21296] - debug: SentMail


1/2 16:53:02 [21296] - warn: [trudesk:events:sendSubscriberEmail] - Error: 140347564676992:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:827:

1/2 16:53:02 [21296] - debug: SentMail

**Comment by Hasbanos** [comment]
> And this was installed using the ubuntu script?
> Also one more thing to check, `node --version`?

I'm using CentOS  7 not ubuntu.So not ubuntu script.
download trudesk from below location.
git clone https://www.github.com/polonel/trudesk

then do the below steps.
$ npm install -g yarn
$ yarn
$ yarn run build
$ node runner

node  --version : v9.11.2

**Comment by polonel** [comment]
Have you tried to disable SSLv3?

**Comment by Hasbanos** [comment]
Fixed.Now Working perfectly.
Thank you for your great support.
