### ISSUE TITLE
Color Scheme unchanging

### ISSUE THREAD

**Issue by cyberfarer** [polonel/trudesk#296]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ x] BUG 
- [ ] FEATURE

**What happened**:
When I select a Built-in Color Scheme or set a color for, as an example, Header background, and select save, the colors do not change.

**What did you expect to happen**:
The colors to change as per the selection.

**How to reproduce it (as minimally and precisely as possible)**:
Simply change the buil-in color scheme from the drop down or enter a color code (#FFF) in any of the options.

**Anything else we need to know?**:
Nope.

**Environment**: 
- Trudesk Version: 1.0.14
- OS (e.g. from /etc/os-release): Ubuntu 18.04.02 LTS
- Node.JS Version: 10.18.0
- MongoDB Version: 3.6.16
- Is this hosted on cloud.trudesk.io: No

**Comment by polonel** [comment]
Please update to the latest version. `(v1.1.1)`
