### ISSUE TITLE
Is it possible to Integrate Trudesk into existing system?

### ISSUE THREAD

**Issue by hungbang** [polonel/trudesk#297]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ ] BUG 
- [x ] FEATURE

**What happened**:
I have an already system, then I want to integrate Trudesk into our system. is it possible to I can do it? 
**What did you expect to happen**:
Something like: 
1. Deploying Trudesk on the dedicated server. 
2. Using Trudesk APIs to communicate between Trudesk server and our system(such as imports our user to Trudesk service, then uses the API login to login into Trudesk server. ...)
3. Reuse the Trudesk View in our system, moving all of the UI source code of the Trudesk to our Frontend code. For example, we have a menu item called Service Desk when the user clicks this menu item, the Trudesk view will be displayed to the user. 

The steps above just an idea that I think. But I am not sure it's possible or not. 
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: latest
- OS (e.g. from /etc/os-release): Linux server
- Node.JS Version: latest
- MongoDB Version: latest
- Is this hosted on cloud.trudesk.io:

**Comment by polonel** [comment]
I can't answer this question because I know nothing of your current setup and integration. Trudesk front-end is nothing more than a react app. 

This is an open-source project, in which you are free to modify the source code to fit the needs you are trying to meet.
