### ISSUE TITLE
LDAP

### ISSUE THREAD

**Issue by cyberfarer** [polonel/trudesk#300]
Neither a bug nor a feature, but requesting clarification.

LDAP is timing out for me. The Bind DN should be in what format?

cn=username,dc=sub,dc=domain,dc=com
"CN=username,dc=sub,dc=domain,dc=com"
(CN=username,dc=sub,dc=domain,dc=com)

Is it the same for Search Base?

So far nothing is working for me so any help is appreciated.

Thank you.

**Comment by ybizeul** [comment]
I can't even see where LDAP configuration here, can you help ?

**Comment by polonel** [comment]
It's under Accounts -> Create dropdown -> import

**Comment by cyberfarer** [comment]
Hi. Following up on this. The problem I'm having appears to be that my ldap is samba4. 

So if I use this command: 
`/etc/trudesk# ./node_modules/ldapjs/bin/ldapjs-search -d2 -u ldap://10.10.255.108 -D "user@sub.domain.com" -b "cn=Users,dc=sub,dc=domain,dc=com" -w xxxxxx "(objectClass=*)"
`
It works. But I can't use that bind dn in the trudesk setup.

**Comment by polonel** [comment]
I will look into this. I have only tested with Windows LDAP.

**Comment by cyberfarer** [comment]
Sorry, I spoke too soon. It does work with "user@sub.domain.com" but it also works with "cn=user,dc=sub,dc=domain,dc=com" also. The issue seems to be with the wizard. I can watch it authenticate but then communications just seem to end.

**Comment by cyberfarer** [comment]
Update: Using tcpdump, I can see the ldap server is responding and sending back data but for some reason the bind isn't recognized.
