### ISSUE TITLE
Email replies as ticket thread.

### ISSUE THREAD

**Issue by shad9323** [polonel/trudesk#301]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ ] BUG 
- [x] FEATURE

**What happened**:
When replying to email notifications of tickets, it is being created as a new ticket.
**What did you expect to happen**:
The reply emails should be added as a thread to the ticket.
**How to reproduce it (as minimally and precisely as possible)**:
Get an email notification and reply to it as an email.

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: 1.1.0 .
- OS (e.g. from /etc/os-release): CentOS Linux 7
- Node.JS Version: v9.11.2
- MongoDB Version: v4.2.2
- Is this hosted on cloud.trudesk.io: No

**Comment by polonel** [comment]
This is a feature of Trudesk Cloud. (https://cloud.trudesk.io)
