### ISSUE TITLE
Login with LDAP credentials (LIVE, no user import)

### ISSUE THREAD

**Issue by cotanmarius** [polonel/trudesk#302]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [] BUG 
- [X] FEATURE

**What happened**:
It would be great to have to the option to use the active directory login credentials directly in trudesk, without importing the users.

**What did you expect to happen**:
Allow active directory users to login to trudesk with their LDAP credentials, without the need to create/import the users from the active directory into trudesk DB

**How to reproduce it (as minimally and precisely as possible)**:
- Trudesk is conncted to the LDAP Server.
- An active directory user acces the trudesk panel and logs in using his active directory credentials

**Anything else we need to know?**:

**Environment**:
Trudesk Version: 1.1.2
OS (e.g. from /etc/os-release): 18.04.2
Node.JS Version: v10.18.0
MongoDB Version: v3.6.13
Is this hosted on cloud.trudesk.io: No

**Comment by polonel** [comment]
Users have to get imported. It is planned in the cloud version to have an LDAP sync module that can update the users every X minutes to add/modify/remove users that are pulled from LDAP.

**Comment by cotanmarius** [comment]
One more quesion:

when importing users from LDAP, can we use the same password as for LDAP login?
