### ISSUE TITLE
Cannot get email and notifications to work

### ISSUE THREAD

**Issue by greygoosey** [polonel/trudesk#304]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [X] BUG 
- [ ] FEATURE

**What happened**:
No emails are being sent for notifications. When a user tries to use forgot password a 502 Bad Gateway is occurring with Apache and a 404 Error when using Nginx. Everything else appears to be working.

Perhaps I missed a key step?

**What did you expect to happen**:
I expected emails to be sent for ticket updates and password reset.

**How to reproduce it (as minimally and precisely as possible)**:
I followed the Docker install instructions and then for Nginx I used the example config.

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: Trudesk v1.0.17
- OS (e.g. from /etc/os-release): Ubuntu 18.04
- Node.JS Version:
- MongoDB Version:
- Is this hosted on cloud.trudesk.io: No

**Comment by polonel** [comment]
Can you upgrade to the latest version? `v1.1.2`

Also, did you configure the mailer inside trudesk settings?

**Comment by cotanmarius** [comment]
@greygoosey 
I had a problem with creting tickets from email and my problem get solved by installing trudesk v1.1.2 (fresh install).

And of course, how @polonel  mentioned above, you have to configure mail in trudesk (outgoing and incoming server, you need this info from the hosting provider or your own server config).

If you use a firewall, check if it is not blocking the ports for sending/receiving email

**Comment by greygoosey** [comment]
@polonel Yes i configured mailer settings. The exact settings used work in other apps.

Will try the upgrade now.

**Comment by greygoosey** [comment]
@polonel @cotanmarius same results on v1.1.2 fresh install. However, now I can see a 404 for the favicon as well as example.domain.com/forgotpass

**Comment by polonel** [comment]
@greygoosey depending on any changes you may have made it may require a rebuild. Please run
```
yarn build
```

**Comment by greygoosey** [comment]
@polonel sorry, quite new to docker. But would restarting the container do the same thing?

**Comment by cotanmarius** [comment]
@greygoosey 

From my experience with testing Trudesk, it is much easyer to use Ubuntu 18.03.3 with docker. You have all the necessary install steps on th documentation page.

For me worked with docker
