### ISSUE TITLE
Cannot delete user

### ISSUE THREAD

**Issue by cotanmarius** [polonel/trudesk#305]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [X] BUG 
- [] FEATURE

**What happened**:
It is not possible to delete an user becease of existing tickets.

**What did you expect to happen**:
The user should be removed from the DB but is only marked as locked

**How to reproduce it (as minimally and precisely as possible)**:
The user has 2 open tickets which are not assigned to an agent. I have deleted this 2 tickets, the tickets have been deleted succefully and than tried to delete the user but the system complains that the user has open tickets altought the tickets were deleted before.

**Anything else we need to know?**:

**Environment**:
Trudesk Version: 1.1.2
OS (e.g. from /etc/os-release): 18.04.2 (docker)
Node.JS Version: v10.18.0
MongoDB Version: v3.6.13
Is this hosted on cloud.trudesk.io: No

**Comment by cotanmarius** [comment]
Any update?

**Comment by polonel** [comment]
I'll add the option to permanently delete the ticket as it is implemented in the cloud version. Just hasn't made it over to the OSS version yet.

**Comment by cotanmarius** [comment]
@polonel  That's great, thank you!

**Comment by polonel** [comment]
Part of `v1.1.3` you can permanently delete tickets now in `Settings->Backup/Restore->Deleted Tickets`
