### ISSUE TITLE
Wrong Password for the users imported from AD/LDAP

### ISSUE THREAD

**Issue by cotanmarius** [polonel/trudesk#306]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [X] BUG 
- [] FEATURE

**What happened**:
I have imported users from the Active Directory, but i am not able to login with this users on trudesk: wrong username or password

**What did you expect to happen**:
Login to trudesk with the imported users using the same user and password as used to login into AD/LDAP.

It should be possible to import the username and the password from the active directoy

**How to reproduce it (as minimally and precisely as possible)**:
I have imported all the users (about 70) from active directory.
I have tried to login into trudesk using my AD username and password but it is not possible because username/password is wrong.

I have also tried to use the email address or my account name but i got the same result.

**Anything else we need to know?**:

**Environment**:
Trudesk Version: 1.1.2
OS (e.g. from /etc/os-release): 18.04.2 (docker)
Node.JS Version: v10.18.0
MongoDB Version: v3.6.13
Is this hosted on cloud.trudesk.io: No

**Comment by cotanmarius** [comment]
Any update?

**Comment by polonel** [comment]
I know this isn't the best implementation of LDAP import as it doesn't pull the password in. I also don't have it documented but it creates a trudesk user with the default password of `Password1!` when importing.

**Comment by cotanmarius** [comment]
Would it be possible maybe to try importing the password together with the username?

**Comment by polonel** [comment]
If the passwords are stored encrypted in LDAP/AD it wouldn't be possible to import password as trudesk uses its own SALT hash for passwords which would not match LDAP passwords. 

One of the features that haven't been implemented yet (which may be coming soon depending on Cloud updates), is the ability to authenticate directly to LDAP/AD. The users/accounts would them be managed through AD.

**Comment by cotanmarius** [comment]
Ok, i understand.
And this is planned only for the cloud or is there any chance to have this on the open source version too?
