### ISSUE TITLE
Mobile App user name length restricted to minimum 5 characters

### ISSUE THREAD

**Issue by cotanmarius** [polonel/trudesk#307]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [X] BUG 
- [] FEATURE

**What happened**:
Cannot login into the mobile app when the user name is shorter than 5 characters

**What did you expect to happen**:
Login into trudesk app using a 3 charactes long user name

**How to reproduce it (as minimally and precisely as possible)**:
We use 3 charactes user names in the active directory, imported the users into trudesk but we are not able to login into trudesk app because the user name is too short.

In the website, it is possible to login using 3 chars length user name

**Anything else we need to know?**:

**Environment**:
Trudesk Version: 1.1.2
OS (e.g. from /etc/os-release): 18.04.2 (docker)
Node.JS Version: v10.18.0
MongoDB Version: v3.6.13
Is this hosted on cloud.trudesk.io: No

**Comment by polonel** [comment]
iOS or Android?

**Comment by cotanmarius** [comment]
Hi,

the same problem with both IOS and Android

**Comment by cotanmarius** [comment]
Any update?

**Comment by polonel** [comment]
Apple is rejecting the app. Due to changes with iOS 13 and the app was built with ionic 1. I'm working to get it fixed and approved by apple. No ETA as of now.

**Comment by cotanmarius** [comment]
Hmm, that's a bad news :(
