### ISSUE TITLE
Incorrecct Time

### ISSUE THREAD

**Issue by Hasbanos** [polonel/trudesk#308]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
Showing incorrect time.In Messages , Conversations and  Ticket (update time).

**What did you expect to happen**:
![WhatsApp Image 2020-01-24 at 5 43 05 PM](https://user-images.githubusercontent.com/59249287/73068684-d3292f00-3ed1-11ea-819c-69b11e622739.jpeg)
File Attached.Its show two time.One is Correct and another one is incorrect.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Trudesk Version:  1.1.0 
- OS (e.g. from /etc/os-release):  CentOS Linux 7 (Core)
- Node.JS Version: v9.11.2
- MongoDB Version:  4.2.2
- Is this hosted on cloud.trudesk.io: No

**Comment by bschultz-vae** [comment]
I have the same issue - I believe it is the same thing reported in the forums here:
https://forum.trudesk.io/t/re-correct-time-display-issue/566/1

**Comment by Hasbanos** [comment]
Hii @bschultz-vae   @polonel 
Yes.
It's change after every refresh.
Every time it's not practical. How to Fix it.

**Comment by shad9323** [comment]
Hi Chris,

I am facing a similar issue as well. The time and date of ticket shown in the main screen, is different from what is shown in the ticket details screen.

**Comment by polonel** [comment]
What UTC offset?

**Comment by bschultz-vae** [comment]
The UTC time on my install is +10

![image](https://user-images.githubusercontent.com/56668493/73717350-45690180-4765-11ea-9a44-c5a94a2a2022.png)

**Comment by polonel** [comment]
Ok. It's falling back to the default of -5. I'll work on getting it corrected.

**Comment by Hasbanos** [comment]
UTC +05:30 is in my Install.

**Comment by bschultz-vae** [comment]
Thanks Chris!!

**Comment by Hasbanos** [comment]
Thank you Chris!

**Comment by superbrudd** [comment]
Hi - I just updated to 1.1.3 and the issue is still occurring...

![image](https://user-images.githubusercontent.com/3052813/75415783-524dcf00-5978-11ea-96b3-0055dd30618e.png)

**Comment by akshay1007** [comment]
I am still facing this issue any work around ??

**Comment by akshay1007** [comment]
@polonel 
Hi am using  1.1.3 docker version of trudesk and facing date time issue .
 1. Date time is showing wrong in all the places I am in UTC +5:30
Please find the attached screen shot 
![image](https://user-images.githubusercontent.com/42769008/84989165-e4185c80-b160-11ea-88c6-0335e54ef9b1.png)
![image](https://user-images.githubusercontent.com/42769008/84989248-027e5800-b161-11ea-9384-f49b247f7fd0.png)

2. For Ticket history it is not showing time updated , in Older version we used to see the updated time 
![image](https://user-images.githubusercontent.com/42769008/84989468-58eb9680-b161-11ea-9636-1855f9b5af6b.png)

![image](https://user-images.githubusercontent.com/42769008/84989616-93553380-b161-11ea-87d2-1e83e442a664.png)

{
  "name": "trudesk",
  "version": "1.1.3",
  "private": true,
  "engines": {
    "node": ">=9.10.0"
  },

Please help us 

Regards,
akshay
