### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by shivkadoor** [polonel/trudesk#309]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x ] BUG 
- [ ] FEATURE

**What happened**:
I cloned the git (latest version) and followed the instructions for mac installation.
Had issues with node-sass during build. Installed it manually and rebuild and started. Manually created a database in mongodb before starting application
**What did you expect to happen**:
connect to data base and start the program
**How to reproduce it (as minimally and precisely as possible)**:
$ git clone https://www.github.com/polonel/trudesk
$ cd trudesk
$ npm install -g yarn
$ yarn
$yarn add node-sass
use compass to create a mongodb database - newtrudesk
$ yarn run build
$ node runner

**Anything else we need to know?**:

**Environment**:
local/standalone
- Trudesk Version:
1.1.2
- OS (e.g. from /etc/os-release):
Mac OS Catalina 10.15.2
- Node.JS Version:
v12.14.1
- MongoDB Version:
v4.2.1

- Is this hosted on cloud.trudesk.io:
No.

**Comment by polonel** [comment]
Can you provide log messages of what happens? what errors are logged when starting trudesk with `yarn start`?

**Comment by shivkadoor** [comment]
/Users/shivaprasadkadoor/github/sparcem/src>yarn start
yarn run v1.21.1
$ node ./app
2/5 13:40:14 [3592] - info: ===>>> SPAR CEM <<<===
2/5 13:40:14 [3592] - info: App version: 1.0.15
2/5 13:40:14 [3592] - info: Running in: development
2/5 13:40:14 [3592] - info: Server Time: Wed Feb 05 2020 13:40:14 GMT+0530 (India Standard Time)
2/5 13:40:14 [3592] - error: Oh no, something went wrong with DB! - Authentication failed.
2/5 13:40:14 [3592] - error: FETAL: Authentication failed.
2/5 13:40:14 [3592] - warn: Retrying to connect to MongoDB in 10secs...
2/5 13:40:24 [3592] - error: Oh no, something went wrong with DB! - Authentication failed.
2/5 13:40:24 [3592] - error: Oh no, something went wrong with DB! - Authentication failed.
2/5 13:40:24 [3592] - error: FETAL: Authentication failed.
2/5 13:40:24 [3592] - warn: Retrying to connect to MongoDB in 10secs...
2/5 13:40:34 [3592] - error: Oh no, something went wrong with DB! - Authentication failed.
2/5 13:40:34 [3592] - error: Oh no, something went wrong with DB! - Authentication failed.
2/5 13:40:34 [3592] - error: FETAL: Authentication failed.
2/5 13:40:34 [3592] - warn: Retrying to connect to MongoDB in 10secs...
Hi, this is the yarn start results

**Comment by polonel** [comment]
This error shows that your authentication to Mongodb is not setup correctly.

You are also on an older version and should upgrade to the latest. `v1.1.3`
