### ISSUE TITLE
Couldn't delete ticket types

### ISSUE THREAD

**Issue by venkateshlb** [polonel/trudesk#310]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ X] BUG 
- [ ] FEATURE

**What happened**:
Couldn't delete the ticket types
**What did you expect to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Trudesk Version:
- OS (e.g. from /etc/os-release):
- Node.JS Version:
- MongoDB Version:
- Is this hosted on cloud.trudesk.io:

**Comment by polonel** [comment]
Closing as not enough information is listed. I'm able to delete ticket types with my version. Please fill out the entire bug report.
