### ISSUE TITLE
 Tagging field disable in form

### ISSUE THREAD

**Issue by yrsdi** [polonel/trudesk#312]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ ] BUG 
- [ ] FEATURE

**What happened**:  Tagging field disable in form

![Screenshot_2020-02-04_17-34-53](https://user-images.githubusercontent.com/865556/73737305-f62acd00-4774-11ea-97fc-854e0cc17daa.png)

**What did you expect to happen**: it's should be enable

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Trudesk Version:
- OS (e.g. from /etc/os-release):
- Node.JS Version:
- MongoDB Version:
- Is this hosted on cloud.trudesk.io:

**Comment by polonel** [comment]
I believe it is enabled but you probably do not have any tags created yet. So it's displaying nothing when you click on it. `Settings->Tickets->Tags`

**Comment by yrsdi** [comment]
ok thank you. case closed
