### ISSUE TITLE
Deleted users are not being re-created when sending email to support email address

### ISSUE THREAD

**Issue by cotanmarius** [polonel/trudesk#313]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [X] BUG 
- [] FEATURE

**What happened**:
Deleted users are not being created automatically when they send an email to the trudesk email account

**What did you expect to happen**:
The user should be created automatically and and email with the username and password should be sent to the source email address

**How to reproduce it (as minimally and precisely as possible)**:

- As you recommended, i have installed the v1.1.3.
- I have sent an email to the trudesk email address.
- Ticket and a new account was created
- I have deteled the ticket from the ticket menu and from the backup and restore menu
- I have deleted the user from the customers menu: succesfull
- After a few minutes, i've sent another email from the same email address
- New ticket was created but no user.
- After some time i found the user in the customers menu but i haven't received any email with the username and password
- Tried to login with the email address and the password from the first email: not working. Invalid username and password

**Anything else we need to know?**:

**Environment**:
Trudesk Version: 1.1.3
OS (e.g. from /etc/os-release): 18.04.2 (docker)
Node.JS Version: v10.18.0
MongoDB Version: v3.6.13
Is this hosted on cloud.trudesk.io: No

**Comment by polonel** [comment]
Can you try the same with a server restart after the user is deleted? I believe it may think the user still exist due to the cache, and thus not create a user that _already_ exists.
