### ISSUE TITLE
[bug] Pacer never finishes

### ISSUE THREAD

**Issue by Wqrld** [polonel/trudesk#314]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x ] BUG 
- [ ] FEATURE

**What happened**:
The pacer never finishes loading and slowly goes to 99.999999 probably due to socket.io

**What did you expect to happen**:
Pacer should ignore socket.io

**How to reproduce it (as minimally and precisely as possible)**:
Do a fresh install and enter the admin area

**Anything else we need to know?**:
Fresh install

**Environment**:
newest trudesk as of 16-02-2020

**Comment by Wqrld** [comment]
please reopen

**Comment by polonel** [comment]
I'm not experiencing this issue. Can you confirm that your browser is connecting to WebSocket as it should?

**Comment by Wqrld** [comment]
my browser connects to the websocket normally, i had some other issues during install like elasticsearch so it might have to do with that.
