### ISSUE TITLE
How to deploy trudesk in azure?

### ISSUE THREAD

**Issue by eliyasbaby** [polonel/trudesk#315]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ ] BUG 
- [x ] FEATURE

**What happened**:
i am trying to deploy the trudesk application in azure.i could pull both docker images and created as azure container instance but i am not able to connect trudesk and mongo db. 
**What did you expect to happen**:
both mongo db and trudesk should deploy and mongo db storage need to mound  
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Trudesk Version:
- OS (e.g. from /etc/os-release):
- Node.JS Version:
- MongoDB Version:
- Is this hosted on cloud.trudesk.io:

**Comment by Wqrld** [comment]
are you using docker in the vms or are the images hosted directly in like a kubernetes?

**Comment by eliyasbaby** [comment]
@Wqrld thanks for your comments.i want deploy in the second way, means using existing docker images from docker hub and using kubernetes.
