### ISSUE TITLE
Time is wrong in UI and reports (Timezone ignored)

### ISSUE THREAD

**Issue by ArpanKIIT2017** [polonel/trudesk#319]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
Wrong time displayed everywhere in UI and in reports. Timezone is incorrect. After refresh time is proper but again wrong when navigated in client side. Similar to #308 but problem is in all places.

**What did you expect to happen**:
Expect to see proper time consistently everywhere and in reports (very vital).

**How to reproduce it (as minimally and precisely as possible)**:
Just use your software (even in the docker demo) with some other timezone. I have tested with Asia/Kolkata. Just see a ticket creation time and refresh the same page. Then again check time after refresh.

**Anything else we need to know?**:
Issue is vital (at least in reports) and urgent.

Dockerfile (for reference)
FROM golang:1.10.0-alpine AS gcsfuse
RUN apk add --no-cache git
ENV GOPATH /go
RUN go get -u github.com/googlecloudplatform/gcsfuse

FROM node:10.10-alpine AS builder

RUN mkdir -p /usr/src/trudesk
WORKDIR /usr/src/trudesk

COPY . /usr/src/trudesk

RUN apk add --no-cache --update bash make gcc g++ python
RUN npm install -g yarn
RUN yarn install --production=true
RUN npm rebuild bcrypt node-sass --build-from-source
RUN cp -R node_modules prod_node_modules
RUN yarn install --production=false
RUN yarn build
RUN rm -rf node_modules && mv prod_node_modules node_modules

FROM node:10.10-alpine
WORKDIR /usr/src/trudesk
RUN apk add --no-cache ca-certificates bash mongodb-tools fuse && rm -rf /tmp/*
COPY --from=builder /usr/src/trudesk .
COPY --from=gcsfuse /go/bin/gcsfuse /usr/local/bin

EXPOSE 8118

CMD [ "/bin/bash", "/usr/src/trudesk/startup.sh" ]

**Environment**:
- Trudesk Version: 1.0.17, 1.1.2 (in docker demo)
- OS (e.g. from /etc/os-release): Ubuntu 18.04
- Node.JS Version: 
- MongoDB Version:
- Is this hosted on cloud.trudesk.io: No

**Comment by superbrudd** [comment]
I agree - same problem still occurring (https://github.com/polonel/trudesk/issues/308 did not fix the issue)

**Comment by superbrudd** [comment]
This is still an issue.

**Comment by polonel** [comment]
I am aware. I haven't finished implementing a fix that is universal.

**Comment by superbrudd** [comment]
just bumping this one to reopen.

**Comment by ArpanKIIT2017** [comment]
This still needs a fix
