### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by pedroricardo** [polonel/trudesk#320]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ ] BUG 
- [ ] FEATURE

**What happened**:

**What did you expect to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Trudesk Version:
- OS (e.g. from /etc/os-release):
- Node.JS Version:
- MongoDB Version:
- Is this hosted on cloud.trudesk.io:

![image](https://user-images.githubusercontent.com/36576303/75776076-0614dd00-5d32-11ea-96a3-48771618b9ed.png)

**Comment by polonel** [comment]
https

**Comment by pedroricardo** [comment]
![image](https://user-images.githubusercontent.com/36576303/76151078-91be9e80-608f-11ea-87bd-0ced3ea1b186.png)

**Comment by pedroricardo** [comment]
![image](https://user-images.githubusercontent.com/36576303/76151082-9b480680-608f-11ea-85de-78c67e619957.png)

**Comment by polonel** [comment]
I moved it for you until I can get it resolved. https://files.trudesk.io/install/install_ubuntu.sh
