### ISSUE TITLE
Readme.md Docs link is broken

### ISSUE THREAD

**Issue by mlsad3** [polonel/trudesk#323]
The Readme.md points to:
http://www.trudesk.io/docs

When it should point to:
https://docs.trudesk.io/

Going to the first link is broken, and redirects you to trudesk.io (no documentation available at that location)

**Comment by mlsad3** [comment]
heartbeat :)

**Comment by polonel** [comment]
Thanks. I'm working to get a lot of the documentation updated. I'll update the readme in the next push.
