### ISSUE TITLE
Trudesk Self-Hosted Docs are out-of-date

### ISSUE THREAD

**Issue by shahyar** [polonel/trudesk#326]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
The documentation on https://docs.trudesk.io/v1/guide/ point to an incorrect location for the Ubuntu install script.

**Comment by teutat3s** [comment]
I also noticed that the docker install docs need updating.
They point to docker images with trudesk version `1.0`
```
docker pull polonel/trudesk:1.0
```
instead of 
```
docker pull polonel/trudesk:1.1
```

**Comment by memtech3** [comment]
Where is the repository for documentation?

**Comment by memtech3** [comment]
@polonel

**Comment by Teascade** [comment]
How is Trudesk then hosted? I've made an issue at #391 about my problems, but if you have any knowledge, it would be appreciated

**Comment by memtech3** [comment]
It's supposed to be self hostable and have a paid cloud hosted and supported version but the docs are MIA so self hosted looks kind of dead

**Comment by alecs** [comment]
I am running it in docker with this config:
`version: '3.7'
services:
  trudesk:
# polonel/trudesk:1.1.3
    image: polonel/trudesk:next
    restart: always
#    ports:
#      - 8118:8118
    environment:
      NODE_ENV: production
      PORT: 8118
      TRUDESK_DOCKER: "true"
      TD_MONGODB_SERVER: mongo
      TD_MONGODB_DATABASE: trudesk
      TD_MONGODB_USERNAME: trudesk
      TD_MONGODB_PASSWORD: somepassword
    networks:
      - traefik
      - reverse_proxy
      - trudesk_internal
    deploy:
      replicas: 1
      restart_policy:
        delay: 10s
        max_attempts: 1
        window: 60s
      labels:
        - "traefik.enable=true"
        - "traefik.port=8118"
        - "traefik.docker.network=reverse_proxy"
        - "traefik.passHostHeader=true"
        - "traefik.backend=trudesk"
        - "traefik.protocol=http"
        - "traefik.frontend.rule=Host:trudesk.domain.com"
        - "traefik.cachet.frontend.entryPoints=http,https"
        - "traefik.cachet.frontend.headers.SSLRedirect=false"
    volumes:
      - /shared/truedesk/uploads:/usr/src/trudesk/public/uploads
      - /shared/truedesk/plugins:/usr/src/trudesk/plugins
      - /shared/truedesk/backups:/usr/src/trudesk/backups
  mongo:
# this image tries a chown which will fail when dockremap is in place.
#    image: mongo:3.6
# this is based on alpine with mongo 3.6.5
#    image: mvertes/alpine-mongo:3.6.5-0
# or mongo 4
#    image: clutteredcode/mongo-alpine
# local image 3.6.7
    image: my_mongodb:latest
    restart: always
    hostname: mongo
    environment:
      - MONGO_USERNAME=masterofpuppets
      - MONGO_PASSWORD=metallica91
#    ports:
#      - "127.0.0.1:27017:27017"
    networks:
       - trudesk_internal
    volumes:
# if auto adding user fails, just create a mongod.conf with security disabled
#      - /shared/mongod.conf:/etc/mongod.conf
      - /shared/truedesk/db:/data/db
      - /shared/truedesk/configdb:/data/configdb

networks:
  traefik:
    external: true
    attachable: true
  reverse_proxy:
    external: true
    attachable: true
  trudesk_internal:`

**Comment by Teascade** [comment]
@alecs I have a few questions if you don't mind. 

- How do you get trudesk to sign in to the mongodb? The only way I could make it work without having no authentication at all, was by having an environment variable `TD_MONGODB_URI: "mongodb://trudesk:trudesk_pass@trudesk_db:27017/trudeskdb?authSource=admin"`. The `?authSource=admin` was the key for me to getting it work.
- Secondly and more importantly, with the same version of trudesk image I still have the problem that the front page doesn't work correctly and it says `Error - Invalid Graph Data`. Do you have any idea about that problem?

**Comment by alecs** [comment]
1) with the env vars, but it won`t work from the start; I needed to do the granting manually. Grant permissions on admin and full rights to the created mongo database.
2) no, did not hit that.

Initially I booted up everything and my mongo docker created the root account, but if you are not using the same container you can:
```
> db.createUser({user: 'rootus',
... pwd: 'tiktok'
... roles: [{role: 'root', db: 'admin'}]
... })
Successfully added user: {
        "user" : "rootus",
        "roles" : [
                {
                        "role" : "root",
                        "db" : "admin"
                }
        ]
}

> use admin
switched to db admin
> db.createUser(
... {
... user: "trudesk",
... pwd: "bumbumbum",
... roles: [ { role: "readWrite", db: "trudesk" } ]
... }
... )
Successfully added user: {"user" : "trudesk","roles" : [{"role" : "readWrite","db" : "trudesk"}]
```

**Comment by polonel** [comment]
New documentation is located at https://docs.trudesk.io/v1.2
