### ISSUE TITLE
How to assign a ticket to administrator ?

### ISSUE THREAD

**Issue by krazylearner** [polonel/trudesk#33]
Hi,
we have a user who has created ticket .Now we want to assign that ticket to administrator ?

can you please tell me how to do that via api and admin dashboard ?
i checked api docs and dashboard but cant seem to find it ?

Thanks

**Comment by polonel** [comment]
All Administrators can be set as assignee. I apologize that the majority of the documentation is incomplete. Including the built-in tour.
Setting the assignee through the API can be done with the [UpdateTicket](http://app.trudesk.io/apidocs/#api-Ticket-updateTicket) call.
[See Source](https://github.com/polonel/trudesk/blob/0.1.10-rc2/src/controllers/api/v1/tickets.js#L525)

I have also attached a simple GIF of setting the assignee through the UI. I know this is not very obvious and it is in the process of being revamped in an upcoming UI update for better clarity.

![aqylsuvxpe](https://user-images.githubusercontent.com/626303/32058186-5ecb6ef0-ba37-11e7-8686-b8e98e16d92e.gif)
