### ISSUE TITLE
Error 500 /api/v1/groups/all

### ISSUE THREAD

**Issue by naraphox** [polonel/trudesk#330]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ X ] BUG 
- [ ] FEATURE

**What happened**:
I was trying to get a list of my groups so I can get a group ID so to be able to setup API create user and I am getting Error 500 when calling /api/v1/groups/all using my proper token, without token or incorrect token it states proper status fail stating invalid key like it should, but when I put valid key I just get error 500.

**What did you expect to happen**:
This should respond with a list of groups.

**How to reproduce it (as minimally and precisely as possible)**:
Just call /api/v1/groups/all with a proper accesstoken, I been trying it all day to no result.

**Anything else we need to know?**:
I call it like this from CLI and get same result as my script does:
curl -H "accesstoken: mytokenishere" -l https://mysubdomain.trudesk.io/api/v1/groups/all

**Environment**:
- Trudesk Version: Cloud
- OS (e.g. from /etc/os-release): N/A
- Node.JS Version: N/A
- MongoDB Version: N/A
- Is this hosted on cloud.trudesk.io: yes

**Comment by polonel** [comment]
The cloud version of trudesk does not fully support APIv1. The entire API is being rewritten to support GQL.
