### ISSUE TITLE
Auto Subscribe Tickets send by Email

### ISSUE THREAD

**Issue by cotanmarius** [polonel/trudesk#335]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ X] BUG 
- [ ] FEATURE

**What happened**:
If someone send and email, a new ticket will be created. If i comment to that email, the user does not receive any email notification, because, by default, he is not subscribed to this ticket.

**What did you expect to happen**:
The user should receive updates (comments, notes) on tickets by default.
IDEA: There should be also an option in settings to activate/deactivate this function.

**How to reproduce it (as minimally and precisely as possible)**:
Send an email to the trudesk email address, post a comment from the trudesk panel and check if you receive a notification on your email.

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: 1.1.3
- OS (e.g. from /etc/os-release): Ubuntu 20.04 LTS x64
- Node.JS Version: 
- MongoDB Version:
- Is this hosted on cloud.trudesk.io: self hosted on docker container using the official instal

**Comment by cotanmarius** [comment]
Any uodate?

**Comment by polonel** [comment]
I'll look into a way to implement this on this version. This is something has already been overhauled on the cloud version to work as you intend.

**Comment by cotanmarius** [comment]
@polonel 

Thank you!

This means it will be included on the next release?

**Comment by bilson** [comment]
+1

**Comment by cotanmarius** [comment]
Any updates?
