### ISSUE TITLE
Stuck on "debug: Windows platform detected. Downloading MongoDB Tools" after node runner

### ISSUE THREAD

**Issue by uzair1124** [polonel/trudesk#336]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG

- [x ] BUG 
- [ ] FEATURE

**What happened**:
 I have installed it successfully ,but when i run node runner it stuck on "debug: Windows platform detected. Downloading MongoDB Tools" 

and trudesk app is not running and not showing any screen.

**What did you expect to happen**:

login screen to display or run the trudesk application.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Trudesk Version:  v1.1.3
- OS (e.g. from /etc/os-release):  Windows 10 
- Node.JS Version:  v12.16.1
- MongoDB Version:  v4.2.6

- Is this hosted on cloud.trudesk.io: No

**Comment by uzair1124** [comment]
![node_runner_error](https://user-images.githubusercontent.com/38960130/83263743-7f5c8880-a1d8-11ea-8531-1ceb140ab09c.PNG)

**Comment by uzair1124** [comment]
ok thankss @polonel
 let me do this

**Comment by uzair1124** [comment]
Hello @polonel thanks for your support.
1. I have downgraded Mongo version to 3.6.18.
2. Run command node runner , now app runs it shows login screen , but it didn't logged in to show dasktop.
3. It show error , "No User Found" . kindly guide me 
![NoUserFound](https://user-images.githubusercontent.com/38960130/83327539-10de0000-a296-11ea-8171-ed84b58b34b6.PNG)

**Comment by polonel** [comment]
Delete the `config.json` file and restart the server. It should show the install screen instead of the login screen. From there you can create your admin user account again and I would create a new database because 3.6 and 4.0 are vastly different.

**Comment by uzair1124** [comment]
thanks again @polonel

**Comment by uzair1124** [comment]
Hello @polonel  i have deleted `config.json` file and restart the server , now it is showing install screen instead of login , then i have created new  user by clicking `Add New Database` , now this following error is shown. 
Can you please further guide me ? 
Thanks again for your precious time and support.
![mongo-ERROR](https://user-images.githubusercontent.com/38960130/83351867-19e7d380-a361-11ea-89b9-eea8af56738a.PNG)

**Comment by polonel** [comment]
You need to delete the trudesk database if you select **New Database**. It can't create keys that already exist in the database.

**Comment by uzair1124** [comment]
Thanks @polonel . 
It works now( succesfully logged in and dashboard is shown) .
Thanks again for your support
