### ISSUE TITLE
Invoking create User API via Curl from within Node.js Failure.

### ISSUE THREAD

**Issue by monoto** [polonel/trudesk#339]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
Adding a new user by calling create user api

**What did you expect to happen**:
a new user account

**How to reproduce it (as minimally and precisely as possible)**:

From within Node.js, calling curl using command line interface:
```
               var postData = querystring.stringify({
			'aUsername' : self.accountUid,
			'aPass' : self.accountPassword,
			'aPassConfirm' : self.accountPassword,
			'aFullname' : self.accountFullname,
			'aEmail' : self.accountEmail,
			'aRole' : 'user',
			'aTitle' : 'Customer'
		});
		
		postData += '&aGrps[0]=5ed52318487a2e7ccef5e825';
		
		var cmd = 	"curl -H \"Content-Type: applications/json\" " +
					"-H \"accessToken: " +
					self.accessToken +
					"\" -X POST localhost:8118/api/v1/users/create --data \"" +
					postData + "\"";
					
		commandline.get(cmd, function(err, data, stderr) {

			console.log(data);
			
			if (!err)
			{
				if (callback) callback({status: 'success'});
			}
			else
			{
				if (callback) callback({status: 'failure'});
			}
		});
```

curl command response:
{"success":false,"error":"Invalid Post Data"}

**Anything else we need to know?**:
No sure about how to pass array to post data.  
Querystring.stringify incorrectly handles array of a single element and returns 
aGrps=[group id] which led to the same Invalid Post Data.  
That was why I have to append it afterward.
Should I pass a literal string as: `"[\"<group id>\"] `  ?
That didn't work either.

**Environment**:
- Trudesk Version: 1.1.3
- OS (e.g. from /etc/os-release): Amazon cloud AM2
- Node.JS Version: 12.0.4
- MongoDB Version: 4.0.18
- Is this hosted on cloud.trudesk.io: no

**Comment by monoto** [comment]
```
var postData = querystring.stringify({
			'aUsername' : self.accountUid,
			'aPass' : self.accountPassword,
			'aPassConfirm' : self.accountPassword,
			'aFullname' : self.accountFullname,
			'aEmail' : self.accountEmail,
			'aRole' : 'user',
			'aTitle' : 'Customer',
			'aGrps' : "[\"5ed52318487a2e7ccef5e825\"]"
		});

		var cmd = 	"curl -H \"Content-Type: application/x-www-form-urlencoded\" " +
					"-H \"accessToken: " +
					self.accessToken +
					"\" -X POST localhost:8118/api/v1/users/create --data \"" +
					postData + "\"";
					
		commandline.get(cmd, function(err, data, stderr) {

			console.log(data);
			
			if (!err)
			{
				if (callback) callback({status: 'success'});
			}
			else
			{
				if (callback) callback({status: 'failure'});
			}
		});
```

using Content-Type: application/x-www-form-urlencoded, now I am getting

{"success":false,"error":"Invalid Group Array"}

**Comment by polonel** [comment]
Have you tried not wrapping the `aGrps` in `"`

**Comment by monoto** [comment]
Yes. Querystring.stringify incorrectly handles array of a single element and returns
aGrps=5ed52318487a2e7ccef5e825 which is no longer an array and led to  Invalid Post Data.

**Comment by monoto** [comment]
My latest Try:

var cmd = 	"curl -H \"Content-Type: application/x-www-form-urlencoded\" " +
			"-H \"accessToken: " +
			self.accessToken +
			"\" -X POST http://localhost:8118/api/v1/users/create";
					
		cmd += " --data-urlencode \"aUsername=" + self.accountUid + "\"";
		cmd += " --data-urlencode \"aPass=" + self.accountPassword + "\"";
		cmd += " --data-urlencode \"aPassConfirm=" + self.accountPassword + "\"";
		cmd += " --data-urlencode \"aFullname=" + self.accountFullname + "\"";
		cmd += " --data-urlencode \"aEmail=" + self.accountEmail + "\"";
		cmd += " --data-urlencode \"aRole=user\"";
		cmd += " --data-urlencode \"aTitle=Customer\"";
		cmd += " --data-urlencode \"aGrps=['5ed52318487a2e7ccef5e825']\"";

Error:  {"success":false,"error":"Invalid Group Array"}

**Comment by polonel** [comment]
https://github.com/polonel/trudesk/blob/master/src/controllers/api/v1/users.js#L120-L236

**Comment by monoto** [comment]
Got it to work this way:

    var cmd = 	"curl -H \"Content-Type: application/x-www-form-urlencoded\" " +
					"-H \"accessToken: " +
					self.accessToken +
					"\" -X POST http://localhost:8118/api/v1/users/create";
					
		cmd += " --data-urlencode \"aUsername=" + self.accountUid + "\"";
		cmd += " --data-urlencode \"aPass=" + self.accountPassword + "\"";
		cmd += " --data-urlencode \"aPassConfirm=" + self.accountPassword + "\"";
		cmd += " --data-urlencode \"aFullname=" + self.accountFullname + "\"";
		cmd += " --data-urlencode \"aEmail=" + self.accountEmail + "\"";
		cmd += " --data-urlencode \"aRole=User\"";
		cmd += " --data-urlencode \"aTitle=Customer\"";
		cmd += " --data-urlencode \"aGrps=5ed52318487a2e7ccef5e825\"";
		cmd += " --data-urlencode \"aGrps=\"";

Needs multiple aGrps with the second one empty to make it an array.  
I dumped the result from apiUsers.create function as below and it passed the array check.

{"success":true,"result":{"aUsername":"Panama.City","aPass":"mypasswd","aPassConfirm":"mypasswd","aFullname":"Panama City","aEmail":"panama.city@mydomain.com","aRole":"User","aTitle":"Customer","aGrps":["5ed52318487a2e7ccef5e825",""]}}

**Comment by monoto** [comment]
Now I am getting this error for the empty group id. 

`{"success":false,"error":{"message":"Cast to ObjectId failed for value \"\" at path \"_id\" for model \"groups\"","name":"CastError","stringValue":"\"\"","kind":"ObjectId","value":"","path":"_id"}}`

However, the user account did get created successfully and added to the right group.
