### ISSUE TITLE
URGENT: Wrong Ticket-ID assigned to a new ticket

### ISSUE THREAD

**Issue by cotanmarius** [polonel/trudesk#341]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [X] BUG 
- [ ] FEATURE

**What happened**:
Trudesk assigned a wrong ticket number, which is already in use by a closed ticket.
When i click on the ticket link which has been sent by email, it goes to the closed thicket from the last week.

The new ticket does not exist at all. It seems that the system is complety compromised.

**What did you expect to happen**:
A new ticket with an unique ticket id should be created

**How to reproduce it (as minimally and precisely as possible)**:
Ticket 1031 was created by sending and email tot the trudesk dedicated email address. The ticket 1031 has been closed last week and this week another user sendt a ticket by email. This ticket got the same number as the ticket from the last week: 1031 (sent from different users and different email addresses to the same trudesk email address)

**Anything else we need to know?**:

Ticker 1031 has been closed last 
![grafik](https://user-images.githubusercontent.com/52410664/84753093-daef8a00-afbe-11ea-8481-e6f866eee648.png)

A new ticket with the same number has been created:
![grafik](https://user-images.githubusercontent.com/52410664/84753112-e2169800-afbe-11ea-8cdc-e174aab974bd.png)

**Environment**:
- Trudesk Version: 1.1.3 
- OS (e.g. from /etc/os-release): Ubuntu 20.04 LTS / Docker
- Node.JS Version:
- MongoDB Version:
- Is this hosted on cloud.trudesk.io: self hosted on docker container using the official instal

**Comment by cotanmarius** [comment]
Hi!

Any update?

**Comment by polonel** [comment]
whats the ticket counter show in the mongodb counter collection?

**Comment by cotanmarius** [comment]
@polonel Thank you for the reply.

How/where can i check this?

**Comment by polonel** [comment]
In the Database. Counter Collection.
