### ISSUE TITLE
Reopening #319 Timezone ignored

### ISSUE THREAD

**Issue by ArpanKIIT2017** [polonel/trudesk#343]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
Wrong time displayed everywhere in UI and in reports. Timezone is incorrect. After refresh time is proper but again wrong when navigated in client-side. Similar to #308 but the problem is in all places.

**What did you expect to happen**:
Expect to see proper time consistently everywhere and in reports (very vital).

**How to reproduce it (as minimally and precisely as possible)**:
Just use your software (even in the docker demo) with some other timezone. I have tested with Asia/Kolkata. Just see a ticket creation time and refresh the same page. Then again check time after refresh.

**Anything else we need to know?**:
Issue is vital (at least in reports) and urgent.

Dockerfile (for reference)
FROM golang:1.10.0-alpine AS gcsfuse
RUN apk add --no-cache git
ENV GOPATH /go
RUN go get -u github.com/googlecloudplatform/gcsfuse

FROM node:10.10-alpine AS builder

RUN mkdir -p /usr/src/trudesk
WORKDIR /usr/src/trudesk

COPY . /usr/src/trudesk

RUN apk add --no-cache --update bash make gcc g++ python
RUN npm install -g yarn
RUN yarn install --production=true
RUN npm rebuild bcrypt node-sass --build-from-source
RUN cp -R node_modules prod_node_modules
RUN yarn install --production=false
RUN yarn build
RUN rm -rf node_modules && mv prod_node_modules node_modules

FROM node:10.10-alpine
WORKDIR /usr/src/trudesk
RUN apk add --no-cache ca-certificates bash mongodb-tools fuse && rm -rf /tmp/*
COPY --from=builder /usr/src/trudesk .
COPY --from=gcsfuse /go/bin/gcsfuse /usr/local/bin

EXPOSE 8118

CMD [ "/bin/bash", "/usr/src/trudesk/startup.sh" ]

**Environment**:
- Trudesk Version: 1.0.17, 1.1.2 (in docker demo)
- OS (e.g. from /etc/os-release): Ubuntu 18.04
- Node.JS Version: 
- MongoDB Version:
- Is this hosted on cloud.trudesk.io: No

**Comment by polonel** [comment]
Can you confirm that this is the case after you change the timezone and restart the server? Clear your Localstorage in your browser or use a private browsing session after the restart of the server. The timezone is stored in local storage after your initial login. 

All the client-side time/date display is pulled from that local storage variable. This is to prevent having to query the DB for the timezone after every page change/refresh. 

In this current version of the self-hosted version there is no such thing as "client" timezone. The timezone set on the server in settings is the timezone all time/date would be displayed as. Unless it has an incorrect timezone still stored in local storage.

**Comment by ArpanKIIT2017** [comment]
I'll check and revert for sure! Thanks for your cooperation

Regards,
Arpan Mukherjee
