### ISSUE TITLE
Migrate from MongoDB to Firebase/Firestore

### ISSUE THREAD

**Issue by coolrb** [polonel/trudesk#346]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ ] BUG 
- [x] FEATURE

**What happened**: We are trying to customize trudesk. We would like to change from Mongodb to firestore. 
**What did you expect to happen**: Please suggest us what are the changes we can make to have it seamlessly migrated to firestore
**How to reproduce it (as minimally and precisely as possible)**: We tried to play around src/database/index.js, but it need much more work than changing the db connection.

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: Latest
- OS (e.g. from /etc/os-release): MacOS
- Node.JS Version: 10.19.0
- MongoDB Version: 
- Is this hosted on cloud.trudesk.io: No

**Comment by polonel** [comment]
What node js module are you using to connect to Firestone?

Trudesk is built with Mongoose so much of its database schema is around mongoose specific API.

**Comment by coolrb** [comment]
We are using https://github.com/angular/angularfire . Firestore is also a nosql database like mongodb. Hence I dont think there would be much issues. Just wanted to know which packages I should look into for changes?

**Comment by polonel** [comment]
Yea, actually it would require a new interface into the database models. If you look at https://github.com/polonel/trudesk/blob/master/src/models/ticket.js you can see that even though MongoDB is schemaless mongoose is used to create a schema to easily validate and manage the data model within the trudesk codebase.

**Comment by coolrb** [comment]
Thanks for information. Firestore also provides similar kind of schema support with class( a typescript standard) e.g. a location model `export class Location {
  address = "";
  latitude = 0.0;
  longitude = 0.0;
  postalCode = "";
  countryName = "";
  state = "";
  city = "";
  region = "";
}`
Is there any service/factory method that manages all models? Here are couple of my questions:
- Login/Authentication: post login, what are the objects get created and which function/file does that? Could you please share with me any document to help me understand the flow
- Are the models managed from a single factory or each module has its own implementation?

**Comment by polonel** [comment]
Unfortunately, the cloud version was rewritten to with a model factory, and this open-source version lags behind that implementation. My goal is to bring it over but haven't had the time yet. To answer your point in this codebase all models have their own implementation.

As far as login; when the API is called. It generates a `jsonwebtoken` and a session in the DB. Once this `jsonwebtoken` expires it checks for an active session before automatically refreshing the token and sending the updated tokens back to the client.

https://github.com/polonel/trudesk/blob/master/src/controllers/api/v2/common.js

The goal is to port a lot of the cloud backend logic to this version for manageability. Thus why not much work has been put into this version as of late. Should be _soon_

**Comment by coolrb** [comment]
Thats quite lots of work. I thought to start with, first add a new db connection for Firestore, then use it for login and token management. And later work on other models. 
BTW, if you can with me any cloud code, I will be able to expedite my work on firestore integration.
