### ISSUE TITLE
This error has come please resolve it.

### ISSUE THREAD

**Issue by ashu145107** [polonel/trudesk#360]
**this a BUG REPORT **:

- [ {"success":false,"error":{"driver":true,"name":"MongoError","index":0,"code":11000,"errmsg":"E11000 duplicate key error collection: trudesk.settings index: name_1 dup key: { : \"gen:version\" }"}}] BUG 

**What happened**: When i install trudesk with new database then this bug has occured?

**What did you expect to happen**: to resolve this bug that's it.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Trudesk Version:
- OS (e.g. from /etc/os-release):
- Node.JS Version:
- MongoDB Version:
- Is this hosted on cloud.trudesk.io:

**Comment by polonel** [comment]
I am not able to reproduce with a fresh database install.
