### ISSUE TITLE
After adding a new user through API if you visit the users page it freezes and takes down site

### ISSUE THREAD

**Issue by BronacusAmmon** [polonel/trudesk#363]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ X] BUG 
- [ ] FEATURE

**What happened**:
In the docker installation I sent a post request to the create user api returning with a success but when I navigate to the users panel after it disconnects and will not reconnect any more.

**What did you expect to happen**:
I thought I'd be able to see the new users in the panel

**How to reproduce it (as minimally and precisely as possible)**:
On a fresh docker install create a group then when using the api if you successfully create a user for that group then visit the user panel on the webpage it will freeze and not allow any connections any longer.

**Anything else we need to know?**:
Can successfully create and check user from hosted website directly, but not from API

**Environment**:
- Trudesk Version: 1.0
- OS (e.g. from /etc/os-release): Ubuntu 20
- Node.JS Version: v10.10.0
- MongoDB Version: 3.6
- Is this hosted on cloud.trudesk.io: No

**Comment by polonel** [comment]
Can you provide the server logs?

**Comment by polonel** [comment]
What version of the API are you using? v2 is what the entire UI uses so if your able to create an account in the UI there shouldn't be a reason why you couldn't using the API directly. https://github.com/polonel/trudesk/blob/master/src/controllers/api/v2/accounts.js
