### ISSUE TITLE
Guest Chat Feature

### ISSUE THREAD

**Issue by sunder6218** [polonel/trudesk#365]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ ] BUG 
- [x] FEATURE

**What happened**:
Im trying to integrate trudesk in my website for its chat and ticketing engine and i have noticed that in order to have a chat with an agent, the customer has to login, my use case is, a customer visiting my site should not have the need to login to chat to an agent however for raising a ticket, the customer should login.

**What did you expect to happen**:
There should be a feature to chat with agent without the need to login to trudesk with an anonymous login and only need to login when a ticket needs to be raised

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**: Docker
- Trudesk Version: 1.0.17
- OS (e.g. from /etc/os-release): ubuntu 16.04
- Node.JS Version:6.17.1
- MongoDB Version:3.6
- Is this hosted on cloud.trudesk.io: no

**Comment by polonel** [comment]
This is a feature of the Trudesk Cloud platform. As seen on https://trudesk.io

This is not a feature of the self-hosted open-source version.

**Comment by LuigiElleBalotta** [comment]
@polonel will it be a feature of the self-hosted version? Or is there an API to write our own chat?
