### ISSUE TITLE
Mailer crashes server

### ISSUE THREAD

**Issue by dushyantbangal** [polonel/trudesk#371]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
Mailer with SMTP is not working. The test connection is successful, but no mail is sent.
If I enable the "Enable New Email Templates" and trigger forgot password, the server crashes.

I copied the following from `pm2 monit`
```
desk > TypeError: Cannot read property 'compile' of undefined        
     trudesk >     at /etc/trudesk/src/controllers/main.js:341:53            
     trudesk >     at /etc/trudesk/node_modules/async/dist/async.js:473:16   
     trudesk >     at next (/etc/trudesk/node_modules/async/dist/async.js:5329:29)                                        
     trudesk >     at /etc/trudesk/node_modules/async/dist/async.js:969:16   
     trudesk >     at /etc/trudesk/src/controllers/main.js:319:41            
     trudesk >     at nextTask (/etc/trudesk/node_modules/async/dist/async.js:5324:14)                                    
     trudesk >     at next (/etc/trudesk/node_modules/async/dist/async.js:5331:9)                                         
     trudesk >     at /etc/trudesk/node_modules/async/dist/async.js:969:16   
     trudesk >     at /etc/trudesk/src/controllers/main.js:315:22            
     trudesk >     at /etc/trudesk/node_modules/mongoose/lib/model.js:4659:16
     trudesk >     at /etc/trudesk/node_modules/mongoose/lib/query.js:4090:12
     trudesk >     at process.nextTick (/etc/trudesk/node_modules/mongoose/lib/query.js:2682:28)                          
     trudesk >     at process._tickCallback (internal/process/next_tick.js:61:11)
```

**What did you expect to happen**:
Mail notification of created ticket or reset password

**How to reproduce it (as minimally and precisely as possible)**:
1. Install using the Ubuntu script.
2. Configure SMTP.in Mailer
3. Create Ticket (You will not get any email)
4. Turn "Enable New Email Templates"
5. Trigger reset password (`pm2 monit` will show the server crashed and restarted)

**Anything else we need to know?**:
I have deployed on EC2 with all outgoing open and 8118 incoming open.
I am using office365 SMTP settings with port 587.

**Environment**:
- Trudesk Version: v1.1.2
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Node.JS Version: v10.22.1
- MongoDB Version: v4.2 (Atlas)
- Is this hosted on cloud.trudesk.io: No

**Comment by dushyantbangal** [comment]
**Update:**
The SMTP not working part was an issue from my end. However, the following part is still happening:
>If I enable the "Enable New Email Templates" and trigger forgot password, the server crashes.

**Comment by obutov** [comment]
Seeing the same behavior with SMTP configuration.

**Comment by cyberfarer** [comment]
I am seeing the same issue when the templates are enabled.

**Comment by cyberfarer** [comment]
I noticed something that maybe nothing, but on the line in question (/etc/trudesk/src/controllers/main.js:341:53) the text global.HandleBars.compile has an uppercase B. Previously, at line 308, the 'B' is lowercase: Handlebars. 

Does this matter? If I experiment, do I need to run yarn build or restart?

**Comment by cyberfarer** [comment]
So, editing the line /etc/trudesk/src/controllers/main.js:341:53 and changing global.HandleBars.compile to global.Handlebars.compile and then restarting with `pm2 restart trudesk` solves the problem.
