### ISSUE TITLE
elasticsearch does not work

### ISSUE THREAD

**Issue by koanvi** [polonel/trudesk#377]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
elasticsearch does not work
**What did you expect to happen**:
elasticsearch does work
**How to reproduce it (as minimally and precisely as possible)**:
lately i upgraded

**Anything else we need to know?**:
[index_not_found_exception] no such index [trudesk], with { resource.type="index_or_alias" & resource.id="trudesk" & index_uuid="_na_" & index="trudesk" }

**Environment**:
- Trudesk Version:1.1.3
- OS (e.g. from /etc/os-release):Ubuntu 20.04.1 LTS \n \l
- Node.JS Version:v10.19.0
- MongoDB Version:4.4.1
- Is this hosted on cloud.trudesk.io:no
- elasticsearch version:7.9.3

**Comment by RodoggA** [comment]
Downgrade your elastic search to 6.8 and let me know how that goes.
