### ISSUE TITLE
[Mailer] Send mail when ticket's status change

### ISSUE THREAD

**Issue by Fiuma** [polonel/trudesk#379]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ ] BUG 
- [x] FEATURE

**What happened**:
Mailer doesn't send mail when ticket closed. 

**What did you expect to happen**:
That Trudesk send a mail to User, Agents and Admins when status of ticket changes.

**How to reproduce it (as minimally and precisely as possible)**:
Only just change a ticket's status.

**Environment**:
- Trudesk Version: 1.1.3;
- OS (e.g. from /etc/os-release): CentOS Linux 8 (Core);
- Node.JS Version: v10.21.0;
- MongoDB Version: 4.4;
- Is this hosted on cloud.trudesk.io: NO.

**Comment by cyberfarer** [comment]
Is the user subscribed to the ticket?

**Comment by Fiuma** [comment]
Hello Cyberfarer, 

yes, I just tryed.  
Users that open a ticket receive only notify of Comments.

This behaviour is normal? 

Thanks for your reply.

**Comment by cyberfarer** [comment]
This project doesn't appear to be maintained so we are moving to zammad.org.
