### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by yogumanivannan** [polonel/trudesk#39]
I got below issue during installation

Crap! Something funky happened.
Alright. This entire install script is in beta. Didn't I mention that? Anyway, there are a couple of options below to try and resolve the issue. There are some common pit falls and workarounds in the docs that may help. Submitting the issue will help identify any bugs in the script and will help others as well.

{"success":false,"error":{"name":"MongoError","message":"Authentication failed.","ok":0,"errmsg":"Authentication failed.","code":18,"codeName":"AuthenticationFailed"}}
![turedesk_installation](https://user-images.githubusercontent.com/31209650/34091101-8357344c-e3e1-11e7-81c8-5de471dcc5ae.png)

OS : Windows 8 64 BIT

**Comment by polonel** [comment]
It failed to authenticate to the mongodb instance. You either entered the wrong credentials or changed them on the server before finishing the install. 

Be sure to check out the documentation and consider using the prebuilt VM image.

**Comment by yogumanivannan** [comment]
Can you please tell me where to find the documentation ?. I tried this link but it is not working http://www.trudesk.io/v1/guide

**Comment by polonel** [comment]
Yes. That is the correct address. Please try again, It should be fixed.

**Comment by polonel** [comment]
I'm going to close this issue. Feel free to let me know if you still experience issues.

**Comment by yogumanivannan** [comment]
I do have any authentication enabled. I use the default Mongo DB settings. FYI I can able to connect with my Robo 3T (Mongo db client)

**Comment by yogumanivannan** [comment]
Should i change anything in config.json ?
