### ISSUE TITLE
Experiencing slowness in web page loading

### ISSUE THREAD

**Issue by SunilRangpadiya** [polonel/trudesk#392]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**: We have hosted our trudesk setup in EC2 instance in AWS. We are in the initial stage of usage so our database size is also very small. But still, we are facing the slow loading of the web pages on every refresh. some of the APIs (settings, groups and roles) get called on every refresh and it takes around 2.5 to 3 sec and those are also called in sequence and not parallel. hence the page loading time goes to 30 40 sec on every refresh and if the internet is slow then it takes even more than a minute to load.
**What did you expect to happen**:
I checked the same on hosted demo setup i.e. (http://docker.trudesk.io/) and it's pretty fast. all the APIs take less than 300ms. So is there any configuration that we are missing which causes this latency or any optimization patch which we need to do at our end?

**How to reproduce it (as minimally and precisely as possible)**:
Host the setup in the local system or in any cloud system

**Anything else we need to know?**:
we are using the hosted the MongoDB 

**Environment**:
- Trudesk Version: 1.1.3
- OS (e.g. from /etc/os-release): Amazon Linux 2
- Node.JS Version: 9.11.0
- MongoDB Version: 4.2.11
- Is this hosted on cloud.trudesk.io: no (hosted in EC2 instance)

**Comment by shahyar** [comment]
The focus is the API v2 development which solves this issue. So, until that gets released, it's not going to be fixed.

**Comment by niteeshhegde** [comment]
@shahyar any estimated date for the next release?
