### ISSUE TITLE
TruDesk not starting after post installation wizard on Kubernetes

### ISSUE THREAD

**Issue by dimuit86** [polonel/trudesk#401]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x ] BUG 
- [ ] FEATURE

**What happened**:

I'm trying to setup Trudesk on a Kubernetes cluster. everything seems working fine. But, Trudesk not accessible after 1st reboot at the post-installation wizard. 

**What did you expect to happen**:

Trudesk makes it accessible even after a reboot. 

**How to reproduce it (as minimally and precisely as possible)**:

#### Not accessible after click restart.
![Screenshot_1](https://user-images.githubusercontent.com/79132146/112421745-a8489e00-8d55-11eb-99d0-c718ae8b2e8d.png)

#### Trudesk and Mongo on Kubernetes
![Screenshot_2](https://user-images.githubusercontent.com/79132146/112421747-aa126180-8d55-11eb-95dc-4cca89c73aaf.png)

#### Trudesk Logs when restarting
![Screenshot_3](https://user-images.githubusercontent.com/79132146/112421748-aa126180-8d55-11eb-8d16-af3fa32a98f5.png)

#### MongoDB logs
![Screenshot_4](https://user-images.githubusercontent.com/79132146/112421749-aaaaf800-8d55-11eb-884d-dbcafa588014.png)

**Anything else we need to know?**:

Is it possible to run Trudeks on Kubernetes. Does it have an existing bug that makes it unable to run on Kubernetes?

**Environment**:
- Trudesk Version:  1.1.3 Docker image
- OS (e.g. from /etc/os-release): Kubernetes
- Node.JS Version: 
- MongoDB Version: mongo:3.6
- Is this hosted on cloud.trudesk.io: No

**Comment by dimuit86** [comment]
> k

Hi @polonel , Do you have a workaround to fix this issue?

**Comment by dimuit86** [comment]
Does anyone knows is this project abundant? 🤔

**Comment by polonel** [comment]
Yes, I run multiple k8s installs. It requires the config.json to set as a Config Map or set the docker env var and supply the database connection as an ENV var (TRUDESK_DOCKER=true). Similar to https://docs.trudesk.io/v1/guide/installation.html#Docker-Install

The `TRUDESK_DOCKER=true` flag should be set after the admin user is created in the database through the initial install wizard. It forces the core to skip the install wizard and use the Mongo Env vars. Thus using the config map is the better approach as the mongo connection data is stored there.

Something like:
```yml
volumeMounts:
  - mountPath: /usr/src/trudesk/config.json
  name: trudesk-config-json
  readOnly: true
  subPath: config.json
```
