### ISSUE TITLE
Can not use POST methods like login or create user

### ISSUE THREAD

**Issue by MagMueller** [polonel/trudesk#417]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x ] BUG 
- [ ] FEATURE

**What happened**:
I want to use the API with node js. I can use all get methods, e.g. i can get an user or I can get a ticket via the uid. But I can not use POST methods, for example create a user or even login does not work.
If I want to create a group I get:
```
   data: {
      success: false,
      error: 'Error: groups validation failed: name: Path `name` is required.'
    }
```

If I want to login:
` data: 'Forbidden' `

If I want to create an user:
`data: { success: false, error: 'Invalid Post Data' }`
But my data is just:

```
const data = JSON.stringify({
    aUsername:    "name",
    aPass:        "password",
    aPassConfirm: "password",
    aFullname:    "fullafdname",
    aEmail:       "email@email.com",
    aRole:        "user",
    aTitle:       "EndUser",
    aGrps:        ""
}
```

**What did you expect to happen**:
I want to create an user or login in.

**How to reproduce it (as minimally and precisely as possible)**:
e.g. the login error:

```
const axios = require('axios');
const user_data = JSON.stringify({
   username: "admin",
   password: "admin"
});

url = "yourUrl/api/v1/"

function login(data){
    axios({
        method: 'POST',
        url: url + "login",
        "data": data, 
        headers:{'Content-Type': "applications/json"}
    }) 
    .then((res) => {
        console.log(res)
        return res.data
    })
    .catch((error) => {
        console.error(error)
        return error
    });
}
  
login(user_data)
```

**Anything else we need to know?**:
no

**Environment**:
- Trudesk Version: v1.0.12  or I just downloaded it last we (the stable version)
- OS (e.g. from /etc/os-release): macOS Catalina 10.15.4
- Node.JS Version: v14.17.0
- MongoDB Version: v4.2.0

**Comment by polonel** [comment]
Can you try the latest version. `1.0.12` is very outdated. Can you give it a try with `1.1.6`

**Comment by MagMueller** [comment]
Thank you, I wrote the wrong Trudesk Version, I just copy the one from the documents, because I thought that is the newest. Actually, I'm using 1.1.6. 

Do you need something else to help me?

**Comment by michael-ra** [comment]
Instead of

`headers:{'Content-Type': "applications/json"}`

just use

`headers:{'Content-Type': "application/json"}`.

And it will work like a charm :)
