### ISSUE TITLE
CSV "Add users" not working

### ISSUE THREAD

**Issue by crimsonclyde** [polonel/trudesk#418]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
CSV import not working.

This might be not a real bug, but if anyone has same issues maybe this could be a good place to find more info.
All in all thx to polonel the containers work great!

**What did you expect to happen**:
Use a csv file in format:
username,fullname,email,roleid,title while roleID is the one from mongo

To get the ID use (container: mongo_db)
mongo
show dbs
use trudesk
db.trudesk.find().pretty()

**How to reproduce it (as minimally and precisely as possible)**:
1. Create users.csv
2. Add and save content to it:
Jane,Jane Doe,xxx@mycorp.me,60xxxxx53857,MyCorp
John,John Doe,xy@mycorp.me,60xxxxxb53857,MyCorp
3. Try to import via CSV import 

**Anything else we need to know?**:
Browser console:
`Uncaught SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
    allcomplete https://help.mycorp.me:88/js/7.js:18
    complete https://help.mycorp.me:88/js/0.js:57
    onreadystatechange https://help.mycorp.me:88/js/0.js:57
    upload https://help.mycorp.me:88/js/0.js:57
    xhrupload https://help.mycorp.me:88/js/0.js:57
    init https://help.mycorp.me:88/js/0.js:57
    dispatch https://help.mycorp.me:88/js/0.js:25
    handle https://help.mycorp.me:88/js/0.js:25`

Server log
`TypeError: csv is not a function
    at accountsController.uploadCSV (/usr/src/trudesk/src/controllers/accounts.js:291:16)
    at Layer.handle [as handle_request] (/usr/src/trudesk/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/trudesk/node_modules/express/lib/router/route.js:137:13)
    at middleware.redirectToLogin (/usr/src/trudesk/src/middleware/middleware.js:77:10)
    at Layer.handle [as handle_request] (/usr/src/trudesk/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/trudesk/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/src/trudesk/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/src/trudesk/node_modules/express/lib/router/layer.js:95:5)
    at /usr/src/trudesk/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/usr/src/trudesk/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/trudesk/node_modules/express/lib/router/index.js:275:10)`

Tried with reverse proxy (nginx) and without (only http) same thing.
Tried with role "user" and "User" because someone else mentioned it. No luck.

Image upload is working and everything else, it seems, as well. Only CSV import, not.

This was the only resource I found so far.
https://forum.trudesk.io/t/how-to-import-user-from-csv/131

**Environment**:
- Trudesk Version: trudesk v1.1.6
- OS (e.g. from /etc/os-release): NAME="Ubuntu", VERSION="20.04.2 LTS (Focal Fossa)
- Node.JS Version: v12.22.1
- MongoDB Version: db version v3.6.23
- Is this hosted on cloud.trudesk.io: No

**Comment by polonel** [comment]
This is indeed a bug. I'll work on getting it fixed.

**Comment by crimsonclyde** [comment]
Let me know if you need additional information, I will be happy to support if I can!

**Comment by polonel** [comment]
CSV Format
``` csv
Username,Name,Email,RoleId,Title
test.user,Test User, test@test.com, 5c89591a681b48468c7e99a1,User Title

**Comment by crimsonclyde** [comment]
@polonel 
Will test and report tomorrow :) thx for that quick response on that.

**Comment by crimsonclyde** [comment]
Tested works.

Just a hint. I need to restart the trudesk!

@polonel : Thx for your help!
Rly appriciated and awesome work. Keep up your good spirit! Cheers!
