### ISSUE TITLE
Ubuntu Install Script not working anymore.

### ISSUE THREAD

**Issue by 0x4e44** [polonel/trudesk#419]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ X] BUG 
- [ X] FEATURE  = Feature not working anymore 

**What happened**: Install bash file seems to be not present anymore

**What did you expect to happen**: install 

**How to reproduce it (as minimally and precisely as possible)**: trying to run the command tu download the SH file = not working.

**Anything else we need to know?**:

**Environment**:
- Trudesk Version:
- OS (e.g. from /etc/os-release):
- Node.JS Version:
- MongoDB Version:
- Is this hosted on cloud.trudesk.io:

**Comment by polonel** [comment]
I need to move it to a different host. I'll get it moved later tonight and update the readme. Thanks for the report.

**Comment by 0x4e44** [comment]
Readme was in fact updated , but the file is not accessible. 

![image](https://user-images.githubusercontent.com/83678523/124926198-3aa24400-dfcb-11eb-9de5-3df8f439c55e.png)

**Comment by polonel** [comment]
This has been resolved.
