### ISSUE TITLE
New ticket window does not close automatically

### ISSUE THREAD

**Issue by penge1510** [polonel/trudesk#420]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [X] BUG 
- [ ] FEATURE

**What happened**:
Hi, 
It's a new fresh installation. When I try to add a new ticket the new ticket windows does not close automatically. The ticket is creating but the window still appear. If I click the _create_ button again the ticket is creating again and again and again, until I hit the _Cancel_. 

**What did you expect to happen**:
The ticket window to close automatically. 

**How to reproduce it (as minimally and precisely as possible)**:
Follow the install instructions from the official page of Trudesk.

**Anything else we need to know?**:
Any help would be appreciated. Thanks in advance!

**Environment**:
- Trudesk Version: 1.1.6
- OS (e.g. from /etc/os-release): Debian GNU/Linux 10 (buster)
- Node.JS Version: 16.4.1
- MongoDB Version: 4.2.15
- Is this hosted on cloud.trudesk.io: No

**Comment by nickbe** [comment]
Same problem here. 

I've created several tickets suddenly after clicking the "create" button multiple times 😆

**Comment by alsemany** [comment]
Hi, 
I just create a pull request 
https://github.com/polonel/trudesk/pull/423
, actually the api response is missing so the api will be pending untill get timeout

**Comment by polonel** [comment]
I just merged #423. I will push a version update later tonight. In the meantime you can check out #423 to add the response back I deleted by mistake.
