### ISSUE TITLE
accounts validation failed because of role

### ISSUE THREAD

**Issue by MagMueller** [polonel/trudesk#422]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x ] BUG 
- [ ] FEATURE

**What happened**:
I tried to create a new user.
But:

`{
    "success": false,
    "error": {
        "errors": {
            "role": {
                "stringValue": "\"user\"",
                "kind": "ObjectId",
                "value": "user",
                "path": "role",
                "reason": {}
            }
        },
        "_message": "accounts validation failed",
        "name": "ValidationError",
        "message": "accounts validation failed: role: Cast to ObjectId failed for value \"user\" at path \"role\""
    }
}`

**What did you expect to happen**:
Create a new user.

**How to reproduce it (as minimally and precisely as possible)**:
My body is:
`{
    "aUsername":    "name123",
    "aPass":        "password",
    "aPassConfirm": "password",
    "aFullname":    "fullafdname",
    "aEmail":       "info@naklar.xyz",
    "aRole":        "user",
    "aTitle":       "EndUser",
    "aGrps":        ["60f43d601e5bad11f007ff34"]
}
`
I use api/v1/users/create
My Headers are also fine.

**Anything else we need to know?**:
In node.js I just get:
data: { success: false, error: [Object] }
I tried to put the role in {} or in [] or "" or use Support or User, what can I do?

**Environment**:
-Trudesk Version: v1.1.6.
-OS (e.g. from /etc/os-release): macOS Catalina 10.15.4
-Node.JS Version: v14.17.0
-MongoDB Version: v4.2.0

**Comment by MagMueller** [comment]
And another thing: In the docs under https://docs.trudesk.io/v1/api/#Create there is a spelling error:
-H "Content-Type: applications/json" \ -> better use
-H "Content-Type: application/json" \
 it took me some time until  I realized it.

But it has nothing todo with the error above.

**Comment by polonel** [comment]
`aRole` is the ObjectID of the role.

**Comment by MagMueller** [comment]
so not "user", but a long ID like for aGrps?
How can I find this aRole ID?

**Comment by polonel** [comment]
Yes. You can return a full list of all the roles via sending a `GET` request to `/api/v1/roles` then use the `_id` of the role.

**Comment by MagMueller** [comment]
Thank you so much!
