### ISSUE TITLE
Chat window cannot be closed anymore

### ISSUE THREAD

**Issue by nickbe** [polonel/trudesk#424]
- [x] BUG 
- [ ] FEATURE

The chat window cannot be closed anymore.
The x - button does not react to mouse clicks.

- Trudesk Version: 1.1.7
- OS Ubuntu 18.04
- Node.JS Version: Docker Installation
- MongoDB Version: Docker Installation
- Hosted Version

**Comment by polonel** [comment]
Any errors logged in the Browser Console?

**Comment by nickbe** [comment]
The same moment I wanted to check the console - clicking the chat windows - it closed 🙄 .
Interestingly enough my chat window was open everywhere I logged in (from 3 different locations) and I couldn't close it.
Now it suddenly closed and I can't reprodice the thing. Anyway I'll immediately check the console when it occurs again.

**Comment by polonel** [comment]
Yea, as you describe it the bug could be that the server thinks the window is still open based on it being open on the other clients. It _should_ tell all clients to close the window when you close it but the others could report back it is open at the same time it is closed thus forcing it to stay open. If there is a bug that's where I would start testing.

I'll look into it but if you can reproduce it, reopen this issue.

**Comment by nickbe** [comment]
Thanks. I will do.

**Comment by nickbe** [comment]
Same situation again. And I just checked the console. But no error - nothing. It simply won't close.
How can I force it to assume that no others are open anymore?
