### ISSUE TITLE
On create of ticket, it generates error: TypeError: Cannot read property 'next' of null

### ISSUE THREAD

**Issue by coolrb** [polonel/trudesk#428]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
Tickets are not getting created. In the backend I am getting error
TypeError: Cannot read property 'next' of null
    at /home/user/trudesk/src/models/ticket.js:135:26
**What did you expect to happen**:
A ticket should get created
**How to reproduce it (as minimally and precisely as possible)**:
I have installed successfully using source code. The mongodb, we are using is:
MongoDB shell version v5.0.1
Build Info: {
    "version": "5.0.1",
    "gitVersion": "318fd9cabc59dc9651f3189b622af6e06ab6cd33",
    "openSSLVersion": "OpenSSL 1.1.1f  31 Mar 2020",
    "modules": [],
    "allocator": "tcmalloc",
    "environment": {
        "distmod": "ubuntu2004",
        "distarch": "x86_64",
        "target_arch": "x86_64"
    }
}
**Anything else we need to know?**:
On further analysis, I have found that the next uid from collection "counters" generates error. In the mongodb, there is no collection with name "counters"
**Environment**:
- Trudesk Version: latest stable
- OS (e.g. from /etc/os-release): Ubuntu 20.04
- Node.JS Version: v10.24.1
- MongoDB Version: "5.0.1",
- Is this hosted on cloud.trudesk.io: no

**Comment by polonel** [comment]
MongoDB 5 is not supported.
