### ISSUE TITLE
will not connect to mongodb server

### ISSUE THREAD

**Issue by zorgrian** [polonel/trudesk#430]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

## Note: this is related to trudesk-1.1.6, yet it also relates to ALL versions
The latest version did not work for the same reasons; I read that 1.1.6 does work, so I have also tried this, with no success!

## What happened:

I installed Trudesk using the following:

![image](https://user-images.githubusercontent.com/1559119/129017267-bd75a7d4-c088-4931-8e6b-24f13d4604bb.png)

However, this did not work and produced the same failure as all other versions of Trudesk (self-hosted)

Additionally, kindly note that **the one liner install for UBUNTU** no longer connects to anything useful. 

### Running the app.jss "node app.jss"

![image](https://user-images.githubusercontent.com/1559119/129008157-d81589f4-90ae-4bfa-9b57-586a59f79fbb.png)

To me, this looks like it is running properly, **but it does not connect to ElasticSearch**, **and more importantly, NO connection to  MongoDB from the browser set-up pages.**

### This is what it looks like
![image](https://user-images.githubusercontent.com/1559119/129009674-bcd57717-cbc0-4257-9c43-8d0247c2e03a.png)
Then, despite the friendly message saying it's painless…

![image](https://user-images.githubusercontent.com/1559119/129009855-c6d91d89-8b96-4cc3-8c33-92a7620d669d.png)

Then…

![image](https://user-images.githubusercontent.com/1559119/129011458-76a33b55-3b5c-45ca-a90a-6fd918b115c4.png)

### I can live without the ElasticSearch But then...
**We skip the elastic Search and proceed to try connecting to MongoDB**. (which, I assume, is asking for a username and password of my specification as, this seems logical, but I cannot find where this might be documented. **Is it documented?**

![probs](https://user-images.githubusercontent.com/1559119/129013765-d19fdb33-98da-4274-8c5b-bd723052651d.png)

 
## What did you expect to happen?

**I would expect a connection to be made to MongoDB, using the username and password, supplied from the browser.**

## How to reproduce it (as minimally and precisely as possible)

Please see the screenshots above.

**Anything else we need to know?**:

## Environment:
1. Trudesk Version: I have tested ALL versions and none of them connect to MongoDB in a way that I would expect. There is nothing to indicate that I need to create a database in MongoDB first, yet I have also tried this, which does not work either. I have also made sure that MongoDB is running “service start MongoDB”
2. OS Xubuntu 20.04
3. Node.JS Version: 

![image](https://user-images.githubusercontent.com/1559119/129015037-c2c80bc4-92bf-48a6-8f1e-d62372bfc067.png)

4. MongoDB Version:

![image](https://user-images.githubusercontent.com/1559119/129015625-adf627df-ca88-48b5-b534-4a3e18d3b93b.png)

5. Is this hosted on cloud.trudesk.io: NO!

# Please help
1. Is there anyone actively looking at these problems?
2. Is the source in active development?
3. Does the self-hosted version of Trudesk actually work?
4. Can anyone see what might be going wrong here, and if so, please make a constructive comment?

**Comment by zorgrian** [comment]
linux 20.04
v1.1.8

**Comment by polonel** [comment]
If the one-liner didn't work (I guess you're on a new version of Ubuntu), you will need to manually add the `trudesk` user to the `trudesk` database on your freshly installed MongoDB server. It will populate the database but the user has to exist inside MongoDB for it to have a way to connect.

Something like...
```
db = db.getSiblingDB('trudesk');
db.createUser({"user": "trudesk", "pwd": "#TruDesk1$", "roles": ["readWrite", "dbAdmin"]});
```
