### ISSUE TITLE
Installation script error - ubuntu 16.04 & 18.04

### ISSUE THREAD

**Issue by zilong13** [polonel/trudesk#440]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:

root@trudesk:~# curl -L -s http://www.trudesk.io/install/install_ubuntu.sh | sudo bash
bash: line 1: syntax error near unexpected token `newline'
bash: line 1: `<!DOCTYPE html>'

**What did you expect to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

How I can run this script correcly?

**Environment**:
- Trudesk Version:
- OS (e.g. from /etc/os-release):
- Node.JS Version:
- MongoDB Version:
- Is this hosted on cloud.trudesk.io:

**Comment by polonel** [comment]
The link in the docs is old. Please use the link/command listed on the README.md.

`curl -L -s https://files.trudesk.io/install/install_ubuntu.sh | sudo bash`

**Comment by zilong13** [comment]
Sorry, I am new. can you share where I can find README.MD. Thans.
