### ISSUE TITLE
The link in the docs is old. Please use the link/command listed on the README.md.

### ISSUE THREAD

**Issue by zilong13** [polonel/trudesk#442]
The link in the docs is old. Please use the link/command listed on the README.md.

`curl -L -s https://files.trudesk.io/install/install_ubuntu.sh | sudo bash`

_Originally posted by @polonel in https://github.com/polonel/trudesk/issues/440#issu
------------------------------------------------------------------------new error occurred
brian@helpdesk:~$ curl -L -s https://files.trudesk.io/install/install_ubuntu.sh | sudo bash
bash: line 2: $'\r':command not found
bash: line 9: $'\r':command not found
bash: line 11: $'\r':command not found
bash: line 16: $'\r':command not found
bash: line 17: $'\r':command not found
bash: line 17: syntax error near unexpected token '$'{\r''
'ash: line 17: 'function_Spinner(){

**Comment by polonel** [comment]
for some reason I haven't figured out GCP is redirecting the requests all of a sudden. Remove the `-L` and it should work.

`curl -s https://files.trudesk.io/install/install_ubuntu.sh | sudo bash`

**Comment by polonel** [comment]
I need to fix some packages for the script to work with trudesk version `1.1.8`

Working on that now.. Will report back soon.

**Comment by polonel** [comment]
Okay, It's working with a couple of caveats.

If you wish to install Elastic Search with the install script, afterward in the setup wizard, **Skip the Elastic Search Configuration**
Take the default setups for the MongoDB settings and select **New Database**
- Create your admin user, then restart.
- Once logged in go to Settings > Elastic Search and in the server configuration, you will likely see **false**. Change to **localhost** and click Apply. You'll get an error stating that Elastic Search is not enabled and to restart the server. 
- In the Ubuntu Shell execute `sudo pm2 restart trudesk`
- After restart, go back to Settings > Elastic Search and click **Rebuild** Under Rebuild index. 
- Everything should function normally now. 

This is a new issue, so I'm working on a resolution to the problem.

**Comment by polonel** [comment]
Fix for elasticsearch has been pushed to develop. Fix will be included in `v1.1.9` coming later this weekend.
