### ISSUE TITLE
Docker install error ("name":"ValidatorError","message":"Path `value` is required.")

### ISSUE THREAD

**Issue by thiago-prado-cavalcanti** [polonel/trudesk#446]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [X] BUG 
- [ ] FEATURE

**What happened**:
First try:
{"success":false,"error":{"errors":{"value":{"name":"ValidatorError","message":"Path `value` is required.","properties":{"message":"Path `value` is required.","type":"required","path":"value"},"kind":"required","path":"value"}},"_message":"settings validation failed","name":"ValidationError","message":"settings validation failed: value: Path `value` is required."}}

Second try:
{"success":false,"error":{"driver":true,"name":"MongoError","index":0,"code":11000,"keyPattern":{"name":1},"keyValue":{"name":"gen:version"}}}
**What did you expect to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Install MongoDB:
docker run --name mongodb -v /data/db:/data/db -v /data/configdb:/data/configdb -d mongo:latest

Install Trudesk:
docker run --name trudesk --link mongodb:mongodb -v /data/trudesk/uploads:/usr/src/trudesk/public/uploads -v /data/trudesk/plugins:/usr/src/trudesk/plugins -v /data/trudesk/backups:/usr/src/trudesk/backups -e NODE_ENV=production -e TRUDESK_DOCKER=true -e TD_MONGODB_SERVER=mongodb -e TD_MONGODB_DATABASE=trudesk -P -d polonel/trudesk

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: 1.1.10
- OS (e.g. from /etc/os-release): Amazon Linux / Docker
- Node.JS Version: v16.11.1
- MongoDB Version: latest
- Is this hosted on cloud.trudesk.io: No

**Comment by lost-station** [comment]
This error is related to the Elastic search check, i assume.
https://github.com/polonel/trudesk/blob/0d015632bc4472544d54fb4b78bf01e6e976a645/src/controllers/install.js#L140-L141

If you remove this comment, the installation continues:
https://github.com/polonel/trudesk/blob/0d015632bc4472544d54fb4b78bf01e6e976a645/src/controllers/install.js#L177

**Comment by JesusFregoso** [comment]
the second try is related to an already trudesk database installation.

enter into docker mongo bash delete the trudesk database and start over from fresh install.

`docker exec -it mongodb mongo`

then inside mongo run this commands.
list databases to verify trudesk database

`db.adminCommand( { listDatabases: 1 } )`

then use trudesk

`use trudesk;`

then drop the database

`db.dropDatabase();`

start over with trudesk
