### ISSUE TITLE
During first launch stuck on "Downloading MongoDB Tools"

### ISSUE THREAD

**Issue by Nikeweke** [polonel/trudesk#447]
- [x] BUG 
- [ ] FEATURE

**What happened**:
During first launch stuck on "Downloading MongoDB Tools"

**What did you expect to happen**:
All process must be painless and smooth during first launch

**How to reproduce it (as minimally and precisely as possible)**:
Make first launch

**Anything else we need to know?**:
When I call `callback()` in `src\settings\defaults.js - downloadWin32MongoDBTools` at `file.on('close')` event its works well 

```js 
// src\settings\defaults.js 

function downloadWin32MongoDBTools {
  // ...
   http
    .get('http://storage.trudesk.io/tools/' + filename, function (response) {
      response.pipe(file)
      file.on('finish', function () {
        file.close()
      })
      file.on('close', function () {
        fs.createReadStream(path.join(savePath, filename))
          .pipe(unzipper.Extract({ path: savePath }))
          .on('close', function () {
            fs.unlink(path.join(savePath, filename), callback)
          })
      })
      callback()  // <!----  this one 
    })
    .on('error', function (err) {
      fs.unlink(path.join(savePath, filename))
      winston.debug(err)
      return callback()
    })
}
```

**Environment**:
- Trudesk Version: 1.1.10
- OS (e.g. from /etc/os-release): WIndows 10
- Node.JS Version: 12.22.2
- MongoDB Version: 3.6
- Is this hosted on cloud.trudesk.io: no

**Comment by polonel** [comment]
On Windows, I have to host the MongoDB tools that it needs to download. It's looking for the tools via MongoDB version number. Please verify that you are indeed running one of the following versions of MongoDB. If you are running a different version either change the MongoDB version or let me know **exactly** which full version number you have and I will try to get the tools hosted.

Currently hosted tools:
- MongoDB 3.6.0
- MongoDB 3.6.9
- MongoDB 4.0
- MongoDB 4.0.8
