### ISSUE TITLE
Trudesk - Settings, unusual field input and controls

### ISSUE THREAD

**Issue by kalleyne** [polonel/trudesk#452]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [X ] BUG 
- [ ] FEATURE

**What happened**: The input fields within Settings seem to operate oddly in response to use of the backspace key.

**What did you expect to happen**: I believe that the first character in the field should be able to be deleted via backspace. This currently does not happen.

**How to reproduce it (as minimally and precisely as possible)**: Try to delete all characters within the field using backspace starting from the right of the field and moving to the left with each backspace keystroke. The first character never seems to get deleted and then the whole field repopulates with the original data. The only way to successfully clear the field and replace it with fresh new data is to block the content within the field with mouse or keyboard cursor control keys and then overwrite the field with the new data because the delete key won't work correctly either. As you can believe, this is tricky behavior especially when trying to replace password info which is masked by dots.

**Anything else we need to know?**: I'm not sure if this is a related issue to the above problem but there seems to be an issue with getting Mailer Check to work correctly with Rackspace email IMAP server - secure.emailsrvr.com when using either port 143 or 993. The logs don't show anything much except - "Invalid Log File...". Perhaps future releases can show more verbose debug info for the mailer?

I really like what you have done with the development of Trudesk. Easy install via Ubuntu Install Script. Easy form of backup although I've not tested restore as yet. Simple layout. But for now, the issue with Mailer Check somewhat prevents me from expanding my testing to a larger trial.

**Environment**:
- Trudesk Version: 1.1.10 
- OS (e.g. from /etc/os-release): 20.04.3 LTS (Focal Fossa)
- Node.JS Version: v12.22.7
- MongoDB Version: 4.4.10
- Is this hosted on cloud.trudesk.io: No

**Comment by polonel** [comment]
Confirmed.
