### ISSUE TITLE
Refused to execute script from 'https://site.com/install' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

### ISSUE THREAD

**Issue by maielo** [polonel/trudesk#458]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
Can't install truedesk on selfhosted version

In browser i can see this error and the button to install it is unresponsive
```
Refused to execute script from 'https://xxxxxxx.com/install' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

Uncaught TypeError: window.truRequire is not a function
```
**What did you expect to happen**:
Be able to install it or be able to click on the button to install it

**How to reproduce it (as minimally and precisely as possible)**:
Just build app and access it through link

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: 1.1.1
- OS (e.g. from /etc/os-release): Debian 11
- Node.JS Version: 14
- MongoDB Version: 5
- Is this hosted on cloud.trudesk.io: No

**Comment by polonel** [comment]
did you run `yarn build`?
