### ISSUE TITLE
Cannot connect to MongoDB, authentication failed

### ISSUE THREAD

**Issue by panpetedextra** [polonel/trudesk#46]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [X] BUG 
- [ ] FEATURE

**What happened**: Cannot connect to MongoDB, connection failed
![image](https://user-images.githubusercontent.com/18523001/35842268-934f0d60-0b33-11e8-8d6d-d6823b6ddfa8.png)

This is log from MongdoDB
![image](https://user-images.githubusercontent.com/18523001/35842272-a20647ce-0b33-11e8-9e2c-766f961fbd42.png)

**How to reproduce it (as minimally and precisely as possible)**:
Install dependencies: npm i yarn -g and then yarn
Build the scripts: npm run build
Start the server: npm start
Navigate to: http://localhost:8118

**Environment**:
- Trudesk Version: 0.1.10
- OS (e.g. from /etc/os-release): Windows 7 64
- Node.JS Version: 8.9.3
- MongoDB Version: 3.6
- Is this hosted on cloud.trudesk.io: No

**Comment by panpetedextra** [comment]
Found that for Ununtu script there is a part to generated admin account.
It seems that for Windows installation this part has to be done manually?

**Comment by AdrianRodriguezLlave** [comment]
I had the same problem in Windows. I have solved it starting mongodb in different command prompt and creating user/password manually.

**Comment by panpetedextra** [comment]
Hi AdrianRodriguezLlave,

Thank you for your comment, I can now proceed to next step.

Too bad I still got issue for PM2 due to my security setting on my PC so I decide to use Virtual appliance :(.

**Comment by polonel** [comment]
@panpetedextra Sorry for the lack of documentation right now on setting up trudesk on windows. I'm pushing for a 1.0 release, then I will iron out the documentation. I've actually rolled the appliance out in a production environment for a small client; about 100 tickets a week. 

Also I'm in TestFlight with the iOS client if you wish to sign up for the beta, head over to http://trudesk.io
Any feedback is welcomed. Thank you for your interest in trudesk.

**Comment by LoicSellaye** [comment]
> I had the same problem in Windows. I have solved it starting mongodb in different command prompt and creating user/password manually.

Hi, I am facing the same problem, could you please tell me how did create user/password manually 

Best

**Comment by reaton333** [comment]
I'm a noob to mongodb so the tutorials belows helped me create a user in the database along with enabling authorization. I was having issues connecting for awhile because I created the user in the correct database with the correct username and password but did no enable authorization on the database itself. Hope this helps!
https://www.shellhacks.com/mongodb-create-database-and-user-mongo-shell/
https://www.shellhacks.com/mongodb-auth-enable-authentication-create-admin-root-user/

Create User: 
\> mongo
> use trudesk
> db.createUser(
  {
    user: "trudesk",
    pwd: "some_password",
    roles: [ { role: "readWrite", db: "trudesk" } ]
  }
)

-------------------------------------------
Enable Authentication:
Open mongo.conf file, or in my case it was the mongo.cfg

Make sure this line in somewhere in this file:
security:
  authorization: "enabled"

**Comment by LoicSellaye** [comment]
Thank you for your great and working answer.
Now it's ok I got it working!

Best

**Comment by arvindvohra** [comment]
lack of trudesk install documentation on windows, i am unable to setup.

**Comment by polonel** [comment]
@arvindvohra Not sure what you mean? https://docs.trudesk.io/v1/guide/installation.html#Windows-Install

**Comment by grknsolak** [comment]
problem continue for linux .. help!!

**Comment by bert3ch** [comment]
Hello, 
facing the same problem but I couldt find a solution. Mangoshell doesnt connect too. 
help please
