### ISSUE TITLE
Update MongoDB to latest version

### ISSUE THREAD

**Issue by johandavidson** [polonel/trudesk#462]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ ] BUG 
- [x] FEATURE

**What happened**:

**What did you expect to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
It would be great to upgrade the MongoDB version used by Truedesk to the latest available since MongoDB 3.6.x is rather old now.

**Environment**:
- Trudesk Version:
- OS (e.g. from /etc/os-release):
- Node.JS Version:
- MongoDB Version:
- Is this hosted on cloud.trudesk.io:

**Comment by polonel** [comment]
I'm working on migrating to the latest.

**Comment by polonel** [comment]
Next release is updated for MongoDB 5.0
