### ISSUE TITLE
Trudesk crash during Installation when doing admin setup

### ISSUE THREAD

**Issue by milanosoftware** [polonel/trudesk#466]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ ] BUG 
- [ ] FEATURE

**What happened**:
Crash during admin setup. Unable to complete the installation

**What did you expect to happen**:
Expected to get it installed and ready to use the application
**How to reproduce it (as minimally and precisely as possible)**:
Run the install .. 

**Anything else we need to know?**:
I have elasticsearch installed as well
**Environment**:
- Trudesk Version: 1.1.11
- OS (e.g. from /etc/os-release): Ubuntu 18.04
- Node.JS Version:  12.12.1
- MongoDB Version: 4.4
- Is this hosted on cloud.trudesk.io: No

**Comment by polonel** [comment]
I need a little more information. What do the logs show `logs/output.log` and `logs/error.log`
