### ISSUE TITLE
Unable to change logo, favicon and color palette

### ISSUE THREAD

**Issue by gmarcostam** [polonel/trudesk#469]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
Using the docker version of Trudesk I can't update the logo and the favicon, also I can't change the color palette in Appearance.
After I save the changes those are not applied.

**What did you expect to happen**:
I expect to change logo, favicon and color palette.

**How to reproduce it (as minimally and precisely as possible)**:
Just install the Docker version using the official guide

**Anything else we need to know?**:
No

**Environment**:
- Trudesk Version: 1.1.11 (Docker)
- OS (e.g. from /etc/os-release): Docker on Debian 11
- Node.JS Version: 
- MongoDB Version: 3.6 (Docker)
- Is this hosted on cloud.trudesk.io: No

**Comment by polonel** [comment]
Did you configure the mount point correctly? The demo site (https://docker.trudesk.io) is running on the latest docker container and I'm able to upload the logo and change the color scheme.

**Comment by gmarcostam** [comment]
I used the following docker command:

`docker run --name trudesk -p127.0.0.1:49153:8118 --link mongodb:mongodb \
    -v /data/trudesk/uploads:/usr/src/trudesk/public/uploads \
    -v /data/trudesk/plugins:/usr/src/trudesk/plugins \
    -v /data/trudesk/backups:/usr/src/trudesk/backups \
    -e NODE_ENV=production \
    -e TRUDESK_DOCKER=true \
    -e TD_MONGODB_SERVER=mongodb -e TD_MONGODB_DATABASE=trudesk \
    -P -d polonel/trudesk:1.1.11`

I created in advance all folders inside **/data**

Then, in the Nginx configuration I added the following configuration:

`location ~ ^/(uploads/) {
                root /data/trudesk;
                access_log off;
                expires modified +1h;
        }`

Could you please check if there is an error in my procedure?

Thanks

**Comment by polonel** [comment]
Seems like things are being cached maybe. Have you tried to clear the browser cache and reload the page after making the changes?

**Comment by gmarcostam** [comment]
I tried but it's not working

**Comment by agarofalo-larus** [comment]
> Seems like things are being cached maybe. Have you tried to clear the browser cache and reload the page after making the changes?

I have the same problem too @gmarcostam  , the cache has nothing to do with it

**Comment by polonel** [comment]
I have fixed the issues with the uploading of the images in the next release. 

As far as the color scheme. Can you confirm that if you change the color scheme and then reboot the docker container, does it load the new color scheme?

**Comment by gmarcostam** [comment]
> development

Yes, if I change the color scheme then reboot it is working.
In addition, If a set NODE_ENV=development does not require to reboot.
