### ISSUE TITLE
Replace Icon for "Notices" in WebGui

### ISSUE THREAD

**Issue by Gill-Bates** [polonel/trudesk#474]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ ] BUG 
- [x] FEATURE

Instead of using the "Warning" Icon for Notice, I would suggest the "description" Icon

![image](https://user-images.githubusercontent.com/25774289/152510313-63126614-b3c5-42bd-b05a-e87746e1ea93.png) ![image](https://user-images.githubusercontent.com/25774289/152510415-1c7f5644-5b0a-4ac3-8788-1073e7599156.png)

**Comment by polonel** [comment]
Thanks for the suggestion. I actually went with `campaign` as it's more of an "Announcement".
