### ISSUE TITLE
Introducing a "Maintenance Mode"

### ISSUE THREAD

**Issue by Gill-Bates** [polonel/trudesk#475]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ ] BUG 
- [x] FEATURE

I suggest a "Maintenance Mode". The Login should be only possible for Admins.

![image](https://user-images.githubusercontent.com/25774289/152511568-1d2dd141-e9fa-4204-afb5-1b0ecf31efbb.png)

**Comment by polonel** [comment]
Is included in next release.
