### ISSUE TITLE
Stuck at Processing mails

### ISSUE THREAD

**Issue by muhammet806** [polonel/trudesk#477]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x ] BUG 
- [ ] FEATURE

**What happened**:
In Mailer settings, I defined Mail Checker. Later, when I sent a test mail, I realized that it did not turn into a ticket. When I checked my Mail Inbox, the test mail I sent was deleted.

**What did you expect to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Logs: 
2/21 16:04:09 [28714] - debug: MailCheck: Nothing to Fetch.
2/21 16:05:09 [28714] - debug: Processing 2 Mail
2/21 16:05:48 [28714] - debug: User disconnected (transport close): admin - 4Uwym7Suo9JdpVAtAAAB
2/21 16:05:49 [28714] - debug: User successfully connected: admin
2/21 16:06:09 [28714] - debug: MailCheck: Nothing to Fetch.

**Environment**:
- Trudesk Version:
- OS (e.g. from /etc/os-release): Linux Mint 20.3
- Node.JS Version: 12.22.10
- MongoDB Version: 4.4.12
- Is this hosted on cloud.trudesk.io: no

**Comment by polonel** [comment]
Do you have the "Create Account" option enabled? If no account is found with the same FROM address, and this option is not enabled, the system simply discards the message. 

To make sure we are troubleshooting the same version, is this the latest Trudesk Version? (v1.1.11)

**Comment by muhammet806** [comment]
Already enabled. Also trudesk version 1.1.11

**Comment by polonel** [comment]
What email provider? I want to make sure I'm replicating your setup the best I can.

**Comment by muhammet806** [comment]
I'am using SITEGROUND. 

IF you need more information, I can create one mail adress for replication.

**Comment by polonel** [comment]
I'm going to have to look into this in-depth. I have tested with Gmail, Office 365, On-Prem Exchange, Zoho, and Outlook.com. All emails parse correctly and a ticket was created. Can you create a temp account at one of the listed above providers to confirm if it processes the mail correctly? This will help narrow it down to your provider. As I can't test with SITEGROUND.

**Comment by muhammet806** [comment]
I sent polonel@gmail.com an email. Please check your emails.

**Comment by polonel** [comment]
I have performed a test with the provided email account and have shown the issue is with your SSL certificate and not with Trudesk. A ticket was created when the connection was made over port `143` but failed when using SSL due to `altname` missing with the certificate.
