### ISSUE TITLE
Deployment on AWS

### ISSUE THREAD

**Issue by AbacusQ** [polonel/trudesk#478]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [X] BUG 
- [ ] FEATURE

**What happened**:

I tried to deploy Trudesk on AWS Lightsail today. Well, this did not work properly. I did following steps:
`sudo apt update`
`sudo apt upgrade -y`
`sudo apt install npm`
`sudo npm update caniuse-lite`
`sudo npm i -g caniuse-lite`
`sudo apt install cmdtest`
`sudo npm update`
`sudo npm update caniuse-lite browserslist`
`curl -L -s https://files.trudesk.io/install/ubuntu.sh | sudo bash`

and got a response. At this point the process is stuck:
`\Browserslist: caniuse-lite is outdated. Please run next command 'yarn upgrade caniuse-lite browserslist'`

**Environment**:
- Trudesk Version: Latest
- OS (e.g. from /etc/os-release): Ubuntu 20.04
- Node.JS Version: Latest
- MongoDB Version: Latest
- Is this hosted on cloud.trudesk.io: No

**Comment by polonel** [comment]
this is just a warning and shouldn't prevent the instance from running. I see this all the time in production env and still run with no issues. It's due to an outdated third-party package that has been replaced in an upcoming version release.
