### ISSUE TITLE
trudesk database in mongodb is not created. install issue

### ISSUE THREAD

**Issue by Ahlam-dev** [polonel/trudesk#488]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ ] BUG 
- [ ] FEATURE

**What happened**:
after setting up required packages and running the app. trudesk database in mongodb is not created and getting this error on node runner 
```
 error: Oh no, something went wrong with DB! - connect ECONNREFUSED 127.0.0.1:27017
3/28 09:38:10 [404985] - debug: MongoTest process terminated
```
![image](https://user-images.githubusercontent.com/68360550/160374182-dd00d9c9-c486-4c41-9426-62f3b6bebb0d.png)
**existing databases**
![image](https://user-images.githubusercontent.com/68360550/160374351-d1f4d0d7-7f70-4380-a7a8-7034aa26d2c6.png)
**result of mongod**
![Screenshot (147)](https://user-images.githubusercontent.com/68360550/160377171-df7eaa94-3ec0-4a30-98b1-0cd716479c1e.png)

**What did you expect to happen**:
trudesk database is to be created on mongodb along with the user for authentication
**How to reproduce it (as minimally and precisely as possible)**:
I have installed all the required packages in the document one by one.
mongodb server is running
cloned the github repo and applied steps on document

**Environment**:
- Trudesk Version: 1.1.11
- OS (e.g. from /etc/os-release): ubuntu 20.04
- Node.JS Version: 12.22.11
- MongoDB Version: 4.4.13
- Is this hosted on cloud.trudesk.io: no

**Comment by polonel** [comment]
If you manually installed MongoDB you must manually create the database and user from trudesk to authenticate with. 
Trudesk doesn't know if you are installing to an existing database or a fresh database until you tell it, which it needs to know what database and user to connect to MongoDB to. 

The ubuntu install script handles all this for you.
