### ISSUE TITLE
AccessDenied

### ISSUE THREAD

**Issue by f0regen** [polonel/trudesk#491]
curl -L -s https://storage.trudesk.io/install/ubuntu-tango.sh

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>YXHB1XZBY321NNSJ</RequestId>
<HostId>UEbI5B0B3XfsaG9/xxbkZuE/Cp5HVIVjzenhIjyaSeq8D/M8P1xyBeUWfOA89IuHRHmsXQ4QFFw=</HostId>
</Error>
```

**Comment by polonel** [comment]
Looks like I missed it in the documentation. The file was renamed to `ubuntu-1.2.sh`

`curl -L -s https://storage.trudesk.io/install/ubuntu-1.2.sh`
