### ISSUE TITLE
Abandonware?

### ISSUE THREAD

**Issue by thephox1982** [polonel/trudesk#493]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
The cloud version stopped working with 503 for about a week and half now.

Can't install self hosted using Ubuntu
curl -L -s [http://www.trudesk.io/install/install_ubuntu.sh]() | sudo bash

Can't build using Yarn from GIT..

**What did you expect to happen**:
To be able to use this in at least ONE way or another.

**How to reproduce it (as minimally and precisely as possible)**:
Try to login to the cloud version.
Try to install on Debian 11 with all dependencies pre-installed as directed from the directions by 
either using the ubuntu method OR building from GIT.

**Anything else we need to know?**:
We would love a fix and to be able to use this promising product again!

**Environment**:
- Trudesk Version: Latest
- OS (e.g. from /etc/os-release): Debian 11
- Node.JS Version: 17.9.0
- MongoDB Version: 5.0.7
- Is this hosted on cloud.trudesk.io: Both cloud and self host builds..

**Comment by polonel** [comment]
Not sure what documentation you're looking at but the www.trudesk.io/install/install_ubuntu.sh file was moved years ago to 

`curl -L -s http://files.trudesk.io/install/install_ubuntu.sh | sudo bash`

The above install script is for Trudesk version 1.1.11 and before. 

Since you reported trying to use the Latest version of trudesk, I'm assuming you're referencing version 1.2.0 which was released **6 days ago**. Please read the release notes. [https://github.com/polonel/trudesk/releases/tag/v1.2.0](https://github.com/polonel/trudesk/releases/tag/v1.2.0) which links to the new documentation.  (This information is also listed in the `README`)

**Comment by thephox1982** [comment]
I had to scroll back on the server console, I apparently copied the wrong link from another attempt from me trying to find a version that worked..

The actual curl I tried was: curl -L -s https://storage.trudesk.io/install/ubuntu-1.2.sh | sudo bash
I have updated my original post here to reflect that, I copied wrong link from another one I tried in an attempt to see if it would work which obviously it didn't as it didn't exist anymore.

curl -L -s https://storage.trudesk.io/install/ubuntu-1.2.sh | sudo bash results in this error:
bash: line 1: syntax error near unexpected token `newline'
bash: line 1: `<?xml version="1.0" encoding="UTF-8"?>'

All other methods including build from GIT do not work and the Cloud based service is down and has been for weeks, so I migrated to support system. I also saw no noticed in my looking through the main website that there was a new build or that link had changed. Again, if it has changed the documentation has the wrong link and needs updated.

I just tried the link you gave me and that seems to work fine at least (curl -L -s http://files.trudesk.io/install/install_ubuntu.sh | sudo bash) just need to get the documentation to reflect said change. :-)

**Comment by thephox1982** [comment]
I stand corrected..
`dpkg: error processing package mongodb-org-tools (--install):
 dependency problems - leaving unconfigured                                                 /Errors were encountered while processing:
 mongodb-org-tools                                                                          [DONE]
Downloading the latest version of Trudesk.        [DONE]
Building... (its going to take a few minutes)                      [DONE]
bash: line 292: yarn: command not found
Starting...                                                        |nphox@localhost:~$|
`

That is what I got, it hangs while trying to install, yarn is installed, so not sure what command it was referring to and also the bit about "error processing package mongodb-org-tools" I tried to install that on it's own and it did the same error so a dependency is having errors.. LOL everything about my linux server is up to date and all repo's are functional.. I don't get it, maybe the dependency has been an issue the whole time, who knows. But you can close this since I went elsewhere, it was nice while it worked right..

**Comment by thephox1982** [comment]
https://twelixty.trudesk.io/ just in case others are working fine..
For me I get 503 Service Temporarily Unavailable (openresty/1.15.8.1)

**Comment by polonel** [comment]
Yea I've closed it. I literally just tested the `curl -L -s https://storage.trudesk.io/install/ubuntu-1.2.sh | sudo bash` on a fresh Ubuntu 20.04 deployment on AWS and had no issues. Ubuntu != Debian. Yes, ubuntu is built on Debian, but the repos are completely different. The script is searching for a package in the ubuntu repo that is not named the same in the Debian repo or even present in their repo. 

Please tell me what documentation you refer to that is not updated to reflect the new script. the `README` is current and new documentation was built for `v1.2.0`  [https://github.com/polonel/trudesk/blob/master/README.md#deploy-trudesk-anywhere](https://github.com/polonel/trudesk/blob/master/README.md#deploy-trudesk-anywhere) and [https://docs.trudesk.io/v1.2/](https://docs.trudesk.io/v1.2/)

I personally do not support the cloud version of trudesk. You will need to email support@trudesk.io
