### ISSUE TITLE
Unable to setup Trudesk Locally

### ISSUE THREAD

**Issue by mamach** [polonel/trudesk#494]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
While setup trying to create user is showing following screen

![image](https://user-images.githubusercontent.com/3888640/163770928-ea106212-25fd-440d-b5e6-fa79865bf536.png)

**What did you expect to happen**:
should be able to redirect to login page and allow login with credentials created.

**How to reproduce it (as minimally and precisely as possible)**:
created the following users and ran mongodb with --auth option.
db.createUser({ user: "trudesktest", pwd: "trudesk", roles: ["userAdminAnyDatabase"] })
use trudesk
db.createUser(
  {
    user: "trudesktest",
    pwd: "trudesk",
    roles: [ { role: "dbOwner", db: "trudesk" } ]
  }
)
**Anything else we need to know?**:
no
**Environment**: Ubuntu 20.04 LTS
- Trudesk Version: Latest from github
- OS (e.g. from /etc/os-release): 
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

- Node.JS Version: 16.14.2
- MongoDB Version: 5.0.6
- Is this hosted on cloud.trudesk.io: no

**Comment by polonel** [comment]
Can you please copy and paste the text in the error box and post here?

**Comment by polonel** [comment]
Closing due to lack of update. Please feel free to post the error and I will reopen it.
