### ISSUE TITLE
SiteUrl not used, cannot mount on any subpath e.g. domain.com/tickets

### ISSUE THREAD

**Issue by rsurgiewicz** [polonel/trudesk#496]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [X] BUG 
- [ ] FEATURE

**What happened**:
Trudesk baseUrl/Site Url is not used for generating links.
I'd like to mount it with traefik revproxy on  `domain.com/tickets` but all links (img/a etc.) are generated with `/` 

**What did you expect to happen**:

When site Url is set all links should be generated using the site Url

**How to reproduce it (as minimally and precisely as possible)**:

Spin a trudesk container, and set siteUrl -> check generated linkshrefs
**Anything else we need to know?**:

**Environment**:
- Trudesk Version: 1.2 tagged
- OS (e.g. from /etc/os-release): docker
- Is this hosted on cloud.trudesk.io: No

**Comment by polonel** [comment]
This is unsupported. You should mount to a subdomain instead. `tickets.domain.com`
