### ISSUE TITLE
How do you create multiple mailboxes?

### ISSUE THREAD

**Issue by zigojacko** [polonel/trudesk#498]
Literally that. I can't see how to set up multiple mailboxes in the demo nor find any reference to this anywhere.

Surely it is possible?

**Comment by polonel** [comment]
I'm not sure what you mean by mailbox? Trudesk doesn't use mailboxes.

**Comment by zigojacko** [comment]
> I'm not sure what you mean by mailbox? Trudesk doesn't use mailboxes.

The tickets come in to an email address yes? How do you set up more than one email address and display of tickets? 

For example, one for @support, one for @sales, one for @accounts etc... This is what I was calling a mailbox.

**Comment by polonel** [comment]
The Community Edition can only "poll" a single IMAP mailbox. It then takes the email and converts it to a ticket. A limitation of the community edition. 

The separation of tickets via email submission to certain departments/teams was developed inside the cloud version of Trudesk.  I personally don't work on the cloud version, so more information can be found at https://trudesk.io or support@trudesk.io

**Comment by zigojacko** [comment]
> The Community Edition can only "poll" a single IMAP mailbox. It then takes the email and converts it to a ticket. A limitation of the community edition.
> 
> The separation of tickets via email submission to certain departments/teams was developed inside the cloud version of Trudesk. I personally don't work on the cloud version, so more information can be found at https://trudesk.io or [support@trudesk.io](mailto:support@trudesk.io)

I see. Would there be any plans or consideration to make this change in the community edition can you confirm? It would be desperately needed in our company if we were to move to Trudesk.
