### ISSUE TITLE
It's possible ?

### ISSUE THREAD

**Issue by newerit** [polonel/trudesk#504]
I am find the system ticket with integration, whatsapp api, telegram and librenms API

**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ ] BUG 
- [x] FEATURE

**What happened**:

**What did you expect to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Trudesk Version:
- OS (e.g. from /etc/os-release):
- Node.JS Version:
- MongoDB Version:
- Is this hosted on cloud.trudesk.io:

**Comment by polonel** [comment]
I'm not sure what you're asking?

My best guess is you are wondering if there is an API to interface with those platforms. If so, no there is no 3rd party integration with the community edition of trudesk.
