### ISSUE TITLE
Ticket import JPG failed

### ISSUE THREAD

**Issue by Deenecek** [polonel/trudesk#505]
- [X] BUG 
- [ ] FEATURE

Hi polonel, when I want add image to ticket:
Error uploading file:  <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Internal Server Error</pre>
</body>
</html>

Today 2.6.2022 Im updating trudesk, when i connect to trudesk i still could see version 1.2, why? I use steps for update as in version 1. 
git pull
yarn install
yarn run build
pm2 restart trudesk

Thank a lot !

- Trudesk Version: 1.2
- OS: Linux 20.04 
- Node.JS Version: Newest
- MongoDB Version: Newest
- Is this hosted on cloud.trudesk.io: No

**Comment by polonel** [comment]
Are you seeing this error when you upload an attachment or when you paste in a JPG in the comment and it uploads?

you need to make sure you are on the right branch/commit and not a detached head.

```
git checkout v1.2.3
```

If you've made edit to the source, you will need to stash those changes first.
