### ISSUE TITLE
curl -L -s https://storage.trudesk.io/install/ubuntu-1.2.sh - not working

### ISSUE THREAD

**Issue by frankiec05** [polonel/trudesk#508]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**: So I just installed a clean version of ubuntu 20.04 as stated in the instructions located here: https://docs.trudesk.io/v1.2/#deploying-instance 
and the first step is to enter this command:
curl -L -s https://storage.trudesk.io/install/ubuntu-1.2.sh
^^ That command is just spitting out exact word for word as what displays on that link like it does not execute anything just basically copies word for word of the site without any command ran

![image](https://user-images.githubusercontent.com/68263870/175205732-895c6eb3-7aba-48c0-85b3-f3854fa7a72f.png)

**What did you expect to happen**: The command to run properly

**How to reproduce it (as minimally and precisely as possible)**: N/A

**Anything else we need to know?**: No.

**Environment**:
- Trudesk Version: 1.2
- OS (e.g. from /etc/os-release): Ubuntu 20.04
- Node.JS Version: N/A
- MongoDB Version: N/A
- Is this hosted on cloud.trudesk.io: No

**Comment by VINISHVV** [comment]
@frankiec05
I am also facing same issue, can you help me
