### ISSUE TITLE
Website not displaying

### ISSUE THREAD

**Issue by frankiec05** [polonel/trudesk#509]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ ] BUG 
- [ ] FEATURE
- [x ] Other

**What happened**: So I would execute the command "curl -L -s https://storage.trudesk.io/install/ubuntu-1.2.sh | sudo bash" and it would install everything without a problem. The issue that I am having is when its all done installing I would go to HTTP://ip-address:8181 and it would not pull anything up. I reinstalled it many times and it is not working :/

**What did you expect to happen**: The website loads up instantly.

**How to reproduce it (as minimally and precisely as possible)**: Unknown.

**Anything else we need to know?**: No.

**Environment**:
- Trudesk Version: 1.2
- OS (e.g. from /etc/os-release): Ubuntu 20.04
- Node.JS Version: Ukn
- MongoDB Version: Ukn
- Is this hosted on cloud.trudesk.io: No

**Comment by polonel** [comment]
you need to replace the `ip-address` with the IP address of your Ubuntu server. For example `http://192.168.1.2:8118`

Where 192.168.1.2 would be the IP address of the Ubuntu Server.

**Comment by frankiec05** [comment]
Correct... 

![image](https://user-images.githubusercontent.com/68263870/175215147-7a2ebfe1-4e82-45fc-9ae4-cd69099cff4c.png)
