### ISSUE TITLE
Why an old version of mongdb in install_ubuntu.sh

### ISSUE THREAD

**Issue by jkornblum** [polonel/trudesk#51]
This is more of a question than an issue. I am complete newbie to mongodb but I see the current community version is 3.6 and the `install_ubuntu` bash script is calling for 3.2. 

Is there a reason why this project is pinned to 3.2 or it just hasn't been updated?

Also can the `install_ubuntu.sh` be added to the github repo?

**Comment by polonel** [comment]
I’m currently working out an update now to take it to 3.6. There was some
issues with mongoose that have been resolved that was preventing me from
updating.

**Comment by polonel** [comment]
The Ubuntu install script now contains `MongoDB 3.6` and `Node.JS 8.9.4`
