### ISSUE TITLE
Website not displaying. (Previous was closed :/)

### ISSUE THREAD

**Issue by frankiec05** [polonel/trudesk#510]
What happened: So I would execute the command "curl -L -s https://storage.trudesk.io/install/ubuntu-1.2.sh | sudo bash" and it would install everything without a problem. The issue that I am having is when its all done installing I would go to http://ip-address:8181/ and it would not pull anything up. I reinstalled it many times and it is not working :/

What did you expect to happen: The website loads up instantly.

How to reproduce it (as minimally and precisely as possible): Unknown.

Anything else we need to know?: No.

Environment:

Trudesk Version: 1.2
OS (e.g. from /etc/os-release): Ubuntu 20.04
Node.JS Version: Ukn
MongoDB Version: Ukn
Is this hosted on cloud.trudesk.io: No

Correct... 

![image](https://user-images.githubusercontent.com/68263870/175215147-7a2ebfe1-4e82-45fc-9ae4-cd69099cff4c.png)

I have been doing that and its not working :/

My original one was closed :/

**Comment by frankiec05** [comment]
http://149.28.68.240:8118/

In case you would like to attempt.

**Comment by polonel** [comment]
on the server make sure `trudesk` is actually running by running the command

`sudo pm2 status`

Should list trudesk and give you the active state.

**Comment by polonel** [comment]
I'm not sure where your machine is running. Is this a local VM or in the cloud that you are accessing through a cloud provider?
A firewall seems to block your access to port `8118`. For example, in AWS you have to manually add the port to the inbound of the SecurityGroup. 

Considering the IP you linked is an external real-world IP, I believe its a firewall issue blocking your access to the server on port `8118`

**Comment by frankiec05** [comment]
Okay so I added these to my firewall:

![image](https://user-images.githubusercontent.com/68263870/175237582-a9f8e6d6-6e79-4e67-9bf7-872f823192f9.png)

**Comment by polonel** [comment]
Make sure the Ubuntu firewall is disabled

sudo ufw disable

**Comment by frankiec05** [comment]
Fixed my problem thank you!
