### ISSUE TITLE
Api fetch to group endpoint return 0 group

### ISSUE THREAD

**Issue by mmorin-equisoft** [polonel/trudesk#513]
**Is this a BUG REPORT or FEATURE REQUEST?**:
- [x] BUG 
- [ ] FEATURE

**What happened**:
When I try to create a new ticket, a fetch to the groups is make and 0 groups are return.
Without a  group,  I can't create an issue, a pop up with the error ([Object, Object]) open on left down corner. 

**What did you expect to happen**:
2 groups in the listbox. 

**How to reproduce it (as minimally and precisely as possible)**:
1. Simply install a new trudesk
    a. wget https://raw.githubusercontent.com/polonel/trudesk/master/docker-compose.yml
    b. docker-compose up

**Anything else we need to know?**:
The call is make to this URL : http://localhost:8118/api/v2/groups?limit=1000&page=0
I try with the `v1` and all my groups were return, but 0 with the v2. 

Every of my groups were in the db collection groups.

**Environment**:
- Trudesk Version:  1.2.4
- OS (e.g. from /etc/os-release): Mac OS 12.0 (21A344)
- Node.JS Version: v16.14.2 (polonel/trudesk:1)
- MongoDB Version: MongoDB shell version v5.0.9 (mongo:5.0-focal)
- Is this hosted on cloud.trudesk.io: No

**Comment by polonel** [comment]
I'm not able to reproduce. I'm getting full list with both v1 and v2. Can you tell me what role you are assigned or if you changed any of the permission settings?

**Comment by mmorin-equisoft** [comment]
When I try It, I was an Admin
