### ISSUE TITLE
New Customer Account Creation Error on v1.2.3

### ISSUE THREAD

**Issue by rickyprat** [polonel/trudesk#514]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**: After upgrading to v1.2.3, I got an error when creating a new customer account. This only happens if I assign a group to a new user (Customer) during account creation, error does not seem to occur when I did not assign group to a new user. And there are no problems with Admin and Agent account creation.

![v1 2 3 New Customer Account Creation Error (1)](https://user-images.githubusercontent.com/108453512/176616298-347bef4e-c108-4526-8146-92c0ec57c796.png)

Then if I try to click the Create Account button again, it shows duplicate key error. I can confirm that after closing the New Account menu and refreshing the page, the new user has already created.

![v1 2 3 New Customer Account Creation Error (2)](https://user-images.githubusercontent.com/108453512/176616365-c9fe8325-6972-4e0f-8445-d52f3570b692.png)

**What did you expect to happen**: Successfully creating new customer account without error.

**How to reproduce it (as minimally and precisely as possible)**: On v1.2.3 or v1.2.4, Create a new customer account and assign a group to that new user (Customer), then click Create Account.

**Anything else we need to know?**: Before upgrading, I was using v1.1.11 and never had this problem before. Also, after updating to v1.2.4, it shows the same behavior. I tried tracing it back to v1.2.2 and then found the same error.

**Environment**:
- Trudesk Version: 1.2.3
- OS (e.g. from /etc/os-release): Docker Container on Debian GNU/Linux 11
- Node.JS Version: 16.14.2
- MongoDB Version: 5.0.9
- Is this hosted on cloud.trudesk.io: No

**Comment by polonel** [comment]
This is fixed in the next release (`v1.2.5`)
