### ISSUE TITLE
Multiple security issues (docker install)

### ISSUE THREAD

**Issue by codygamer666** [polonel/trudesk#519]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x ] BUG 
- [ ] FEATURE

**What happened**:
Just installed the site for my company, for security purposes I tested it with multiple website scanners and some vulnerabilities were found.

**What did you expect to happen**:
No vulnerabilities

**How to reproduce it (as minimally and precisely as possible)**:
Point some website scanner at the service

**Anything else we need to know?**:

![Immagine 2022-07-08 114308](https://user-images.githubusercontent.com/96527590/177966443-c94cc487-1feb-42a3-b800-86c0382b6d6b.jpg)

![Immagine 2022-07-08 114413](https://user-images.githubusercontent.com/96527590/177966471-04c148c8-ef8d-48f6-994f-2c31926447a5.jpg)

**Environment**:
- Trudesk Version: 1.2.4
- OS (e.g. from /etc/os-release): Debian, Docker
- Node.JS Version: Docker-Compose
- MongoDB Version: Docker-Compose
- Is this hosted on cloud.trudesk.io: NO

**Comment by polonel** [comment]
I am aware and have already started the process to remediate the issues. Angular has already been completely dropped in the next release.
