### ISSUE TITLE
ticket types > create and tags > create does not do anything

### ISSUE THREAD

**Issue by jkornblum** [polonel/trudesk#52]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [X] BUG 
- [ ] FEATURE

**What happened**:
I navigate the menu using settings > ticket types and click the "create" button in the top right.
The screen flashes (modal appears briefly), if I press it again the modal comes up and stays.

If I repeat the same procedure on tags I see the loading bar go across screen but no modal or change in screen. Repeated presses on create do nothing after this.

**What did you expect to happen**:
I expect modals (correct?) to be displayed to allow me to create a tag or ticket type

**How to reproduce it (as minimally and precisely as possible)**:
Navigating off  `http://localhost:8118/settings/tickettypes/` and returning reproduces the behavior. The same for `../tags`

**Anything else we need to know?**:
This is a fresh install, only one created ticket and the one admin user.

**Environment**:
- Trudesk Version: Trudesk version 0.1.10 [release candidate]
- OS (e.g. from /etc/os-release): Ubuntu 17.10, FireFox
- Node.JS Version: 9.5
- MongoDB Version: 3.2
- Is this hosted on cloud.trudesk.io: no

**Comment by jkornblum** [comment]
Create tag still does nothing (with commit 9632c23). Ticket type issues seem to be resolved.

**Comment by polonel** [comment]
Just to confirm, you're on the development branch and you ran a rebuild of the client-side scripts.
`yarn run build`?

**Comment by jkornblum** [comment]
Yep sorry that ones on me. Works fine now thanks.
Nice project.
