### ISSUE TITLE
Minimum Character Requirements are Inconsistent

### ISSUE THREAD

**Issue by rickyprat** [polonel/trudesk#526]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**: Some User that has less than 5 character username or less than 3 character password cannot login because of the minimum characters requirements are inconsistent.

/src/views/install.hbs

1. Username minimum 5 characters: `if (!adminInfoFormData['admin-username'] || (adminInfoFormData['admin-username'].length < 5)) {`
2. Fullname username minimum 1 character: `if (!adminInfoFormData['admin-fullname'] || (adminInfoFormData['admin-fullname'].length < 1)) {`
3. Password minimum 6 characters: `if (!adminInfoFormData['admin-password'] || (adminInfoFormData['admin-password'].length < 6)) {`

/src/client/containers/Modals/CreateAccountModal.jsx

1. line 171 Username minimum 4 characters: `data-validation-length={'min4'}`
2. line 183 Full Name minimum 2 characters: `data-validation-length={'min2'}`
3. Password minimum 1 character when the Password Complexity is disabled:
- line 117 password: this.password.length > 1 ? this.password : undefined,
- line 118 passwordConfirm: this.passwordConfirm.length > 1 ? this.passwordConfirm : undefined
- line 206 `data-validation={this.props.common.accountsPasswordComplexity ? 'length' : 'none'}`

/src/views/login.hbs

1. line 229 Username and Password minimum 3 characters: `if (u.length < 3 || p.length < 3)`

/mobile/templates/views/login.html

1. line 28 Username minimum 5 characters: `<input type="text" name="username" autocorrect="off" autocapitalize="none" placeholder="Username" class="md" ng-model="auth.username" ng-required="true" ng-minlength="5" required>`
2. line 32  Password minimum 5 characters: `<input type="password" name="password" placeholder="Password" class="md" ng-model="auth.password" ng-required="true" ng-minlength="5">`

**What did you expect to happen**: Consistent character validation in every step of account creation and login, so that all users can login. Since #523 has already merged, perhaps you could use the same validation as in the initial Admin creation at Trudesk installation (5 characters for username, 1 characters for full name, 6 characters for password)? I can create a new pull request if you approve.

**How to reproduce it (as minimally and precisely as possible)**: Login as Admin, disable password complexity, create an Account with 4 character username and 2 character password, logout, then login with the new Account (from desktop or mobile).

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: v1.2.4
- OS (e.g. from /etc/os-release): Docker Container on Debian GNU/Linux 11
- Node.JS Version: 16.14.2
- MongoDB Version: 5.0.9
- Is this hosted on cloud.trudesk.io: No

**Comment by rickyprat** [comment]
Are you saying that in other languages that are not using latin alphabet, it would be impractical if username has to be 5 characters and password has to be 6 characters? How about 4 characters for username and password?

Full name is OK though because it already has a minimum of 1 character.

**Comment by polonel** [comment]
I think 4 is a good median. Ideally, trudesk should have the options in settings to customize what best fits the user for each deployment. I just looked at some of the usernames I have in production and I see names like "**Anna**" as a username. 

So if you want to implement it at 4 characters. I'll add a setting to customize the requirement (within the GUI) at a later date.

**Comment by rickyprat** [comment]
Thanks Chris for the answer.

That's just my suggestion, the 4 character username I mentioned is in development. I just think it'd be better if in the next release trudesk has consistency for the minimum or (and) maximum character from initial admin creation to account creation after installation, also when updating from profile too.

**Comment by polonel** [comment]
No problem. 

I'm going to release `1.2.5` on Sunday (7-17-2022). If you have the PR before I release I'll merge it beforehand.

**Comment by rickyprat** [comment]
Here it is for now #528, 4 characters for username and password, 1 character for Full Name.

**Comment by polonel** [comment]
Merged. Will be included in `v1.2.5`
