### ISSUE TITLE
several bugs in user creation process

### ISSUE THREAD

**Issue by jkornblum** [polonel/trudesk#53]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [X] BUG 
- [ ] FEATURE

**What happened**:
1. Error:undefined toast in bottom left corner when trying to create a new user without a group (not required by form).
2. User not displayed in `http://localhost:8118/accounts` when modal closes (after successful creation)
3. App crashes (unable to connect) if I just press refresh on `../accounts` pages after modal closes

**What did you expect to happen**:
1. The form to prevent me from creating user until all required fields are filled out or error message to provide feedback when no group is selected.
2. The user to appear in the users list after modal closes (without navigating away from page)

**How to reproduce it (as minimally and precisely as possible)**:
1. go to `../accounts` and press the red plus button in right corner
2. fill out all fields, leave group blank, press CREATE ACCOUNT

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: 0.1.10 [release candidate]
- OS (e.g. from /etc/os-release): Ubuntu 17.10, FireFox
- Node.JS Version: 9.5
- MongoDB Version: 3.2
- Is this hosted on cloud.trudesk.io: no

**Comment by polonel** [comment]
In regards to 3, are you using Firefox by chance?  Firefox has an issue with showing the "Disconnected" overlay when refreshing the page.

**Comment by jkornblum** [comment]
Yes FireFox 58.0.2 on Ubuntu
