### ISSUE TITLE
[HELP] 404 Error in v1.2.5

### ISSUE THREAD

**Issue by mzch** [polonel/trudesk#531]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG? 
- [ ] FEATURE

**What happened**:
Running Trudesk, I can see only 404 error page.

**What did you expect to happen**:
Show login page.

**How to reproduce it (as minimally and precisely as possible)**:
1. clone trudesk repository
2. run `yarn` && `yarn build`
3. create `config.yml`
4. create mongodb database
5. run `yarn start`

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: `v1.2.5`
- OS (e.g. from /etc/os-release): `Debian GNU/Linux 11 (bullseye)`
- Node.JS Version: `v16.15.1`
- MongoDB Version: `5.3.2`
- Is this hosted on cloud.trudesk.io: No, self-hosted.

**config.yml**
```yaml
mongo:
  host: 192.168.207.10
  port: '27017'
  username: trudesk
  password: password
  database: trudesk
tokens:
  secret: secret
  expires: 900
elasticsearch: {}
```

**Brower screen shot**
<img width="1516" alt="ScreenShot" src="https://user-images.githubusercontent.com/621178/179716147-6a818b10-bbcb-40bc-b588-0d73b48be290.png">

**Log**
```
07-19-2022 02:05:10 [2026654] info: 	    .                              .o8                     oooo
07-19-2022 02:05:10 [2026654] info: 	  .o8                             "888                     `888
07-19-2022 02:05:10 [2026654] info: 	.o888oo oooo d8b oooo  oooo   .oooo888   .ooooo.   .oooo.o  888  oooo
07-19-2022 02:05:10 [2026654] info: 	  888   `888""8P `888  `888  d88' `888  d88' `88b d88(  "8  888 .8P'
07-19-2022 02:05:10 [2026654] info: 	  888    888      888   888  888   888  888ooo888 `"Y88b.   888888.
07-19-2022 02:05:10 [2026654] info: 	  888 .  888      888   888  888   888  888    .o o.  )88b  888 `88b.
07-19-2022 02:05:10 [2026654] info: 	  "888" d888b     `V88V"V8P' `Y8bod88P" `Y8bod8P' 8""888P' o888o o888o
07-19-2022 02:05:10 [2026654] info: 	==========================================================================
07-19-2022 02:05:10 [2026654] info: 	trudesk v1.2.5 Copyright (C) 2014-2022 Chris Brame
07-19-2022 02:05:10 [2026654] info:
07-19-2022 02:05:10 [2026654] info: 	Running in: production
07-19-2022 02:05:10 [2026654] info: 	Server Time: Tue Jul 19 2022 02:05:10 GMT-0700 (Pacific Daylight Time)
07-19-2022 02:05:11 [2026654] info: 	Connected to MongoDB
07-19-2022 02:05:14 [2026654] info: 	SocketServer Running
07-19-2022 02:05:15 [2026654] info: 	Trudesk is now listening on port: 8118
07-19-2022 02:05:15 [2026654] info: 	trudesk Ready
```

**Comment by rusty1281** [comment]
This is the same issue that is being resolved for the past 1 day. Covered in this [ticket](https://github.com/polonel/trudesk/issues/530)

**Comment by mzch** [comment]
Oh, thanks. I searched only `404` `error`, so I didn't notice this ticket.

**Comment by polonel** [comment]
Closing in favor of #530

**Comment by mzch** [comment]
Fine! Thanks for your effot! :)
