### ISSUE TITLE
Support of TRUDESK behind Proxy

### ISSUE THREAD

**Issue by clackner-gpa** [polonel/trudesk#536]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ ] BUG 
- [x] FEATURE

**What happened**:
We are trying to run TRUDESK behind a reverse Proxy. When a user enters their password incorrectly too many times all users get a 409 too many requests error on the login page.

**What did you expect to happen**:
The user (or the roiginating IP in this case) should be getting the 409 but other systems should be able to reach the page
**How to reproduce it (as minimally and precisely as possible)**:
Put TRUDESK behind a reverse proxy and try the wrong password a few times.

**Anything else we need to know?**:
There is an easy fix in Express where you can set `trust proxy`. We are using Docker and can submit a pull request to simply add an environmental Variable to use this setting. Just wanted to check if this has been under consideration or if there is a different solution already before doing so.

**Environment**:
- Trudesk Version: 1.2.5
- OS (e.g. from /etc/os-release): Docker on Linux
- Node.JS Version:
- MongoDB Version:
- Is this hosted on cloud.trudesk.io: No

**Comment by polonel** [comment]
Thanks for the information. A pull request is most welcome. I thought about this when implementing the rate-limiting but couldn't test thoroughly at the time.

**Comment by clackner-gpa** [comment]
We submitted a Pull request for this issue. Please see https://github.com/polonel/trudesk/pull/542
