### ISSUE TITLE
The users cannot commend or update Ticket

### ISSUE THREAD

**Issue by Chesterguan** [polonel/trudesk#537]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
The users who have the access to the tickets, cannot update or comment tickets.

**What did you expect to happen**:
When clicking on a specific ticket, the user(consumer) could access the ticket and make comments.

**How to reproduce it (as minimally and precisely as possible)**:
* Deploy with docker instance
* Create users with all permissions of tickets and comments
* Use user account to create the ticket
* Click on ticket

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: latest
- OS (e.g. from /etc/os-release): Alpine Linux v3.15
- Node.JS Version: v16.14.12
- MongoDB Version: 5.0
- Is this hosted on cloud.trudesk.io: No

**Comment by polonel** [comment]
Pushing a hotfix

**Comment by polonel** [comment]
I have pushed a fix to master and retagged to `v1.2.5`

Also, docker images have been updated. Just repull tag `v1.2.5`

Please confirm.

**Comment by Chesterguan** [comment]
@polonel  Hi there, I just tested with v1.2.5, and the feature is fulfilled. Thanks for the rapid response.
