### ISSUE TITLE
How to set permission for agent that he can only access the ticket which assigned to him

### ISSUE THREAD

**Issue by yarun1234** [polonel/trudesk#538]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ ] BUG 
- [ ] FEATURE

**What happened**:
Agent can view all ticket of group (assined,unassined,open,new,pending etc)
**What did you expect to happen**:
Agent should only able to see assign tickets (assined)
**How to reproduce it (as minimally and precisely as possible)**:
create two agent of same team and create a ticket of group which can access by agents now and assign that ticket to one of them  i want that only assigned agent can view the ticket but now both agent can view that ticket.

**Anything else we need to know?**:
no
**Environment**:
- Trudesk Version: letest
- OS (e.g. from /etc/os-release): 
- Node.JS Version: 
- MongoDB Version:
- Is this hosted on cloud.trudesk.io:

**Comment by polonel** [comment]
There is an option under permissions for the role you want to only see their tickets. Once the setting is change you will need to restart the server for the permissions to flush out the cache.

![image](https://user-images.githubusercontent.com/626303/181117349-8e4157f2-b9b7-4f5e-b28d-99dc05d954d8.png)

**Comment by polonel** [comment]
Apologies, I read your question wrong. Right now there is no way for agents to only see the tickets they are assigned to.
