### ISSUE TITLE
Get all tickets for the particular user via API v2

### ISSUE THREAD

**Issue by mjk14** [polonel/trudesk#539]
Hi. I want to access to the particular user tickets but when I call /API/v1/tickets, the result includes all tickets of all groups. I see this issue but I can't access API v2 routes. how can I do that?
https://github.com/polonel/trudesk/issues/160
@polonel 
**Environment**:
- Trudesk Version:polonel/trudesk:1.2.4 (docker image)
- MongoDB Version:mongo:5.0-focal (docker image)

**Comment by peastuti** [comment]
any news on this?
