### ISSUE TITLE
How can we open dashboard by access token

### ISSUE THREAD

**Issue by yarun1234** [polonel/trudesk#543]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ ] BUG 
- [ ] FEATURE

**What happened**:
How can we open dashboard by access token, i want to  redirect agent by it's access token and directly open his trudesk account avoid login window
**What did you expect to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Trudesk Version:
- OS (e.g. from /etc/os-release):
- Node.JS Version:
- MongoDB Version:
- Is this hosted on cloud.trudesk.io:

**Comment by polonel** [comment]
This is not possible. Multiple services run on the dashboard including numerous API endpoints, Websockets, and HTTP Only cookies. The dashboard also utilized API v1 and v2 endpoints which require different access tokens and JWT tokens. It sounds like you're trying to do something custom and bypass Trudesk's authentication system. 

As you are free to hack away at Trudesk's core, this is something I will not implement within its core codebase.

**Comment by yarun1234** [comment]
@polonel  no i need a url that i can share with my agent so that he can directly open his dashboard by clicking on that url
like https://abc.com?access_token=sdsdsfds

and the access_token i can fetch by  post api :  /api/v1/login with body { "username": "abc", "password": "xyz"}

**Comment by polonel** [comment]
I understood what you were asking, and this is not possible. You will need to log in using the login page to set the required authentication in order to see any page behind the login page. This is something that will add an extra layer of complexity to the codebase. 

You are free to fork and hack together a solution that fits your requirements.
