### ISSUE TITLE
MailCheck retrieving emails correctly but not creating tickets.

### ISSUE THREAD

**Issue by mrt-prodz** [polonel/trudesk#544]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [X] BUG 
- [ ] FEATURE

**What happened**:
mailCheck is properly retrieving emails but no ticket is created afterward. (using IONOS mail service)

**What did you expect to happen**:
mailCheck should retrieve emails and create tickets.

**How to reproduce it (as minimally and precisely as possible)**:
Using Mailer Check with IONOS.

**Anything else we need to know?**:
While debugging I could see that `mailCheck.Imap.closeBox` and `mailCheck.Imap.end` are never called, no error in the logs, it just hangs after `mailCheck.Imap.addFlags`. It does mark the emails as SEEN so this part works, not sure if it hangs after that because node imap waits for some specific response from the mail server, but nothing happens afterward.

Debug logs will not show anything specific beside : `Processing x Mail`

A quick and dirty test by replacing async.series with the following fixed the issue on my end : 
```js
f.once('end', function () {
  mailCheck.Imap.addFlags(results, flag, function() {
    mailCheck.Imap.closeBox(true, function () {
      mailCheck.Imap.end();
      handleMessages(mailCheck.messages, function () {
        mailCheck.Imap.destroy()
      })
    })
  })
})
```
But I am not really understanding why the async.series in the original source would not properly use the callback on my environment.

Any idea ?

**Environment**:
- Trudesk Version: (Docker) polonel/trudesk:1.2.5
- OS (e.g. from /etc/os-release): (Docker) Alpine Linux v3.15.4
- Node.JS Version: v16.14.2
- MongoDB Version: (Docker) mongo:5.0-focal
- Is this hosted on cloud.trudesk.io: No

**Comment by mrt-prodz** [comment]
Another issue I seem to have is the following :

https://github.com/polonel/trudesk/blob/5bbc42395de7d2589daa97d6837500826448ac11/src/mailer/mailCheck.js#L167-L206

`message` is declared outside the whole `f.on('message'` event. When we overwrite it for each new message in case we have multiple UNSEEN emails it will result in `mailCheck.messages` having the lastest email multiple times since we are pushing the same reference.

Moving the declaration of `var message = {}` inside `msg.on('body'..` solve this issue on my end.

```javascript
f.on('message', function (msg) {
  msg.on('body', function (stream) {
    var message = {}
    var buffer = ''
    ...
```

I doubt I'm the only one having this issue with multiple emails ? Should I open a new issue regarding this ?

**Comment by mrt-prodz** [comment]
On my environment, mailCheck.js has now the following patched `function bindImapReady ()` : 

```javascript
function bindImapReady () {
  try {
    mailCheck.Imap.on('ready', function () {
      openInbox(function (err) {
        if (err) {
          mailCheck.Imap.end()
          winston.debug(err)
        } else {
          async.waterfall(
            [
              function (next) {
                mailCheck.Imap.search(['UNSEEN'], next)
              },
              function (results, next) {
                if (_.size(results) < 1) {
                  winston.debug('MailCheck: Nothing to Fetch.')
                  return next()
                }

                winston.debug('Processing %s Mail', _.size(results))

                var flag = '\\Seen'
                if (mailCheck.fetchMailOptions.deleteMessage) {
                  flag = '\\Deleted'
                }

                var f = mailCheck.Imap.fetch(results, {
                  bodies: ''
                })

                f.on('message', function (msg) {
                  msg.on('body', function (stream) {
                    var message = {}
                    var buffer = ''
                    stream.on('data', function (chunk) {
                      buffer += chunk.toString('utf8')
                    })

                    stream.once('end', function () {
                      simpleParser(buffer, function (err, mail) {
                        if (err) winston.warn(err)

                        if (mail.headers.has('from')) {
                          message.from = mail.headers.get('from').value[0].address
                        }

                        if (mail.subject) {
                          message.subject = mail.subject
                        } else {
                          message.subject = message.from
                        }

                        if (_.isUndefined(mail.textAsHtml)) {
                          var $ = cheerio.load(mail.html)
                          var $body = $('body')
                          message.body = $body.length > 0 ? $body.html() : mail.html
                        } else {
                          message.body = mail.textAsHtml
                        }

                        mailCheck.messages.push(message)
                      })
                    })
                  })
                })

                f.on('end', function () {
                  winston.debug('f on end')
                  mailCheck.Imap.addFlags(results, flag, function() {
                    winston.debug('imap addFlags')
                    mailCheck.Imap.closeBox(true, function () {
                      winston.debug('imap closeBox')
                      mailCheck.Imap.end();
                      winston.debug('calling handleMessages')
                      winston.debug(mailCheck.messages.length + ' messages')
                      handleMessages(mailCheck.messages, function () {
                        mailCheck.Imap.destroy()
                      })
                    })
                  })
                })

              }
            ],
            function (err) {
              if (err) winston.warn(err)
              mailCheck.Imap.end()
            }
          )
        }
      })
    })
  } catch (error) {
    winston.warn(error)
    mailCheck.Imap.end()
  }
}
```

It retrieves properly multiple emails and create all corresponding tickets.

**Comment by polonel** [comment]
Do you want to submit a PR for your changes?

**Comment by mrt-prodz** [comment]
Sure, I'll make a PR during the weekend.

I also want to thank you for your work on Trudesk, this is exactly what I needed for an easy to use task-management system.

**Comment by polonel** [comment]
Thank you for your contribution.
