### ISSUE TITLE
Template editing is not available

### ISSUE THREAD

**Issue by YaponchikLIN** [polonel/trudesk#550]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ ] BUG 
- [ ] FEATURE

**What happened**:
It is not possible to edit mail templates

**What did you expect to happen**:
I can edit templates

**How to reproduce it (as minimally and precisely as possible)**:
Just go to Mailer settings

**Anything else we need to know?**:
Tell me if it is possible to activate the template editing function somehow. I tried it in v 1.2.4 and it worked there. If template editing is not available in this release, then at what point will this feature return?
![Templates](https://user-images.githubusercontent.com/97743066/184633001-24977453-efdd-43db-847f-ff3d2500cbe8.jpg)

**Environment**:
- Trudesk Version: 1.2.5
- OS (e.g. from /etc/os-release): Ubuntu
- Node.JS Version: v16.16.0
- MongoDB Version: EDITION MongoDB 4.4.9 Community

**Comment by blakstrox** [comment]
@polonel I am also having this same issue. How to fix it? Please help.

**Comment by DylanBanta** [comment]
I am also having this issue.
Trudesk 1.2.11
Using Docker with polonel/trudesk:1
SMTP is working as I can receive password reset emails, but don't receive anything when creating a new ticket.
When I have the "Enable New Email Templates" checked, the password reset email will be formatted nicely, and if I have it unchecked it will be bare bones with only text and a hyperlink.
