### ISSUE TITLE
Update ticket priority

### ISSUE THREAD

**Issue by AhmedAdel999** [polonel/trudesk#558]
- [x] BUG 
- [ ] FEATURE

**What happened**:
When updating ticket priority, it doesn't update.

**What did you expect to happen**:
The ticket priority should be updated.

**How to reproduce it (as minimally and precisely as possible)**:

Send a `put` request to update any ticket with the body of `"priority": "[priorityId]"`

**Anything else we need to know?**:
No

**Environment**:
- Trudesk Version: 1.0.17 
- OS (e.g. from /etc/os-release): Arch Linux
- Node.JS Version: 18.7.0
- MongoDB Version: 5
- Is this hosted on cloud.trudesk.io: No

**Comment by polonel** [comment]
Are you really on version `1.0.17`?
