### ISSUE TITLE
Data transfer to state

### ISSUE THREAD

**Issue by YaponchikLIN** [polonel/trudesk#565]
Can you tell me please how to transfer data from the 'message' event to state? 
Data comes from an external source to listen to them, I wrote window.addListener in main.hbs. There 'listener' works out. But it is unclear how to transfer data from main.hbs to state. I tried write 'window.addListener' in the react component, but it didn't work. Also added 'emitter' to the event folder (emitter.on('message'... ) But that didn't work either. Now I'm trying to call 'action' from main.hbs to transfer data to state, but so far without success.

**Comment by polonel** [comment]
I'm not sure what you mean by _"Data comes from an external source to listen to them"_ 

I'm not sure if you mean a JS event or a WS event.

**Comment by YaponchikLIN** [comment]
The data is sent from another site, the data can only be intercepted using window.addListener('message'... . And then it is not clear how to transfer the data to the react component. But I solved this problem in the following way
![image](https://user-images.githubusercontent.com/97743066/192253146-a6ea553f-6082-4ed4-a1bb-b45e66f6e810.png)
But I think this is not quite right, I would like to know another solution to the problem
