### ISSUE TITLE
Ability to customize Status

### ISSUE THREAD

**Issue by clackner-gpa** [polonel/trudesk#566]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ ] BUG 
- [x] FEATURE

**What happened**:
We would like the ability to customize Status of a ticket (change Label, Color, add additional Status...)
**What did you expect to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
We are happy to add another pull request. I mostly got it working, the only concern I have is migration from a previous version. I would appreciate a pointer on how to handle that case, since this would include the addition of a new Database Table. 
**Environment**:
- Trudesk Version:
- OS (e.g. from /etc/os-release):
- Node.JS Version:
- MongoDB Version:
- Is this hosted on cloud.trudesk.io:

**Comment by polonel** [comment]
You will need to look at https://github.com/polonel/trudesk/blob/master/src/settings/defaults.js and the default status of what they are now (New, Open, Pending, Closed). 

Then check out https://github.com/polonel/trudesk/blob/master/src/migration/index.js to loop through all the tickets setting the status field on each ticket to match the new default `_id` of the status. This will only happen once when the version is `< x.x.x`

This is something I try to perform as rarely as possible but it is how I handle migrations in the past.

**Comment by clackner-gpa** [comment]
Pull Request added. I was hoping to add the ability to determine which Status is used for the Views (Open, Pending, Active etc) but we currently don't have the bandwidth. We may get back to that at a later time
