### ISSUE TITLE
how we run (https://trudesk.io/) trudesk code locally on windows 11 after clone from github

### ISSUE THREAD

**Issue by zainbintariq357** [polonel/trudesk#573]
### ****1::  Please tell me which language is used in this project only react,javascript or anyone else**
**2:: When i run the npm install , I can see this type of error that have been given below:****

`npm ERR! code **ERESOLVE**
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: trudesk@1.2.6
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17.0.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14.0 || ^15.0.0 || ^16.0.0-0" from react-html-parser@2.0.2
npm ERR! node_modules/react-html-parser
npm ERR!   react-html-parser@"2.0.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\ztariq\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ztariq\AppData\Local\npm-cache\_logs\2022-10-13T15_03_14_515Z-debug-0.log`

**Comment by polonel** [comment]
Don't run `npm install` use `yarn install` the dependencies are version locked with yarn.

**Comment by zainbintariq357** [comment]
Why the Registration is disabled in trudesk when we are submit the create account form.

**Comment by zainbintariq357** [comment]
Second one what can i do next after running yarn install 

Please reply me as soon as possible because i can not move forward without running your project.

**Comment by zainbintariq357** [comment]
Documentation guide for only ubantu and other platform not for windows. How we can achieve this goal in window.

**Comment by polonel** [comment]
Trudesk.io Registration is closed. This is for the cloud version of trudesk which is different than the open-source version hosted here on GitHub.  I assume you are referring to the cloud version since trudesk.io is the subject of this issue. I do not support the cloud version of trudesk.

![image](https://user-images.githubusercontent.com/626303/195884052-0b833e49-613a-469a-8c7d-c3b4d32da3e3.png)
