### ISSUE TITLE
Having an Issue creating a user with API v1

### ISSUE THREAD

**Issue by postaenzo** [polonel/trudesk#576]
hi, I just installed and run the trudesk stable version. But seems that is still some issue using the v1 API and still cannot find any documentation for the v2. I'm testing the API using postman but I'm not able to create a new user ( login and get existing users ok ). If the v1 is working fine, maybe my request is not valid. I tried in many times and the error that I'm getting is always "Invalid Post Data" from this code section in users.js 
 if (
    !_.every(propCheck, function (x) {
      return x in postData
    })
  ) {
    return res.status(400).json({ success: false, error: 'Invalid Post Data' , postdata: postData})
  }
  One of my test request is below: 
{
     "aUsername":    "user.name1",
     "aPass":        "Passworduser1",
     "aPassConfirm": "Passworduser3",
     "aFullname":    "UserFullName",
     "aEmail":       "user1@yopmail.com",
     "aRole":        "{User}",
     "aTitle":       "Mr",
     "aGrps":        "[{'634e70e4bd99b799cea2e78b'}]"
}

but seems that the method is not receiving it ( req.body seems empty. ) 
I hope I'm wrong, and will be appreciate if you can help me to call correctly that api. 
Will be really appreciate if you can tell me if the stable version is working perfectly fine ( api included ) or not. Because I need to integrate few basic apis functionalities like user creation and tickets management. 
Update: I'm trying to use api v2 but I'm not able to perform the login bcz is asking for a token. 
If some one can help me with these first step I will be super happy to use trudesk. 
- node v16.14.0
- mongo db version v5.0.6

thank you for your support.

_Originally posted by @postaenzo in https://github.com/polonel/trudesk/issues/131#issuecomment-1282149021_

**Comment by polonel** [comment]
Can you show an example of your postman POST? The payload you're sending, etc.

**Comment by postaenzo** [comment]
Hi polonel, thank you in advance for your help. Below the required info. Pls let me know if the v2 API is ready to use or you suggest to use V1 at the moment ? 
- login 
request :
url:  localhost:8118/api/v1/login
payload: 
{
    "username": "postaenzo",
    "password": "myPass4test"
}
response: 
`{
    "success": true,
    "accessToken": "734a78419f97fa50f9b199268a17be5a799dcd56",
    "user": {
        "_id": "634e62b563cec54d6a3ac049",
        "username": "postaenzo",
        "fullname": "Enzo",
        "email": "postaenzo@gmail.com",
        "role": {
            "_id": "634e62b563cec54d6a3ac03f",
            "name": "Admin",
            "description": "Default role for admins",
            "normalized": "admin",
            "isAdmin": true,
            "isAgent": true,
            "id": "634e62b563cec54d6a3ac03f"
        },
        "title": "Administrator",
        "hasL2Auth": false,
        "accessToken": "734a78419f97fa50f9b199268a17be5a799dcd56",
        "deleted": false,
        "lastOnline": "2022-10-18T15:31:19.913Z"
    }
}`
To create an user : 
url: localhost:8118/api/v1/users/create
header:
accessToken : 734a78419f97fa50f9b199268a17be5a799dcd56
payload: 
`{
    "aUsername": "usernameOne",
    "aPass": "Pass4test",
    "aPassConfirm": "Pass4test",
    "aFullname": "username lastname",
    "aEmail": "emailUser@email.com",
    "aRole": "634e62b563cec54d6a3ac041",
    "aTitle": "Mr",
    "aGrps": [
        "634e70e4bd99b799cea2e78b"
    ]
}`
response : 
{
    "success": false,
    "error": "Invalid Post Data"
}
