### ISSUE TITLE
creating a public ticket

### ISSUE THREAD

**Issue by yoonism49** [polonel/trudesk#58]
Hi,

I've enabled the 'Allow Public Tickets' but I see 404 when I hit the API url:

/api/v1/public/tickets/create

Any reasons why this api isn't working?

**Comment by polonel** [comment]
That’s the url for the api to POST to. 

You should visit /newissue

Sorry for the lack of documentation on this. I’m working on getting the docs finished up.

**Comment by yoonism49** [comment]
/api/v1/public/tickets/create

I have posted to the post url above, but I'm getting a response below:
{"success":false,"error":"Invalid Captcha"}

Also what is the full url of the /newissue page? I could not find it.

Thanks!

**Comment by polonel** [comment]
Once you enable public ticket creation on the settings page you can visit `http://{serverhostname}/newissue` in your browser for the ticket creation wizard. This is meant for users without accounts to create an account/ticket.

Please refer to the API docs on creating a ticket when using REST. 
[Creating a ticket with REST](http://trudesk.io/v1/api/#Create-3)

I know the docs are incomplete and I'm working on resolving that.

**Comment by yoonism49** [comment]
I was able to create a public ticket via /newissue.

I just need to know how to create that using REST.

Do you have the body of the request so I can test it out?

Cheers.

**Comment by polonel** [comment]
I'm a little confused on why you can't create an Account, Group, and Ticket using the REST API. The documentation, which shows example request and response can be found in the API documentation (link below).

[Trudesk REST API Documentation](http://trudesk.io/v1/api/)

**Comment by yoonism49** [comment]
So the create api requires an accesstoken.

We need to create a ticket outside of our logged in user. But I assume I can just use the api key and use the the normal create api like a public create. 

I just wanted to separate the logged in users ticket vs non-logged in users tickets. Thats all.

Also if you can point me some documents on the Chat API once it's ready, I'd greatly appreciate it.

Thanks

**Comment by polonel** [comment]
I follow you. I can modify the API for public tickets that will allow the body to create the user and ticket all in the same HTTP Post. I'll get that coded up tonight. (right now the required captcha is preventing this)

_I will ping you when I push the commit for this to develop._

As for the accesstoken, that is only to authenticate the account that's making the request. I have plans to put in a service level accesstoken that can be used. The purpose of this is to just verify permissions of the requesting token. (based on user permissions) Its also used for audit trail as well.

The Chat API is a complete mess right now. Its implementation is going to change in the near future.

**Comment by polonel** [comment]
@yoonism49 Can we discuss your use case? Once I implemented this I had some concerns regarding `spam/bot` tickets being created. There would be no security/permissions for this public ticket API call. I want to make every attempt possible to prevent bots from creating fake or spammy tickets. 

So my question is what are your plans to use this endpoint? Is it possible for your implementation to use an API Key to authenticate before creating the public ticket?

**Comment by rammurthyuio** [comment]
One of the ways to avoid spam/bot creating fake tickets is to assign public ticket creation REST API route a random string. Share the customized URL with the users or clients whoever wants to create tickets without logging in.
Example route would be http://{hostname}/newissue/fsjkdjfbsmdbfjshhe
