### ISSUE TITLE
Trigger A mail to Admin

### ISSUE THREAD

**Issue by nenavathkrishna** [polonel/trudesk#586]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ x] BUG 
- [x] FEATURE

**What happened**:

**What did you expect to happen**:
Whenever an SLA is Overdue for a ticket. We should shoot the mail to the admin.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Trudesk Version:
- OS (e.g. from /etc/os-release):
- Node.JS Version:
- MongoDB Version:
- Is this hosted on cloud.trudesk.io:

**Comment by polonel** [comment]
Planned in v2
