### ISSUE TITLE
Unable to setup or force https

### ISSUE THREAD

**Issue by twillett** [polonel/trudesk#589]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [X ] BUG 
- [ ] FEATURE

**What happened**:
Getting started documentation link for nginx reverse proxy is broken.
**What did you expect to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Go to this link, scroll down and click the nginx reverse proxy hyperlink:
https://docs.trudesk.io/v1.2/

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: 1.2.6
- OS (e.g. from /etc/os-release): Ubuntu 20.04
- Node.JS Version:
- MongoDB Version:
- Is this hosted on cloud.trudesk.io: No. self hosted via digital ocean.

**Comment by polonel** [comment]
Sorry the link on the page is broken. Here is the correct link.

https://docs.trudesk.io/v1.2/getting-started/deployment/nginx-reverse-proxy
