### ISSUE TITLE
[Bug] Can't use Trudesk on multiple sessions (Browser/PC/User)

### ISSUE THREAD

**Issue by tsuzukayama** [polonel/trudesk#59]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [X] BUG 
- [ ] FEATURE

**What happened**:
When multiple users (or two tabs of browser) try to access trudesk, it shows the message 'Disconnected... Trying to reconnect'. Whenever someone else tries to access it, all sessions shows the message.

**Environment**:
- Trudesk Version: 0.1.10 
- OS (e.g. from /etc/os-release): Windows Server 2008
- Node.JS Version: 9.7.1
- MongoDB Version: 3.6.3
- Is this hosted on cloud.trudesk.io: nope

**Comment by polonel** [comment]
Are you using Firefox?

There was an issue with Firefox showing the disconnected state that I just
fixed on the develop branch.

I test using multiple tabs nightly as it’s a very heavy part of my
development process. (With Chrome)

**Comment by tsuzukayama** [comment]
No, I'm using Chrome. I'll try installing it on a linux machine, I think it might be some problem with nginx, since it seems to have some issues on Windows.

**Comment by polonel** [comment]
Yes, this could be the issue. Nginx configuration should forward the original socket request through the proxy to the client. I'm using this setup in a production environment (linux).

Here is an example configure, same configuration as the production.
http://trudesk.io/v1/guide/installation.html#Reverse-Proxy-Nginx

**Comment by tsuzukayama** [comment]
I installed it on Ubuntu 16.04 with the script, and then used nginx to do the reverse proxy. Worked perfectly. Guess the problem was Windows Server. Thanks! I'll be closing the issue now.
