### ISSUE TITLE
still issues with mailer and ticket creation

### ISSUE THREAD

**Issue by e0xify** [polonel/trudesk#592]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ X] BUG 
- [ ] FEATURE

**What happened**:
configured mailer with imap from local mailserver / postfix / dovecot
login works fine, mail gets moved to deleted folder, but no ticket

**What did you expect to happen**:
ticket gets created

**How to reproduce it (as minimally and precisely as possible)**:

starting docker container in  development mode, manually fetch, checking output log
"processing 1 mail" but no ticket gets created

**Anything else we need to know?**:

docker latest

**Environment**:
- Trudesk Version:
- OS (e.g. from /etc/os-release):
- Node.JS Version:
- MongoDB Version:
- Is this hosted on cloud.trudesk.io:

**Comment by Trevoo** [comment]
Do you also have the SMTP server setup for the mailer? Before configured the SMTP on mine I had the same issue. I assume that the ticket creation is getting stopped when trying to send the Ticket Created notification.
