### ISSUE TITLE
trudesk ubuntu-1.2.sh is not working correctly

### ISSUE THREAD

**Issue by APtechnician** [polonel/trudesk#593]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
Installing python: /E: Package 'python' has no installation candidate [FAIL]

Installing Elasticsearch 8 [FAIL] error message below
/Created symlink /etc/systemd/system/multi-user.target.wants/elasticsearch.service -> /lib/systemd/system/elasticsearch.service.
|Job for elasticsearch.service failed.
See "systemctl status elasticsearch.service" and "journalctl -xeu elasticsearch.service" for details.[FAIL]

Installing MongoDB 5.0 [FAIL] error message below
W: https://repo.mongodb.org/apt/ubuntu/dists/focal/mongodb-org/5.0/Release.gpg: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
|E: Unable to correct problems, you have held broken packages.
-Failed to enable unit: Unit file mongod.service does not exist.
-Failed to start mongod.service: Unit mongod.service not found.
Waiting for MongoDB to start...
|Restarting MongoDB...[FAIL]

that's the last error it spits out
bash: line 295: yarn: command not found

**What did you expect to happen**:
MongoDB 5.0 to install successfully
python to install successfully 

**How to reproduce it (as minimally and precisely as possible)**:
rerun the script after applying apt update && apt upgrade -y

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: 1.2.6
- OS (e.g. from /etc/os-release): Ubuntu 22.10
- Node.JS Version:
- MongoDB Version: 5.0
- Is this hosted on cloud.trudesk.io: No (Proxmox)
-Image below:
<img width="942" alt="trudesk" src="https://user-images.githubusercontent.com/126001831/220406564-2d9f0506-dd8b-434f-a2ba-358687109c42.PNG">

**Comment by vegetable8** [comment]
Trudesk is not supported on 22.xx. Try Ubuntu 20.04 and let me know if that fixes your issue

**Comment by APtechnician** [comment]
Same error, I"m lost on what to do at this point
cat /etc/os-releas-
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**Comment by polonel** [comment]
Just tested the script on a fresh **Ubuntu 20.04** deployed on AWS with no issues.
