### ISSUE TITLE
Issue When Creating Tickets VIA API

### ISSUE THREAD

**Issue by mlunato47** [polonel/trudesk#594]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
When creating a test ticket VIA the API I can not interact with the ticket in the UI. When trying to click the ticket in the UI I receive a 502 Bad Gateway error everytime. I have tried a hard reboot of the container running Trudesk and that did not do the trick. The test ticket I created VIA the UI works fine with no issues, I can interact with it as expected. When the 502 error happens I have to go back to the main page and relog in everytime. We are trying to have tickets auto generated from our SIEM tool when an alert of a certain severity comes into the SIEM tool.
**What did you expect to happen**:
When creating the ticket VIA the API I expected to be able to click and interact with the ticket in the UI as normal.
**How to reproduce it (as minimally and precisely as possible)**:
I created the two test tickets VIA a Postman request. Here is the body of the POST being sent from Postman, I changed the actual values to xxx just to omit the actual IDs. When sending the request I have the actual IDs needed. I also receive a success back along with seeing the new ticket in the UI, just getting the 502 bad gateway when clicking it.
{
  "subject": "Testing",
  "issue": "This is a test ticket created using the Trudesk API",
  "owner": "xxx",
  "group": "xxx",
  "type": "xxx",
  "priority": "xxx"
}

**Anything else we need to know?**:
Nothing else needed to know but I am also not sure how to generate an API key for a user. There is no button in the UI to do so. The API key I am using is for the default admin account created when first booting up Trudesk, the other accounts I created don't have a key assigned and there is no way that I am aware of to assign one.
**Environment**:
- Trudesk Version: 1.2.6
- OS (e.g. from /etc/os-release): Linux (Running on AWS EKS)
- Node.JS Version: 16
- MongoDB Version: 4.4.6
- Is this hosted on cloud.trudesk.io: No

**Comment by polonel** [comment]
If you refresh the page are you able to interact with the ticket?

Can you provide any logs from the container (`/usr/src/trudesk/logs`) which should show the container crashing if you get a 502 Bad Gateway. If you have a proxy in front logs from that as well would be helpful.
