### ISSUE TITLE
How to assign a ticket to a Role in trudesk.

### ISSUE THREAD

**Issue by Suhasrcb** [polonel/trudesk#599]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ ] BUG 
- [ ] FEATURE

**What happened**:

**What did you expect to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Trudesk Version:
- OS (e.g. from /etc/os-release):
- Node.JS Version:
- MongoDB Version:
- Is this hosted on cloud.trudesk.io:

**Comment by thebinij** [comment]
#### Is this what you meant?


https://user-images.githubusercontent.com/93417120/229069957-4190a187-50ba-4412-a2b7-ae1bace4021d.mp4
