### ISSUE TITLE
[BUG] Create Tag button does nothing

### ISSUE THREAD

**Issue by tsuzukayama** [polonel/trudesk#60]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [X] BUG 
- [ ] FEATURE

**What happened**:
The create tag button on the admin settings does nothing
**What did you expect to happen**:
Open a form to create a new tag
**How to reproduce it (as minimally and precisely as possible)**:
Click the create tag button

**Anything else we need to know?**:

Trudesk Version: 0.1.10
OS (e.g. from /etc/os-release): Ubuntu Server 16.04
Node.JS Version: 9.7.1
MongoDB Version: 3.6.3
Is this hosted on cloud.trudesk.io: nope

**Comment by polonel** [comment]
This has been fixed with issue #52, It hasn't made its way onto master yet. I'm working to get develop in a stable state so I can merge.
