### ISSUE TITLE
Release Trudesk mobile app on Australian iOS app store.

### ISSUE THREAD

**Issue by sfulham** [polonel/trudesk#602]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ ] BUG 
- [x] FEATURE

**What happened**:
Trudesk is not available and cannot be found in the Australian iOS app store.
**What did you expect to happen**:
Trudesk to be available in the Australian iOS app store.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Trudesk Version:
- OS (e.g. from /etc/os-release):
- Node.JS Version:
- MongoDB Version:
- Is this hosted on cloud.trudesk.io:

**Comment by polonel** [comment]
The native mobile app was disconnected years ago. I didn't have the free time to maintain both. Trudesk now has a web-based mobile version if you open your trudesk installation through the browser on a mobile device.
