### ISSUE TITLE
Emails for Tickets

### ISSUE THREAD

**Issue by mlunato47** [polonel/trudesk#607]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
Emails for ticket creation or modification are not being sent out. Emails for password resets work and are being sent, but there are no emails being sent regarding tickets.
**What did you expect to happen**:
When a ticket is created or modified users/agents attached to the ticket would get an email update.
**How to reproduce it (as minimally and precisely as possible)**:
Mailer is configured to use AWS SES and is connecting fine, password reset emails are bing sent no issues. The ticket emails just don't seem to work. Hosted on AWS EKS

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: Trudesk version 1.2.7
- OS (e.g. from /etc/os-release):
- Node.JS Version:
- MongoDB Version:
- Is this hosted on cloud.trudesk.io: No

**Comment by suprematis** [comment]
I use Postmark (postmark.io) and I get the same behavior.  Emails are delivered when user requests a password reset, but not when a ticket is created or updated.  I am the Notifications Template BETA feature.

![image](https://github.com/polonel/trudesk/assets/24498458/43eaa884-3934-4439-9290-b95f1a4ab880)

**Comment by polonel** [comment]
I am not able to reproduce it. I'm currently using Office 365 and sending to outlook.com & Gmail.

Let's ensure we have users set up to get the emails.

Trudesk will send an email when a ticket is created to everyone in the agent **"Team"** and any users set up in the **"Customer Group"** as **"Send Notifications To"**

Please verify this. 

Another option is to enable `NODE_ENV=development` to show debug logs within the console. you should see something like this:

`06-10-2023 13:01:20 [26876] debug:      Sent [2] emails.`
