### ISSUE TITLE
Setup Error when creating accounts

### ISSUE THREAD

**Issue by HegartyT** [polonel/trudesk#608]
**Is this a BUG REPORT or FEATURE REQUEST?**:
- [x] BUG 

**What happened**:
When the setup server side was completed we went to setup the first user and came across an error. Please see the image attached. 
**What did you expect to happen**:
For the user to have been created and redirected through to the main dashboard. 
**How to reproduce it (as minimally and precisely as possible)**:
I have a VPS with DNS redirects, two instances of Trudesk running for different companies within the same VPS. Then installation of the second instance try complete the first account installation setup.

**Anything else we need to know?**:

**Environment**:
- OS (e.g. from /etc/os-release): Ubuntu LTS Server Edition  
- Is this hosted on cloud.trudesk.io: No

<img width="537" alt="Screenshot 2023-05-24 at 11 59 42" src="https://github.com/polonel/trudesk/assets/46330795/efd6eeb2-8d7b-460a-8c47-468515d77cdd">

**Comment by polonel** [comment]
It won't work that way, unless you are using docker with a proxy in the front like NGINX.
(or kubernetes with a different ingress & pod per)

This error is occurring because the host does not equal the host of the server.
