### ISSUE TITLE
Ubuntu installation script attempts to check for and install python2 instead of python3

### ISSUE THREAD

**Issue by sschwetz** [polonel/trudesk#615]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [X] BUG 
- [ ] FEATURE

**What happened**:

On attempting installation on ubuntu 20.04 the installer attempted to install python package which has been removed and only python3 is installed.

Installing python                                                                                                           -E: Package 'python' has no installation candidate

**What did you expect to happen**:

Installer should recognise that python3 is now python that is supported and attempt installation of it

**How to reproduce it (as minimally and precisely as possible)**:

run ubuntu installation script

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: current
- OS (e.g. from /etc/os-release): Ubuntu 22.04 LTS
- Node.JS Version: N/A
- MongoDB Version: N/A
- Is this hosted on cloud.trudesk.io: No

**Comment by polonel** [comment]
Are you on 20.04 or 22.04? You list both?
