### ISSUE TITLE
Tickets missing on web mobile

### ISSUE THREAD

**Issue by ShadowVoyd** [polonel/trudesk#616]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
Unable to see tickets on web mobile
**What did you expect to happen**:
Active tickets visible in web mobile version
**How to reproduce it (as minimally and precisely as possible)**:
Log in on mobile version with chrome or edge browser on a mobile device. Tickets are not visible even to an admin. Refreshing page and clearing filters does not work. 

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: 1.2.8
- OS (e.g. from /etc/os-release): docker/linux
- Node.JS Version: 16.14.2
- MongoDB Version: 5.0.19
- Is this hosted on cloud.trudesk.io: no

**Comment by ShadowVoyd** [comment]
![Screenshot_20230717_232008_Edge](https://github.com/polonel/trudesk/assets/35205411/9d03b68f-74b2-4720-b441-e6b6466e9451)

**Comment by alecs** [comment]
I fixed this with a tiny hack:
https://github.com/SysOPSRO/trudesk/tree/1.2.9.1

And the image is usable from:
https://hub.docker.com/r/sysopsro/trudesk
