### ISSUE TITLE
[FEATURE] Any plan support chinese searching?

### ISSUE THREAD

**Issue by quickerlab** [polonel/trudesk#62]
1. Create a new topic in chinese
2. Search a chinese string, no searching action.

Is there any plan?
thanks.

**Comment by polonel** [comment]
Support multiple languages is on the roadmap but will not hit at a 1.0 release. I'm having trouble finding users that translate strings to support different languages.

**Comment by stanl33y** [comment]
@polonel Can I collaborate with portuguese(BR) strings? Thinking about using i18n?

**Comment by stanl33y** [comment]
https://crowdin.com/

**Comment by polonel** [comment]
Trudesk is in the process of being translated to Chinese (Special Thanks to @Xcrossd)
Testing is underway, and searching is recieving an update in the very near future with elasticsearch integration. 

Ref: https://crwd.in/trudesk
