### ISSUE TITLE
Trudesk version 1.2.9 - Closed tickets missing?

### ISSUE THREAD

**Issue by nunodsfernandes** [polonel/trudesk#622]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ ] BUG 
- [x] FEATURE

**What happened**:

Upgraded to the latest Trudesk version today.
One thing that i noticed out of the bat is that "Closed ticket" is no longer present on the options:

![image](https://github.com/polonel/trudesk/assets/75372015/b6037228-00b1-4267-acae-20aba23bf715)

Is this by design or is it something wrong?
This was really useful to re-open tickets.

**What did you expect to happen**:
Have Closed Tickets available

**How to reproduce it (as minimally and precisely as possible)**:
N/A

**Anything else we need to know?**:
N/A

**Environment**:
- Trudesk Version: 1.2.9
- OS (e.g. from /etc/os-release): Ubuntu 20.04 LTS
- Node.JS Version: v10.24.1
- MongoDB Version: db version v3.6.23
- Is this hosted on cloud.trudesk.io: No

**Comment by polonel** [comment]
The statuses in the menu were removed during the conversation of static statuses to customizable. I'm working on the best way to handle the ability to add the status back to the menu as in previous releases.

**Comment by nunodsfernandes** [comment]
Got it, thanks :)
Hope it comes soon, since it's a huge thing to be able to list and re-open closed tickets :)
