### ISSUE TITLE
Ticket by status breaks tool

### ISSUE THREAD

**Issue by nunodsfernandes** [polonel/trudesk#623]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ x ] BUG 
- [ ] FEATURE

**What happened**:

Generating report of tickets by Status will only show a blank page

Tickets by priority:
![image](https://github.com/polonel/trudesk/assets/75372015/b5268985-cd17-49db-a5e4-cd7ae9d9f6f8)

Works.

Tickets by Status:

![image](https://github.com/polonel/trudesk/assets/75372015/608d1125-910e-44b4-9add-0aee98282870)
Shows empty page.
Also, it will break the menu also.
To do anything one needs to click on another menu item (i clicked Departments as an example)

**What did you expect to happen**:

Show tickets by status

**How to reproduce it (as minimally and precisely as possible)**:

Click the Generate button and then the By status link.

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: 1.2.9
- OS (e.g. from /etc/os-release): Ubuntu 20.04 LTS
- Node.JS Version: v10.24.1
- MongoDB Version: db version v3.6.23
- Is this hosted on cloud.trudesk.io: No

**Comment by RShadowhand** [comment]
This is an ongoing problem at 1.2.10, not only that, the datepickers in other reports are broken as well when a custom date format is selected.
