### ISSUE TITLE
Ticket emails are not receiving by the customer.

### ISSUE THREAD

**Issue by marvelindxb** [polonel/trudesk#628]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [X ] BUG 
- [ ] FEATURE

**What happened**:
**### Agents are receiving the new ticket details, but not the customer when they are sending an email. If there is a new customer sending a request, they are receiving the welcome email but not the ticket details. Also, the same issue if there is an update on the ticket by the agent. In the case of an update by an agent neither agent nor the customer is receiving any update on the email.**
**What did you expect to happen**:
from the start
**How to reproduce it (as minimally and precisely as possible) **:
sending a new email from existing user or a new user.

**Anything else we need to know? **:
SMTP Header/ Name is not replying as what we provided as input instead just the name in the email id. For eg: abc@xyz.com is the email and I provided the name as Do Not Reply ABC, but the customer is getting them email as 'abc'.

**Environment**:
- Trudesk Version: 1.2.9
- OS (e.g. from /etc/os-release): ubuntu 18.04
- Node.JS Version: V16.20.2
- MongoDB Version: 5.0.20
- Is this hosted on cloud.trudesk.io: No

**Comment by marvelindxb** [comment]
@polonel any update on this?

**Comment by blakstrox** [comment]
Hi I am also having same issue @polonel

**Comment by polonel** [comment]
I'm not sure I understand. You're saying no ticket updates are being emailed but the "New Ticket" email is being sent?

**Comment by blakstrox** [comment]
@polonel The customer is able to get other emails, such as forgot password, etc. But whenever our agents reply to a ticket from the portal, most of the times no email is sent to the customer. Also most of the times, if customer directly replies over email, it is also not refelected on the portal. I can see that email is getting deleted from my IMAP inbox but that same email is not reflected as Ticket in Trudesk.
