### ISSUE TITLE
Mail Checker not working with Exchange server.

### ISSUE THREAD

**Issue by rammurthyuio** [polonel/trudesk#63]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x ] BUG 
- [ ] FEATURE

**What happened**: Mail Checker Not working

**What did you expect to happen**: Create tickets automatically from Exchange mail server

**How to reproduce it (as minimally and precisely as possible)**: I have plugged in the correct values in the settings -> General -> Mail Checker

But it is unable to connect to the Exchange server with the given details.

I wrote my own piece of code and put in the same details and I'm able to get the mails.

**Anything else we need to know?**: Error log shows this 
Error: Timed out while authenticating with server
    at Timeout._onTimeout (/home/ram/Desktop/trudesk/node_modules/imap/lib/Connection.js:139:17)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)

**Environment**:
- Trudesk Version: Latest (pulled the code yesterday - march 16th 2018)
- OS (e.g. from /etc/os-release): ubuntu 16.04
- Node.JS Version: 8.9.3
- MongoDB Version: 3.6.3
- Is this hosted on cloud.trudesk.io: No

**Comment by polonel** [comment]
What version of exchange? 
I have trudesk a production client with exchange 2010 with mail submission as their primary source of submissions. 

I have not tested fully with another version of exchange, so would like to test with version you’re running.

I do know that they had to enable TLS and SSLv3 for it to authenticate.

**Comment by rammurthyuio** [comment]
The Exchange Server Version is 2010 SP3 RU19. Build Number is 14.3.382.0. This version is release in Dec 2017.

**Comment by polonel** [comment]
You said you wrote a bit of code that with correctly. Do you mind sharing the transport configure you use? (Nodemailer)

**Comment by rammurthyuio** [comment]
I have figured out the issue. The 'tls' property is being assigned 'false' value because you are checking port number with number type while you are getting port number as string at line number 52 in /trudesk/src/mailer/mailCheck.js file.
![screenshot from 2018-03-18 13-43-02](https://user-images.githubusercontent.com/33408468/37568985-e3710908-2ab2-11e8-8852-a94edd39e220.png)
![screenshot from 2018-03-18 13-43-34](https://user-images.githubusercontent.com/33408468/37568989-e9c18fa8-2ab2-11e8-96dc-0540a3ec98e8.png)

**Comment by polonel** [comment]
I’ll fix that. That was a pull request.
