### ISSUE TITLE
Multiple vulnerabilities found

### ISSUE THREAD

**Issue by nunodsfernandes** [polonel/trudesk#631]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ x ] BUG 
- [ ] FEATURE

**What happened**:
Scans found multiple vulnerabilities on a vanilla Trudesk install.

![image](https://github.com/polonel/trudesk/assets/75372015/e7c2491b-ca2f-4dfe-8d89-e1fbe0c51156)

**Packages:**

- json5
- minimist
- kind-of
- qs
- scss-tokenizer
- mongoose
- loader-utils
- decode-uri-component
- websocket-extensions

**GH Reference**
- https://github.com/advisories/GHSA-9c47-m6qq-7p4h
- https://github.com/advisories/GHSA-xvch-5gv4-984h
- https://github.com/advisories/GHSA-6c8f-qphg-qjgp
- https://github.com/advisories/GHSA-hrpp-h998-j3pp
- https://github.com/advisories/GHSA-7mwh-4pqv-wmr8
- https://github.com/advisories/GHSA-9m93-w8w6-76hh
- https://github.com/advisories/GHSA-76p3-8jx3-jpfq
- https://github.com/advisories/GHSA-3rfm-jhwj-7488
- https://github.com/advisories/GHSA-w573-4hg7-7wgq
- https://github.com/advisories/GHSA-g78m-2chm-r7qv
- https://github.com/advisories/GHSA-f825-f98c-gj3g

**What did you expect to happen**:
Any mitigation for these issues?

**How to reproduce it (as minimally and precisely as possible)**:
This was the result of a scan conducted by an external tool (Wiz Scan).

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: 1.2.9
- OS (e.g. from /etc/os-release): Ubuntu 20.04 LTS
- Node.JS Version: v10.24.1
- MongoDB Version: db version v3.6.23
- Is this hosted on cloud.trudesk.io: No

**Comment by polonel** [comment]
We utilize Synk for vulnerability patching/testing.  There is already an active PR for Mongoose and the others are unverified. 

Please email security vulnerabilities directly or report them on https://huntr.dev to prevent exposure before a patch is available from the third-party maintainer. 

Thus I am deleting this issue and encourage you to report them to my email or https://huntr.dev
