### ISSUE TITLE
Email polling not working most of the times and reply over email is not reflected on the portal

### ISSUE THREAD

**Issue by blakstrox** [polonel/trudesk#636]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
1. I am not able to poll emails from IMAP account. I can see that mails getting deleted from my mailbox but it is not showing up on the Ticket list. 
2. Also if I reply to an open ticket sometimes the email is not sent to the customer.
3. Whenever customer reply directly over email instead of portal, it never shows in the portal
**What did you expect to happen**:
I need this email issue to be resolved
**How to reproduce it (as minimally and precisely as possible)**:
Configure email polling and try to send an email to the configured email address and try to reply both sides.

**Anything else we need to know?**:

Log:
`10-03-2023 10:11:15 [407] info: 	    .                              .o8                     oooo
10-03-2023 10:11:15 [407] info: 	  .o8                             "888                     `888
10-03-2023 10:11:15 [407] info: 	.o888oo oooo d8b oooo  oooo   .oooo888   .ooooo.   .oooo.o  888  oooo
10-03-2023 10:11:15 [407] info: 	  888   `888""8P `888  `888  d88' `888  d88' `88b d88(  "8  888 .8P'
10-03-2023 10:11:15 [407] info: 	  888    888      888   888  888   888  888ooo888 `"Y88b.   888888.
10-03-2023 10:11:15 [407] info: 	  888 .  888      888   888  888   888  888    .o o.  )88b  888 `88b.
10-03-2023 10:11:15 [407] info: 	  "888" d888b     `V88V"V8P' `Y8bod88P" `Y8bod8P' 8""888P' o888o o888o
10-03-2023 10:11:15 [407] info: 	==========================================================================
10-03-2023 10:11:15 [407] info: 	trudesk v1.2.9 Copyright (C) 2014-2023 Chris Brame
10-03-2023 10:11:15 [407] info: 	
10-03-2023 10:11:15 [407] info: 	Running in: production
10-03-2023 10:11:15 [407] info: 	Server Time: Tue Oct 03 2023 10:11:15 GMT+0000 (Coordinated Universal Time)
10-03-2023 10:11:16 [407] info: 	Connected to MongoDB
10-03-2023 10:11:18 [407] info: 	SocketServer Running
10-03-2023 10:11:18 [407] error: 	connect ECONNREFUSED 127.0.0.1:143 - Error: connect ECONNREFUSED 127.0.0.1:143
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
10-03-2023 10:11:19 [407] info: 	Trudesk is now listening on port: 8118
10-03-2023 10:11:19 [407] info: 	trudesk Ready
10-03-2023 10:13:16 [407] error: 	connect ECONNREFUSED 127.0.0.1:143 - Error: connect ECONNREFUSED 127.0.0.1:143
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
10-03-2023 10:13:32 [407] error: 	connect ECONNREFUSED 127.0.0.1:143 - Error: connect ECONNREFUSED 127.0.0.1:143
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
10-03-2023 10:13:35 [407] error: 	connect ECONNREFUSED 127.0.0.1:143 - Error: connect ECONNREFUSED 127.0.0.1:143
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
10-03-2023 10:21:18 [407] error: 	connect ECONNREFUSED 127.0.0.1:143 - Error: connect ECONNREFUSED 127.0.0.1:143
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
10-03-2023 10:31:18 [407] error: 	connect ECONNREFUSED 127.0.0.1:143 - Error: connect ECONNREFUSED 127.0.0.1:143
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
10-03-2023 10:41:18 [407] error: 	connect ECONNREFUSED 127.0.0.1:143 - Error: connect ECONNREFUSED 127.0.0.1:143`

**Environment**:
- Trudesk Version: 1.2.9
- OS (e.g. from /etc/os-release): Docker
- Node.JS Version: - 
- MongoDB Version: Latest image from Docker
- Is this hosted on cloud.trudesk.io: No

**Comment by second2falcon** [comment]
This issue shouldn't be closed. Running into the same problem with multiple mailservers... Tried iCloud, Gmail, Exchange/Outlook/O365 and my own mailserver. All the same problem. Sending is fine, but receiving doesn't work.
