### ISSUE TITLE
NOT ABLE TO ACCESS THE API

### ISSUE THREAD

**Issue by Ritesh91** [polonel/trudesk#64]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:

**What did you expect to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Trudesk Version:
- OS (e.g. from /etc/os-release):
- Node.JS Version:
- MongoDB Version:
- Is this hosted on cloud.trudesk.io:

**Comment by polonel** [comment]
Have you taken a look at the API documentation? 

You can’t query the API in a browser, as you need the AccessToken header.

**Comment by polonel** [comment]
Also there is no API sitting at trudesk.io

The API is built into the trudesk server instance.
