### ISSUE TITLE
Error on logout

### ISSUE THREAD

**Issue by stanl33y** [polonel/trudesk#65]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
When try to log out nothing happens
Log error:
> You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
> TypeError: Cannot convert undefined or null to object
>     at Function.assign (<anonymous>)
>     at executeOperation (/etc/trudesk/node_modules/mongodb/lib/utils.js:386:14)
>     at Collection.remove (/etc/trudesk/node_modules/mongodb/lib/collection.js:1239:10)
>     at withCallback.collectionReady.then.collection (/etc/trudesk/node_modules/connect-mongo/src/index.js:297:48)
>     at <anonymous>
>     at process._tickDomainCallback (internal/process/next_tick.js:228:7)
> (node:7606) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot convert undefined or null to object
> (node:7606) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> (node:7606) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: Cannot convert undefined or null to object
> (node:7606) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): TypeError: Cannot convert undefined or null to object
> (node:7606) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): TypeError: Cannot convert undefined or null to object
> (node:7606) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): TypeError: Cannot convert undefined or null to object
> (node:7606) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 7): TypeError: Cannot convert undefined or null to object
> (node:7606) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 8): TypeError: Cannot convert undefined or null to object
> (node:7606) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 9): TypeError: Cannot convert undefined or null to object
> (node:7606) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 10): TypeError: Cannot convert undefined or null to object
> (node:7606) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 11): TypeError: Cannot convert undefined or null to object
> (node:7606) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 12): TypeError: Cannot convert undefined or null to object
> (node:7606) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 13): TypeError: Cannot convert undefined or null to object
> (node:7606) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 14): TypeError: Cannot convert undefined or null to object
> (node:7606) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 15): TypeError: Cannot convert undefined or null to object

**What did you expect to happen**:
To log out
**How to reproduce it (as minimally and precisely as possible)**:
Click the logout button
**Anything else we need to know?**:
Nothing else
**Environment**:
- Trudesk Version: v1.0.0
- OS (e.g. from /etc/os-release):

NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
- Node.JS Version: v8.9.4
- MongoDB Version: v3.6.3
- Is this hosted on cloud.trudesk.io: No

**Comment by polonel** [comment]
Thanks. I actually fixed this issue last night but it’s on develop right
now.

https://github.com/polonel/trudesk/commit/7dc2cec5f1168b2083e1a716e07c8f605c2ab2f9

The fix is to downgrade connect-mongo to 1.3.2

**Comment by stanl33y** [comment]
Thanks for your attention, congratulations.
