### ISSUE TITLE
Mailer Check not working at all

### ISSUE THREAD

**Issue by second2falcon** [polonel/trudesk#658]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
When I send an email to my support inbox, I can see it in the webmail portal, but regardless if I do a manual Mailer Check scan, or just wait, Trudesk never seems to recognize there being an email.
**What did you expect to happen**:
Trudesk creating a ticket according to the email sent.
**How to reproduce it (as minimally and precisely as possible)**:
Install Trudesk, setup inboud and outbound mail. Send mail to support inbox.

**Anything else we need to know?**:
Own mailserver running mailcow, but the same issue existed with O365/MS365/Exchange.

**Environment**:
- Trudesk Version: 1.2.10
- OS (e.g. from /etc/os-release): Default docker-compose stack
- Node.JS Version: v16.14.2
- MongoDB Version: 5.0-focal
- Is this hosted on cloud.trudesk.io: No

**Comment by ksolomon75** [comment]
I am also having this issue, connecting to a mailbox hosted in Google Workspace.  The account is set up to use an app password, which works in other apps.

**Comment by sudodaemon** [comment]
Same issue here. I've set up 4 help desk ticket systems to try them all out. No matter what I try, the mail check never works. Same settings in all the other systems, just doesnt work with TruDesk.
