### ISSUE TITLE
Group object as member object ( subgroup)

### ISSUE THREAD

**Issue by nilsjha** [polonel/trudesk#66]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ ] BUG 
- [X] FEATURE

Usage case: In a service-provider helpdesk, with many customers, and each customer have their respective users which submits cases to the helpdesk. For example as a service-provider with 50 IT Support Agents you might have 150 customers, with a few users each who submits cases. Then the process of adding your entire IT Support Agent Department to each of the 150 customers will be very slow and ineffective.

Approach with current possible group structure:
 - Customer group with following members:
      - Customer CEO
      - Customer CTO
      - Customer CFO
      - IT Support Agent 1 (from  service provider - doesn't work at Customer's company)
      - IT Support Agent 2 ( same role  as above)
      - IT Support Agent 3  ( same role  as above)

Any plan to support adding groups as an member object (instead of only being able to add users as members) ?

Example: 
Possible Future approach with group objects as members inside groups:

- Customer group with following members:
      - Customer CEO
      - Customer CTO
      - Customer CFO
      - IT Support Agent Group (this group includes all of our IT support agents, so they are able to interact with the ticket)  ( everyone are from  service provider - doesn't work at Customer's company)

Also the IT Support Agent Group should be able to join multiple Groups ( as the IT Support agents need access to multiple customer groups)

Or maybe a better approach would be to create a global group object ( for example IT Support Agent Group) which has exclusive access to all of the tickets in the system, regardless of normal group membership  (without being Administrators of course).

---

if you are interested in a Norwegian translation of the project, I might be able to contribute in the future (my time-frame after work is very restricted at the moment)

**Comment by polonel** [comment]
Thanks for the request. It's on the roadmap and a top priority for a future release.

**Comment by polonel** [comment]
In Progress: Please see https://forum.trudesk.io/t/agent-system-redesign/34
