### ISSUE TITLE
Click Logout the system can not logout but return back to dashboard

### ISSUE THREAD

**Issue by bizeasy17** [polonel/trudesk#67]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x ] BUG 
- [ ] FEATURE

**What happened**:
Click Logout the system can not logout but return back to dashboard
**What did you expect to happen**:
return to login page
**How to reproduce it (as minimally and precisely as possible)**:
deploy to the same environment . it occurs every time

**Anything else we need to know?**:

**Environment**:
- Trudesk Version:1.0.0
- OS (e.g. from /etc/os-release):macOS 10.13.4
- Node.JS Version:v8.9.4
- MongoDB Version:v3.6.3
- Is this hosted on cloud.trudesk.io:no

**Comment by polonel** [comment]
Please see: https://github.com/polonel/trudesk/issues/65

I'm working hard to get develop at a state that I can merge. 
The work around is listed in issue #65
