### ISSUE TITLE
Error 429 Too many request

### ISSUE THREAD

**Issue by nmincone** [polonel/trudesk#672]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
After attempting to login approx 6-10 times, user is faced with an error page preventing them or any other user from logging in.
**What did you expect to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Repeatedly entering in the wrong username or password

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: Trudesk version 1.2.10 (image polonel/trudesk:1)
- OS (e.g. from /etc/os-release): Debian Docker
- Node.JS Version: 
- MongoDB Version: mongo:5.0-focal
- Is this hosted on cloud.trudesk.io:

**Comment by polonel** [comment]
Not a bug. It's rate is limited with IP BAN, thus preventing you from logging in as any user once the IP is banned.

**Comment by nmincone** [comment]
Noted. It pans the WAN IP? So anyone in the building can't log a support ticket?
How long before it times out?
The only way we found a solution was to restart the docker container.

**Comment by polonel** [comment]
Please see [These ENV Vars](https://github.com/polonel/trudesk/blob/ad4c42c3b88c42d90e41b3615f1ee205925ad03e/src/controllers/main.js#L111-L113) to set to user only or even disable the rate limit entirely if you wish.
