### ISSUE TITLE
Dependency issue while installing 1.2.10 from source

### ISSUE THREAD

**Issue by miko007** [polonel/trudesk#681]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [X] BUG 
- [ ] FEATURE

**What happened**:
While running `npm i` for a checkout of version `1.2.10`, npm *(running node version `20.14.0`)* is complaining about a dependency issue:

```
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: react-html-parser@2.0.2
npm error Found: react@17.0.2
npm error node_modules/react
npm error   react@"17.0.2" from the root project
npm error   peer react@"^16.8.0 || ^17 || ^18" from mobx-react-lite@3.4.0
npm error   node_modules/mobx-react-lite
npm error     mobx-react-lite@"^3.4.0" from mobx-react@7.5.2
npm error     node_modules/mobx-react
npm error       mobx-react@"7.5.2" from the root project
npm error   14 more (mobx-react, react-hot-keys, react-dom, react-colorful, ...)
npm error
npm error Could not resolve dependency:
npm error peer react@"^0.14.0 || ^15.0.0 || ^16.0.0-0" from react-html-parser@2.0.2
npm error node_modules/react-html-parser
npm error   react-html-parser@"2.0.2" from the root project
npm error
npm error Conflicting peer dependency: react@16.14.0
npm error node_modules/react
npm error   peer react@"^0.14.0 || ^15.0.0 || ^16.0.0-0" from react-html-parser@2.0.2
npm error   node_modules/react-html-parser
npm error     react-html-parser@"2.0.2" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
```

i am not able to install trudesk.

**What did you expect to happen**:
`npm` installing all necessary dependencies.

**How to reproduce it (as minimally and precisely as possible)**:
As far as i am concerned:

* Check out version `1.2.10` from this repo
* run `npm i` running node `20.14.0`

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: 1.2.10
- OS (e.g. from /etc/os-release): CentOS Linux release 7.9.2009 (Core)
- Node.JS Version: 20.14.0
- MongoDB Version: –
- Is this hosted on cloud.trudesk.io: no

**Comment by polonel** [comment]
use yarn to install deps so it utilizes the yarn lockfile.
