### ISSUE TITLE
Error: No Api key assigned to this user

### ISSUE THREAD

**Issue by Play-Real** [polonel/trudesk#70]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:

Error: No Api key assigned to this user

**What did you expect to happen**:
Loggin into Trudesk using my android phone (chrome).

**How to reproduce it (as minimally and precisely as possible)**:
Login using chrome on android with another user than the default adminstrator user.

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: Ubuntu Install Script.
- OS (e.g. from /etc/os-release): ubuntu 16.04.4 x64
- Node.JS Version: v8.11.1
- MongoDB Version: v3.6.4
- Is this hosted on cloud.trudesk.io: no

**Comment by polonel** [comment]
This is in fact by design. You will need to log in on a desktop, goto the
profile section and generate an API key. Only the default admin is assigned
an API key during install. All created users will need to generate an API
key on their profile page.

**Comment by Play-Real** [comment]
Sorry i didn't see that option. Because you have to be logged in as a user. Works fine now ! thanks
