### ISSUE TITLE
Capcha not working in IE11

### ISSUE THREAD

**Issue by Hitokirizero** [polonel/trudesk#75]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ ] BUG 
- [x] FEATURE

**What happened**: Capcha not working in IE11

**What did you expect to happen**: To support multi browser

**How to reproduce it (as minimally and precisely as possible)**: 
Steps:
1) Login to trudesk (using IE11 or lower) and click at the Setting>>General
2) Enable the "Allow Public ticket"
3) Logout
4) Go to http://docker.trudesk.io/newissue
5) Fill up the Captha and press Next. 

**Anything else we need to know?**:
Does Trudesk support IE? IF it doesn't support please change this to feature. thanks.

**Environment**:
- Trudesk Version: latest
- OS (e.g. from /etc/os-release): centos7 (Running in docker)
- Node.JS Version: 8.11.2
- MongoDB Version: 3.6.2
- Is this hosted on cloud.trudesk.io: No

**Comment by polonel** [comment]
I'm moving this to a feature. Right now I know there are multiple issues with IE11 that need to be resolved before I would label it as "supported"
