### ISSUE TITLE
Mongo Documentation Request

### ISSUE THREAD

**Issue by dminnick-chegg** [polonel/trudesk#76]
- [ ] BUG 
- [x] FEATURE

**What happened**:
Hi, would you be able to provide some documentation about setting up and configuring Mongo for TruDesk? It took us a while to get up and running with mlab, and it took some trial and error. I think it would be very useful for people wishing to get up and running quickly who aren't super familiar with Mongo. Anyway great project and thanks for building this!

**What did you expect to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
[unrelated] Do you plan to add any db support for other databases (esp relational SQL-based ones)? 

**Environment**:
- Trudesk Version:
- OS (e.g. from /etc/os-release):
- Node.JS Version:
- MongoDB Version:
- Is this hosted on cloud.trudesk.io:

**Comment by polonel** [comment]
Thank you for your request. I will consider it as I'm working on the documentation. I also add a pre-configured Virtual Appliance with MongoDB and trudesk already installed to get up and running quickly without configuration. There are also other MongoDB cloud service providers that will work the same. Also, I want to make you aware of the [Ubuntu install script](http://www.trudesk.io/v1/guide/installation.html#Ubuntu-Install-Script). The install script will go through and handle all the server configuration of both MongoDB and trudesk.

As far as supporting relational database, that more than likely will not be supported. There are many advantages to MongoDB and why I selected it. Mainly its schemaless design and the fact that as the core code evolves the backend database can adapt without modifications. 

Once again, Thank you again for your support of the project and I will keep your request in consideration when completing the docs.
