### ISSUE TITLE
localization to ukrainian language

### ISSUE THREAD

**Issue by andrewlytvyn** [polonel/trudesk#82]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ ] BUG 
- [x] FEATURE

**What happened**:
Cannot change ui localization to ukrain

**Comment by polonel** [comment]
Localization to other languages is on the roadmap for a later release. 
@andrewlytvyn are you interested in helping translate to Ukrain?

**Comment by andrewlytvyn** [comment]
@polonel yes, i am interested to help to translate to Ukraine

**Comment by polonel** [comment]
@andrewlytvyn If you are still interested please see https://crwd.in/trudesk
