### ISSUE TITLE
Unable to use long top-level domains for cloud.trudesk.io

### ISSUE THREAD

**Issue by maxxst** [polonel/trudesk#83]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
Can't use new tld .berlin (or any tld longer than 4 characters) to register with https://cloud.trudesk.io/

**What did you expect to happen**:
Being able to login

**How to reproduce it (as minimally and precisely as possible)**:
Try to use an emailadress like test@test.example

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: 
- OS (e.g. from /etc/os-release):
- Node.JS Version:
- MongoDB Version:
- Is this hosted on cloud.trudesk.io: yes

**Comment by polonel** [comment]
Thanks for the bug report. This issue has been fixed. 

_Please Note: Registration is currently disabled. The public beta will hit later this fall._
