### ISSUE TITLE
Contribute

### ISSUE THREAD

**Issue by leonardonhesi** [polonel/trudesk#86]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ ] BUG 
- [x] FEATURE

I am using your system and would like to contribute, first I would like to do the translation to pt-BR, how can I do it?
I wanted to implement a feature to attach documents to tickets.
I would like to implement a knowledge bank functionality for solution registration, and display the possibility of consulting previous solutions before opening a ticket. Would you like my help?

**Anything else we need to know?**:

**Environment**:
- Trudesk Version:
- OS (e.g. from /etc/os-release):
- Node.JS Version:
- MongoDB Version:
- Is this hosted on cloud.trudesk.io:

**Comment by polonel** [comment]
@leonardonhesi Thank you for your support. I am on the heels of an initial final release and once done, I would like to focus on translations and additional features. I already have plans (partial coding) for a knowledge base built. As of right now, there is no easy way to implement different localizations. Its coming and maybe something you can assist with implementing if interested.

Find me on [Gitter](https://gitter.im/trudesk/Lobby)
