### ISSUE TITLE
how do I generate the dist folder?

### ISSUE THREAD

**Issue by jonasaraujo96** [polonel/trudesk#91]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ ] BUG 
- [X] FEATURE

**What happened**:
I can not generate the dist folder

**What did you expect to happen**:
I want to generate the dist folder

**How to reproduce it (as minimally and precisely as possible)**:
npm start, npm run build

**Anything else we need to know?**:

**Environment**:
- Trudesk Version:
- OS (e.g. from /etc/os-release):
- Node.JS Version:
- MongoDB Version:
- Is this hosted on cloud.trudesk.io:

**Comment by polonel** [comment]
There is no dist folder or the need for one. All you need to do is install the npm modules with `yarn install` and then run `yarn run build` and it builds the assets. Once that is complete you can run `npm start` and it starts the server with the compiled resources.

Be sure to check out the [install documentation](http://trudesk.io/v1/guide/installation.html)

**Comment by jonasaraujo96** [comment]
it worked! but I am not able to connect to the database, I am using centos, can you help me?

err: Couldn't connect; make sure connection is correct.

**Comment by jonasaraujo96** [comment]
when I try to download the virtual appliance, a page with the error appears:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
`<Error>
   <Code>AccessDenied</Code>
   <Message>Access Denied</Message>
   <RequestId>F7554E4750568F5A</RequestId>
   <HostId>U5Q2FEoYdK62qvOSAA1Pkq7/XkrIHbPBBFpdVY0BR8ADR/2tGljg/aey+/ogDH2TPc71xpgZ2f4=</HostId>
</Error>`

**Comment by jonasaraujo96** [comment]
update:
I got it! I just needed to open the ubuntu installation script, and redo the steps in CentOS, it worked for me!
Thank you for your help
