### ISSUE TITLE
Unable to install truedesk giving error

### ISSUE THREAD

**Issue by gaurav0914** [polonel/trudesk#92]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [x] FEATURE

**What happened**:

**What did you expect to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

While installing the truedes.io application it throws error after making connection with mongodb it ask for the newdb or existing db option and then when i select newdb it says to create admin and then when i submit it says to restart in 10 second and then throws following error in screen ({"success":false,"error":{"code":11000,"index":0,"errmsg":"E11000 duplicate key error collection: truedb.counters index: _id_ dup key: { : \"tickets\" }","op":{"_id":"tickets","next":1001,"__v":0}})
**Anything else we need to know?**:

**Environment**:windows server 2012 r2
- Trudesk Version:v1.0.0
- OS (e.g. from /etc/os-release):
- Node.JS Version:8
- MongoDB Version:4.0.2
- Is this hosted on cloud.trudesk.io: on premise

**Comment by gaurav0914** [comment]
error while installing truedesk.io application on mongodb

**Comment by polonel** [comment]
This occurs because the install wizard was either canceled or the page was refreshed during the install. It will require a wipe of the trudesk mongodb database before running the install wizard again.
