### ISSUE TITLE
profile picture cannot be change at mobile site

### ISSUE THREAD

**Issue by johnnyngster** [polonel/trudesk#94]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
At the mobile version i could not click the picture icon and change the profile picture.

**What did you expect to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Suspecting the ionic version is too old

**Environment**:
- Trudesk Version: demo site
- OS (e.g. from /etc/os-release): android
- Node.JS Version: 10.11.0
- MongoDB Version: 3.6
- Is this hosted on cloud.trudesk.io: no

**Comment by polonel** [comment]
Yes. This is possible in the iOS app. Currently waiting for review by the Apple team.

**Comment by johnnyngster** [comment]
android not working thou?

**Comment by polonel** [comment]
Yes, this works on the Android hybrid app. It does not work on the web mobile app.
