### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by Burhan-Ahmed** [polonel/trudesk#95]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**: While starting the server I got this error "error: Oh no, something went wrong with DB! - Authentication failed."

**What did you expect to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Trudesk Version:
- OS (e.g. from /etc/os-release):
- Node.JS Version:
- MongoDB Version:
- Is this hosted on cloud.trudesk.io:

**Comment by polonel** [comment]
What MongoDB version? Did you install MongoDB and point trudesk to your database server? What OS are your running? What does log/output.log say?

**Comment by Burhan-Ahmed** [comment]
I installed the MongoDB but not sure if I have point trudesk to database server. Can you please assist me with that.
I am using Mac 10.13.6. MongoDB version: mongodb-osx-ssl-x86_64-4.0.3

**Comment by polonel** [comment]
I'm working on additional documentation for setting up MongoDB manually. Will update as soon as its available.

**Comment by Burhan-Ahmed** [comment]
Thank you so much.

**Comment by srladuani** [comment]
Hello @polonel I do have the same issue. I have pointed `truedesk` to `mongoserver`. But, when I go on `http://localhost:8118/install` it gives the error mentioned above. I am on ubuntu `18.04`
Thanks.
Sarwan Kumar

**Comment by polonel** [comment]
@srladuani Manually install or with the Ubuntu script?

**Comment by Burhan-Ahmed** [comment]
@polonel When can I expect the documentation for setting up MongoDB manually

**Comment by polonel** [comment]
@Burhan-Ahmed I'm still working on it for the current version of the project. A lot of documentation is changing due to it being outdated from pre-release. In the meantime have you tried to set up a free hosted MongoDB like [https://mlab.com](https://mlab.com)?

**Comment by srladuani** [comment]
> @srladuani Manually install or with the Ubuntu script?

@polonel Thanks for your reply. I have install it manually on my ubuntu machine. And, its working fine.
Actually, I needed to restart node server manually after all that installation setup done.
So, Its working now.
Thanks again.
Sarwan.

**Comment by Burhan-Ahmed** [comment]
@polonel I will try with the free hosted MongoDB like https://mlab.com.
