### ISSUE TITLE
Cannot Create ticket (chrome, android)

### ISSUE THREAD

**Issue by Play-Real** [polonel/trudesk#96]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
Cannot create ticket on Chrome 69.0.3497.100 (Android)

**What did you expect to happen**:
Able to create ticket 
**How to reproduce it (as minimally and precisely as possible)**:
Im not able to select group or type or priority
(when I login onto mobile site with desktop chrome it works fine)

**Anything else we need to know?**:
-User has group(s)

**Environment**:
- Trudesk Version: Trudesk version 1.0.1
- OS (e.g. from /etc/os-release): Ubuntu Installation script
- Node.JS Version:
- MongoDB Version:
- Is this hosted on cloud.trudesk.io:
no

**Comment by Play-Real** [comment]
https://youtu.be/us3an87QV-w

**Comment by polonel** [comment]
Thank you for the information. Investigating.

**Comment by polonel** [comment]
Confirmed.

**Comment by polonel** [comment]
The issue has been fixed on `develop` branch.
