### ISSUE TITLE
Duplicate key mongo error on installations step.

### ISSUE THREAD

**Issue by srladuani** [polonel/trudesk#97]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
{"success":false,"error":{"name":"MongoError","message":"E11000 duplicate key error collection: trudesk.counters index: _id_ dup key: { : \"tickets\" }","driver":true,"index":0,"code":11000,"errmsg":"E11000 duplicate key error collection: trudesk.counters index: _id_ dup key: { : \"tickets\" }"}}

**What did you expect to happen**:
It should redirect to home/dashboard page
**How to reproduce it (as minimally and precisely as possible)**:
On installation Step:
1. Click on `Get Start`
2. Give configurations of mongo db server
3. Fill form for `Admin User Create`
4. Error occured

**Anything else we need to know?**:

**Environment**:
- Trudesk Version:
- OS (e.g. from /etc/os-release):
- Node.JS Version:
- MongoDB Version:
- Is this hosted on cloud.trudesk.io:

**Comment by polonel** [comment]
This occurs because the install was interrupted during the population of
the mongo database. The error states that it already has a duplicate entry
which means you had previously ran the install wizard and it did not
complete.

To resolve you’ll need to empty the mongo database and start fresh.

**Comment by srladuani** [comment]
@polonel Thanks for your reply.
It is resolved now. 
Actually, the issue was due to I did not restart server after installation complete.
