### ISSUE TITLE
Rest API Error on Ticket Create Request

### ISSUE THREAD

**Issue by cydefend** [polonel/trudesk#98]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**: A Rest call POST to /api/v1/tickets/create seems to fail with an error message.  This occurred on a fresh ubuntu 16.04 using the provided install script.

"reason": {
                    "message": "Cast to ObjectId failed for value \"1\" at path \"priority\"",
                    "name": "CastError",
                    "stringValue": "\"1\"",
                    "kind": "ObjectId",
                    "value": 1,
                    "path": "priority"
                }

**What did you expect to happen**: Following the api, I expected a success true response with the details of the ticket.

**How to reproduce it (as minimally and precisely as possible)**:

POST /api/v1/tickets/create HTTP/1.1
Host: 10.30.40.20:8118
accesstoken: 39a5d074f21cf8f8dcdbcb6d7813b6d41725ae86
Content-Type: application/json
Cache-Control: no-cache

{ "subject": "Subject", "issue": "Issue Exmaple", "owner": "5bc76a3691e47d435efe1f3d", "group":"5bc76a3691e47d435efe1f3c", "type": "5bc76a3d9b88fb44b00a7e5a", "priority": 1 }

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: Trudesk version 1.0.1
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Node.JS Version: v10.12.0
- MongoDB Version: db version v3.6.8
- Is this hosted on cloud.trudesk.io: no

**Comment by polonel** [comment]
This is confirmed. It's also a breaking change in the documentation that needs updating as well.
The issue comes from priorities are no longer hardcoded and customizable and the priority field now takes a priority ObjectID.

You can get the priority `_id` from a `GET` call to `/api/v1/tickets/priorities`

_Working on fix now_

**Comment by cydefend** [comment]
Using the priority _id worked.  Thanks!
